### PR TITLE
Cleanup HTML + layout in header of README.md, add OSSRank shield

### PR DESCRIPTION
**Pull request by ryw**
## Description

* Cleanup HTML + layout in header of README.md
* Add OSSRank shield to the header

## Type of change

Non-breaking, readme update

## Checklist:

- [X] My code follows the style guidelines(PEP 8) of MindsDB.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have updated the documentation, or created issues to update them.
- [X] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [X] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by ryw** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by ZoranPandovski — APPROVED** [review]

**Comment by ryw** [comment]
Yes, some information here: https://ossrank.com/about

The algorithm only uses git commit data (NO STARS!) and rewards projects that has more commits and committers, biased fo recently.

The key part of the formula adds up the 10 sub-scores according to the multiplier below: 

* 10x contributors_count for past_30_days
* 8x contributors_count for past_90_days
* 6x contributors_count for past_365_days
* 4x contributors_count for past_1095_days
* 2x contributors_count for all_time

* 5x commits_count for past_30_days
* 4x commits_count for past_90_days
* 3x commits_count for past_365_days
* 2x commits_count for past_1095_days (3 yrs)
* 1x commits_count for all_time

**Pull request merged**
