### PR TITLE
[Docs] Update a link to the Vertica integration #5001

### LINKED ISSUE #5001: [Docs] Update a link to the Vertica integration
## Instructions :page_facing_up:

Here are the step-by-step instructions:

1. Go to the file `/mindsdb/README.md`.

2. Find the section titled `## Database Integrations`. This section contains a table with integrations and their logos.

3. Find the below HTML tag:

`<a href="https://docs.mindsdb.com/">Vertica Badge</a>`

4. Update the `href` value to this link: https://docs.mindsdb.com/data-integrations/all-data-integrations#vertica

5. Save the changes and create a PR.

## Hackathon Issue :loudspeaker:

MindsDB has organized a hackathon to let in more contributors to the in-database ML world.

Each hackathon issue is worth a certain amount of credits that will bring you prizes by the end of the MindsDB Hackathon.

Check out the [MindsDB Hackathon rules](https://mindsdb.com/mindsdb-hackathon)!

## The https://github.com/mindsdb/mindsdb/labels/first-timers-only Label

We are happy to welcome you on board! Please take a look at the rules below for first-time contributors.

1. You can solve only one issue labeled as https://github.com/mindsdb/mindsdb/labels/first-timers-only. After that, please look at other issues labeled as https://github.com/mindsdb/mindsdb/labels/good%20first%20issue, https://github.com/mindsdb/mindsdb/labels/help%20wanted, or https://github.com/mindsdb/mindsdb/labels/integration.

2. After you create your first PR in the MindsDB repository, please sign our CLA to become a MindsDB contributor. You can do that by leaving a comment that contains the following: `I have read the CLA Document and I hereby sign the CLA`

Thank you for contributing to MindsDB!

### PR DESCRIPTION
**Pull request by marsidmali**
## Description

Updated a link to the Vertica integration
Fixes #5001

## Type of change

- [x] 📄 This change requires a documentation update

## Checklist:

- [x] I have updated the documentation, or created issues to update them.

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@marsidmali 
Before we can merge your PR, please sign our CLA following the instructions above.

**Comment by marsidmali** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
