### PR TITLE
added feature engineering in mindsdb

### PR DESCRIPTION
**Pull request by martyna-mindsdb**
Fixes [#73 from mindsdb_private](https://github.com/mindsdb/mindsdb_private/issues/73)

## Please describe what changes you made, in as much detail as possible
  - added `Feature Engineering in MindsDB` in the `mkdocs.yml` file
image

  - added tutorial content (used docs tabular structure to run the commands _simultaneously_)
[Feature Engineering in MindsDB - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9860930/Feature.Engineering.in.MindsDB.-.MindsDB.Documentation.pdf)

mindsdb

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
I completed the tutorial. Please let me know your feedback. Thanks.

Here are the queries I used for examples 1 and 2: 
[queries_example1.txt](https://github.com/mindsdb/mindsdb/files/9854315/queries_example1.txt)
[queries_example2.txt](https://github.com/mindsdb/mindsdb/files/9854316/queries_example2.txt)

**Comment by martyna-mindsdb** [comment]
Here is the current PDF version of this doc page: 
[Feature Engineering in MindsDB - MindsDB Documentation.pdf](https://github.com/mindsdb/mindsdb/files/9868659/Feature.Engineering.in.MindsDB.-.MindsDB.Documentation.pdf)

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
Can we exclude the above csv files and reference them from another location?

**Comment by martyna-mindsdb** [comment]
@ZoranPandovski 
If I understand you correctly, I have already removed the csv files from this tutorial. All tables that I use are in example_db.

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
