### PR TITLE
update all-in-one.yaml

### PR DESCRIPTION
**Pull request by farzanekram07**
1 .Use more descriptive names for the services, like mindsdb-migrations, mindsdb-core, ml-service, db-service, and executor-service.
2. Include comments to explain each section of the code, like the purpose of each service, the dependencies, the environment variables, and the health checks.
3. Use variables for commonly used values, like the port numbers and the storage directory. This makes it easier to update them later and reduces redundancy.
4. Include a version number or a tag for each image to ensure consistency and reproducibility.
5. Add error handling and logging to help with troubleshooting and debugging.

## Description

Please include a summary of the change and the issue it solves. 

**Fixes** #(issue)

## Type of change

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ⚡ New feature (non-breaking change which adds functionality)
- [x] 📢 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📄 This change requires a documentation update

### What is the solution?

(Describe at a high level how the feature was implemented)

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation, or created issues to update them.
- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by farzanekram07** [comment]
check it an review

**Comment by tajkirkpatrick** [comment]
Hey! When I've deployed and attempted to run your new AIO, I experience an issue where either the executor or core does not recognize an "openai" handler existing. I have attempted to go into each container and install the dependencies for the handler manually via pip.

Although, I'm unsuccessful. Have you had any success using the MLMODE openai in your AIO exmaple>? @farzanekram07

**Comment by farzanekram07** [comment]
I personally used and run it correctly. 
Here is an example of how you could modify the script to install the openai module and its dependencies in each container of your AIO deployment:

# Install openai module and dependencies in executor container
docker exec -it aio_executor sh -c "pip install openai"

# Install openai module and dependencies in core container
docker exec -it aio_core sh -c "pip install openai"

If your container names are different, you should replace these values accordingly.

To run the script, save it as a file (e.g. install_openai.sh) and make it executable with the following command:
chmod +x install_openai.sh

Then, run the script with the following command:
./install_openai.sh


I hope this script helps resolve your issue. Let me know if you have any other questions

**Comment by tajkirkpatrick** [comment]
>  Let me know if you have any other questions
Hey @farzanekram07 ,
So I got stuck in a boot-loop for a bit, but after overcoming that. I have executed the shell install script inside of each container. Originally I was only installing within the executor container but I've executed the shell command within both core and executor.

I am attempting to run the command in the MindsDB GUI:
`CREATE ML_ENGINE openai2 FROM openai USING api_key = '<api-key>';`

And am greeted within a python stack trace that originates from within the executor container and populates back up though the core and into the GUI.

```python
Traceback (most recent call last):
  File "/mindsdb/mindsdb/api/mysql/mysql_proxy/executor/executor_wrapper.py", line 162, in query_execute
    executor.query_execute(sql)
  File "/mindsdb/mindsdb/api/mysql/mysql_proxy/executor/executor.py", line 113, in query_execute
    self.do_execute()
  File "/mindsdb/mindsdb/api/mysql/mysql_proxy/executor/executor.py", line 195, in do_execute
    ret = self.command_executor.execute_command(self.query)
  File "/mindsdb/mindsdb/api/mysql/mysql_proxy/executor/executor_commands.py", line 148, in execute_command
    return self.answer_create_ml_engine(statement)
  File "/mindsdb/mindsdb/api/mysql/mysql_proxy/executor/executor_commands.py", line 770, in answer_create_ml_engine
    raise SqlApiException(f"There is no engine '{statement.handler}'")
mindsdb.api.mysql.mysql_proxy.utilities.exceptions.SqlApiException: There is no engine 'openai'
```

**Comment by ilia-tsyplenkov** [comment]
`all-in-one` docker compose file was used just for demonstration of MindsDB microservice mode. It won't be used further.

**Comment by tajkirkpatrick** [comment]
> It won't be used further.

@ilia-tsyplenkov thank you for the explanation! Do you know of any plans to update the docker hub image of mindsdb to python 3.8? I receive a python version dependent error when trying to install the openai dependencies in the default docker hub image, due to it being based in python 3.7

**Comment by ZoranPandovski** [comment]
@tajkirkpatrick The current image is based on `docker.io/pytorch/pytorch:1.9.1-cuda11.1-cudnn8-runtime` we need to check for the compatible version

**Comment by tajkirkpatrick** [comment]
> The current image is based on `docker.io/pytorch/pytorch:1.9.1-cuda11.1-cudnn8-runtime`

@ZoranPandovski  thank you this time, I'm new to the community so I appreciate your response and explanation. Is this a bug I should into an issue to be properly tracked?

**Pull request closed without merging**
