### PR TITLE
Close uploaded file

### LINKED ISSUE #638: Permissions error on /datasources/data
This is reported from the user while uploading the data through the Scout. This happens on a Windows machine [permissions error line](https://github.com/mindsdb/mindsdb/blob/stable/mindsdb/interfaces/datastore/datastore.py#L81)
```
Exception on /datasources/Somedata [PUT] Traceback (most recent call last): File "C:\Users\jp299\AppData\Roaming\mindsdb_gui\mindsdb_server\env\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request rv = self.dispatch_request() File "C:\Users\jp299\AppData\Roaming\mindsdb_gui\mindsdb_server\env\lib\site-packages\flask\app.py", line 1936, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "C:\Users\jp299\AppData\Roaming\mindsdb_gui\mindsdb_server\env\lib\site-packages\flask_restx\api.py", line 375, in wrapper resp = resource(*args, **kwargs) File "C:\Users\jp299\AppData\Roaming\mindsdb_gui\mindsdb_server\env\lib\site-packages\flask\views.py", line 89, in view return self.dispatch_request(*args, **kwargs) File "C:\Users\jp299\AppData\Roaming\mindsdb_gui\mindsdb_server\env\lib\site-packages\flask_restx\resource.py", line 44, in dispatch_request resp = meth(*args, **kwargs) File "C:\Users\jp299\AppData\Roaming\mindsdb_gui\mindsdb_server\env\lib\site-packages\flask_restx\marshalling.py", line 248, in wrapper resp = f(*args, **kwargs) File "C:\Users\jp299\AppData\Roaming\mindsdb_gui\mindsdb_server\env\lib\site-packages\mindsdb\api\http\namespaces\datasource.py", line 114, in put ca.default_store.save_datasource(ds_name, source_type, source, file_path) File "C:\Users\jp299\AppData\Roaming\mindsdb_gui\mindsdb_server\env\lib\site-packages\mindsdb\interfaces\datastore\datastore.py", line 81, in save_datasource os.replace(file_path, source) PermissionError: [WinError 32] El proceso no tiene acceso al archivo porque est� siendo utilizado por otro proceso: 'C:\\Users\\jp299\\AppData\\Local\\Temp\\datasource_file_pzpfjtzc\\Somedata.xlsx' -> 'C:\\Users\\jp299\\AppData\\Roaming\\mindsdb_gui\\mindsdb_server\\env\\lib\\site-packages/var/datastore\\Somedata\datasource\\Somedata.xlsx'
```

### PR DESCRIPTION
**Pull request by StpMax**
Fixes #638 

Reason of issue is not closed uploaded file.

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
**CLA Assistant Lite** All Contributors have signed the CLA.

**Comment by maximlopin** [comment]
now I get this on windows:
```
Exception on /datasources/fsdfsdg [PUT]
Traceback (most recent call last):
  File "C:\Users\maxim\Envs\mindsdb\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\maxim\Envs\mindsdb\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\maxim\Envs\mindsdb\lib\site-packages\flask_restx\api.py", line 375, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\maxim\Envs\mindsdb\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\maxim\Envs\mindsdb\lib\site-packages\flask_restx\resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "C:\Users\maxim\Envs\mindsdb\lib\site-packages\flask_restx\marshalling.py", line 248, in wrapper
    resp = f(*args, **kwargs)
  File "Q:\Desktop\mdb\mindsdb\mindsdb\api\http\namespaces\datasource.py", line 103, in put
    parser.write(chunk)
  File "C:\Users\maxim\Envs\mindsdb\lib\site-packages\multipart\multipart.py", line 1794, in write
    return self.parser.write(data)
  File "C:\Users\maxim\Envs\mindsdb\lib\site-packages\multipart\multipart.py", line 1076, in write
    l = self._internal_write(data, data_len)
  File "C:\Users\maxim\Envs\mindsdb\lib\site-packages\multipart\multipart.py", line 1407, in _internal_write
    self.callback('end')
  File "C:\Users\maxim\Envs\mindsdb\lib\site-packages\multipart\multipart.py", line 605, in callback
    func()
  File "C:\Users\maxim\Envs\mindsdb\lib\site-packages\multipart\multipart.py", line 1758, in on_end
    vars.writer.finalize()
  File "C:\Users\maxim\Envs\mindsdb\lib\site-packages\multipart\multipart.py", line 536, in finalize
    self.on_end()
  File "C:\Users\maxim\Envs\mindsdb\lib\site-packages\multipart\multipart.py", line 530, in on_end
    self._fileobj.flush()
ValueError: flush of closed file
```

**Comment by StpMax** [comment]
Thank you Maxim, will try fix it

**Comment by ZoranPandovski** [comment]
**CLA Assistant Lite** All Contributors have signed the CLA.

**Comment by ZoranPandovski** [comment]
**CLA Assistant Lite** All Contributors have signed the CLA.

**Review by maximlopin — APPROVED** [review]

**Pull request merged**
