### PR TITLE
Added microsoft-access Fix #5251

### LINKED ISSUE #5251: [Docs] Add the `microsoft-access.mdx` file to docs navigation
## Instructions :page_facing_up:

Here are the step-by-step instructions:

1. Go to the `/docs/mint.json` file.

2. Go to the `"navigation"` item (at line 48). This `"navigation"` item stores the navigation structure of the [MindsDB docs](https://docs.mindsdb.com/).

3. Find the `"Data Integrations"` group (at line 291).

4. Add the `microsoft-access.mdx` file to the `"pages"`, like this:

```
	{
          "group": "Data Integrations",
          "pages": [
            "data-integrations/all-data-integrations",
            "...list of other pages...",
            "data-integrations/microsoft-access"
          ]
        }
```

3. Save the changes and create a PR.

## Hackathon Issue :loudspeaker:

MindsDB has organized a hackathon to let in more contributors to the in-database ML world.

Each hackathon issue is worth a certain amount of credits that will bring you prizes by the end of the MindsDB Hackathon.

Check out the [MindsDB Hackathon rules](https://mindsdb.com/mindsdb-hackathon)!

## The https://github.com/mindsdb/mindsdb/labels/first-timers-only Label

We are happy to welcome you on board! Please take a look at the rules below for first-time contributors.

1. You can solve only one issue labeled as https://github.com/mindsdb/mindsdb/labels/first-timers-only. After that, please look at other issues labeled as https://github.com/mindsdb/mindsdb/labels/good%20first%20issue, https://github.com/mindsdb/mindsdb/labels/help%20wanted, or https://github.com/mindsdb/mindsdb/labels/integration.

2. After you create your first PR in the MindsDB repository, please sign our CLA to become a MindsDB contributor. You can do that by leaving a comment that contains the following: `I have read the CLA Document and I hereby sign the CLA`

Thank you for contributing to MindsDB!

### PR DESCRIPTION
**Pull request by dhavall13**
## Description

Adding Microsoft-access to the docs

**Fixes** #5251 

update in mints.json

- [x] 📄 This change requires a documentation update

## What is the solution?
Adding the Microsoft-access file to pages

## Checklist:

- [x] I have updated the documentation or created issues to update them.

### CODE REVIEW

**Comment by dhavall13** [comment]
I have completed the changes

**Comment by dhavall13** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
recheckcla

**Pull request merged**
