### PR TITLE
Integrate IBM Netezza with MindsDB #7750

### PR DESCRIPTION
**Pull request by craigouma**
# IBM Netezza Handler

IBM Netezza handler for MindsDB provides interfaces to connect to IBM Netezza data warehouses and extract data for use in MindsDB.

---

## Table of Contents

- [IBM Netezza Handler](#ibm-netezza-handler)
  - [Table of Contents](#table-of-contents)
  - [About IBM Netezza](#about-ibm-netezza)
  - [IBM Netezza Handler Implementation](#ibm-netezza-handler-implementation)
  - [IBM Netezza Handler Initialization](#ibm-netezza-handler-initialization)
  - [Implemented Features](#implemented-features)
  - [TODO](#todo)
  - [Example Usage](#example-usage)

---

## About IBM Netezza

IBM Netezza is a high-performance data warehouse appliance designed for analytics and business intelligence.

[Learn more about IBM Netezza](https://www.ibm.com/cloud/netezza)

## IBM Netezza Handler Implementation

This handler was implemented using Python with the `pyodbc` library to connect to IBM Netezza databases.

## IBM Netezza Handler Initialization

The IBM Netezza handler is initialized with the following parameters:

- `db_host`: Hostname or IP address of the Netezza server.
- `db_port`: Port number for the Netezza database.
- `db_name`: Name of the Netezza database.
- `db_user`: Username for connecting to Netezza.
- `db_password`: Password for the Netezza user.
- `driver`: ODBC driver name for Netezza (e.g., NetezzaSQL).

## Implemented Features

- [x] Connect to IBM Netezza database.
- [x] Execute SQL queries and return results.
- [x] Retrieve a list of tables available in the Netezza database.
- [x] Get column information for specific tables.

## TODO

- [x] Support INSERT, UPDATE, and DELETE operations for tables.
- [x] Additional tables and queries support.
- [x] Enhancements and optimizations for better performance.

## Example Usage

The first step is to create a database with the new `ibm_netezza` engine by passing in the required connection parameters:

```sql
CREATE DATABASE netezza_datasource
WITH ENGINE = 'ibm_netezza',
PARAMETERS = {
  "db_host": "your_netexza_server",
  "db_port": 5480,
  "db_name": "your_database_name",
  "db_user": "your_username",
  "db_password": "your_password",
  "driver": "NetezzaSQL"
};
```

Use the established connection to query your database:

```sql
SELECT * FROM netezza_datasource.your_table
```

Run more advanced queries:

```sql
SELECT column1, column2
FROM netezza_datasource.your_table
WHERE column3 = 'value'
ORDER BY column1
LIMIT 5
```

Feel free to extend the usage and functionalities to suit your specific requirements with IBM Netezza and MindsDB.

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by craigouma** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ZoranPandovski** [comment]
Can you please provide short video or screenshots for a functional example?

**Comment by craigouma** [comment]
@ZoranPandovski I am unable to create a free IBM Cloud account.

**Comment by craigouma** [comment]
@ZoranPandovski  IBM Netezza is a commercial data warehousing and analytics solution provided by IBM. It's typically used by enterprises and organizations for handling large-scale data processing and analytics tasks. Obtaining access to an IBM Netezza server, as well as the associated support and services, usually involves licensing and associated costs. There is no free version of IBM Netezza available for general use. If you require access to an IBM Netezza server for development, testing, or learning purposes, you may need to discuss this with your organization or inquire about the availability of any trial or demo versions provided by IBM. For personal or educational use, you might consider exploring open-source databases or other data warehousing solutions that offer free community editions. Some popular open-source data warehousing solutions include Apache Hadoop, Apache Hive, and more. IBM Netezza is a commercial product, and obtaining access typically involves costs or organizational agreements. There are open-source alternatives available if you require free solutions for data warehousing and analytics.

**Comment by ZoranPandovski** [comment]
@craigouma How did you develop this without access to an environment? We must verify before merging

**Comment by craigouma** [comment]
@ZoranPandovski I didn't have access to the database that is why at the end of the code I didn't put credentials. IBM doesn't want to approve my card while signing up. If you can provide crede I'll be happy to share screenshots. :))

**Comment by tomhuds** [comment]
@craigouma we will need tests and a real demo in order to approve the PR

@ZoranPandovski

**Comment by craigouma** [comment]
@tomhuds @ZoranPandovski If you could assign someone else to do the testing it'd be great!

**Comment by tomhuds** [comment]
@craigouma I am referring to unit tests & integration tests, and sharing looms videos/screenshots of it working (this is a requirement for PRs). Below is the checklist PR checklist that it seems you may have removed?
image

**Comment by ZoranPandovski** [comment]
Closing this, @craigouma please re-open this if you find a way to test it

**Pull request closed without merging**
