### PR TITLE
Added a Community Tutorial

### PR DESCRIPTION
**Pull request by Tes-program**
Fixes #3095

## Please describe what changes you made, in as much detail as possible
  - Added a community article on How To Forecast Purchase Orders for Shopify Stores Using Open-Source by John Lafleur

mindsdb

### CODE REVIEW

**Comment by Tes-program** [comment]
@ZoranPandovski  Please review and merge. Also, please feel free to add the hacktoberfest-accepted label once approved.

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
rechceckcla

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by Tes-program** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by ZoranPandovski** [comment]
recheck

**Comment by ZoranPandovski** [comment]
@Tes-program sorry, I think you need to remove the dot at the end, please just copy/paste the same text as above

**Comment by Tes-program** [comment]
> @Tes-program sorry, I think you need to remove the dot at the end, please just copy/paste the same text as above

Done

**Comment by ZoranPandovski** [comment]
recheckcla

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
