### PR TITLE
Delete mdb-sage-flow.png

### LINKED ISSUE #3060: [Docs] Remove Sage diagram from old docs
**Describe the bug**
The SageMaker diagram is from old docs so it should be removed from current documentation.

**Fix**
1. Remove https://github.com/mindsdb/mindsdb/blob/staging/docs/mindsdb-docs/docs/assets/mdb-sage-flow.png

### PR DESCRIPTION
**Pull request by MichaelLantz**
Fixes #3060

## Please describe what changes you made, in as much detail as possible
  -Deleting mdb-sage-flow.png

mindsdb

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
Recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by MichaelLantz** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by bilal-aamer** [comment]
@MichaelLantz How did ypu sign the CLA Assistant?

**Review by ZoranPandovski — APPROVED** [review]

**Comment by MichaelLantz** [comment]
Hi @bilal-aamer. On my pull request I made the following [comment](https://github.com/mindsdb/mindsdb/pull/3061#issuecomment-1264619803). If I'm not mistaken I was given a prompt that gave me the policies/instructions outlined in the CLA that guided me through the process.

**Pull request merged**
