### PR TITLE
Shopify App Integration

### PR DESCRIPTION
**Pull request by MinuraPunchihewa**
I have implemented the new integration for Shopify. For now, I have added support for querying Products (products), Customers (customers) and Orders (orders) using the handler.

After some initial testing, it looks to be working as expected. Please do let me know if there is anything that I have missed or if there are any bugs.

I will be adding a README outlining how this handler has been implemented first thing in the morning.

### CODE REVIEW

**Comment by MinuraPunchihewa** [comment]
A README has also been added.

**Comment by ZoranPandovski** [comment]
Can you please make sure this is up to date with staging so we can avoid torch errors

**Comment by MinuraPunchihewa** [comment]
@ZoranPandovski I just merged the code from staging, but the status does not seemed to have changed?

**Comment by MinuraPunchihewa** [comment]
@ZoranPandovski I just merged the code from staging, but the status does not seemed to have changed?

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
