### PR TITLE
Added my tutorial to the list

### PR DESCRIPTION
**Pull request by dohrisalim**
## Description

Added my tutorial to Predict the Energy Usage using MindsDB and MongoDB to the list of tutorials

**Fixes** #3537

## Type of change

Tutorial

### CODE REVIEW

**Comment by dohrisalim** [comment]
@martyna-mindsdb I am not quite sure that I understand you. Could you give me an example? For example should `CREATE PREDICTOR mindsdb.energy_usage_predictor
FROM files
(SELECT * FROM houshold_energy)
PREDICT USAGE;` change to something like `db.predictors.insert({ name: "energy_usage_predictor", predict: "USAGE", connection: "houshold_energy", "select_data_query": "db.USAGE.find()" });
`

**Comment by martyna-mindsdb** [comment]
@dohrisalim 
Exactly. Please have a look at our [Mongo API docs](https://docs.mindsdb.com/mongo/insert).

In your tutorial, you created a database using the [insertOne command](https://docs.mindsdb.com/mongo/database) executed in MongoShell and provided the screenshot of the output from MongoShell. That's great.

But then you switched to the MindsDB Cloud Editor. So the request is to continue in MongoShell for the entire example.

Here is the command to create a predictor in MongoShell:

```
db.predictors.insert({
     name: "energy_usage_predictor",
     predict: "usage",
     connection: "name_of_the_database_where_the_table_resides",
     select_data_query: "db.name_of_the_table.find({})"
});
```

**Comment by dohrisalim** [comment]
@martyna-mindsdb I have made the changes that you requested

**Comment by martyna-mindsdb** [comment]
@dohrisalim 
Thanks!

**Pull request merged**
