### PR TITLE
Update documentation with content from Issue #5005

### LINKED ISSUE #5005: [Docs] Update a title of the `MySQL Sentiment Analysis` tutorial

### PR DESCRIPTION
**Pull request by minseonkkim**
## Description

Update `/docs/nlp/sentiment-analysis-inside-mysql-with-openai.mdx` with the following:
- title: Sentiment Analysis with MindsDB and OpenAI using SQL
- sidebarTitle: Sentiment Analysis using SQL
Fixes #5005

## Type of change
- [x] 📄 This change requires a documentation update

### What is the solution?

- Replace existing title and subtitle with content from issue #5005 

## Checklist:
- [x] I have updated the documentation, or created issues to update them.

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@minseonkkim 
Before we can merge your PR, please sign the CLA following the instructions above.

**Comment by minseonkkim** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
