### PR TITLE
Update the DuckDB link in the README.md file

### PR DESCRIPTION
**Pull request by Saksham093**
## Description

Update the DuckDB link in the README.md file. 
Replaced the <a href="https://docs.mindsdb.com/data-integrations/all-data-integrations#duckdb"> 
with new link : https://docs.mindsdb.com/data-integrations/duckdb

**Fixes** 
#5966 

## Type of change

- [x] 📄 This change requires a documentation update

---
Please review the PR and consider it merging.

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@Saksham093 
Please sign the CLA by leaving a comment here.

**Comment by Saksham093** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
