### PR TITLE
Feature/7753 shared exceptions for handlers

### PR DESCRIPTION
**Pull request by dalalvarun**
Extension to [https://github.com/mindsdb/mindsdb/pull/7956](PR - 7956)

Few lines were deleted by mistake. Adding them back.

### CODE REVIEW

**Comment by dalalvarun** [comment]
@dusvyat Missed these changes
image

Can you please add this as well?

**Comment by VarunDalalTR** [comment]
++ @ZoranPandovski @martyna-mindsdb I missed these line changes and shopify handler wont work untill these are added back!

**Comment by dalalvarun** [comment]
++ @ZoranPandovski @martyna-mindsdb I missed these line changes and shopify handler wont work untill these are added back!

**Comment by dusvyat** [comment]
@dalalvarun - please resolve conflicts and then we should be good to go

**Comment by dalalvarun** [comment]
Done @dusvyat

**Review by dusvyat — APPROVED** [review]

**Pull request merged**
