### PR TITLE
Issue 2292 : Updating correct image paths for Determining Body Fat Percentage Tutorial

### LINKED ISSUE #2292: Load correct images for `Determining Body Fat Percentage`
The images for the ` Determining Body Fat Percentage` tutorial are not loaded correctly. The correct path should be added. 

## Steps :male_detective: :female_detective: 

- Head over to https://github.com/mindsdb/mindsdb/blob/staging/docs/mindsdb-docs/docs/sql/tutorials/bodyfat.md
- Change the path to all images to have **/sql** path as:
```
![uploadfile](/assets/tutorials/bodyfat/upload_file.png)
To:
![uploadfile](/assets/tutorials/sql/bodyfat/upload_file.png)
```

### PR DESCRIPTION
**Pull request by Rutam21**
This PR replaces the incorrect paths for images for the above-said tutorial.

Fixes #2292 

## Please describe what changes you made, in as much detail as possible
  -` /sql` was added to the path of the images so that they load correctly on the web page

### CODE REVIEW

**Comment by Rutam21** [comment]
Hello @ZoranPandovski,
Please review and merge the above PR.

**Review by ZoranPandovski — APPROVED** [review]
Thanks

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   ***I have read the CLA Document and I hereby sign the CLA***
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by Rutam21** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Rutam21** [comment]
recheck

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
