### PR TITLE
Implemented the Channel Resource table to contain info about a YouTube channel 

### LINKED ISSUE #7580: [YouTube] Implement the Channel Resource table to contain info about a YouTube channel
MindsDB integrates with YouTube, so you can access YouTube data and make relevant predictions with MindsDB.

## Resources

Familiarize yourself with the existing YouTube integration: https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/youtube_handler

## Steps to Follow

Currently, the YouTube integration with MindsDB accesses the comments table.

The task is to extend [this implementation](https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/youtube_handler) to include the Channel Resource table to contain info about a YouTube channel.

## :loudspeaker: Additional rewards :trophy:

Each integration extension issue brings 15+ points for SWAG and entry into the draw for a :point_down: :
-  :computer:  [Razer Blade 16 Laptop](https://www.razer.com/gaming-laptops/Razer-Blade-16/RZ09-0483SEJ3-R3U1)
- :shirt: :bear:  [MindsDB Swag](https://store.covver.io/mindsdb/collections/swag-collection)

:information_source: For more info check out https://mindsdb.com/hacktoberfest/ :point_left:

### PR DESCRIPTION
**Pull request by NikeshBaghel**
## Description

Please include a summary of the change and the issue it solves. 

Fixes #7580

## Type of change

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [ ] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have appropriately commented on my code, especially in complex areas.
- [ ] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@NikeshBaghel 
Please sign our CLA to become a contributor.

Also, in all PRs, please provide screenshots or videos presenting a working feature implemented in the PR.

**Comment by martyna-mindsdb** [comment]
This has been solved by the first PR under this issue.

Update: From now on we have started assigning issues to contributors to avoid multiple PRs for one issue.

You can have a look at other hacktoberfest labeled issues.

**Pull request closed without merging**
