### PR TITLE
Added Honey Production Video Tutorial

### LINKED ISSUE #3668: [Video] Predict Honey Production
### Task Description

Create a video tutorial on predicting honey production.

Use the dataset `honeyproduction 1998-2021.csv` available at https://www.kaggle.com/datasets/jessicali9530/honey-production

Predict `totalprod`

### For colours, fonts, images and logos to be used be check out https://mindsdb.com/press-kit

Tag your post with the hastags #mindsdb and #hacktoberfest.

**Basic requirements:**
 
- Video must be of high quality(480p and up)
- If Voice over is used it should be a good voice synthesizer that does not sound too robotic. Please research a good tool to use.
- Video must be uploaded to Youtube.
- Optional- small window at the bottom of your screen of yourself going through a tutorial.
- In the Description box, provide a link of MindsDB's website and github repository link and suggest viewers to join Slack community.
 
> - NOTE: We are not assigning this issue, multiple people can make the PRs.
> - After PR for video submission has been created,it would be reviewed.
> - Only videos that meet the basic requirements will be accepted and points will be rewarded.
> - Videos that do not meet requirements will be sent back with notes on how to improve.
 
## :loudspeaker: Additional rewards :trophy:
 
Each video tutorial brings :nine: points and entry into the draw for a  :point_down: :
 
-  :computer:  [Razer Blade 15 Laptop](https://www.razer.com/hard-bundles/Razer-Blade-15-Bundle-V5-Essential/RZHB-220912-11)
- :headphones:  10 cool audio gadgets 
- :shirt: :bear: MindsDB Swag
:information_source: For more info check out[ https://mindsdb.com/hacktoberfest/](https://mindsdb.com/hacktoberfest/) :point_left: 
 
To participate in the prize draw, you need to complete this form with your contact details and links to all your merged PRs or no-code deliverables. Please submit the form once with all your contributions listed.

### PR DESCRIPTION
**Pull request by NarayanAdithya**
Fixes #3668

## Please describe what changes you made, in as much detail as possible
  - Added Video Tutorial For Honey Production Time Series Forecasting

### CODE REVIEW

**Review by ZoranPandovski — APPROVED** [review]

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by NarayanAdithya** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by NarayanAdithya** [comment]
I have signed the CLA

**Pull request merged**
