### PR TITLE
Fixes #6453

### LINKED ISSUE #6453: [Docs] Update link in `docs\sql\tutorials\customer-churn.mdx`
## Instructions

1. Go to the `docs\sql\tutorials\customer-churn.mdx` file.

2. Search for `/sql/create/predictor` and replace it with `/sql/create/model`

3. Save your changes and create a PR.

## The https://github.com/mindsdb/mindsdb/labels/first-timers-only Label

We are happy to welcome you on board! Please take a look at the rules below for first-time contributors.

1. You can solve only one issue labeled as https://github.com/mindsdb/mindsdb/labels/first-timers-only. After that, please look at other issues labeled as https://github.com/mindsdb/mindsdb/labels/good%20first%20issue, https://github.com/mindsdb/mindsdb/labels/help%20wanted, or https://github.com/mindsdb/mindsdb/labels/integration.

2. Please leave a comment on this issue and wait until you are assigned. Then you can create a PR.

3. After you create your first PR in the MindsDB repository, please sign our CLA to become a MindsDB contributor. You can do that by leaving a comment that contains the following: `I have read the CLA Document and I hereby sign the CLA`

Thank you for contributing to MindsDB!

### PR DESCRIPTION
**Pull request by Pawel1894**
I have read the CLA Document and I hereby sign the CLA

### CODE REVIEW

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by ZoranPandovski** [comment]
recheck

**Comment by Pawel1894** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
@Pawel1894 I think the CLA is not triggered since your comment is in the PR description. Can you please add a new comment with the same CLA agreement?

**Review by ZoranPandovski — APPROVED** [review]

**Comment by Pawel1894** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Pawel1894** [comment]
recheckcla

**Pull request merged**
