### PR TITLE
add tutorial links #4481

### PR DESCRIPTION
**Pull request by Phoenix009**
## Description

Adds community tutorial links to the Using MindsDB via SQL API -> Connect to MindsDB -> Other SQL Clients -> SQL Alchemy page.

**Fixes** #(4481)

## Type of change
Add community tutorial links to the Using MindsDB via SQL API -> Connect to MindsDB -> Other SQL Clients -> SQL Alchemy page.

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation, or created issues to update them.
- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   **Phoenix09** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by Phoenix009** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
Hey @Phoenix009, sorry about this, but you will need to add the email address you are logged in on Git to your GitHub account.

**Comment by Phoenix009** [comment]
recheck

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by Phoenix009** [comment]
Apologies Zoran,

I have now added the email address to the account.
Can you please check if it is fixed now.

**Comment by ZoranPandovski** [comment]
recheckcla

**Pull request merged**
