### PR TITLE
Create documentation-link.md and also deleted the gif's mentioned and share on Facebook and also shared my experience on tweeter.

### PR DESCRIPTION
**Pull request by tushar-sublaik**
Fixes #

## Please describe what changes you made, in as much detail as possible
  - I have provided a link which redirects to the mindsdb documentation page where they have provided many resources which can help the beginners .

mindsdb

### CODE REVIEW

**Comment by tushar-sublaik** [comment]
Added the Facebook post link in the facebook-post.md section.

**Comment by tushar-sublaik** [comment]
Also deleted the mysql-select.gif as per told and solved the staging issue.

**Comment by tushar-sublaik** [comment]
Hi @ZoranPandovski , I have deleted the gif's which were ,mentioned as issues by you.

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by tushar-sublaik** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by tushar-sublaik** [comment]
I have signed the CLA now please check my pull request @ZoranPandovski .

**Pull request merged**
