### PR TITLE
updated index.md file

### PR DESCRIPTION
**Pull request by SaumyaBhushan**
Fixes #

## Please describe what changes you made, in as much detail as possible
  Fix link to CREATE DATABASE statement #2223
I have read the CLA Document and I hereby sign the CLA

mindsdb

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement]() before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   ***I have read the CLA Document and I hereby sign the CLA***
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by SaumyaBhushan** [comment]
recheck

**Comment by ZoranPandovski** [comment]
Hi @SaumyaBhushan to sign the CLA you will just need to copy/paste `I have read the CLA Document and I hereby sign the CLA` as explained above. Thanks

**Comment by SaumyaBhushan** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by SaumyaBhushan** [comment]
recheck

**Comment by SaumyaBhushan** [comment]
recheck

> Hi @SaumyaBhushan to sign the CLA you will just need to copy/paste `I have read the CLA Document and I hereby sign the CLA` as explained above. Thanks

Done @ZoranPandovski

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
