### PR TITLE
[Docs] Correct port value in metabase #6186 -> Fixed

### PR DESCRIPTION
**Pull request by codescalper**
I have read the CLA Document and I hereby sign the CLA

## Description

 Correct port value in metabase
 
 
**Fixes** #6186 

image

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@codescalper 
Please sign our CLA so we can merge your PR.

**Comment by codescalper** [comment]
Added signature in the PR

I have read the CLA Document and I hereby sign the CLA

**Comment by martyna-mindsdb** [comment]
@codescalper 
The comment should contain **only the below line** to trigger the bot:

I have read the CLA Document and I hereby sign the CLA

**Comment by codescalper** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
