### PR TITLE
Added Notion API Handler

### LINKED ISSUE #7479: [Bug]:
### Short description of current behavior

The objective of this issue is to develop a new handler that leverages the Notion API to interface MindsDB with Notion. This integration will empower users to employ MindsDB's capabilities,  to automate tasks such as creating, modifying, and managing Notion pages, answering inquiries, creating bots and posting announcements within the Notion platform.

## Resources :bulb: 

:checkered_flag: To get started, please refer to the following resources:

* :books:  [Building Application Handler docs](https://docs.mindsdb.com/contribute/app-handlers): This documentation will guide you through the process of building a custom handler for MindsDB. It contains essential information on the handler structure, methods, and best practices.

* :book: [Notion Developer docs](https://developers.notion.com/docs)

* :point_right: [Twitter Handler](https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/twitter_handler): This existing handler connects MindsDB with the Twitter API, allowing users to automate tasks related to posting and analyzing tweets. You can use the Twitter Handler as a reference for building the Slack API integration.

*  :point_right:  [Binance API Handler](https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/binance_handler): Another example of a successful MindsDB integration to the Binance API to make trade data available to use for model training and predictions.

## Next Steps :male_detective: :female_detective: 

-     Acquaint yourself with the Notion API.
-     Develop a new handler to bridge MindsDB with Notion.
-     Incorporate the pivotal features described above.
-     Conduct extensive testing of the integration to confirm its seamless operation.
-     Contribute by submitting a pull request with the newly developed Notion Integration handler.

>NOTE: We are not assigning this type of issue. The first PR that solves this will be accepted :fireworks: 

## :loudspeaker: Additional rewards :trophy:

Each App integration brings :five: :zero:  : points for SWAG and entry into the draw for a  :point_down: :
-  :computer:  [Razer Blade 16 Laptop](https://www.razer.com/gaming-laptops/Razer-Blade-16/RZ09-0483SEJ3-R3U1)
- :shirt: :bear:  [MindsDB Swag](https://store.covver.io/mindsdb/collections/swag-collection)
:information_source: For more info check out https://mindsdb.com/hacktoberfest/ :point_left: 

### Video or screenshots

_No response_

### Expected behavior

_No response_

### How to reproduce the error

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by neelshah2409**
## Description

This handler that leverages the Notion API to interface MindsDB with Notion. This integration will empower users to employ MindsDB's capabilities, to automate tasks such as creating, modifying, and managing Notion pages, answering inquiries, creating bots and posting announcements within the Notion platform.

Fixes #7479 

## Type of change

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have appropriately commented on my code, especially in complex areas.
- [ ] Necessary documentation updates are either made or tracked in issues.
- [x] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
Hi @neelshah2409 this actualy just connects to Notion without MindsDB. Please go over other Handlers in MindsDB and see how they work, also you can check the https://docs.mindsdb.com/contribute/app-handlers

**Comment by ZoranPandovski** [comment]
Closing this since it doesn't solve the issue.

**Comment by neelshah2409** [comment]
> Closing this since it doesn't solve the issue.

I would change the code for this in some time

**Pull request closed without merging**
