### PR TITLE
4558 added doc changes for including community tutorial

### PR DESCRIPTION
**Pull request by sijilo**
## description
added doc changes for including community tutorial  for ```Creating Views with MindsDB```

modified:
  - docs/sql/create/view.mdx 
resolves/fixes :
  -  #4558

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by martyna-mindsdb** [comment]
@sijilo
Please use your GitHub account and sign our CLA here. Then we can merge your PR.
Thanks.

**Comment by sijilo** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by sijilo** [comment]
@mindsdbadmin @martyna-mindsdb  added new commits by configuring the email , please review the pr .

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by martyna-mindsdb** [comment]
@sijilo 
If you want your changes to be saved, I'm going to reopen this PR and merge it after reviewing it.

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
Closing this one. The https://github.com/mindsdb/mindsdb/pull/4608 is merged.

**Pull request closed without merging**
