### PR TITLE
#5197: Update Database Integrations href

### PR DESCRIPTION
**Pull request by kvaithin**
## Description

Please include a summary of the change and the issue it solves. 

**Fixes** #5197 

Update README.

## Type of change

Update href link for `## Database Integrations` section.

### What is the solution?

(Describe at a high level how the feature was implemented)

Update href link for `## Database Integrations` section.

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ X] I have updated the documentation, or created issues to update them.
- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by kvaithin** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by kvaithin** [comment]
recheck

**Comment by ZoranPandovski** [comment]
recheckcla

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
