### PR TITLE
added video tutorial - How mindsdb is impacting the world of ML

### PR DESCRIPTION
**Pull request by prathikshetty2002**
I have appended my video tutorial on Mindsdb in the docs

The video is a case study on how mindsdb works and is transforming the ml world. All about mindsdb is explained.

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by prathikshetty2002** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by prathikshetty2002** [comment]
recheck

**Comment by prathikshetty2002** [comment]
recheck

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
