### PR TITLE
#6456 Issue: Update link in docs\sql\tutorials\house-sales-forecasting.mdx

### PR DESCRIPTION
**Pull request by nayangoyal**
## Description

Replacing the line from this "/sql/create/predictor" to "/sql/create/model" in the file "docs\sql\tutorials\house-sales-forecasting.mdx" 

**Fixes** #6456 

## Type of change

(Please delete options that are not relevant)

- [x] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] 📄 This change requires a documentation update

### What is the solution?

(Describe at a high level how the feature was implemented)

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation, or created issues to update them.
- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by martyna-mindsdb** [comment]
@nayangoyal 
Please sign the CLA here so we can merge your PR.

**Comment by nayangoyal** [comment]
**I have read the CLA Document and I hereby sign the CLA**

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by martyna-mindsdb** [comment]
recheckcla

**Pull request merged**
