### PR TITLE
I have replaced the query of issue #6513

### PR DESCRIPTION
**Pull request by ayushrathore111**
## Description

Please include a summary of the change and the issue it solves. 

**Fixes** #6513 

## Type of change
I have replaced the query with given query in file of docs 
path  : docs/custom-model/ray-serve.mdx

(Please delete options that are not relevant)
- [x] ⚡ New feature (non-breaking change which adds functionality)
- [x] 📢 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] 📄 This change requires a documentation update

### What is the solution?

(Describe at a high level how the feature was implemented)

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have updated the documentation, or created issues to update them.
- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@ayushrathore111 
Please follow the rules as described in the issue.

One PR can solve only one issue. And before that, please make sure to get assigned to the issue.

**Comment by martyna-mindsdb** [comment]
@ayushrathore111 
Please undo all changes except the ones requested in an issue assigned to you.

Also, please sign our CLA so we can merge your PR.

**Comment by martyna-mindsdb** [comment]
@ayushrathore111 
Please undo all changes except the ones requested in an issue assigned to you.

Also, please sign our CLA so we can merge your PR.

**Comment by ayushrathore111** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by martyna-mindsdb** [comment]
@ayushrathore111 
Please undo the changes to `docs/custom-model/openai.mdx` and `docs/custom-model/mlflow.mdx`.

The issue you are solving here requires modifying only `docs\custom-model\ray-serve.mdx`.

**Pull request merged**
