### PR TITLE
Updated Vertica link in README.md file

### PR DESCRIPTION
**Pull request by shreyap2702**
Merging this PR successfully closes the issue #5919

### CODE REVIEW

**Comment by shreyap2702** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   **Shreya Pandey** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by shreyap2702** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by martyna-mindsdb** [comment]
@shreyap2702
Please make sure to get assigned to an issue before creating a PR. You can do that by leaving a comment on an issue you want to resolve.

**Comment by martyna-mindsdb** [comment]
@shreyap2702 
This issue has been resolved. Please have a look at other open issues labeled as help-wanted.

**Pull request closed without merging**
