### PR TITLE
Update datastax.mdx Issue : #6546

### PR DESCRIPTION
**Pull request by Aman123lug**
Tip added at the end of the implementation

Please include a summary of the change and the issue it solves. 

**Fixes** #6546

## Singing the CLA
I have read the CLA Document and I hereby sign the CLA

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by martyna-mindsdb** [comment]
@Aman123lug 
Please link the issue like this: https://github.com/mindsdb/mindsdb/issues/6467

Also, please sign our CLA so we can merge your PR.

**Comment by Aman123lug** [comment]
Okay

**Comment by Aman123lug** [comment]
> @Aman123lug Please link the issue like this: #6467
> 
> Also, please sign our CLA so we can merge your PR.

This is not working community@mindsdb.com not opening

**Comment by Aman123lug** [comment]
> @Aman123lug Please link the issue like this: #6467
> 
> Also, please sign our CLA so we can merge your PR.

I am trying to make PR it shows me this 
: Pull request creation failed. Validation failed: You can't perform that action at this time.

**Comment by martyna-mindsdb** [comment]
@Aman123lug 
You can sign the CLA by leaving a comment here that contains this line.

**Comment by martyna-mindsdb** [comment]
recheckcla

**Pull request merged**
