### PR TITLE
new tutorial addition

### PR DESCRIPTION
**Pull request by p-mishra1**
Fixes #3095 

## Please describe what changes you made, in as much detail as possible
  -
  Added a new tutorial link Named [Easy machine learning with MindsDB](https://medium.com/codesight/easy-machine-learning-with-mindsdb-664e27c974f9) by [Liron Navon](https://medium.com/@codesight)

mindsdb

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
Recheccla

**Comment by ZoranPandovski** [comment]
Recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by p-mishra1** [comment]
recheck

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
