### PR TITLE
Fixed non-working links in README file

### LINKED ISSUE #7462: [Docs]: Links not working
## Some Links of docs index are not working properly
- Overview 
- Features
- Database Integration
- Quickstart

### Video or screenshots

https://github.com/mindsdb/mindsdb/assets/101205226/92279993-4668-4f34-83da-2a0f35ea0314

### Anything else?

- Instead of writing all the links in one line we can write it in row wise

## Sample
Screenshot 2023-09-30 200446

### PR DESCRIPTION
**Pull request by harshavardhan-b20**
## Description

This pull request addresses issue #7462 by fixing non-working links in the README file. It ensures that all links in the documentation are functional and lead to the correct destinations.

Fixes #7462

## Type of change

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [x] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [x] Test Location: README file
 - [x] Verification Steps: Manually verify that all links in the README file are functional and lead to the correct destinations.

## Additional Media:

- [ ] I have attached a brief loom video or screenshots showcasing the corrected links.

## Checklist:

- [ ] My code follows the style guidelines (PEP 8) of MindsDB.
- [ ] I have appropriately commented on my code, especially in complex areas.
- [x] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
Let's leave the links in one line as they are and remove the links that doesn't have section in the README

**Comment by harshavardhan-b20** [comment]
Thank you for your feedback! I have made the necessary changes to the README file. The links have been left in one line, and I have removed the links that don't have sections. Please review the updated README.

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by harshavardhan-b20** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ZoranPandovski** [comment]
recheckcla

**Pull request merged**
