### PR TITLE
Test the Writer.ai ML integration & Fix 'Handler 'writer.ai' Missing Dependencies' Error 

### LINKED ISSUE #7623: [Integration Testing] Test the Writer.ai ML integration
### Short description of current behavior

The objective of this issue is to test the Writer.ai integration with MindsDB.

> Note that at the moment this handler can be tested on local MindsDB installation, importing all necessary dependencies.

## Resources

Here are some useful links:

1. Follow the [README.md](https://github.com/mindsdb/mindsdb/blob/staging/mindsdb/integrations/handlers/writer_handler/README.md) file. It stores all the commands that need to be tested.
2. Use the [CREATE ML_ENGINE](https://docs.mindsdb.com/sql/create/ml-engine) command to create Writer.ai engine in MindsDB. Please note this is optional for some integrations.
3. Use the [CREATE MODEL](https://docs.mindsdb.com/sql/create/model) command to create, train, and deploy an AI model in MindsDB.

## Steps to Follow

1. Test the integration as outlined in the Resources above.
2. Save the test results, including commands and their outputs, in the `Writer_QA.md` file in a new GitHub repository in your account. [Here is a sample Manual_QA.md file.](https://github.com/mindsdb/mindsdb/blob/staging/mindsdb/integrations/handlers/mysql_handler/Manual_QA.md)
3. Create a PR in the [MindsDB repository](https://github.com/mindsdb/mindsdb) following these steps:
	- Go to the `/mindsdb/integrations/handlers/` folder and open the `Handlers_Manual_QA.md` file.
	- If all the tests passed, append this line: `Writer.ai Test Passed: <link to the test results in your GitHub repository>`
	- If some tests failed, create an issue to report it and append this line: `Writer.ai Test Failed: <link to the test results in your GitHub repository>, <link to the issue>`

## :loudspeaker: Additional rewards :trophy:

Each integration test brings 10+ points for SWAG and entry into the draw for a :point_down: :
-  :computer:  [Razer Blade 16 Laptop](https://www.razer.com/gaming-laptops/Razer-Blade-16/RZ09-0483SEJ3-R3U1)
- :shirt: :bear:  [MindsDB Swag](https://store.covver.io/mindsdb/collections/swag-collection)

:information_source: For more info check out https://mindsdb.com/hacktoberfest/ :point_left:

### LINKED ISSUE #7719: [Bug]: Handler 'writer' Missing Dependencies Error
### Short description of current behavior

I encountered an issue while trying to run MindsDB with the Writer handler. The error message I received is: 

```
Handler 'writer' cannot be used. Reason is: No module named 'chromadb'

If the error is related to missing dependencies, please try to run the following command in your shell and restart MindsDB:
pip install mindsdb[writer]
```
I attempted to resolve the issue by running the following command: 

`pip install -r mindsdb/integrations/handlers/writer_handler/requirements.txt`

However, I encountered an error during the installation process of related libraries.

### Video or screenshots

bug1

bug

bug2

### Expected behavior

_No response_

### How to reproduce the error

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by maulanaakbardj**
## Description

I've added `writerai` as the last requirement, specifying that it requires at least **Python >=3.9** and for langchain because no matching distribution found for `langchain==0.0.267`

Fixes #7623 & #7719 

Hi  @ZoranPandovski , could you please review this pull request

## Type of change

(Please delete options that are not relevant)

- [x] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ⚡ New feature (non-breaking change which adds functionality)
- [x] 📢 Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [x]   Verification Steps: From error
  
```
Handler 'writer' cannot be used. Reason is: No module named 'chromadb'

If the error is related to missing dependencies, please try to run the following command in your shell and restart MindsDB:
pip install mindsdb[writer] 
```

to `Query successfully completed`

### CODE REVIEW

**Comment by maulanaakbardj** [comment]
To Resolve this issue :

```
Building wheels for collected packages: sentence_transformers, rouge-score, hnswlib
  Building wheel for sentence_transformers (setup.py) ... done
  Created wheel for sentence_transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125953 sha256=e49f8d5cc1c3e849ce3139c880353254af63abd32b4a7a115beebc3bd007536d
  Stored in directory: c:\users\maula\appdata\local\pip\cache\wheels\5e\6f\8c\d88aec621f3f542d26fac0342bef5e693335d125f4e54aeffe
  Building wheel for rouge-score (setup.py) ... done
  Created wheel for rouge-score: filename=rouge_score-0.1.2-py3-none-any.whl size=24970 sha256=e0f4c90c27e6cec8181c9ce3b480dc21faca16a7ff2c3d9e6c0fb76781643403
  Stored in directory: c:\users\maula\appdata\local\pip\cache\wheels\24\55\6f\ebfc4cb176d1c9665da4e306e1705496206d08215c1acd9dde
  Building wheel for hnswlib (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for hnswlib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      running bdist_wheel
      running build
      running build_ext
      building 'hnswlib' extension
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for hnswlib
Successfully built sentence_transformers rouge-score
Failed to build hnswlib
```

I need to download https://visualstudio.microsoft.com/visual-cpp-build-tools/ first.

Next, navigate to "Individual components", find  `MSVC v143 -VS 2022 C++ x64/x86 build tools (Latest)`

image

and Windows 11 SDK

image

then install it.

**Comment by dusvyat** [comment]
@maulanaakbardj - please can you try running on python >=3.9, this change shouldn't be necessary

**Comment by maulanaakbardj** [comment]
@dusvyat, I commented that I'm running Python >=3.9 because my Python environment was previously at 3.8.1. When I tried to install 'writerai,' I encountered an error : 
```
ERROR: Ignored the following versions that require a different python version: 0.14.0 Requires-Python >=3.9; 0.14.1 Requires-Python >=3.9; 0.14.2 Requires-Python >=3.9; 0.15.0 Requires-Python >=3.9; 0.16.0 Requires-Python >=3.9; 0.16.1 Requires-Python >=3.9; 0.17.0 Requires-Python >=3.9; 0.17.1 Requires-Python >=3.9; 0.18.0 Requires-Python >=3.9; 0.19.0 Requires-Python >=3.9; 0.20.0 Requires-Python >=3.9; 0.21.0 Requires-Python >=3.9; 0.21.1 Requires-Python >=3.9; 0.21.2 Requires-Python >=3.9; 0.21.3 Requires-Python >=3.9; 0.22.0 Requires-Python >=3.9; 0.22.1 Requires-Python >=3.9; 0.22.2 Requires-Python >=3.9; 0.23.0 Requires-Python >=3.9; 0.24.0 Requires-Python >=3.9; 0.24.1 Requires-Python >=3.9; 0.24.2 Requires-Python >=3.9; 0.25.0 Requires-Python >=3.9; 0.25.3 Requires-Python >=3.9; 0.29.0 Requires-Python >=3.9; 0.3.1 Requires-Python >=3.9; 0.30.0 Requires-Python >=3.9; 0.30.1 Requires-Python >=3.9; 0.4.0 Requires-Python >=3.9; 0.6.0 Requires-Python >=3.9
ERROR: Could not find a version that satisfies the requirement writerai (from versions: none)
ERROR: No matching distribution found for writerai
```
Finally, I updated my environment and resolved this issue

**Comment by maulanaakbardj** [comment]
Hi @ZoranPandovski, I'm pleased to inform you that after fixing the requirements.txt for the Writer.ai handler, the Writer.ai ML integration testing has successfully passed

Fixes #7623

**Comment by maulanaakbardj** [comment]
> > Hi @ZoranPandovski, I'm pleased to inform you that after fixing the requirements.txt for the Writer.ai handler, the Writer.ai ML integration testing has successfully passed
> > Fixes #7623
> 
> @maulanaakbardj before we merge this, please can you confirm that you are unable to install it with `requirements.txt` on `staging` branch?
> 
> I am not able to replicate the issue on my side
> 
> I am mostly concerned wih not having any version pin for langchain, you can find 0.0.267 langchain on pypi [here](https://pypi.org/project/langchain/0.0.267/).

@dusvyat, I am currently using `langchain==0.0.312` and `writerai==0.30.1`.  I've updated the requirements.txt file to include version pins for langchain & writerai

Here is my `pip freeze`:
```
absl-py==2.0.0
aiohttp==3.8.6
aiosignal==1.3.1
alembic==1.12.0
aniso8601==9.0.1
anyio==3.7.1
appdirs==1.4.4
async-timeout==4.0.3
attrs==23.1.0
backoff==2.2.1
beautifulsoup4==4.12.2
black==23.3.0
Brotli==1.1.0
certifi==2023.7.22
cffi==1.16.0
chardet==5.2.0
charset-normalizer==3.3.0
checksumdir==1.2.0
chromadb==0.3.25
click==8.1.7
clickhouse-connect==0.6.14
cmaes==0.10.0
colorama==0.4.6
coloredlogs==15.0.1
colorlog==6.5.0
contextlib2==21.6.0
contourpy==1.1.1
cryptography==41.0.4
cycler==0.12.1
dataclasses-json==0.6.1
dataprep-ml==0.0.18
datasets==2.14.5
Deprecated==1.2.14
dill==0.3.6
dnspython==2.4.2
duckdb==0.7.1
einops==0.7.0
emoji==2.8.0
et-xmlfile==1.1.0
faiss-cpu==1.7.4
fastapi==0.103.2
filelock==3.12.4
filetype==1.2.0
Flask==1.1.2
Flask-Compress==1.14
flask-restx==1.1.0
flatbuffers==23.5.26
fonttools==4.43.1
frozenlist==1.4.0
fsspec==2023.6.0
greenlet==3.0.0
h11==0.14.0
hnswlib==0.7.0
httptools==0.6.0
huggingface-hub==0.17.3
humanfriendly==10.0
idna==3.4
iniconfig==2.0.0
itsdangerous==2.0.1
Jinja2==3.0.3
joblib==1.3.2
jsonpatch==1.33
jsonpath-python==1.0.6
jsonpointer==2.4
jsonschema==4.19.1
jsonschema-specifications==2023.7.1
kiwisolver==1.4.5
langchain==0.0.312
langdetect==1.0.9
langid==1.1.6
langsmith==0.0.43
lightwood==23.8.1.0
llvmlite==0.41.0
lxml==4.9.3
lz4==4.3.2
Mako==1.2.4
MarkupSafe==2.0.1
marshmallow==3.20.1
marshmallow-enum==1.5.1
matplotlib==3.8.0
MindsDB==23.10.2.0
mindsdb-evaluator==0.0.11
mindsdb-sql==0.7.1
monotonic==1.6
mpmath==1.3.0
multidict==6.0.4
multiprocess==0.70.14
mypy-extensions==1.0.0
mysql-connector-python==8.0.33
networkx==3.1
nltk==3.8.1
numba==0.58.0
numpy==1.25.2
onnxruntime==1.16.1
openpyxl==3.1.2
optuna==3.3.0
overrides==7.4.0
packaging==23.2
pandas==2.0.3
pathspec==0.11.2
patsy==0.5.3
pdf2image==1.16.3
pdfminer.six==20221105
Pillow==10.0.1
platformdirs==3.11.0
plotly==5.17.0
pluggy==1.3.0
posthog==3.0.2
protobuf==3.20.3
psutil==5.9.5
psycopg==3.1.12
psycopg-binary==3.1.12
psycopg2-binary==2.9.9
pyarrow==10.0.1
```

**Comment by maulanaakbardj** [comment]
@dusvyat, When I use langchain==0.0.267, I encounter a conflicting dependency error : 

```
 (mindsdb) D:\Data\Riset\Mindsdb>pip install -r requirements.txt              
Requirement already satisfied: requests>=2.28.1 in d:\data\riset\mindsdb\mindsdb\lib\site-packages (from -r requirements.txt (line 1)) (2.31.0)
Requirement already satisfied: charset-normalizer>=2.1.1 in d:\data\riset\mindsdb\mindsdb\lib\site-packages (from -r requirements.txt (line 2)) (3.3.0)
Requirement already satisfied: protobuf<3.21.0 in d:\data\riset\mindsdb\mindsdb\lib\site-packages (from -r requirements.txt (line 3)) (3.20.3)
Collecting langchain==0.0.267 (from -r requirements.txt (line 4))
  Obtaining dependency information for langchain==0.0.267 from https://files.pythonhosted.org/packages/7a/d0/e99c1f0ba271b8269edd30a9362592ef3aa3499b448924e16f4dd00e58f8/langchain-0.0.267-py3-none-any.whl.metadata
  Downloading langchain-0.0.267-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: SQLAlchemy in d:\data\riset\mindsdb\mindsdb\lib\site-packages (from -r requirements.txt (line 5)) (2.0.21)
Requirement already satisfied: duckdb==0.7.1 in d:\data\riset\mindsdb\mindsdb\lib\site-packages (from -r requirements.txt (line 6)) (0.7.1)
Requirement already satisfied: chromadb==0.3.25 in d:\data\riset\mindsdb\mindsdb\lib\site-packages (from -r requirements.txt (line 7)) (0.3.25)
Requirement already satisfied: pydantic>=1.10.8 in d:\data\riset\mindsdb\mindsdb\lib\site-packages (from -r requirements.txt (line 8)) (1.10.13)
Requirement already satisfied: sentence_transformers==2.2.2 in d:\data\riset\mindsdb\mindsdb\lib\site-packages (from -r requirements.txt (line 9)) (2.2.2)
Requirement already satisfied: markupsafe==2.0.1 in d:\data\riset\mindsdb\mindsdb\lib\site-packages (from -r requirements.txt (line 10)) (2.0.1)
Requirement already satisfied: faiss-cpu>=1.7.4 in d:\data\riset\mindsdb\mindsdb\lib\site-packages (from -r requirements.txt (line 11)) (1.7.4)
Requirement already satisfied: datasets>=2.14.4 in d:\data\riset\mindsdb\mindsdb\lib\site-packages (from -r requirements.txt (line 12)) (2.14.5)
Requirement already satisfied: nltk>=3.8.1 in d:\data\riset\mindsdb\mindsdb\lib\site-packages (from -r requirements.txt (line 13)) (3.8.1)
Requirement already satisfied: rouge-score>=0.1.2 in d:\data\riset\mindsdb\mindsdb\lib\site-packages (from -r requirements.txt (line 14)) (0.1.2)
Requirement already satisfied: dill==0.3.6 in d:\data\riset\mindsdb\mindsdb\lib\site-packages (from -r requirements.txt (line 15)) (0.3.6)
Requirement already satisfied: writerai==0.30.1 in d:\data\riset\mindsdb\mindsdb\lib\site-packages (from -r requirements.txt (line 16)) (0.30.1)
Requirement already satisfied: PyYAML>=5.3 in d:\data\riset\mindsdb\mindsdb\lib\site-packages (from langchain==0.0.267->-r requirements.txt (line 4)) (6.0.1)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in d:\data\riset\mindsdb\mindsdb\lib\site-packages (from langchain==0.0.267->-r requirements.txt (line 4)) (3.8.6)
Collecting dataclasses-json<0.6.0,>=0.5.7 (from langchain==0.0.267->-r requirements.txt (line 4))
  Obtaining dependency information for dataclasses-json<0.6.0,>=0.5.7 from https://files.pythonhosted.org/packages/97/5f/e7cc90f36152810cab08b6c9c1125e8bcb9d76f8b3018d101b5f877b386c/dataclasses_json-0.5.14-py3-none-any.whl.metadata
  Using cached dataclasses_json-0.5.14-py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: langsmith<0.1.0,>=0.0.21 in d:\data\riset\mindsdb\mindsdb\lib\site-packages (from langchain==0.0.267->-r requirements.txt (line 4)) (0.0.43)
Collecting numexpr<3.0.0,>=2.8.4 (from langchain==0.0.267->-r requirements.txt (line 4))
  Obtaining dependency information for numexpr<3.0.0,>=2.8.4 from https://files.pythonhosted.org/packages/93/44/08ddbebeb3587876a03c758f0068587c42dc6785031190478e0d25667848/numexpr-2.8.7-cp311-cp311-win_amd64.whl.metadata
  Downloading numexpr-2.8.7-cp311-cp311-win_amd64.whl.metadata (8.9 kB)
Requirement already satisfied: numpy<2,>=1 in d:\data\riset\mindsdb\mindsdb\lib\site-packages (from langchain==0.0.267->-r requirements.txt (line 4)) (1.25.2)
Collecting openapi-schema-pydantic<2.0,>=1.2 (from langchain==0.0.267->-r requirements.txt (line 4))
  Downloading openapi_schema_pydantic-1.2.4-py3-none-any.whl (90 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 90.0/90.0 kB 1.3 MB/s eta 0:00:00
Requirement already satisfied: tenacity<9.0.0,>=8.1.0 in d:\data\riset\mindsdb\mindsdb\lib\site-packages (from langchain==0.0.267->-r requirements.txt (line 4)) (8.2.3)
Requirement already satisfied: pandas>=1.3 in d:\data\riset\mindsdb\mindsdb\lib\site-packages (from chromadb==0.3.25->-r requirements.txt (line 7)) (2.0.3)
Requirement already satisfied: hnswlib>=0.7 in d:\data\riset\mindsdb\mindsdb\lib\site-packages (from chromadb==0.3.25->-r requirements.txt (line 7)) (0.7.0)
Requirement already satisfied: clickhouse-connect>=0.5.7 in d:\data\riset\mindsdb\mindsdb\lib\site-packages (from chromadb==0.3.25->-r requirements.txt (line 7)) (0.6.14)
Requirement already satisfied: fastapi>=0.85.1 in d:\data\riset\mindsdb\mindsdb\lib\site-packages (from chromadb==0.3.25->-r requirements.txt (line 7)) (0.103.2)
Requirement already satisfied: uvicorn[standard]>=0.18.3 in d:\data\riset\mindsdb\mindsdb\lib\site-packages (from chromadb==0.3.25->-r requirements.txt (line 7)) (0.23.2)
Requirement already satisfied: posthog>=2.4.0 in d:\data\riset\mindsdb\mindsdb\lib\site-packages (from chromadb==0.3.25->-r requirements.txt (line 7)) (3.0.2)
Requirement already satisfied: onnxruntime>=1.14.1 in d:\data\riset\mindsdb\mindsdb\lib\site-packages (from chromadb==0.3.25->-r requirements.txt (line 7)) (1.16.1)
Requirement already satisfied: tokenizers>=0.13.2 in d:\data\riset\mindsdb\mindsdb\lib\site-packages (from chromadb==0.3.25->-r requirements.txt (line 7)) (0.14.1)
Requirement already satisfied: tqdm>=4.65.0 in d:\data\riset\mindsdb\mindsdb\lib\site-packages (from chromadb==0.3.25->-r requirements.txt (line 7)) (4.66.1)
Requirement already satisfied: typing-extensions>=4.5.0 in d:\data\riset\mindsdb\mindsdb\lib\site-packages (from chromadb==0.3.25->-r requirements.txt (line 7)) (4.8.0)
Requirement already satisfied: overrides>=7.3.1 in d:\data\riset\mindsdb\mindsdb\lib\site-packages (from chromadb==0.3.25->-r requirements.txt (line 7)) (7.4.0)
Requirement already satisfied: transformers<5.0.0,>=4.6.0 in d:\data\riset\mindsdb\mindsdb\lib\site-packages (from sentence_transformers==2.2.2->-r requirements.txt (line 9)) (4.34.0)
Requirement already satisfied: torch>=1.6.0 in d:\data\riset\mindsdb\mindsdb\lib\site-packages (from sentence_transformers==2.2.2->-r requirements.txt (line 9)) (2.1.0)
Requirement already satisfied: torchvision in d:\data\riset\mindsdb\mindsdb\lib\site-packages (from sentence_transformers==2.2.2->-r requirements.txt (line 9)) (0.16.0)
Requirement already satisfied: scikit-learn in d:\data\riset\mindsdb\mindsdb\lib\site-packages (from sentence_transformers==2.2.2->-r requirements.txt (line 9)) (1.3.1)
Requirement already satisfied: scipy in d:\data\riset\mindsdb\mindsdb\lib\site-packages (from sentence_transformers==2.2.2->-r requirements.txt (line 9)) (1.11.3)
Requirement already satisfied: sentencepiece in d:\data\riset\mindsdb\mindsdb\lib\site-packages (from sentence_transformers==2.2.2->-r requirements.txt (line 9)) (0.1.99)
Requirement already satisfied: huggingface-hub>=0.4.0 in d:\data\riset\mindsdb\mindsdb\lib\site-packages (from sentence_transformers==2.2.2->-r requirements.txt (line 9)) (0.17.3)
Requirement already satisfied: certifi>=2022.12.7 in d:\data\riset\mindsdb\mindsdb\lib\site-packages (from writerai==0.30.1->-r requirements.txt (line 16)) (2023.7.22)
INFO: pip is looking at multiple versions of writerai to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r requirements.txt (line 4) and writerai==0.30.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    langchain 0.0.267 depends on dataclasses-json<0.6.0 and >=0.5.7
    writerai 0.30.1 depends on dataclasses-json>=0.6.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

image

**Comment by dusvyat** [comment]
@maulanaakbardj please remove `writerai`, it is not a required dependency for the handler AFAIK.

You are seeing the dep clash as you added `writerai` to the handler `requirements.txt`

Please checkout `staging` branch, using an venv with python >= 3.9, install writer `requirements.txt` after installing main mindsdb `requirements.txt`

**Comment by maulanaakbardj** [comment]
@dusvyat , I've removed `writerai`

**Comment by maulanaakbardj** [comment]
@dusvyat , I followed your instructions to install "writer requirements.txt" after installing "main mindsdb requirements.txt." However, there were some dependency conflicts when running:

For `pip install -r mindsdb/integrations/handlers/writer_handler/requirements.txt`:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behavior is the source of the following dependency conflicts.
mindsdb 23.10.2.0 requires duckdb==0.6.1, but you have duckdb 0.7.1 which is incompatible.
```


For `pip install writerai`:
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behavior is the source of the following dependency conflicts.
dataprep-ml 0.0.18 requires dataclasses-json<0.6.0,>=0.5.4, but you have dataclasses-json 0.6.1 which is incompatible.
langchain 0.0.267 requires dataclasses-json<0.6.0,>=0.5.7, but you have dataclasses-json 0.6.1 which is incompatible.
mindsdb 23.10.2.0 requires duckdb==0.6.1, but you have duckdb 0.7.1 which is incompatible.
mindsdb 23.10.2.0 requires pyparsing==2.3.1, but you have pyparsing 3.1.1 which is incompatible.
type-infer 0.0.15 requires dataclasses-json<0.6.0,>=0.5.4, but you have dataclasses-json 0.6.1 which is incompatible.
```

Despite these dependency conflicts, I was still able to successfully test the Writer.ai ML integration in MindsDB.

**Comment by maulanaakbardj** [comment]
I thought that even though there were some dependency conflicts when installing `mindsdb/integrations/handlers/writer_handler/requirements.txt`, it didn't seem to affect the results of testing the Writer.ai ML integration in MindsDB. So, I'm **reverting back to the original state** for `mindsdb/integrations/handlers/writer_handler/requirements.txt`.

**Comment by dusvyat** [comment]
@maulanaakbardj thanks for your diligence! Are we good to  merge and close this PR?

**Comment by maulanaakbardj** [comment]
> @maulanaakbardj thanks for your diligence! Are we good to merge and close this PR?

Yeah, this PR can be merged. Thanks @dusvyat

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
