### PR TITLE
Add car prices Tutorial

### PR DESCRIPTION
**Pull request by Pipboyguy**
Signed-off-by: Marcel Coetzee <marcelcoetzee@tutanota.com>

### CODE REVIEW

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by Pipboyguy** [comment]
recheck

**Comment by Pipboyguy** [comment]
@ZoranPandovski

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
No idea why it doesn't trigger the CLA, let's sign in another PR :)

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
