### PR TITLE
Fix file upload link in retrain doc page

### PR DESCRIPTION
**Pull request by ujwalkumar1995**
## Description

Fixed the link in retrain doc page

**Fixes** #4507 

## Type of change

(Please delete options that are not relevant)
- [x] 📄 This change requires a documentation update

### What is the solution?

Fixed the link as suggested in the issue description.

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation, or created issues to update them.
- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@ujwalkumar1995
Before I can merge your PR, please sign our CLA, as mentioned above. Thanks.

**Comment by ujwalkumar1995** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
