### PR TITLE
oracledb version updated from 1.0.2 to 2.4.1

### PR DESCRIPTION
**Pull request by divyakhatiyan**
## Description

Currently the version of oracledb version is 1.0.2, which is not compatible with Python 3.11 and throwing error when installing the oracle handler.

Fixes #issue_number
https://github.com/mindsdb/mindsdb/issues/9798#event-14631930043

## Type of change
- [x] 🐛 Bug fix (non-breaking change which fixes an issue)
oracledb Version has been upgraded from 1.0.2 to 2.4.1 in requirements.txt file
This version is compatible with all the required python versions. Details are in https://github.com/mindsdb/mindsdb/issues/9798#event-14631930043

## Verification Process

To ensure the changes are working as expected:

 - [x]   Test Location: [Specify the URL or path for testing.](https://github.com/mindsdb/mindsdb/issues/9798#event-14631930043)
 - [x]   Verification Steps: Upgraded the oracledb version from 1.0.2 to 2.4.1 and tested the oracle handler installation on local system, URL: https://github.com/mindsdb/mindsdb/issues/9798#event-14631930043 contains all the logs and screenshots as testing evidence. 

## Additional Media:

- [x] I have attached a brief loom video or screenshots showcasing the new functionality or change.
Video and screenshots are available at https://github.com/mindsdb/mindsdb/issues/9798#event-14631930043

## Checklist:

- [Yes ] My code follows the style guidelines(PEP 8) of MindsDB. 
- [Yes ] I have appropriately commented on my code, especially in complex areas.
- [Seems to be part of regular maintenance ] Necessary documentation updates are either made or tracked in issues.
- [config change- change in test not required ] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Comment by mindsdbadmin** [comment]
<br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb/blob/main/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request. </sub><sub>Posted by the **CLA Assistant Lite bot**.</sub>

**Comment by divyakhatiyan** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by divyakhatiyan** [comment]
recheck

**Comment by divyakhatiyan** [comment]
Opening another pull request therefore marking it as closed

**Pull request closed without merging**
