### PR TITLE
Add Article To `Tutorials.md` 

### PR DESCRIPTION
**Pull request by alissatroiano**
Fixes #3095 

### File Changed: 
- `docs/mindsdb-docs/docs/tutorials.md`
### Type of Change:
  - Addition
### Details: 
- Added new article to `tutorials.md` list
     - Article:  [Self-Service Machine Learning with Intelligent Databases](https://medium.com/mindsdb/self-service-machine-learning-with-intelligent-databases-ea628aa85f1e)
     - Author:  [MindsDB Team](https://medium.com/@mindsdbteam) to `tutorials.md`
     - [x] Links to article included
     - [x] Links to author included 

## Screenshots:

tutorial-2

### CODE REVIEW

**Comment by alissatroiano** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by ZoranPandovski** [comment]
recheckcla

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
