### PR TITLE
[Intercom] Implemented conversations table

### PR DESCRIPTION
**Pull request by ritwickrajmakhal**
## Description

Implemented `Conversations` table for intercom handler.

## Type of change

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] 📄 This change requires a documentation update

## Verification Process
refer #8274

### SELECT
image

### WHERE
Screenshot from 2023-11-13 22-21-34

### INSERT
image

### UPDATE
image
- [x] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have appropriately commented on my code, especially in complex areas.
- [x] Necessary documentation updates are either made or tracked in issues.
- [x] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Review by MinuraPunchihewa — CHANGES_REQUESTED** [review]
Hey @ritwickrajmakhal,
This looks good.
Would it be possible for us to structure the output though? I am referring to columns like `first_contact_reply`.

**Comment by ritwickrajmakhal** [comment]
Hey @MinuraPunchihewa, thanks for the review, But actually I am having my University exam from 1st of December. I should make all the changes after 21th of December, till then please bear with me 🙌.

**Comment by MinuraPunchihewa** [comment]
@ritwickrajmakhal Understood. This should be fine.

**Comment by MinuraPunchihewa** [comment]
Hey @ritwickrajmakhal,
I was just wondering why this was closed? Did you face some sort of problem?

**Comment by ritwickrajmakhal** [comment]
I have created this handler using a 15 days free trial of intercom, now my trial has ended. Can you help me with an API key which has the subscription of intercom?

**Comment by MinuraPunchihewa** [comment]
@ZoranPandovski Do we happen to have an API key already?

**Pull request closed without merging**
