### PR TITLE
Initial Google Analytics Handler 

### LINKED ISSUE #7948: [Integration] Integrate Google Analytics with MindsDB
The goal of this issue is to build a new handler that will utilize the Google Analytics API to connect MindsDB to Google Analytics.

## Resources :bulb: 

:checkered_flag: To get started, please refer to the following resources:

* :books:  [Building Application Handler docs](https://docs.mindsdb.com/contribute/app-handlers): This documentation will guide you through the process of building a custom handler for MindsDB. It contains essential information on the handler structure, methods, and best practices.

* :book:  [Google Analytics API](https://developers.google.com/analytics/?sjid=14531705457468543723-EU)

* :point_right: [Twitter Handler](https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/twitter_handler): This existing handler connects MindsDB with the Twitter API, allowing users to automate tasks related to posting and analyzing tweets. You can use the Twitter Handler as a reference for building the Slack API integration.

*  :point_right:  [Binance API Handler](https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/binance_handler): Another example of a successful MindsDB integration to the Binance API to make trade data available to use for model training and predictions.

## Next Steps :male_detective: :female_detective: 
 
-   You can familiarize yourself with the Google Analytics API.
-   Create a new handler that connects MindsDB to Google Analytics.
-   Implement the core features mentioned above.
-   Thoroughly test the integration to ensure proper functionality.
-   Submit a pull request with the new Google Analytics Integration handler.

## :loudspeaker: Additional rewards :trophy:

Each App integration brings :five: :zero:  : points for SWAG and entry into the draw for a  :point_down: :
- :computer:  [Razer Blade 16 Laptop](https://www.razer.com/gaming-laptops/Razer-Blade-16/RZ09-0483SEJ3-R3U1)
- :shirt: :bear:  [MindsDB Swag](https://store.covver.io/mindsdb/collections/swag-collection)
:information_source: For more info check out https://mindsdb.com/hacktoberfest/ :point_left:

### PR DESCRIPTION
**Pull request by TalaatHasanin**
## Description

Initial commit for google analytics handler, I've added select statement 

Fixes #7948

## Type of change

(Please delete options that are not relevant)

- [x] ⚡ New feature (non-breaking change which adds functionality)
- [x] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [x]   Test Location: Specify the URL or path for testing.
 - [x]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [x] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have appropriately commented on my code, especially in complex areas.
- [x] Necessary documentation updates are either made or tracked in issues.
- [x] Relevant unit and integration tests are updated or added.

Screenshot from 2024-01-06 19-54-00

### CODE REVIEW

**Review by MinuraPunchihewa — CHANGES_REQUESTED** [review]
Hey @TalaatHasanin,
This looks great!
A few notes to get this ready to merge,
1. Can we please make it so that the credentials can also be passed as a URL? By using a parameter called `credentials_url`? You might be able to use this [utility](https://github.com/mindsdb/mindsdb/blob/staging/mindsdb/integrations/handlers/utilities/auth_utilities/google_oauth_utilities.py) that we've developed for authenticating through Google.
2. I think you can move the logic for creating and getting conversion events to the `ConversionEventsTable`. I feel that the logic belongs there. We can then remove the `call_application_api()` function as well.
3. It looks like there are a couple of CI checks failing: there are seem to be a couple of unused dependencies and then a few basic flake issues.
4. I see a few `print()` statements, specifically in the tests. Can we please remove these and use the logger if you do want to print something out?
5. This is more of a question, but it looks like there is a PROPERTY_ID value hard-coded in the tests. Is this a sensitive value? If so, let's remove it.

**Comment by TalaatHasanin** [comment]
Is there is something I have to do to solve failed checks? @ZoranPandovski

**Comment by TalaatHasanin** [comment]
ok @MinuraPunchihewa I'll check that

**Comment by TalaatHasanin** [comment]
Can I skip `credentials_url` for now as I'm using service account credentials and it's different from oauth credentials?
just skip for hashnode hackathon purposes and I'll continue working on it 
@MinuraPunchihewa

**Comment by MinuraPunchihewa** [comment]
@TalaatHasanin Oh, yes. My bad. We don't have to go the OAuth route. Let's stick with this. In that case, we can provide the option of providing the content of the service account keys as a JSON. This has already been implemented in the [BigQuery handler](https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/bigquery_handler).

I think this implementation will be easier, but if you want to skip it, that's completely fine, but please do me the favor of opening up an issue for it, so that it can be done later.

**Comment by TalaatHasanin** [comment]
@MinuraPunchihewa Can you review my last commit?

1- note that `requirements.txt` have the required packages to handle google analytics admin api, these packages are not callable with their names it called with something like `import google.analytics` 
2- I've skipped the `credentials_file` parameter for now but I'll work on it after the hackathon
3- I can't move the logic of get and create conversion events methods as it require `self.property_id` handler parameter so I make them more readable by merge the common logic in two separates method, one of them is a static method

**Comment by MinuraPunchihewa** [comment]
Hey @hamishfagg,
How can we resolve `check_requirements` check that is failing here? As @TalaatHasanin has mentioned, the package in question here is called `google-analytics-admin`, however, it is imported as `from google.analytics.admin_v1beta import ...`. Does our CI take this into account?

**Review by MinuraPunchihewa — CHANGES_REQUESTED** [review]
Hey @TalaatHasanin,
1. I have tagged our DevOps team here, hopefully they should be able to help us with this.
2. That is fine. It need not be a URL, rather just the ability to pass the content as JSON.
3. I think you can accomplish this by creating a `get_property_id()` or `get_url()` function in the handler to either return the `property_id` directly or as a complete URL that it is used to build. I believe the function relating to conversion events can then be moved to `ConversionEventsTable`. It's not really a question of readability, but rather where the logic belongs. Plus, it is my personal opinion that the use of `call_application_api()` where the name of a method is passed and then that method is called within it is quite hacky.
4. I see that you have removed some of your tests from before. Is there a reason for this?
5. You have removed the `PROPERTY_ID` variable, but it is still passed as a connection parameter. Is this a sensitive value? If not, you can keep it as is.

**Comment by TalaatHasanin** [comment]
1- Do you mean move these lines wih their methods to `google_analytics_tables.py`?
2- Can you explain me `get_property_id` method, I think the user have to get that property id to start interacting with GA4
photo_2024-01-09_13-19-57

**Comment by hamishfagg** [comment]
Hey @TalaatHasanin , can you please add a mapping to our requirements checking script under this line: https://github.com/mindsdb/mindsdb/blob/aa3078b94010283d4eeb4f0f12b10c8ed7a508bf/tests/scripts/check_requirements.py#L71

Your added line will need to look like: `"google-analytics-admin": ["google"]`

That should fix the `check_requirements` job

**Comment by MinuraPunchihewa** [comment]
> Hey @TalaatHasanin , can you please add a mapping to our requirements checking script under this line:
> 
> https://github.com/mindsdb/mindsdb/blob/aa3078b94010283d4eeb4f0f12b10c8ed7a508bf/tests/scripts/check_requirements.py#L71
> 
> Your added line will need to look like: `"google-analytics-admin": ["google"]`
> 
> That should fix the `check_requirements` job

Thank you, @hamishfagg!

**Comment by MinuraPunchihewa** [comment]
> @MinuraPunchihewa 1- Do you mean move these lines wih their methods to `google_analytics_tables.py` and just return `result` ? 2- Can you explain me `get_property_id` method, I think the user have to get that property id to start interacting with GA4, the user can't access data with the property id only, he must have the creds file too. photo_2024-01-09_13-19-57

Hey @TalaatHasanin,
I am suggesting that you move the following methods to the `ConversionEventsTable` class in google_analytics_tables.py : `get_conversion_events()`, `create_conversion_event()`, `update_conversion_event()` and `delete_conversion_event()`.

As you have correctly said, both the property ID and an auth object created using the creds file is needed to run these methods. So, I think you can do it like this:

Introduce a method called `get_property_id()` to the handler class (`GoogleAnalyticsHandler`). It will simply return the property_id when called:
```
get_property_id(self):
  return self.property_id
```

Now, you can use this method and the `connect()` method of the handler within the other methods that have been moved. The get_conversion_events() can now look as follows:

```
    def get_conversion_events(self, params: dict = None) -> pd.DataFrame:
        """
        Get conversion events from Google Analytics Admin API
        Args:
            params (dict): query parameters
        Returns:
            DataFrame
        """
        service = self.handler.connect()
        property_id = self.handler.get_property_id()
        page_token = None

        while True:
            request = ListConversionEventsRequest(parent=f'properties/{property_id}',
                                                  page_token=page_token, **params)
            result = service.list_conversion_events(request)

            page_token = result.next_page_token
            if not page_token:
                break
        return result
```
Does this make sense? I see that the property ID is essentially used as part of the URL endpoint for the above method. Therefore, you can even create a `get_api_url()` method instead in the handler:
```
get_api_url(self, endpoint):
  return f'{endpoint}/{property_id}'
```
Let me know if anything is unclear.

By the way, a new flake issue is being flagged after your updates to `check_requirements.py`. That will need to be resolved as well.

**Comment by TalaatHasanin** [comment]
Can you check the last one @MinuraPunchihewa

**Review by MinuraPunchihewa — CHANGES_REQUESTED** [review]
Hey @TalaatHasanin,
This looks great! I just have a few final comments,
1. Let's move get_api_url() to the handler, because I think we might re-use this if we decide to add other tables.
2. In a previous commit you made, I saw a lot more comprehensive tests for your handler, can we add them back? Essentially, I think we need to add a few more comprehensive tests.
3. Finally, lets just confirm (either by running the tests or through manual validation) that everything works fine after all the refactoring that you have done.

**Comment by TalaatHasanin** [comment]
check this @MinuraPunchihewa

**Comment by TalaatHasanin** [comment]
I've added the readme file and docs for this integration
@MinuraPunchihewa

**Comment by torrmal** [comment]
can you also add in the docs, so that it shows in the datasources/overview.mdx

**Comment by TalaatHasanin** [comment]
Done 👍 @torrmal

**Review by MinuraPunchihewa — APPROVED** [review]

**Comment by MinuraPunchihewa** [comment]
Great work, @TalaatHasanin! Please, if you could, open an issue for adding that JSON parameter, so that we don't forget about it.

**Comment by TalaatHasanin** [comment]
> Great work, @TalaatHasanin! Please, if you could, open an issue for adding that JSON parameter, so that we don't forget about it.

Thanks @MinuraPunchihewa , yes I will

**Pull request merged**
