### PR TITLE
Solved issue#5572

### PR DESCRIPTION
**Pull request by harshkanani204**
## Description

Please include a summary of the change and the issue it solves. 

**Fixes** #(issue)

## Type of change
Solved issue Add `tdengine` to the docs navigation#5572

### What is the solution?
Added the `tdengine` file as the last item to the `"pages"` in the `"Data Integrations"` group(at line 310 in `docs\mint.json`)

### CODE REVIEW

**Comment by harshkanani204** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by harshkanani204** [comment]
recheck

**Comment by harshkanani204** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
