### PR TITLE
Initial implementation of Webz Application Handler

### PR DESCRIPTION
**Pull request by rmaceissoft**
## Description

Initial implementation of the Webz Handler

**Fixes** #5644

## Type of change

- [x] ⚡ New feature (non-breaking change which adds functionality)

### Implemented Features

Retrieve the following data from Webz.io
- [x] News articles, blog posts and online discussions
- [x] Reviews

Supported the following SQL clauses:
- [x] LIMIT
- [x] WHERE
- [x] ORDER_BY
- [x] Column Selection

## Video or screenshots

- https://www.loom.com/share/1b38820ce55d4a72ba91a1c2a7340e7a?sid=81c9e904-c832-492e-a842-156dfb6d6047

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation, or created issues to update them.
- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by rmaceissoft** [comment]
Hi @tmichaeldb 👋 
thanks for reviewing the PR. I just pushed the requested changes.

**Comment by rmaceissoft** [comment]
TODOs (for future reference): 

- [ ] Allow to filter results by GET param `timestamp` 
  - [ ] News, Blogs, Discussions (https://docs.webz.io/reference#get-parameters)
  - [ ] Review (https://docs.webz.io/reference#data-segmentation-1)
- [ ] Add support for Data Segmentation API:
  - [ ] News, Blogs, Discussions ((https://docs.webz.io/reference#data-segmentation))
  - [ ] Reviews (https://docs.webz.io/reference#data-segmentation-1)

**Pull request merged**
