### PR TITLE
add SQL format style to doc per issue #2947

### LINKED ISSUE #2947: Add SQL format style for all SQL commands/keywords in the MindsDB docs
Throughout the documentation pages at [MindsDB docs](https://docs.mindsdb.com/), there are SQL commands and keywords used. In the `.md` files, some of them are written as _\`SQL COMMAND\`_ instead of _\`#!sql SQL COMMAND\`_. The _#!sql_ prefix ensures that the SQL style is used.

The task is to go over all the doc pages and add the _#!sql_ prefix.

**Example 1:**
Take this text:
> You can now preview the available data with a standard \`SELECT\` statement.

And change it to:
> You can now preview the available data with a standard \`#!sql SELECT\` statement.

**Example 2:**
Take this text:
> Click on the \`ADD DATABASE\` button.

And change it to:
> Click on the \`#!sql ADD DATABASE\` button.

### PR DESCRIPTION
**Pull request by sanittawan**
Fixes #2947 (only one fix to a single doc file to start. But more needs to be done later)

## Please describe what changes you made, in as much detail as possible
  - I added a prefix `!#sql` to a SQL command `WHERE` on line 84 in `what-is-mindsdb.md` file

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheck

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   **wb571025** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by sanittawan** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ZoranPandovski** [comment]
Thanks @sanittawan, please once you add the email just post `I have read the CLA Document and I hereby sign the CLA`  :raised_hands:

**Comment by sanittawan** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by sanittawan** [comment]
I'm sorry I'm not sure how to fix the CLA issue.

**Comment by ZoranPandovski** [comment]
All good, you have signed it now

**Review by ZoranPandovski — APPROVED** [review]

**Comment by sanittawan** [comment]
Thanks @ZoranPandovski

**Pull request merged**
