### PR TITLE
Issue #3179 Added Tutorial to predict the type of glass

### LINKED ISSUE #3179: Tutorial to Predict the Type of Glass
## Task Description
Create a predictor to predict the type of glass based on its refractive index and the elements it contains.

Use the `glass.csv` dataset available at https://www.kaggle.com/datasets/danushkumarv/glass-identification-data-set.

## :loudspeaker: Additional rewards :trophy:

Each tutorial brings :three: points and entry into the draw for a  :point_down: :

-  :computer:  [Razer Blade 15 Laptop](https://www.razer.com/hard-bundles/Razer-Blade-15-Bundle-V5-Essential/RZHB-220912-11)
- :headphones:  10 cool audio gadgets 
- :shirt: :bear: MindsDB Swag
:information_source: For more info check out https://mindsdb.com/hacktoberfest/ :point_left:

### PR DESCRIPTION
**Pull request by botketan**
Added Tutorial to predict the type of glass using MindsDB

Fixes #3179 

## Please describe what changes you made, in as much detail as possible
  Added a tutorial on how to predict the type of glass using MindsDB

mindsdb

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
recheck

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
recheck

**Comment by botketan** [comment]
Has the PR gone through sorry i am a bit new to this stuff

**Comment by botketan** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by botketan** [comment]
@ZoranPandovski  Please merge this or let me know if something is wrong

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
recheckcla

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
