### PR TITLE
Trino ldap

### PR DESCRIPTION
**Pull request by bachng2017**
Fixes #

- add http_scheme and basic auth (password) to trino handler/integration
- fix engine name in the document

sample config with http_scheme and basic auth
```
CREATE DATABASE trino_datasource
WITH ENGINE='trino',
PARAMETERS={
  "user": "trino_user",
  "http_scheme": "https",
  "port": 443,
  "password": "trino_password",
  "host": "trino_host",
  "catalog": "trino_catalog",
  "schema": "trino_schema"
};
```

### CODE REVIEW

**Comment by bachng2017** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by bachng2017** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by bachng2017** [comment]
seems to be a duplicate of #2587

**Comment by bachng2017** [comment]
recheck

**Comment by bachng2017** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by bachng2017** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ZoranPandovski** [comment]
Thaks @bachng2017 there is a bug with the CLA bot but you already signed it. If this is ready for review feel free to move it from draft

**Comment by bachng2017** [comment]
thanks @ZoranPandovski , yes I've struggleg how to pass the tests (because the change seems not to be relevant to the fails). Please take a review when you are available (also imho the test actions also need to be improved)

**Review by ZoranPandovski — APPROVED** [review]
Thanks, lgtm

**Pull request merged**
