### PR TITLE
Updated windows.mdx

### PR DESCRIPTION
**Pull request by vaibhavmishra4g**
Creating this for the issue #5657 
I have read the CLA Document and I hereby sign the CLA

## Description

Please include a summary of the change and the issue it solves. 

**Fixes** #5657

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@vaibhavmishra4g 
If you want to have your PR merged, please sign our CLA by leaving a comment here that contains this line: I have read the CLA Document and I hereby sign the CLA

**Comment by martyna-mindsdb** [comment]
@vaibhavmishra4g 
Please sign it here, not on the issue.

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
