### PR TITLE
updated query in docs\nlp\question-answering-inside-mysql-with-openai.mdx

### PR DESCRIPTION
**Pull request by anjali29singh**
#6471 
## Type of change

- [ ] 📄 This change requires a documentation update

Replaced the SELECT * FROM models
WHERE name = 'question_answering_model'  in with DESCRIBE question_answering_model;
## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation, or created issues to update them.
- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@anjali29singh 
Please sign our CLA by leaving a comment here: I have read the CLA Document and I hereby sign the CLA

**Comment by anjali29singh** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by martyna-mindsdb** [comment]
@anjali29singh 
I see that you've made other changes to this file.
Please undo all the changes, except for the one that was requested in this issue.

**Comment by martyna-mindsdb** [comment]
@anjali29singh 
If you go to the `Files changed` tab of this PR, you'll see all other changes made to this file. Please undo them.

**Pull request merged**
