### PR TITLE
add cassandra

### PR DESCRIPTION
**Pull request by yenper**
## Description

**Fixes** mint.json 
Add Cassandra file

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by yenper** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by yenper** [comment]
recheck

**Comment by martyna-mindsdb** [comment]
@yenper 
Please make sure you get assigned to the issue https://github.com/mindsdb/mindsdb/issues/5088 before solving it.

Also, please include the issue number in the PR description.

**Pull request merged**
