### PR TITLE
Update implementation chapter

### PR DESCRIPTION
**Pull request by ChetanChoudhary007**
## Description

Adding the given instruction into the implementation chapter in amazon-dynamodb.mdx file

**Fixes** #(6234)

## Type of change

Adding Tip in the implementation section 

### What is the solution?

Add the given instruction at the given location or section in the document

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by martyna-mindsdb** [comment]
@ChetanChoudhary007 
Please link the issue like this: https://github.com/mindsdb/mindsdb/issues/6234

Please sign our CLA so we can merge your PR.

**Comment by ChetanChoudhary007** [comment]
issue #6234 
I have read the CLA Document and I hereby sign the CLA

**Comment by ZoranPandovski** [comment]
recheckcla

**Pull request merged**
