### PR TITLE
added openai mdx file

### PR DESCRIPTION
**Pull request by Greatvictory24**
Merging this Pull Request closes the Issue #6092

### CODE REVIEW

**Comment by Greatvictory24** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by Greatvictory24** [comment]
recheck

**Comment by Greatvictory24** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by martyna-mindsdb** [comment]
@Greatvictory24 
Please include the above review comments in the mdx file so to explain the errors that you got.

**Comment by martyna-mindsdb** [comment]
@Greatvictory24 
Are you still working on it?

**Pull request merged**
