### PR TITLE
Create aws-redshift.mdx

### PR DESCRIPTION
**Pull request by souravpy**
solved issue #4460 :  [Docs] Create a doc page for the Amazon Redshift data integration

## Description

Please include a summary of the change and the issue it solves. 

**Fixes** #(issue)

## Type of change

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📄 This change requires a documentation update

### What is the solution?

(Describe at a high level how the feature was implemented)

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation, or created issues to update them.
- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by souravpy** [comment]
Is there any additional changes or additions I need to make in this and previous .mdx files? Let me know

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
You will need to write more information about the Redsihft handler. Please check the https://docs.mindsdb.com/contribute/data-integration-page

**Comment by souravpy** [comment]
@ZoranPandovski I have updated it as proposed, kindly check : updated issue https://github.com/mindsdb/mindsdb/issues/4460 : [Docs] Create a doc page for the Amazon Redshift data integration

**Comment by ZoranPandovski** [comment]
Closing this as you have opened another https://github.com/mindsdb/mindsdb/pull/4549 PR

**Pull request closed without merging**
