### PR TITLE
Updating Getting Started Guide

### LINKED ISSUE #1671: Add links to deployments in Getting Started guide :link:
In the getting started guide add links to the Docker, PyPI, Cloud sections in docs.

>Note: We are accepting the first PR that solves the issue.

## Steps :male_detective: :female_detective: 

- Head over to https://github.com/mindsdb/mindsdb/blob/staging/docs/mindsdb-docs/docs/info.md
- Add links to Docker, PyPI, Cloud as /deployment/...

## Additional rewards :1st_place_medal: 

Each documentation PR brings :one:   point for entry into the draw for a :computer:  Deep Learning Laptop powered by the NVIDIA RTX 3080 Max-Q GPU or other swag :shirt: :bear: .  For more info check out https://mindsdb.com/hacktoberfest/

### PR DESCRIPTION
**Pull request by MichaelLantz**
Fixes #1671

## Please describe what changes you made, in as much detail as possible
  - Adding links to various deployment methods in getting started guide.

mindsdb

### CODE REVIEW

**Comment by MichaelLantz** [comment]
Gotcha will do. Thanks @ZoranPandovski .

**Comment by MichaelLantz** [comment]
Hi @ZoranPandovski based on other docs I think the new relative links I used are correct in the .md file but I get 404 errors based on the specfic URL of my commit when I test. Am I missing something or does this resolve itself once it's merged and in the staging branch?

**Comment by MichaelLantz** [comment]
Interesting I get the same error when using the link here: https://github.com/mindsdb/mindsdb/blob/staging/docs/mindsdb-docs/docs/sql/connect/cloud.md

I'll hope for the best and let smarter folks than me weigh in.

**Comment by parthiv11** [comment]
@MichaelLantz This .md files are converted to html pages where the link work best..
Dont worry ٩ ◔̯◔)۶

**Pull request merged**
