### PR TITLE
Created Doc for Google sheets.

### PR DESCRIPTION
**Pull request by thefool76**
## Description

Please include a summary of the change and the issue it solves. 

**Fixes** #(issue)
#4708
## Type of change
Added Docs for the handler.

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
@thefool76 
Please remove the Couchbase docs from this PR, as this PR is for Google Sheets.

Also, the content is duplicated in the Google-sheets.mdx file. Please fix it.

**Comment by thefool76** [comment]
ok will fix it. my bad

**Comment by paxcema** [comment]
@thefool76 can you help me understand what, exactly, was the contribution here? This seems like a copy-paste of the file contributed by another user, [here](https://github.com/mindsdb/mindsdb/blob/staging/docs/data-integrations/google-sheets.mdx).

Not only that, this PR actually broke the `staging` branch due to a name collision, so I'd really like to understand. Otherwise, as it stands, this looks to me like a violation of the code of conduct that we adhere to.

**Comment by paxcema** [comment]
@thefool76 I had to revert this contribution due to the major problems that it caused downstream in `staging`. Feel free to open another PR if you wish, and please 1) be careful with duplicated name files that differ only in casing and 2) add me as a reviewer to ensure the content is not repeated. Thanks.

**Comment by thefool76** [comment]
Sorry for the issue @paxcema. and thanks for resolving the issue 👍

**Pull request merged**
