### PR TITLE
fixed broken link in docs/custom-model/openai.mdx

### PR DESCRIPTION
**Pull request by NishitSingh2023**
## Description

changed /sql/create/predictor to /sql/create/model in docs/custom-model/openai.mdx

**Fixes** [issue](https://github.com/mindsdb/mindsdb/issues/6356)

## Type of change

- 📄 This change requires a documentation update

### What is the solution?

Replaced /sql/create/predictor to /sql/create/model in docs/custom-model/openai.mdx and fixed the broken link

## Checklist:

- My code follows the style guidelines(PEP 8) of MindsDB.
- I have commented my code, particularly in hard-to-understand areas.
- I have updated the documentation, or created issues to update them.

### CODE REVIEW

**Comment by NishitSingh2023** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   **Nishit** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by NishitSingh2023** [comment]
recheck

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by martyna-mindsdb** [comment]
@NishitSingh2023 
Please see the message above. You may have to add your email address used for this commit to your GitHub account:

**Nishit** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Pull request merged**
