### PR TITLE
Add content to the DROP JOB page

### PR DESCRIPTION
**Pull request by snorfyang**
## Description

Please include a summary of the change and the issue it solves. 

**Fixes** #5809

## Type of change

Add docs.

### CODE REVIEW

**Comment by snorfyang** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by snorfyang** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by snorfyang** [comment]
> @snorfyang There was a mistake in the issue description. These changes were supposed to be made in the `jobs.mdx` file.
> 
> Also, before creating a PR, please leave a comment on an issue and wait until we assign you. Then you can create a PR.

@martyna-mindsdb 
Sorry for the mistake:( Could you please reopen this PR? I'll cover the previous commit.

**Pull request closed without merging**
