### PR TITLE
#5081 Update a link to the Matrix One integration

### PR DESCRIPTION
**Pull request by MJMcNazir**
## Description
Update a link (in the README.md file) to the Matrix One integration

**Fixes** #5081

### CODE REVIEW

**Comment by MJMcNazir** [comment]
have read the CLA Document and I hereby sign the CLA

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@MJMcNazir 
Please sign our CLA as instructed above.

**Comment by MJMcNazir** [comment]
recheckcla

**Comment by MJMcNazir** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
