### PR TITLE
Made Changes to the rag_handler.py file

### LINKED ISSUE #8606: refactor writer handler to only query writer api and return results
## Issue Description

We should make `writer_handler` to simply query the writer api completions endpoint and remove the RAG component as `rag_handler` has this functionality

### Impact
The current implementation of the `writer_handler`  is causing confusion and redundancy in the codebase. It is not clear what the function is intended to do and how it differs from the `rag_handler`. This lack of clarity can lead to misunderstandings and potential bugs.

### PR DESCRIPTION
**Pull request by asif-reh**
## Description

RAGHandler is focused on the creation and prediction aspects of the question-answering model, while WriterEvaluator is dedicated to evaluating the performance of the model, including retrieval and generation metrics.

Fixes #8606 
## Type of change
I made some changes to the function in the rag_handler.py file.
(Please delete options that are not relevant.)

- [x] 🐛 Bug fix (non-breaking change which fixes an issue)

## Verification Process

To ensure the changes are working as expected:

 - [x]   Test Location: Specify the URL or path for testing.
 - [x]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have appropriately commented on my code, especially in complex areas.
- [x] Necessary documentation updates are either made or tracked in issues.
- [x] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Comment by dusvyat** [comment]
@asif-reh fyi the aim of https://github.com/mindsdb/mindsdb/issues/8606  is to refactor `writer_handler`, the focus shouldn't be on `rag_handler`

**Comment by asif-reh** [comment]
Ok

**Review by asif-reh — COMMENTED** [review]
In reference to LiteLLM_handler I have applied proper logic to the writer_Handler where model evalution is the difference from RAG_Handler code.

**Comment by ZoranPandovski** [comment]
Closing as outdated, please comment so we sync if you continue working on this

**Comment by dusvyat** [comment]
rag_handler is deprecated, no issue closing this @ZoranPandovski

**Pull request closed without merging**
