### PR TITLE
Add Oracle DB handler

### LINKED ISSUE #2330: [New Integration]:  👀👀 Oracle Database Integration 👍👍
### Is there an existing integration?

- [X] I have searched the existing integrations.

## Oracle is the most used  Database in the Industry
As it is the most popular SQL database it should be in the integration of MindsDB.

- It would help developers to implement In database AI.
- It would make a headache for developers to implement ML.

### Motivation

As a developer, I think for my developers **`Friends`** and their problems to implement AI.
 As most of the industry is using oracle as it is  `easy + popular`  database .

And it would be great to get a model with an `account + few clicks on the buttons` and ready to predict and use AI Tables in Database.

### Implementation

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by eskarimov**
Fixes #2330 

The PR intends to add Oracle DB integration.

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   ***I have read the CLA Document and I hereby sign the CLA***
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by eskarimov** [comment]
**I have read the CLA Document and I hereby sign the CLA**

**Comment by ZoranPandovski** [comment]
recheckcla

**Review by ZoranPandovski — APPROVED** [review]
Thanks, looks great

**Review by StpMax — APPROVED** [review]
looks fine

**Pull request merged**
