### PR TITLE
PyCaret Integration

### PR DESCRIPTION
**Pull request by MinuraPunchihewa**
This is a draft PR to understand where I am going wrong and what can be imporoved.

I have added an initial integration to handle classification tasks. However, when I try to run `CREATE PREDICTOR` statements, I get the following error,

```
2022-10-14 22:08:04,295 - INFO - Traceback (most recent call last):
  File ".\mindsdb\api\http\namespaces\sql.py", line 35, in post
    result = mysql_proxy.process_query(query)
  File ".\mindsdb\api\mysql\mysql_proxy\mysql_proxy.py", line 490, in process_query
    executor.query_execute(sql)
  File ".\mindsdb\api\mysql\mysql_proxy\executor\executor.py", line 110, in query_execute
    self.do_execute()
  File ".\mindsdb\api\mysql\mysql_proxy\executor\executor.py", line 221, in do_execute
    ret = self.command_executor.execute_command(self.query)
  File ".\mindsdb\api\mysql\mysql_proxy\executor\executor_commands.py", line 475, in execute_command
    return self.answer_create_predictor(statement)
  File ".\mindsdb\api\mysql\mysql_proxy\executor\executor_commands.py", line 806, in answer_create_predictor
    ml_handler = self.session.integration_controller.get_handler(ml_integration_name)
  File ".\mindsdb\utilities\with_kwargs_wrapper.py", line 43, in wrapper
    return method(*args, **kwargs)
  File ".\mindsdb\interfaces\database\integrations.py", line 284, in get_handler
    connection_data = integration_data.get('connection_data', {})
AttributeError: 'NoneType' object has no attribute 'get'

2022-10-14 22:08:04,432 - ERROR - http exception: index 0 is out of bounds for axis 0 with size 0
Traceback (most recent call last):
  File "C:\Users\minurap\Anaconda3\envs\mindsdb_sc\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\minurap\Anaconda3\envs\mindsdb_sc\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\minurap\Anaconda3\envs\mindsdb_sc\lib\site-packages\flask_restx\api.py", line 403, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\minurap\Anaconda3\envs\mindsdb_sc\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\minurap\Anaconda3\envs\mindsdb_sc\lib\site-packages\flask_restx\resource.py", line 49, in dispatch_request
    resp = meth(*args, **kwargs)
  File ".\mindsdb\api\http\namespaces\analysis.py", line 96, in post
    data_frame=DataFrame(data, columns=column_names)
  File ".\mindsdb\integrations\handlers\lightwood_handler\lightwood_handler\lightwood_handler.py", line 188, in analyze_dataset
    analysis = lightwood.analyze_dataset(data_frame)
  File "C:\Users\minurap\Anaconda3\envs\mindsdb_sc\lib\site-packages\lightwood\api\high_level.py", line 125, in analyze_dataset
    problem_definition = ProblemDefinition.from_dict({'target': str(df.columns[0])})
  File "C:\Users\minurap\Anaconda3\envs\mindsdb_sc\lib\site-packages\pandas\core\indexes\base.py", line 4604, in __getitem__
    return getitem(key)
IndexError: index 0 is out of bounds for axis 0 with size 0
2022-10-14 22:08:04,467 - ERROR - [2022-10-14 22:08:04,460] ERROR in app: Exception on /api/analysis/data [POST]
Traceback (most recent call last):
  File "C:\Users\minurap\Anaconda3\envs\mindsdb_sc\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\minurap\Anaconda3\envs\mindsdb_sc\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\minurap\Anaconda3\envs\mindsdb_sc\lib\site-packages\flask_restx\api.py", line 403, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\minurap\Anaconda3\envs\mindsdb_sc\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\minurap\Anaconda3\envs\mindsdb_sc\lib\site-packages\flask_restx\resource.py", line 49, in dispatch_request
    resp = meth(*args, **kwargs)
  File ".\mindsdb\api\http\namespaces\analysis.py", line 96, in post
    data_frame=DataFrame(data, columns=column_names)
  File ".\mindsdb\integrations\handlers\lightwood_handler\lightwood_handler\lightwood_handler.py", line 188, in analyze_dataset
    analysis = lightwood.analyze_dataset(data_frame)
  File "C:\Users\minurap\Anaconda3\envs\mindsdb_sc\lib\site-packages\lightwood\api\high_level.py", line 125, in analyze_dataset
    problem_definition = ProblemDefinition.from_dict({'target': str(df.columns[0])})
  File "C:\Users\minurap\Anaconda3\envs\mindsdb_sc\lib\site-packages\pandas\core\indexes\base.py", line 4604, in __getitem__
    return getitem(key)
IndexError: index 0 is out of bounds for axis 0 with size 0

2022-10-14 22:08:04,475 - ERROR - ERROR:mindsdb.api.http.initialize:Exception on /api/analysis/data [POST]
Traceback (most recent call last):
  File "C:\Users\minurap\Anaconda3\envs\mindsdb_sc\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\minurap\Anaconda3\envs\mindsdb_sc\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\minurap\Anaconda3\envs\mindsdb_sc\lib\site-packages\flask_restx\api.py", line 403, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\minurap\Anaconda3\envs\mindsdb_sc\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\minurap\Anaconda3\envs\mindsdb_sc\lib\site-packages\flask_restx\resource.py", line 49, in dispatch_request
    resp = meth(*args, **kwargs)
  File ".\mindsdb\api\http\namespaces\analysis.py", line 96, in post
    data_frame=DataFrame(data, columns=column_names)
  File ".\mindsdb\integrations\handlers\lightwood_handler\lightwood_handler\lightwood_handler.py", line 188, in analyze_dataset
    analysis = lightwood.analyze_dataset(data_frame)
  File "C:\Users\minurap\Anaconda3\envs\mindsdb_sc\lib\site-packages\lightwood\api\high_level.py", line 125, in analyze_dataset
    problem_definition = ProblemDefinition.from_dict({'target': str(df.columns[0])})
  File "C:\Users\minurap\Anaconda3\envs\mindsdb_sc\lib\site-packages\pandas\core\indexes\base.py", line 4604, in __getitem__
    return getitem(key)
IndexError: index 0 is out of bounds for axis 0 with size 0
```

What is going on here?

For reference, this is the statement that I ran,

```
CREATE PREDICTOR pycaret.iris_classifier
FROM s3_datasource
    (SELECT * FROM S3Object) AS obj
PREDICT variety AS variety;
```

### CODE REVIEW

**Comment by paxcema** [comment]
Hi @MinuraPunchihewa!

I believe (@ea-rus can help us confirm) the error is that the Lightwood engine is not being imported, which means data analysis -prior to your engine being called- is not working. Probably some dependency is missing from the python environment you're using to develop the PyCaret engine.

We are in the process of moving some elements (like data analysis) out of lightwood so that it doesn't force the entire package along with its heavy dependencies as requirements for any `mindsdb` installation that would not use lightwood. In the meantime, please try to install lightwood within this environment and try again 👀.

**Comment by MinuraPunchihewa** [comment]
Hey @paxcema, I believe I did have `lightwood` installed, but I think installing `pycaret` has caused some dependency conflicts. 

I looked at the `requirements.txt` file for the lightwood handler and it looks like I need to install `lightwood[all_extras] >= 22.8.1.0`. When I tried that, I get the following,
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
yellowbrick 1.3.post1 requires numpy<1.20,>=1.16.0, but you have numpy 1.21.6 which is incompatible.
pycaret 2.3.10 requires numba<0.55, but you have numba 0.56.3 which is incompatible.
pycaret 2.3.10 requires scikit-learn==0.23.2, but you have scikit-learn 1.0.2 which is incompatible.
jupyter-client 7.4.2 requires python-dateutil>=2.8.2, but you have python-dateutil 2.8.0 which is incompatible.
```
Any ideas how to circumvent this?

**Comment by paxcema** [comment]
Hmm, this is a tricky issue. We will internally discuss how to let the data analysis call to fail, as a temporal fix while the component is moved out of lightwood. Hopefully it is a quick fix. 

In the meantime, I'm afraid my suggestion is to either wait or manually try to find a set of dependencies where importing both lightwood and pycaret works, for which there is no guarantee a solution exists :/.

**Comment by MinuraPunchihewa** [comment]
@paxcema Thank you for your response! Please let me know if you do find a fix for the data analysis component.

I will see what I can do from my end as well.

**Comment by MinuraPunchihewa** [comment]
Hey @paxcema,
This sounds great! I will definitely give this another shot. I will keep you updated on the progress.

**Comment by ZoranPandovski** [comment]
Closing as duplicate of https://github.com/mindsdb/mindsdb/pull/5229

**Pull request closed without merging**
