### PR TITLE
Added FirestoreDB Integration

### PR DESCRIPTION
**Pull request by shivam-dhaka**
## Description

Please include a summary of the change and the issue it solves. 

Fixes [#8046](https://github.com/mindsdb/mindsdb/issues/8046)

## Type of change

(Please delete options that are not relevant)

- [x] ⚡ New feature (non-breaking change which adds functionality)
- [x] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [x]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [x] I have attached a brief loom video or screenshots showcasing the new functionality or change.
firestore_createdb
firestore_select
firestore_update

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have appropriately commented on my code, especially in complex areas.
- [x] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Comment by MinuraPunchihewa** [comment]
Hey @shivam-dhaka,
If you have completed this PR, please mark it as 'Ready for review'.

**Comment by shivam-dhaka** [comment]
@MinuraPunchihewa i'm finalising the update functionality. Once done i will mark this as ready for review.

**Review by MinuraPunchihewa — CHANGES_REQUESTED** [review]
Hey @shivam-dhaka,
Sorry for the delay.
A few things that we need to complete before merging this,
1. Let's please add some unit tests for this handler.
2. Can we make it so that the credentials for the service account can be passed either as a file (which you've already done) or as a JSON object? You can refer the the [BigQuery handler](https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/bigquery_handler) to understand how this can be done.
3. This is more of a question than a request; since Firestore is a NoSQL database, is your handler able to handle nested objects? If so, please add a screenshot of this and if not, please incorporate this functionality.

Please add a couple more screenshots for the last two fixes/enhancements.

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
Hey @shivam-dhaka can you please address the above changes so we can merge this? Thanks

**Comment by shivam-dhaka** [comment]
@ZoranPandovski Sorry I forgot mention i went on a long vacation. Just came back last week. Will address the request changes. Would like to mention that getting the sub-collection/nested objects in the collection without knowing the id of the object is not supported as of now in firestore so that will be missing. I will resolve the rest of the two points and ping you guys!

**Comment by ZoranPandovski** [comment]
Closing as outdated, please comment so we sync if you continue working on this

**Pull request closed without merging**
