### PR TITLE
Added Airtable to the data-integrations group.

### PR DESCRIPTION
**Pull request by Ajneesh21**
Added Airtable to the data-integrations group.

### CODE REVIEW

**Comment by Ajneesh21** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by martyna-mindsdb** [comment]
@Ajneesh21 
Please link the issue number https://github.com/mindsdb/mindsdb/issues/5084 in the PR description.

**Pull request merged**
