### PR TITLE
corrected port value in mongo-compass

### LINKED ISSUE #6187: [Docs] Correct port value in `mongo-compass`
## Instructions

1. Go to the `docs/connect/mongo-compass.mdx` file.

2. Go to line 75 and replace `the port value is custom for your instance` with `the port value is 3306`

3. Save your changes and create a PR.

## The https://github.com/mindsdb/mindsdb/labels/first-timers-only Label

We are happy to welcome you on board! Please take a look at the rules below for first-time contributors.

1. You can solve only one issue labeled as https://github.com/mindsdb/mindsdb/labels/first-timers-only. After that, please look at other issues labeled as https://github.com/mindsdb/mindsdb/labels/good%20first%20issue, https://github.com/mindsdb/mindsdb/labels/help%20wanted, or https://github.com/mindsdb/mindsdb/labels/integration.

2. Please leave a comment on this issue and wait until you are assigned. Then you can create a PR.

3. After you create your first PR in the MindsDB repository, please sign our CLA to become a MindsDB contributor. You can do that by leaving a comment that contains the following: `I have read the CLA Document and I hereby sign the CLA`

Thank you for contributing to MindsDB!

### PR DESCRIPTION
**Pull request by DeltaProxima**
I have read the CLA Document and I hereby sign the CLA

## Description

Corrected port value in mongo-compass
resolves #6187
image

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation, or created issues to update them.
- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@DeltaProxima 
Please sign our CLA so we can merge your PR.

**Comment by DeltaProxima** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
