### PR TITLE
Issue #6523: [Docs]: Change Mongo docs user to username

### PR DESCRIPTION
**Pull request by ansarisaqlain987**
## Description

Changed the `user` parameter with `username`

**Fixes** #(issue)
Issue [#6523](https://github.com/mindsdb/mindsdb/issues/6523)

## Type of change

- [X] 🐛 Bug fix (non-breaking change which fixes an issue)

### What is the solution?

Changed the `user` parameter with `username`

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [X] I have updated the documentation, or created issues to update them.
- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by ansarisaqlain987** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ansarisaqlain987** [comment]
recheck

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
