### PR TITLE
PyCaret Integration

### PR DESCRIPTION
**Pull request by MinuraPunchihewa**
This is a draft PR for the PyCaret ML integration.

### CODE REVIEW

**Comment by MinuraPunchihewa** [comment]
Hey @paxcema,
I have created a new draft PR for the PyCaret integration. I would appreciate if you can take a look at my work.

At the same time, I am not really able to use this integration due to the following error,
```
ERROR:mindsdb.main:get_handler: import error - Pandas requires version '3.0.0' or newer of 'jinja2' (version '2.11.3' currently installed).
2023-03-27 21:41:58,461 - INFO - Traceback (most recent call last):
  File "/home/minura/PycharmProjects/mindsdb_og/./mindsdb/api/http/namespaces/sql.py", line 33, in post
    result = mysql_proxy.process_query(query)
  File "/home/minura/PycharmProjects/mindsdb_og/./mindsdb/api/mysql/mysql_proxy/mysql_proxy.py", line 488, in process_query
    executor.query_execute(sql)
  File "/home/minura/PycharmProjects/mindsdb_og/./mindsdb/api/mysql/mysql_proxy/executor/executor.py", line 116, in query_execute
    self.do_execute()
  File "/home/minura/PycharmProjects/mindsdb_og/./mindsdb/api/mysql/mysql_proxy/executor/executor.py", line 211, in do_execute
    ret = self.command_executor.execute_command(self.query)
  File "/home/minura/PycharmProjects/mindsdb_og/./mindsdb/api/mysql/mysql_proxy/executor/executor_commands.py", line 516, in execute_command
    return self.answer_create_predictor(statement)
  File "/home/minura/PycharmProjects/mindsdb_og/./mindsdb/api/mysql/mysql_proxy/executor/executor_commands.py", line 1005, in answer_create_predictor
    ml_handler = self.session.integration_controller.get_handler(
  File "/home/minura/PycharmProjects/mindsdb_og/./mindsdb/interfaces/database/integrations.py", line 333, in get_handler
    handler = DBClient(integration_engine, **handler_ars)
  File "/home/minura/PycharmProjects/mindsdb_og/./mindsdb/integrations/handlers_client/db_client_factory.py", line 23, in __call__
    return handler_class(**kwargs)
TypeError: 'NoneType' object is not callable
```

I also have the following dependency conflicts in my environment,
```
mindsdb-streams 0.1.1 requires certifi==2021.5.30, but you have certifi 2022.12.7 which is incompatible.
mindsdb-streams 0.1.1 requires requests==2.26.0, but you have requests 2.28.2 which is incompatible.
```

Could it be due to this?

I am not entirely sure what the problem is.

**Comment by paxcema** [comment]
Hey @MinuraPunchihewa!

Sure, would be happy to help you figure it out. Quick question, in the example above did you previously create an instance of the engine via `CREATE ML_ENGINE pycaret FROM pycaret`?

We're only using `mindsdb-streams` for the Kafka and Redis connectors. I think it's safe to say we're okay to continue development now and figure out the collisions once the PR is ready. Chances are, we can make those `mindsdb-streams` requirements a bit less strict.

**Comment by paxcema** [comment]
> Are you asking if I previously created another model using pycaret?

Not exactly. In case it's not clear from our documentation, once you have added an ML engine to the source code, MindsDB will try to import it and, if successful, will make it available to users. However, users still have to _register_ this ML engine before using it correctly. For this, you need to execute a query like the following:

```sql
CREATE ML_ENGINE pycaret FROM pycaret
```

At which point (if everything else goes okay) you should be able to train models through the new integration.

_However_, this bit:
> I get the log message that states that the pycaret handler cannot be used, even though the relevant dependencies have been installed.

Points back to the conflict you mention. Just to be sure, try to debug this and check for the status of the integration controller's output [here](https://github.com/mindsdb/mindsdb/blob/a19d49cc6ecd917aa6c5a53c958294f842bbd3c9/mindsdb/__main__.py#L185), by accessing the `'pycaret'` key. If there is an error that confirms the `mindsdb-stream` conflict, then please proceed with the PR and we will review ASAP 👍

**Comment by MinuraPunchihewa** [comment]
> ```sql
> CREATE ML_ENGINE pycaret FROM pycaret
> ```
Damn, I was not aware of this. Thank you so much for the information. Apologies, I seem to have missed that.

Yes, I will take a look at `mindsdb-stream` and open a PR.

**Comment by ZoranPandovski** [comment]
Hey Minura, what is the status here?

**Comment by MinuraPunchihewa** [comment]
Hey @ZoranPandovski,
I've put this hold on for now. I will definitely pick it back up soon.

**Comment by ZoranPandovski** [comment]
@MinuraPunchihewa Closing this for now, once you have time to finish this we can re open it

**Pull request closed without merging**
