### PR TITLE
Add Text-Summarization tutorial

### PR DESCRIPTION
**Pull request by vishalj0501**
## Description

This PR tests the text summarization tutorial 
https://docs.mindsdb.com/nlp/text-summarization-inside-mysql-with-openai and documents the all executed commands and their output.

**Fixes** - [#6057](https://github.com/mindsdb/mindsdb/issues/6057)

## Type of change

- 📄 Tested the Text Summarization tutorial

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by vishalj0501** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by martyna-mindsdb** [comment]
recheckcla

**Pull request merged**
