### PR TITLE
 added the commutnity  tutorial links

### PR DESCRIPTION
**Pull request by likithkun**
## Added the community tutorial  links 

**Fixes** 

## Type of change

-  📄 This change requires a documentation update

-  I have updated the documentation, or created issues to update them.

- I have read the CLA Document and I hereby sign the CLA

### CODE REVIEW

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by ZoranPandovski** [comment]
@likithkun  Can you please sign the CLA before we merge this?

**Comment by ZoranPandovski** [comment]
@likithkun Can you please sign the CLA before we merge this?

**Comment by likithkun** [comment]
> @likithkun Can you please sign the CLA before we merge this?

Sure

**Comment by likithkun** [comment]
@ZoranPandovski sure

**Comment by likithkun** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ZoranPandovski** [comment]
recheckcla

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
