### PR TITLE
Added delete method to SqlStatementParser

### LINKED ISSUE #785: Add delete method to SqlStatementParser
We have a simple tool for the initial processing of SQL commands: class SqlStatementParser. It has method parse_as_insert which parses SQL INSERT statements. We need a similar method for the DELETE statement. It should parse the statement and return such a result:
```
SqlStatementParser("delete from database_a.table_a where column_a = 1").parse_as_delete()
{
    'database': 'database_a',
    'table': 'table_a',
    'where': {
        'column_a': 1
    }
}
```
```
SqlStatementParser("delete from table_a where column_a = 1 and column_b = ?").parse_as_delete()
{
    'database': None,
    'table': 'table_a',
    'where': {
        'column_a': 1,
        'column_b': SQL_PARAMETER
    }
}
```
Some limitations:
1. We assume is only equality joined using 'AND' in 'WHERE'.
2. It can be a parameterized query: in this case parameter (?) should be defined as SQL_PARAMETER in the result.
At the end of class there is the static `test` method. It will be good if you add these two examples above in it after 'parse_as_delete' will be done.  You can run tests to test the implementation as :
```
 python3 mindsdb/api/mysql/mysql_proxy/classes/sql_statement_parser.py
```
For more information about this please add comments so we can guide you.

### PR DESCRIPTION
**Pull request by lavandosovich**
Fixes #785 

- extended `__init__` method for `SqlStatementParser`
- added `parse_as_delete` method for `SqlStatementParser` instance
- added several testcases for `parse_as_delete`
- added check for `where` clause in tests

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/> 
   - - -
   ***I have read the CLA Document and I hereby sign the CLA***
   - - - 
   <sub>You can retrigger this bot by commenting **recheckcla** in this Pull Request</sub>

**Comment by lavandosovich** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by StpMax — APPROVED** [review]

**Comment by StpMax** [comment]
Great! Thank you :+1:

**Pull request merged**
