### PR TITLE
select_data_query updated

### LINKED ISSUE #3358: Update MongoDB insert
As I remember I removed this bulky way to pass select_data_query for long ago. 
```
 {
            "collection": "house_sales", 
            "call": [{
                    "method": "find",
                    "args": []
             }]
     }
```
But it is still in doc: https://docs.mindsdb.com/mongo/insert/

Now right way is pass just raw string to destination database, as described in my local doc (db.house_sales.find({}))
https://github.com/mindsdb/mindsdb/blob/staging/mindsdb/api/mongo/README.md#creating-predictor

_Originally posted by @ea-rus in https://github.com/mindsdb/mindsdb/issues/3297#issuecomment-1275791753_

### PR DESCRIPTION
**Pull request by Anupam-USP**
Fixes #3358

## Please describe what changes you made, in as much detail as possible
  - Updated both the syntax description and example.
  - Used [this](https://github.com/mindsdb/mindsdb/blob/staging/mindsdb/api/mongo/README.md#creating-predictor) as reference

mindsdb

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by Anupam-USP** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Anupam-USP** [comment]
recheck

**Comment by ZoranPandovski** [comment]
recheckcla

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
