### PR TITLE
Update Manual_QA.md for Shopify handler

### PR DESCRIPTION
**Pull request by maarioos1308**
## Description

Update the Manual QA testing file for Shopify handler.

**Fixes** ##6957

## Description:
Add Qa testing for insert method.

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation, or created issues to update them.
- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
@maarioos1308
Did you test it on Cloud or locally?

**Comment by maarioos1308** [comment]
I tested it both o cloud and locally

**Comment by martyna-mindsdb** [comment]
@maarioos1308 
Great. Can you add a Shopify doc page to this PR please?

Here is the template to be followed: https://docs.mindsdb.com/app-integrations/github

**Comment by maarioos1308** [comment]
The Shopify doc is already made

**Comment by martyna-mindsdb** [comment]
@maarioos1308 
Yes - you're right. I just noticed that it was created but it wasn't linked in the mint.json file.

**Pull request merged**
