### PR TITLE
added . at the end of the docker build command

### LINKED ISSUE #7921: [Bug]:  docker build command error
### Short description of current behavior

In the mindsdb/docker/README.md file, I noticed instructions related to building the release image

Current Instructions:
```
To build the `release` image using the version reported at
https://public.api.mindsdb.com/installer/release/docker___success___None:

docker build -f release --no-cache -t mindsdb/mindsdb
```
However, I encountered a slight confusion when attempting to run the provided command,
It seems the correct command should include the . at the end, indicating the build context

```
docker build -f release --no-cache -t mindsdb/mindsdb .

```

### Video or screenshots

_No response_

### Expected behavior

_No response_

### How to reproduce the error

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by nehaal10**
## Description

added "." at the end of the build statement 

Fixes #7921

## updated documentation

(Please delete options that are not relevant)

- [x] 🐛 Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] Necessary documentation updates are either made or tracked in issues.

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by nehaal10** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by nehaal10** [comment]
recheck

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
