### PR TITLE
Added a step in Windows installation guide

### PR DESCRIPTION
**Pull request by 2170chm**
This step resolves the encoding error on Windows systems with default encoding standards other than UTF-8.

## Description

Added a step in the Windows installation guide to solve a Windows system's common encoding issue.

**Fixes** #5478 

## Type of change

(Please delete options that are not relevant)

- [x] 📄 This change requires a documentation update

### What is the solution?

Added a step for users to enable the beta feature of windows, which allows the system to use the UTF-8 encoding standard.

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation, or created issues to update them.
- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@2170chm 
Please sign our CLA following the instructions above, so we can merge your PR.

**Comment by 2170chm** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
