### PR TITLE
adds github commit table

### LINKED ISSUE #7541: [GitHub] Implement the Commits table for a GitHub repository
MindsDB integrates with GitHub, so you can fetch data from GitHub and use it to train models or make predictions with MindsDB.

## Resources

Familiarize yourself with the existing GitHub integration: https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/github_handler

## Steps to Follow

Currently, the GitHub integration with MindsDB comes with the `issues` and `pull_requests` tables.

The task is to extend [this implementation](https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/github_handler) to include the `commits` table.

**Please note that we are not assigning this type of issue.
Create a PR and link it to this issue.
The first PR that solves this will be accepted** :fireworks:

## :loudspeaker: Additional rewards :trophy:

Each integration test brings 15+ points for SWAG and entry into the draw for a :point_down: :
-  :computer:  [Razer Blade 16 Laptop](https://www.razer.com/gaming-laptops/Razer-Blade-16/RZ09-0483SEJ3-R3U1)
- :shirt: :bear:  [MindsDB Swag](https://store.covver.io/mindsdb/collections/swag-collection)

:information_source: For more info check out https://mindsdb.com/hacktoberfest/ :point_left: 

**Please note that we are not assigning this type of issue.
Create a PR and link it to this issue.
The first PR that solves this will be accepted** :fireworks:

### PR DESCRIPTION
**Pull request by abhijitpal1247**
## Description

I have added a github commit table in mindsdb github handler

Fixes #7541

## Type of change

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [ ] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have appropriately commented on my code, especially in complex areas.
- [x] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@abhijitpal1247 
Please sign our CLA as above.

Also, have you tested it? Please provide screenshots of querying the commits table.

**Comment by abhijitpal1247** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by martyna-mindsdb** [comment]
This issue has been resolved by the first accepted PR.

**Pull request closed without merging**
