### PR TITLE
Added community tips to what-is-mindsdb.mdx

### PR DESCRIPTION
**Pull request by ZepingSun**
## Description
Updated the end of what-is-mindsdb.dx with the following:

```
<Tip>
**From Our Community**

Check out the articles and video guides created by our community:

- Article on [What is MindsDB?](https://medium.com/@okekeebubechukwu08/what-is-mindsdb-b6862af21492)
  by [Gloria Okeke E.J](https://medium.com/@okekeebubechukwu08)

- Article on [What is MindsDB? How to get started with it ](https://medium.com/@hritikd3/what-is-mindsdb-how-to-get-started-2b3cf6d99707)
  by [Hritik Dangi](https://github.com/hritikd3)

- Video guide on [Video: What is MindsDB?](https://www.youtube.com/watch?v=SrDPYqQrzaw) by
  [Alissa Troiano](https://github.com/alissatroiano)

- Video guide on [What is MindsDB | How to Get Started | A Cloud/AI Enabled Database](https://www.youtube.com/watch?v=XWDVxYVGH9M)
  by [Arman Chand](https://github.com/ArmanChand)

- Video guide on [What is MindsDB and How to Get Started](https://youtu.be/zHReFuFUI34) by
  [Hritik Dangi](https://www.linkedin.com/in/hritikd3/)

- Video guide on [What is MindsDB?](https://www.youtube.com/watch?v=i2tMs4MX_yw) uploaded on
  [ExploringTech](https://www.youtube.com/channel/UCBMdmavh3528_4Yn6WR7p7Q) by
  [Rutam Prita Mishra](https://community.ops.io/rutamhere)

- Video guide on [What is MindsDB - AI Database Prediction](https://www.youtube.com/watch?v=8ySq7Y3sfJs)
  by [Bhavesh Mishra](https://github.com/thefool76)

- Video guide on [What is MindsDB ?](https://www.youtube.com/watch?v=81Q2aQWuwDM) by
  [Syed Zubeen](https://github.com/syedzubeen)
</Tip>
```

**Fixes**  #4461

## Type of change
- [x] 📄 Updated documentation 

### What is the solution?
Updated as per Description

## Checklist:
- [x] I have updated the documentation, or created issues to update them.

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Review by ZoranPandovski — APPROVED** [review]

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@ZepingSun
Before we can merge your PR, please sign the CLA by dropping a comment `I have read the CLA Document and I hereby sign the CLA`.
Thanks.

**Comment by ZepingSun** [comment]
I have read the CLA Document and I hereby sign the CLA 

> **CLA Assistant Lite bot:** Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> I have read the CLA Document and I hereby sign the CLA
> 
> You can retrigger this bot by commenting **recheck** in this Pull Request

**Comment by ZepingSun** [comment]
> @ZepingSun Before we can merge your PR, please sign the CLA by dropping a comment `I have read the CLA Document and I hereby sign the CLA`. Thanks.

Gotcha and thanks!

**Comment by martyna-mindsdb** [comment]
@ZepingSun 
Could you please drop a comment that contains just this sentence? Thanks.

I have read the CLA Document and I hereby sign the CLA

**Comment by ZepingSun** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
