### PR TITLE
Done Manual_QA.md for Apache hive.

### PR DESCRIPTION
**Pull request by maarioos1308**

### CODE REVIEW

**Review by chandrevdw31 — COMMENTED** [review]
@maarioos1308 is the 1st row a row that is listed in your database? just need to confirm that the header columns are not pulling through as row values.
image

**Comment by maarioos1308** [comment]
Yes this are the columns. This probably is due to the wrong data entry from my side.

**Comment by chandrevdw31** [comment]
> Yes this are the columns. This probably is due to the wrong data entry from my side.

@maarioos1308 do you mind correcting the data entry? as when the PR is merged and the doc is checked there will be no indication that it is a data entry issue and not something to do with the handler. Just a minor cleanup. Once you have updated screenshot we can merge

**Comment by maarioos1308** [comment]
@chandrevdw31 I updated the screenshot.

**Review by chandrevdw31 — APPROVED** [review]

**Pull request merged**
