### PR TITLE
Added Manual QA Test the Hugging Face - Industry tutorial

### PR DESCRIPTION
**Pull request by hoipranav**
Merging this Pull Request closes Issues #6087

### CODE REVIEW

**Comment by hoipranav** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by hoipranav** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by martyna-mindsdb** [comment]
@hoipranav
In future, please follow the rules as mentioned in the issue description. `Please leave a comment on this issue and wait until you are assigned. Then you can create a PR.`

**Pull request merged**
