### PR TITLE
New Tutorial: Predict Sales of Manufacturing with MindsDB using Java

### PR DESCRIPTION
**Pull request by Rutam21**
The list is updated with a new tutorial on how to `Predict Sales of Manufacturing with MindsDB using Java`,

## Description

A new blog is published on the above topic and its respective link has been added to the Tutorials List.

**Fixes** #3448 

## Type of change

- [x] 📄 This change requires a documentation update

## Checklist:

- [x] I have followed the CONTRIBUTING guidelines.
- [x] I have created this PR with the best community practices and standards.

### CODE REVIEW

**Comment by Rutam21** [comment]
@chandrevdw31 Please review and suggest changes, if any.

**Review by AMK9978 — CHANGES_REQUESTED** [review]
I don't think linking to your article in another website is a professional way for our project's tutorial. As far as I see, other tutorials are based on the defined template and plain.

**Review by AMK9978 — CHANGES_REQUESTED** [review]
I don't think linking to your article in another website is a professional way for our project's tutorial. As far as I see, other tutorials are based on the defined template and plain. I suggest to get them here please.

**Comment by chandrevdw31** [comment]
@AMK9978 please note that contributors can post their tutorials on publishing websites like dev.to,medium hashnode etc. and link it to our docs tutorial. You will see most of the tutorials are linked to an external website. This is so that other people can read it aswell.

**Pull request merged**
