### PR TITLE
Fixed error linking image files in markdown

### PR DESCRIPTION
**Pull request by r-scheele**
Fixes #

## Please describe what changes you made, in as much detail as possible
  - Fixed errors displaying image files in all the documentation markdown files, with the correct path.

mindsdb

### CODE REVIEW

**Comment by r-scheele** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by r-scheele** [comment]
recheck

**Comment by ZoranPandovski** [comment]
recheckcla

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
Can you explain please why did you change the file paths? This images are working correctly

**Comment by r-scheele** [comment]
> Can you explain please why did you change the file paths? This images are working correctly

They're not working properly that's why i changed it(please check), But now they are.

**Comment by ZoranPandovski** [comment]
Nope, assets is the main directory for serving the images, we don't need to change the paths. Please check the other issues for contributions https://github.com/mindsdb/mindsdb/projects/12

**Pull request closed without merging**
