### PR TITLE
Fixed Script for Running Handler Unit Tests in Workflow

### PR DESCRIPTION
**Pull request by MinuraPunchihewa**
## Description

This PR fixes the script for running handler unit tests on push.

## Type of change

- [X] 🐛 Bug fix (non-breaking change which fixes an issue)

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Checklist:

- [X] My code follows the style guidelines(PEP 8) of MindsDB.
- [X] I have appropriately commented on my code, especially in complex areas.
- [ ] Necessary documentation updates are either made or tracked in issues - N/A
- [X] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Comment by MinuraPunchihewa** [comment]
@ZoranPandovski There was a small bug in the script for running our unit tests for handlers, which I have fixed here.
However, I don't think this is the best way to go about it; because we are using mocks in our tests, I don't think these will show up in our coverage.

Running the unit tests for Postgres locally:
image

Submission to Coveralls:
image

**Comment by ZoranPandovski** [comment]
Let's chat on slack for this

**Comment by MinuraPunchihewa** [comment]
@ZoranPandovski Sure, sounds good.

**Comment by MinuraPunchihewa** [comment]
@ZoranPandovski Despite what we discussed during our call, I believe this still need to be merged. The commands that are generated within the loop of the existing script is incorrect. They are currently generated in the following form: 
`pytest --cov=mindsdb/integrations/handlers/test_mysql_handler tests/unit/handlers/test_mysql.py`

But, they should be:
`pytest --cov=mindsdb/integrations/handlers/mysql_handler tests/unit/handlers/test_mysql.py`

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
