### PR TITLE
Added the given content to the end of feature-importance.mdx file

### PR DESCRIPTION
**Pull request by kushalnl7**
## Description

Added the given content in issue #4562 at the end of **feature-importance.mdx** file

**Fixes** #4562

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation, or created issues to update them.
- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   **Kushal Lahoti** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@kushalnl7
Before we can merge your PR, please sign our CLA.
Please see the instruction above. Thanks.

**Comment by kushalnl7** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ZoranPandovski** [comment]
Hey @kushalnl7 you will need to add the email that you are logged in locally on Git, to your GitHub account

**Comment by ZoranPandovski** [comment]
Hey @kushalnl7 you will need to add the email that you are logged in locally on Git, to your GitHub account, please.

**Comment by kushalnl7** [comment]
Hi @ZoranPandovski, I have just added my email-id on my local git. What do I need to make it visible on remote?

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
I think it should be vice-versa. You need to add the email address used for this commits added to your GitHub account

**Comment by kushalnl7** [comment]
recheck

**Comment by kushalnl7** [comment]
> I think it should be vice-versa. You need to add the email address used for this commits added to your GitHub account

It's already added.

**Comment by ZoranPandovski** [comment]
recheckcla

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
