### PR TITLE
[docs] adds strapi to integrations

### PR DESCRIPTION
**Pull request by ritwickrajmakhal**
## Description
Added documentaion for [Strapi](https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/strapi_handler) handler

## Type of change

- [x] 📄 This change requires a documentation update

## Additional Media:
image

- [x] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have appropriately commented on my code, especially in complex areas.
- [x] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
Please solve the conflicts. Also can we update the integration to not use camel case name for pluralApiIds, and change it to snake case

**Comment by ritwickrajmakhal** [comment]
I think `plural_api_ids` will be good instead of `pluralApiIds`, but for that I have change the codes of strapi handler. Ok I will 
commit it soon.

**Review by ZoranPandovski — APPROVED** [review]

**Comment by martyna-mindsdb** [comment]
I must have missed this PR.

@ritwickrajmakhal 
Can you please create another PR to reformat the [Strapi doc page](https://docs.mindsdb.com/integrations/app-integrations/strapi) to contain two sections `## Connection` and `## Usage`, like you did here: https://github.com/mindsdb/mindsdb/pull/8277/files

**Comment by ritwickrajmakhal** [comment]
Hey @martyna-mindsdb, I have already planned to create another PR very soon, Because I got the knowledge from you in the previous PRs

**Pull request merged**
