### PR TITLE
added akovtunenko_amazon_simple_notification_service_api_integration

### LINKED ISSUE #5558: [Integration]: Amazon Simple Notification Service API Integration
The goal of this issue is to build a new handler that will utilize the Amazon Simple Notification Service (SNS) API to enable integration between MindsDB and Amazon SNS. This integration will allow users to leverage the power of machine learning for various automation tasks, such as sending notifications, managing subscriptions, and handling events using the Amazon SNS service.

## Resources :bulb:
:checkered_flag: To get started, please refer to the following resources:

* :books: [Building Application Handler docs](https://docs.mindsdb.com/contribute/app-handlers): This documentation will guide you through the process of building a custom handler for MindsDB. It contains essential information on the handler structure, methods, and best practices.

* :book: [Amazon SNS API docs](https://docs.aws.amazon.com/sns/latest/api/welcome.html): This documentation contains all the endpoints and parameters that are available through the Amazon SNS API, including information on how to create topics, publish messages, and manage subscriptions.

* :point_right: [Twitter Handler](https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/twitter_handler): This existing handler connects MindsDB with the Twitter API, allowing users to automate tasks related to posting and analyzing tweets. You can use the Twitter Handler as a reference for building the Amazon SNS API integration.

* :point_right: [Binance API Handler](https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/binance_handler): Another example of a successful MindsDB integration to the Binance API to make trade data available to use for model training and predictions.

## Next Steps :male_detective: :female_detective:
* Familiarize yourself with the Amazon SNS API.
* Create a new handler that connects MindsDB to Amazon SNS.
* Implement the core features mentioned above.
* Thoroughly test the integration to ensure proper functionality.
* Submit a pull request with the new Amazon SNS Integration handler.

Thank you for contributing to MindsDB :bear: !

### PR DESCRIPTION
**Pull request by Alexander198961**
## Description
 Amazon Simple Notification Service API Integration

Fixes #5558

## Type of change

- [x] ⚡ New feature (non-breaking change which adds functionality)

## Verification Process

To ensure the changes are working as expected:

 - [x]   Test Location: Specify the URL or path for testing.
 - [x]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [x] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have appropriately commented on my code, especially in complex areas.
- [x] Necessary documentation updates are either made or tracked in issues.
- [x] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Comment by Alexander198961** [comment]
work in progress

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you all sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb/blob/staging/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   **0** out of **2** committers have signed the CLA.<br/>:x: @Alexander198961<br/>:x: @oleksandrKovtunenko<br/><sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Review by MinuraPunchihewa — CHANGES_REQUESTED** [review]
Hey @Alexander198961,
Thank you for your contribution. I would like to kindly request that you do the following,
1. Please add screenshots or a short video of this integration working.
2. I also noticed that your `APITable` implementations, i.e. `topics` and `messages` only support and 1 and 2 columns respectively. Is this all of the information that is returned through the API? If not, can we incorporate those columns as well?

**Comment by Alexander198961** [comment]
thx will check this

**Comment by Alexander198961** [comment]
link to video https://drive.google.com/file/d/1AmeyBpVS_RW4ebET4gqKHsppw9U1t_Vd/view?usp=sharing

**Comment by MinuraPunchihewa** [comment]
Hey @Alexander198961,
OK, is it possible to implement `SELECT` for messages?
Also, can we clean up your code a little bit? One suggestion is to get rid of `call_sns_api()` and move the other methods to the `APITable` implementations. For instance, `create_topic()`, `delete_topic()` can be moved to `TopicsTable` and so forth.
I also don't think `supported_columns` and `columns` need to be class variables.

**Comment by Alexander198961** [comment]
ok will do

**Comment by MinuraPunchihewa** [comment]
Hey @Alexander198961,
Did you run into some sort of issue? Is that why this was closed?

**Comment by Alexander198961** [comment]
@MinuraPunchihewa i will recreate this week

**Comment by MinuraPunchihewa** [comment]
@Alexander198961 That's great. Thank you.

**Pull request closed without merging**
