### PR TITLE
Discounts Table Implementation#7871

### LINKED ISSUE #7871: [Shopify] Implement the Discounts table
### Short description of current behavior

MindsDB integrates with Shopify, so you can access your Shopify data and make relevant forecasts with MindsDB.

## Resources

Familiarize yourself with the existing Shopify integration: https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/shopify_handler

## Steps to Follow

The task is to extend [this implementation](https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/shopify_handler) to include the Discounts table from Shopify API.

## :loudspeaker: Additional rewards :trophy:

Each integration test brings 15+ points for SWAG and entry into the draw for a :point_down: :
-  :computer:  [Razer Blade 16 Laptop](https://www.razer.com/gaming-laptops/Razer-Blade-16/RZ09-0483SEJ3-R3U1)
- :shirt: :bear:  [MindsDB Swag](https://store.covver.io/mindsdb/collections/swag-collection)

:information_source: For more info check out https://mindsdb.com/hacktoberfest/ :point_left: 

**Please note that this issue of for first-time contributors to MindsDB**

### Video or screenshots

_No response_

### Expected behavior

_No response_

### How to reproduce the error

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Aadish1233**
Created a new class DiscountsTable

## Description

Please include a summary of the change and the issue it solves. 

Fixes #7871 

## Type of change

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [x] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [x]   Test Location: Specify the URL or path for testing.
 - [x]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [ ] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have appropriately commented on my code, especially in complex areas.
- [x] Necessary documentation updates are either made or tracked in issues.
- [x] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by Aadish1233** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Aadish1233** [comment]
recheck

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by martyna-mindsdb** [comment]
@Aadish1233 
Please provide screenshots or a short video showing all command you implemented for the Discounts table.

**Comment by Aadish1233** [comment]
Uploading shopify-tablespy-visual-studio-code-2023-10-20-01-01-08_O3t8CVQu.mp4…
Comands for Discounts table

**Comment by Aadish1233** [comment]
Commands for Discount Tables
https://github.com/mindsdb/mindsdb/assets/120332757/7ea67b38-5d0c-4822-8f40-54ce18545c5a

**Comment by Aadish1233** [comment]
hey please accept the pull request @mindsdbadmin

**Comment by martyna-mindsdb** [comment]
Looks good @Aadish1233 

Please provide a video that presents what's mentioned in my last comment, so this PR can be completed.

**Comment by Aadish1233** [comment]
how do I open Mindsdb Editor on local host

**Comment by martyna-mindsdb** [comment]
@Aadish1233 
You need to install MindsDB locally and start it. Here are the instructions: https://docs.mindsdb.com/contribute/install

**Comment by ZoranPandovski** [comment]
This doesn't work, closing. @Aadish1233 please check other help-wanted issues

**Pull request closed without merging**
