### PR TITLE
Added byom.mdx and changed mint.json accordingly #5990

### PR DESCRIPTION
**Pull request by R-Yash**
## Description

Create and add the byom file to navigation

**Fixes** #5990 

## Type of change

(Please delete options that are not relevant)

- [x] 📄 This change requires a documentation update

### Updated the documentation as requested

(Describe at a high level how the feature was implemented)

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation, or created issues to update them.
- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by R-Yash** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by R-Yash** [comment]
recheck

**Comment by R-Yash** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by R-Yash** [comment]
recheck

**Comment by martyna-mindsdb** [comment]
@R-Yash
This issue has been already resolved (there is a merged PR above).

Please have a look at other help-wanted issues.

**Pull request closed without merging**
