### PR TITLE
Updated Mariadb Docs

### PR DESCRIPTION
**Pull request by Shadowpii**
## Description

#6672 

## Type of change

📄 This change requires a documentation update

### What is the solution?

Updated Mariadb Documentation

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by Shadowpii** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by martyna-mindsdb** [comment]
@Shadowpii 
Please see the review comment above, make the updates, and push them to this PR.

**Comment by martyna-mindsdb** [comment]
@Shadowpii 
Please correct it as mentioned in the review comment (the tip box should be at line 28).

**Pull request merged**
