### PR TITLE
Updated Python versions in the /setup/self-hosted/pip/windows doc page

### PR DESCRIPTION
**Pull request by AyanDas348**
## Updated Python versions in the /setup/self-hosted/pip/windows doc page

Ensure the user installs correct version of Python to not have dependency errors.

**Fixes** #(issue)
It fixes the issue #6240 

## Type of change

Changed the python version in /setup/self-hosted/pip/windows doc page.
- [x] 📄 This change requires a documentation update

## Checklist:

- [x] I have updated the documentation.

### CODE REVIEW

**Comment by AyanDas348** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
recheckcla

**Pull request merged**
