### PR TITLE
Improved Code Quality

### PR DESCRIPTION
**Pull request by pierizvi**
These changes were made to improve the readability and maintainability of the code, and to prevent potential errors or bugs caused by these mistakes.

### CODE REVIEW

**Comment by pierizvi** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by pierizvi** [comment]
recheck

**Comment by pierizvi** [comment]
@martyna-mindsdb review/update PR

**Pull request closed without merging**
