### PR TITLE
Update README.md #5031

### PR DESCRIPTION
**Pull request by revanthsonu**
Updated the link to hive

## Description

changed the link from "https://docs.mindsdb.com/what-is-mindsdb" to "https://docs.mindsdb.com/data-integrations/all-data-integrations#hive"

**Fixes** #(issue) redirection 

## Type of change

- [X] 📄 This is a documentation update

### What is the solution?

This was a basic hyperlink change issue

## Checklist:

- [X] My code follows the style guidelines(PEP 8) of MindsDB.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have updated the documentation, or created issues to update them.

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@revanthsonu 
Before we can merge your PR, please sign our CLA following the instructions above.

**Comment by revanthsonu** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
