### PR TITLE
Discord API Handler

### LINKED ISSUE #7505: [Integration]: Discord API Integration
The goal of this issue is to build a new handler that will utilize the Discord API to connect MindsDB to Discord. This integration will allow users to leverage MindsDB's OpenAI or Hugging Face integration to automate various tasks, such as writing and responding to messages, answering questions, and to post announcements within the Discord platform.

## Resources :bulb: 

:checkered_flag: To get started, please refer to the following resources:

* :books:  [Building Application Handler docs](https://docs.mindsdb.com/contribute/app-handlers): This documentation will guide you through the process of building a custom handler for MindsDB. It contains essential information on the handler structure, methods, and best practices.

* :book:  [Discord Developer docs](https://discord.com/developers/docs/intro)

* :point_right: [Twitter Handler](https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/twitter_handler): This existing handler connects MindsDB with the Twitter API, allowing users to automate tasks related to posting and analyzing tweets. You can use the Twitter Handler as a reference for building the Slack API integration.

*  :point_right:  [Binance API Handler](https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/binance_handler): Another example of a successful MindsDB integration to the Binance API to make trade data available to use for model training and predictions.

## Next Steps :male_detective: :female_detective: 
 
-   You can familiarize yourself with the Discord API.
-   Create a new handler that connects MindsDB to a Discord.
-   Implement the core features mentioned above.
-   Thoroughly test the integration to ensure proper functionality.
-   Submit a pull request with the new Discord Integration handler.

## :loudspeaker: Additional rewards :trophy:

Each App integration brings :five: :zero:  : points for SWAG and entry into the draw for a  :point_down: :
-  :computer:  [Razer Blade 16 Laptop](https://www.razer.com/gaming-laptops/Razer-Blade-16/RZ09-0483SEJ3-R3U1)
- :shirt: :bear:  [MindsDB Swag](https://store.covver.io/mindsdb/collections/swag-collection)
:information_source: For more info check out https://mindsdb.com/hacktoberfest/ :point_left:

### PR DESCRIPTION
**Pull request by Lavesh-Akhadkar**
## Description

Please include a summary of the change and the issue it solves. 

Fixes #7505

## Type of change

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [ ] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have appropriately commented on my code, especially in complex areas.
- [ ] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
Can you please add README with all of the information how this work

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by Lavesh-Akhadkar** [comment]
hey @ZoranPandovski I have seen some Handlers and it seems that their README.md uses sql, I am not familiar with SQL, should i just create documentation with reference to python usage?

**Comment by ZoranPandovski** [comment]
@Lavesh-Akhadkar how did you developed this without trying the SQL queries? Is this working through MindsDB? Please include video that showcase fully functional integration

**Comment by Lavesh-Akhadkar** [comment]
hey @ZoranPandovski I am really sorry I am not familiar with SQL, I just followed through your documentation of how to create an API handler and made the handler like wise I don't know what I can do more regarding this I will unassign myself from this issue as I thought I only had to make the API handler according to the docs.

Rest assured the code I have written by following the docs for creating an API handler works perfectly fine when used in a python environment I have tested it out by creating webhooks and sending messages to discord server.

I am sorry for wasting your time and for any losses this might've created.

**Comment by dalalvarun** [comment]
@Lavesh-Akhadkar just run mindsdb locally and use the discord integration if it works properly or not - whether it gets, updates, deleted and creates records into ur discord tables. Create a video for this and upload it here.

**Comment by ZoranPandovski** [comment]
This doesn;t work. Closing for now

**Pull request closed without merging**
