### PR TITLE
Update the Trino Link in the README.md

### PR DESCRIPTION
**Pull request by shekhar-chauhan**
## Description

Updated the document to add the new link for Trino.
Issue #5877 

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have updated the documentation, or created issues to update them.

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@shekhar-chauhan 
Please sign our CLA by leaving a comment here: I have read the CLA Document and I hereby sign the CLA

**Comment by martyna-mindsdb** [comment]
@shekhar-chauhan 
Do you want to complete this PR?

**Comment by shekhar-chauhan** [comment]
@martyna-mindsdb @SebastianJames55, My sincere apologies in not closing the PR. As you all suggested that one should "ask" and "wait" since the issue was assigned to someone else, I should've immediately closed it. My bad. On the other hand, I think I should also write an automation script which scours GitHub in search of all open issues, and ask them to assign it to me, and then wait endlessly, cause, even if it is a small issue, I own it, I'll take as much time as I want to, and if someone else does it, it's their fault, why didn't they respect the fact that I'm assigned the issue. 
Because, 
aristocracy or monarchy >>>>> contributing or learning or growing or making the best out of whatever time is in front of you.

**Comment by martyna-mindsdb** [comment]
Thanks @shekhar-chauhan 

You're welcome to have a look at other open issues labeled as help-wanted. We add new ones regularly.

**Comment by SebastianJames55** [comment]
@martyna-mindsdb I have a few doubts
1. first-timers-only refers to first PR in open-source or in mindsDB? (I'm guessing the former) 
2. once we request for an issue to be assigned, as a rule of thumb how many days do we have to wait before reaching out again? 
3. what do we do if no response is received after the above-mentioned number of days? Are we to ask in the #questions slack channel?

**Comment by martyna-mindsdb** [comment]
@SebastianJames55 
Here are the answers:
1. The first-timers-only labeled issues refer to contributors that haven't contributed to MindsDB yet.
2. We usually assign issues within a day.
3. Yes - you can join our Slack community here: https://mindsdb.com/joincommunity

**Pull request closed without merging**
