### PR TITLE
fixes [Bug]: Hubspot integration broken #9782

### LINKED ISSUE #9782: [Bug]: Hubspot integration broken
### Short description of current behavior

When trying to install the extension through the UI or through the exec command I get the following error 

name 'List' is not defined

### Video or screenshots

image
image

### Expected behavior

The container to install the extension and be able to connect to hubspot

### How to reproduce the error

Go to settings, extensions and install Hubspot

Optionally install it through docker exec containerID pip install 'mindsdb[hubspot]'

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by poisonvine**
## Description

Removed line 1 of hupspot_tables.py ("if False:"), which prevented the import of List from typing. 

Fixes #9782

## Type of change

&#x2611; 🐛 Bug fix (non-breaking change which fixes an issue)

## Checklist:

&#x2611; My code follows the style guidelines(PEP 8) of MindsDB.
&#x2611; I have appropriately commented on my code, especially in complex areas.
&#x2611; Necessary documentation updates are either made or tracked in issues.
&#x2611; Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you all sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb/blob/main/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   **0** out of **2** committers have signed the CLA.<br/>:x: @code-vine<br/>:x: @poisonvine<br/><sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by poisonvine** [comment]
I have read the CLA Document and I hereby sign the CLA
[ x] poisonvine  [x] code-vine

**Comment by poisonvine** [comment]
recheck

**Comment by poisonvine** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by code-vine** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ZoranPandovski** [comment]
recheckcla

**Review by ZoranPandovski — APPROVED** [review]

**Comment by poisonvine** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
