### PR TITLE
Fixed the Execution Logic for the Popularity Recommender Integration

### PR DESCRIPTION
**Pull request by MinuraPunchihewa**
## Description

Please include a summary of the change and the issue it solves. 

Fixes https://github.com/mindsdb/mindsdb/issues/9528

## Type of change

- [X] 🐛 Bug fix (non-breaking change which fixes an issue)

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [ ] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have appropriately commented on my code, especially in complex areas.
- [ ] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Comment by MinuraPunchihewa** [comment]
Hey @dusvyat,
I've made some small changes to fix the Population Recommender engine in this PR (this fixes `create()`), however, I noticed that `predict()` does not run successfully because an error pops at this [line](https://github.com/mindsdb/mindsdb/blob/c5747ca20dcc2090bb7c5218e6b2bc0368f542c5/mindsdb/integrations/handlers/popularity_recommender_handler/popularity_recommender_handler.py#L86). The reason, from what I have gathered, is that the `is_in()` function cannot be used on a list column, which is what 'popular_items' is. Do you have any suggestions for how this can be resolved? Since this is a `LazyFrame`, some of the options I tried such as using `map_rows()` with a function to filter the rows did not work.

**Review by dusvyat — APPROVED** [review]
lgtm

**Comment by MinuraPunchihewa** [comment]
Hey @dusvyat,
Let me know what you think of the comment I have left above.

**Comment by ZoranPandovski** [comment]
@MinuraPunchihewa Let's open new issue for [this](https://github.com/mindsdb/mindsdb/pull/9529#issuecomment-2249668690) and solve it in another PR

**Comment by MinuraPunchihewa** [comment]
@ZoranPandovski Understood. I will create an issue now.

**Pull request merged**
