### PR TITLE
[Integration] TripAdvisor (v.0.0.1): Adding tests for ReviewsTable, PhotosTable and NeabyLocationTable

### LINKED ISSUE #5369: [Integration] TripAdvisor Integration
The goal of this issue is to build a new handler that will utilize the TripAdvisor API to connect MindsDB to TripAdvisor, a company that operates online travel agencies, comparison shopping websites, and mobile apps with user-generated content. This integration will enable TripAdvisor users to use ML to research travel destinations and more.

## Resources :bulb: 

:checkered_flag: To get started, please refer to the following resources:

* :books:  [Building Application Handler docs](https://docs.mindsdb.com/contribute/app-handlers): This documentation will guide you through the process of building a custom handler for MindsDB. It contains essential information on the handler structure, methods, and best practices.

* :book:  [TripAdvisor API docs](https://tripadvisor-content-api.readme.io/reference/overview)

* :point_right: [Twitter Handler](https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/twitter_handler): This existing handler connects MindsDB with the Twitter API, allowing users to automate tasks related to posting and analyzing tweets. You can use the Twitter Handler as a reference for building the Slack API integration.

*  :point_right:  [Binance API Handler](https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/binance_handler): Another example of a successful MindsDB integration to the Binance API to make trade data available to use for model training and predictions.

## Next Steps :male_detective: :female_detective: 
 
-   You can familiarize yourself with the TripAdvisor API.
-   Create a new handler that connects MindsDB to a TripAdvisor workspace.
-   Implement the core features mentioned above.
-   Thoroughly test the integration to ensure proper functionality.
-   Submit a pull request with the new TripAdvisor Integration handler.

Thank you for contributing to MindsDB!

### PR DESCRIPTION
**Pull request by HahaBill**
## Description

Adding tests to finalise the integration

Fixes #5369 

## Type of change

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x ] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [x ]   Test Location: Specify the URL or path for testing: ***tests/handler_tests/test_tripadvisor_handler.py***
 - [x ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [ ] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [x ] My code follows the style guidelines(PEP 8) of MindsDB.
- [x ] I have appropriately commented on my code, especially in complex areas.
- [x ] Necessary documentation updates are either made or tracked in issues.
- [x ] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Comment by HahaBill** [comment]
Fixing the code rn

**Comment by HahaBill** [comment]
@ZoranPandovski @martyna-mindsdb  I corrected the issues with code_checking, but it appears that the integration from AutoGluon does not comply with code_checking, despite having been merged into MindsDB.

**Comment by HahaBill** [comment]
Made an issue #8009 and it is being resolved

**Comment by someshfengde** [comment]
> AutoGluon code_checking fix: Made an issue #8009 and it is being resolved

It's resolved :)

**Comment by HahaBill** [comment]
> > AutoGluon code_checking fix: Made an issue #8009 and it is being resolved
> 
> 
> 
> It's resolved :) by #8014

Noice!!

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
