### PR TITLE
[Docs]:Update instructions for Google Sheets

### PR DESCRIPTION
**Pull request by Rhythm-08**
## Description

Please include a summary of the change and the issue it solves.
Added the tip at the end of the Implementation chapter in docs/data-integrations/google-sheets.mdx

**Fixes** #(issue)
#6668 

## Type of change

(Please delete options that are not relevant)
- [X] 📄 This change requires a documentation update

### What is the solution?

(Describe at a high level how the feature was implemented)

## Checklist:

- [X] My code follows the style guidelines(PEP 8) of MindsDB.
- [X] I have updated the documentation, or created issues to update them.

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@Rhythm-08 
Please sign our CLA by leaving a comment here: I have read the CLA Document and I hereby sign the CLA

**Comment by martyna-mindsdb** [comment]
recheckcla

**Pull request merged**
