### PR TITLE
Changed Scylladb connection docs

### LINKED ISSUE #2679: [Documentation] Change Sclylladb connection docs
The required parameters are changed so the users can now connect to Scylla using:

```
CREATE DATABASE scylladb_datasource
WITH ENGINE='scylladb',
PARAMETERS={
  "user":"user@mindsdb.com",
  "password": "pass",
  "secure_connect_bundle": "/home/zoran/Downloads/secure-connect-mindsdb.zip"
};
```
The `CREATE DATABASE` query at 
https://github.com/mindsdb/mindsdb/blob/a09fd4ecc9e62f1e30ac4b3f22505ce704c350c7/docs/mindsdb-docs/docs/sql/create/databases.md#scylla should be changed with the one above.

### PR DESCRIPTION
**Pull request by gulio-python**
Fixes #2679

## Please describe what changes you made, in as much detail as possible
  - I changed the CREATE DATABASE query for scylladb so users can connect with Scylla.

mindsdb

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by gulio-python** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by ZoranPandovski — APPROVED** [review]
Thanks @gulio-python

**Comment by gulio-python** [comment]
> Thanks @gulio-python

No problem, I'm happy to help!

**Pull request merged**
