### PR TITLE
Allow query clickhouse_handler with HTTP protocol

### PR DESCRIPTION
**Pull request by flaneur2020**
The Clickhouse HTTP protocol have many good parts, like easy to query (with a simple curl), easy to monitor and easy to put it behind a proxy, etc. But mindsdb only support the clickhouse-native protocol yet, it'd be cool to support both.

The depended clickhouse-sqlalchemy actually both supports the native driver (with clickhouse-driver) and a HTTP driver, we can take advantage of the abstraction of clickhouse-sqlalchemy to both support the HTTP and native protocols with a little modification.

This PR adds a `protocol` arg which default as native, the existed behaviour will not be affected.

Regards.

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by flaneur2020** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by flaneur2020** [comment]
recheck

**Review by ZoranPandovski — APPROVED** [review]
Awesome, thanks @flaneur2020

**Pull request merged**
