### PR TITLE
Bumped langchain Version for Compatibility with llama-index

### PR DESCRIPTION
**Pull request by MinuraPunchihewa**
## Description

This PR bumps the version of `langchain` used in the Docker image because the current version used seems to conflicts with `llama-index`.

### Fixes:
https://github.com/mindsdb/mindsdb/issues/7445#issuecomment-1757580657

## Type of change

- [X] 🐛 Bug fix (non-breaking change which fixes an issue)

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Checklist:

- [X] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have appropriately commented on my code, especially in complex areas.
- [ ] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
Can you please solve the flake8 issues from the previous PR https://github.com/mindsdb/mindsdb/actions/runs/6483415314/job/17604941583?pr=7698#step:5:1.

**Comment by MinuraPunchihewa** [comment]
> Can you please solve the flake8 issues from the previous PR https://github.com/mindsdb/mindsdb/actions/runs/6483415314/job/17604941583?pr=7698#step:5:1.

It's done, Zoran.

**Comment by ZoranPandovski** [comment]
Please check the conflicts

**Comment by MinuraPunchihewa** [comment]
@ZoranPandovski Looks like Max has fixed the flake8 issues in a separate PR. So, this just has the bump in the `langchain` version now.

**Pull request merged**
