### PR TITLE
Adding url support for mysql db connections

### LINKED ISSUE #7235: [mysql-integration] Allow to specify a connection string
### Short description and motivation for the proposed feature

Connection strings are used by some tools, libraries and MySQL/MariaDB storage engines. Some people prefer to use connection strings.

Allow to specify MySQL host, port, user, password, database name as a connection string:

```
mysql://user:passwprd@host/db
```

If a connection string is specified, information contained in it should be omitted. Otherwise, information that is currently mandatory should still be treated as mandatory.

### Video or screenshots

_No response_

### Describe some possible solutions

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by einhverfr**
New rules have an ability to specify username and password in either the URL or the connection info supplied via JSON.  Failure to have any required information set up triggers an error.

## Description

Fixes #7235 

## Type of change

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [X] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [x]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.
 
To test manually, one can connect to a local system using a URI in the format as follows, making changes as needed.  This is submitted in the "url" field of the API request.

mysql://user:passwprd@host/db

I was unable to find automatic authentication tests in the test suite.  I could add them there if you can direct me.

## Additional Media:

- [ ] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [X] My code follows the style guidelines(PEP 8) of MindsDB.
- [X] I have appropriately commented on my code, especially in complex areas.
- [X] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

See above, could not find authentication tests.

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Review by StpMax — APPROVED** [review]

**Comment by StpMax** [comment]
recheck

**Pull request merged**
