### PR TITLE
added ; at the end of SELECT query in docs/data-integrations/couchbas…

### PR DESCRIPTION
**Pull request by Nyx1on**
…e.mdx

## Description

Added  ;  at the end of SELECT query in docs/data-integrations/couchbae.mdx file.

**Fixes** #(issue)

## Type of change

(Please delete options that are not relevant)

- [x] 🐛 Bug fix (non-breaking change which fixes an issue)

### What is the solution?

Just added a ; at the end of SELECT query

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation, or created issues to update them.
- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@Nyx1on 
Please make sure to get assigned to an issue (https://github.com/mindsdb/mindsdb/issues/5795) before creating a PR. You can do that by leaving a comment on an issue.

Please sign our CLA by leaving a comment here that contains this line: I have read the CLA Document and I hereby sign the CLA

**Comment by martyna-mindsdb** [comment]
@Nyx1on 
Please let us know if you want to have your PR merged. If so, please sign the CLA as requested above.

**Comment by Nyx1on** [comment]
> @Nyx1on 
> Please make sure to get assigned to an issue (https://github.com/mindsdb/mindsdb/issues/5795) before creating a PR. You can do that by leaving a comment on an issue.
> 
> Please sign our CLA by leaving a comment here that contains this line: I have read the CLA Document and I hereby sign the CLA

I have read the CLA document and I hereby sign the CLA

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by martyna-mindsdb** [comment]
@Nyx1on 
To trigger the bot, please leave a comment here that contains only this line: I have read the CLA Document and I hereby sign the CLA

**Comment by Nyx1on** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
