### PR TITLE
Updating the SQL to verify the status of the spam_classifier model

### PR DESCRIPTION
**Pull request by kunaljubce**
## Description

Updating the SQL to verify the status of the spam_classifier model. Issue - https://github.com/mindsdb/mindsdb/issues/6514

**Fixes** #6514 

## Type of change

- [x] 📄 This change requires a documentation update

### What is the solution?

Replaced - 
`
SELECT *
FROM mindsdb.models
WHERE name = 'spam_classifier';`
with 
`
DESCRIBE spam_classifier;
`
in `docs\nlp\nlp-mindsdb-hf.mdx` file

## Checklist:

- [x] I have updated the documentation, or created issues to update them.

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@kunaljubce 
Please sign our CLA by leaving a comment here: I have read the CLA Document and I hereby sign the CLA

**Comment by kunaljubce** [comment]
> I have read the CLA Document and I hereby sign the CLA

I have read the CLA Document and I hereby sign the CLA

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by kunaljubce** [comment]
@martyna-mindsdb Thanks for the merge. Since this is my first PR, do I qualify to get credits for this PR? 

image

**Comment by martyna-mindsdb** [comment]
@kunaljubce 
Please submit a form with your PRs to get credits.

@chandrevdw31 
Please help.

**Comment by chandrevdw31** [comment]
Hey @kunaljubce, yes since the PR is merged you can claim for swag rewards on our rewards page, please submit the Claim Rewards form https://mindsdb.com/community

**Comment by kunaljubce** [comment]
Thanks a lot @martyna-mindsdb , @chandrevdw31 :)

**Pull request merged**
