### PR TITLE
Update [DOCS] in `docs/data-integrations/apache-impala.mdx`

### LINKED ISSUE #6269: [Docs] Update instructions for Apache Impala
## Instructions

1. Go to the `docs/data-integrations/apache-impala.mdx` file.

2. At the end of the `Implementation` chapter, add the following content:

```
<Tip>
If you installed MindsDB locally via pip, you need to install all handler dependencies manually. To do so, go to the handler's folder (mindsdb/integrations/handlers/impala_handler) and run this command: `pip install -r requirements.txt`.
</Tip>
```

3. Save your changes and create a PR.

## The https://github.com/mindsdb/mindsdb/labels/first-timers-only Label

We are happy to welcome you on board! Please take a look at the rules below for first-time contributors.

1. You can solve only one issue labeled as https://github.com/mindsdb/mindsdb/labels/first-timers-only. After that, please look at other issues labeled as https://github.com/mindsdb/mindsdb/labels/good%20first%20issue, https://github.com/mindsdb/mindsdb/labels/help%20wanted, or https://github.com/mindsdb/mindsdb/labels/integration.

2. Please leave a comment on this issue and wait until you are assigned. Then you can create a PR.

3. After you create your first PR in the MindsDB repository, please sign our CLA to become a MindsDB contributor. You can do that by leaving a comment that contains the following: `I have read the CLA Document and I hereby sign the CLA`

Thank you for contributing to MindsDB!

### PR DESCRIPTION
**Pull request by BabaYaga1221**
## Description

Please include a summary of the change and the issue it solves. 

Fixes #6269 

## Type of change

(Please delete options that are not relevant)

- [X] 📄 This change requires a documentation update

### What is the solution?

(Describe at a high level how the feature was implemented)

## Checklist:

- [X] I have updated the documentation, or created issues to update them.

I have read the CLA Document and I hereby sign the CLA

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@BabaYaga1221 
Please sign our CLA by leaving a comment here: I have read the CLA Document and I hereby sign the CLA

**Comment by BabaYaga1221** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
