### PR TITLE
Update what-is-nlp.mdx

### PR DESCRIPTION
**Pull request by jayesh-RN**
[#6041](https://github.com/mindsdb/mindsdb/issues/6041)

As per guide ,  I had updated NLP documentation and included GPT-4 in that.

## Description

Included :
" ...and [OpenAI’s GPT-3 and GPT-4 models](https://openai.com/), OpenAI’s GPT-3 and GPT-4 models.. "

in last paragraph
 solves. 

**Fixes** #(issue)

## Type of change

- [x] 📄 This change requires a documentation update

### What is the solution?

Added GPT-4 with GPT-3

## Checklist:

- [x] I have updated the documentation, or created issues to update them.

- [x] I have read the CLA Document and I hereby sign the CLA

[#6041](https://github.com/mindsdb/mindsdb/issues/6041)

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
@jayesh-RN 
Please remember to link the issue in the PR description, like this: https://github.com/mindsdb/mindsdb/issues/6041

**Comment by martyna-mindsdb** [comment]
@jayesh-RN 
Please sign our CLA following the instructions above.

**Comment by jayesh-RN** [comment]
recheck in this Pull Request

**Comment by martyna-mindsdb** [comment]
@jayesh-RN 
You should sign the CLA by leaving a comment here.

Please leave a comment here that contains only this line: I have read the CLA Document and I hereby sign the CLA

**Comment by jayesh-RN** [comment]
I have read the CLA Document and I hereby sign the CLA
recheck in this Pull Request

**Comment by jayesh-RN** [comment]
Done...

**Pull request merged**
