### PR TITLE
New community video guide updated with a new video by Rutam 😎

### LINKED ISSUE #3369: [Video] What is MindsDB?
### Task Description

**Create a video about:**
- What is MindsDB
- How the concept of AI tables is implemented
- The solution MindsDB offers.
- Why choose MindsDB.

Information can be based of the documentation https://docs.mindsdb.com/what-is-mindsdb/.

**Basic requirements:**

- Video must be of high quality(480p and up)
- If Voice over is used it should be a good voice synthesizer that does not sound too robotic. Please research a good tool to use.
- Optional- small window at the bottom of your screen of yourself going through a tutorial.
- Video must be uploaded to Youtube.
- In the Description box, provide a link of MindsDB's website and github repository link and suggest viewers to join Slack community.

> - NOTE: We are not assigning this issue, multiple people can make the PRs.
> - After PR for video submission has been created,it would be reviewed.
> - Only videos that meet the basic requirements will be accepted and points will be rewarded.
> - Videos that do not meet requirements will be sent back with notes on how to improve.

## :loudspeaker: Additional rewards :trophy:
 
Each tutorial brings :nine: points and entry into the draw for a  :point_down: :
 
-  :computer:  [Razer Blade 15 Laptop](https://www.razer.com/hard-bundles/Razer-Blade-15-Bundle-V5-Essential/RZHB-220912-11)
- :headphones:  10 cool audio gadgets 
- :shirt: :bear: MindsDB Swag
:information_source: For more info check out[ https://mindsdb.com/hacktoberfest/](https://mindsdb.com/hacktoberfest/) :point_left: 
 
To participate in the prize draw, you need to complete this form with your contact details and links to all your merged PRs or no-code deliverables. Please submit the form once with all your contributions listed.

### PR DESCRIPTION
**Pull request by Rutam21**
Fixes #3369 

## Please describe what changes you made, in as much detail as possible

  - I have uploaded a new video on the topic- **What is MindsDB?**.
  - I have updated the list of community video guides with the link to this new video.

## Points Earned
- 9️⃣ Points for making a new video.
- 1️⃣ Point for adding a new Video Link to the Community List.

💚 mindsdb

### CODE REVIEW

**Comment by Rutam21** [comment]
@ZoranPandovski Please review and approve.

**Comment by alissatroiano** [comment]
Great work @Rutam21 ! I'm excited to make one of these myself.

@ZoranPandovski Does adding the link to tutorials.md count as another point (a total of 10 points) for these submissions? 

I just want to make sure I keep track of mine properly...

**Comment by Artemis6969** [comment]
@Rutam21 Please don't mention the issue as it will close the issue automatically when your PR is merged

**Comment by ZoranPandovski** [comment]
Good question I will check with the team, but I think it would be just the video points

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
