### PR TITLE
added inventory table implementation

### LINKED ISSUE #7488: [Shopify] Implement the Inventory table
MindsDB integrates with Shopify, so you can access your Shopify data and make relevant forecasts with MindsDB.

## Resources

Familiarize yourself with the existing Shopify integration: https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/shopify_handler

## Steps to Follow

Currently, the Shopify integration with MindsDB accesses tables from Shopify API that store products and customers.

The task is to extend [this implementation](https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/shopify_handler) to include the Inventory table from Shopify API.

**Please note that we are not assigning this type of issue.
The first PR that solves this will be accepted** :fireworks:

## :loudspeaker: Additional rewards :trophy:

Each integration test brings 15+ points for SWAG and entry into the draw for a :point_down: :
-  :computer:  [Razer Blade 16 Laptop](https://www.razer.com/gaming-laptops/Razer-Blade-16/RZ09-0483SEJ3-R3U1)
- :shirt: :bear:  [MindsDB Swag](https://store.covver.io/mindsdb/collections/swag-collection)

:information_source: For more info check out https://mindsdb.com/hacktoberfest/ :point_left: 

**Please note that we are not assigning this type of issue.
The first PR that solves this will be accepted** :fireworks:

### PR DESCRIPTION
**Pull request by Better-Boy**
## Description

This PR introduces the inventory table.

Fixes #7488

## Type of change

(Please delete options that are not relevant)

- [x] ⚡ New feature (non-breaking change which adds functionality)
- [x] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

## Additional Media:

Screenshot 2023-10-03 at 3 08 11 AM

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have appropriately commented on my code, especially in complex areas.
- [ ] Necessary documentation updates are either made or tracked in issues.
- [x] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   **Abhi** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by Better-Boy** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by martyna-mindsdb** [comment]
@Better-Boy 
Can you add the usage examples (like SELECT) to the README.md file please?

**Comment by Better-Boy** [comment]
@martyna-mindsdb Updated readme file

**Review by ZoranPandovski — APPROVED** [review]

**Comment by martyna-mindsdb** [comment]
@Better-Boy 
Is @abhi your account?

**Review by martyna-mindsdb — APPROVED** [review]

**Comment by Better-Boy** [comment]
@martyna-mindsdb you mean slack account?

**Comment by martyna-mindsdb** [comment]
Looks like it is your other GitHub account, as mentioned above:

image

**Comment by MinuraPunchihewa** [comment]
Hey @ZoranPandovski, @martyna-mindsdb, @Better-Boy,
Sorry, I was slightly slow with my review.
From what I can see there are two levels to Shopify inventory: Inventory Items and Inventory Levels. It looks like what has been implemented here is the table for inventory levels, and it seems like we have another PR already for inventory items,
https://github.com/mindsdb/mindsdb/pull/7493

Therefore, I think we need both. But, maybe we should register this table as `inventory_levels` instead of `inventory`? Also, change the associate class names, function names etc.?

**Comment by martyna-mindsdb** [comment]
Thanks @MinuraPunchihewa 

@Better-Boy Can you open another PR to rename `inventory` to `inventory_levels` please?

**Comment by Better-Boy** [comment]
@martyna-mindsdb the new changes are in https://github.com/mindsdb/mindsdb/pull/7528

**Pull request merged**
