### PR TITLE
Shopify location table

### LINKED ISSUE #7512: [Shopify]: Location Table Implementation
### Is there an existing integration? No

- [X] I have searched the existing integrations.

### Use Case

The information in location table is needed to get inventory information.

### Motivation

The information in location table is needed to get inventory information.

### PR DESCRIPTION
**Pull request by issamarabi**
## Description

This PR introduces the `LocationTable` to the Shopify integration in MindsDB, enabling users to query location data directly from their Shopify stores.

Fixes #7512 (assuming this is the issue number for the Location Table Implementation)

## Type of change

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: `https://your-mindsdb-instance-url.com/v3/datasources/shopify_datasource` (This is an example. Replace with the actual MindsDB instance URL).
 - [x]   Verification Steps:
      1. Setup the Shopify integration by providing the required `shop_url` and `access_token`.
      2. Query the location data using: 
      ```sql
      SELECT id, name, address
      FROM shopify_datasource.locations
      ORDER BY id
      LIMIT 5
      ```
      3. Verify that the data fetched matches the locations in the Shopify store.

## Additional Media:

- [ ] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have appropriately commented on my code, especially in complex areas.
- [x] Necessary documentation updates are either made or tracked in issues.
- [x] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Review by martyna-mindsdb — APPROVED** [review]

**Review by MinuraPunchihewa — APPROVED** [review]
Looks good to me!

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by martyna-mindsdb** [comment]
@issamarabi 
Before we can merge your PR, please sign our CLA by leaving a comment here: I have read the CLA Document and I hereby sign the CLA

**Comment by issamarabi** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by ZoranPandovski — APPROVED** [review]
The tests are failing because of PostgreSQL API not related to this PR so we can merge this once @issamarabi signs the cla

**Pull request merged**
