### PR TITLE
Fixes Issue #3281

### LINKED ISSUE #3281: Tutorial to Predict the House Prices using the dataset from Kaggle

### PR DESCRIPTION
**Pull request by Moddy2024**
Fixes #3281

## Please describe what changes you made, in as much detail as possible
  - I have created a tutorial that will help teach data engineering,feature engineering, using many different models and Ensembling.

mindsdb

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by Moddy2024** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
Hey the idea here was to use MindsDB for this

**Comment by Moddy2024** [comment]
> Hey the idea here was to use MindsDB for this

Okay I will perform the necessary changes

**Pull request closed without merging**
