### PR TITLE
Unit tests/7890 shopify

### LINKED ISSUE #7890: [Unit Tests] Add unit tests for the Shopify integration
MindsDB integrates with Shopify, so you can access your Shopify data and make relevant forecasts with MindsDB.

## Resources

Familiarize yourself with the existing Shopify integration: https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/shopify_handler

## Steps to Follow

The task is to add unit tests to [this implementation](https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/shopify_handler) to test all implemented functionalities.

## :loudspeaker: Additional rewards :trophy:

Each integration test brings 15+ points for SWAG and entry into the draw for a :point_down: :
-  :computer:  [Razer Blade 16 Laptop](https://www.razer.com/gaming-laptops/Razer-Blade-16/RZ09-0483SEJ3-R3U1)
- :shirt: :bear:  [MindsDB Swag](https://store.covver.io/mindsdb/collections/swag-collection)

:information_source: For more info check out https://mindsdb.com/hacktoberfest/ :point_left:

### PR DESCRIPTION
**Pull request by dalalvarun**
## Description

Unit tests for Shopify Handler

Fixes #7890 

## Type of change

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [X]   Verification Steps: Added in readme.md at tests\unit\shopify_handler

## Additional Media:

- [x] I have attached a brief loom video or screenshots showcasing the new functionality or change.

Screenshot 2023-10-27 034859

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have appropriately commented on my code, especially in complex areas.
- [x] Necessary documentation updates are either made or tracked in issues.
- [x] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Comment by dalalvarun** [comment]
@martyna-mindsdb Done

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
Please add all tests in one file. Also, can we reference the conftest file outside of the repo ?

**Comment by dalalvarun** [comment]
> Please add all tests in one file. Also, can we reference the conftest file outside of the repo ?

Yea I will add the tests in one file.
Btw, I didnt understand what you mean by referencing the conftest file outside of the repo.

**Comment by dalalvarun** [comment]
@ZoranPandovski Do you want me to move the huge json data from the conftest file to a **resources** folder?

**Comment by dalalvarun** [comment]
@ZoranPandovski @martyna-mindsdb Lets merge this today ?

**Review by lnxpy — CHANGES_REQUESTED** [review]
Would you squash all your commits into one/two?! Thanks. :)

**Comment by dalalvarun** [comment]
@lnxpy If you merge this PR, all the commits would be automatically squashed.
From my side, its not easy to squash since the history contains commits from others as well that was pulled when I made changes after Zoran's feedback

**Comment by lnxpy** [comment]
@dalalvarun You're right, but already squashed commits make it much easier to review. :)

Thanks.

**Comment by dalalvarun** [comment]
@lnxpy Can you check the "Files Changed" tab?  That will show you all the file changes across multiple commits

**Comment by lnxpy** [comment]
There are 14 commits that indicates changes through only 5 files. It seems like you've committed each chunk separately. GitHub's reviewing system is smart, but quite over-powered as it adds up some confusion to the reviewing process. You're all good though. :)

**Review by MinuraPunchihewa — COMMENTED** [review]
Hey @dalalvarun,
I really like how you have written these tests, especially your use of fixtures. The one problem that I see is that how you have structured them do not really align with what we right now (we haven't really placed any tests for data or app handlers within the `tests/unit` directory).

In all honesty though, our tests for handlers are little bit all over the place and there is some cleanup that needs to be done on our end. 

I think we have two options for proceeding with this,
1. Place your tests in `tests/handler_tests`: not recommended because the current structure is to have just a single `pytest` file for each handler.
2. Create a new directory (package) called tests in `mindsdb/integrations/handlers/shopify_handler` and place your tests in there: this is recommended because I think a little more flexibility can be allowed there and you can maintain the same structure that you have now. The `requirements.txt` file will not be necessary because the dependencies for the handler have already been defined within that path. If you take a look at some of our other handlers, you will notice that some of them already have tests defined like this.

Sorry for the trouble, like I said, I think it is necessary from our end to structure our tests a little better. It is a work in progress.

If you can make this change, I think we can go ahead and merge this.

**Comment by ZoranPandovski** [comment]
Closing as outdated, please comment so we re-open if you continue working on this

**Pull request closed without merging**
