### PR TITLE
🗞️🗞️Cryptopanic Handler Added

### LINKED ISSUE #5548: [Integration]: CryptoPanic API Integration
### Short description of current behavior

The goal of this issue is to build a new handler that will utilize the CryptoPanic API to enable users of MindsDB to analyze and predict cryptocurrency trends. This integration will allow users to build ML models that can predict market trends, monitor social media sentiment, and make informed investment decisions.

## Resources :bulb:
:checkered_flag: To get started, please refer to the following resources:

* :books: [Building Application Handler docs](https://docs.mindsdb.com/contribute/app-handlers): This documentation will guide you through the process of building a custom handler for MindsDB. It contains essential information on the handler structure, methods, and best practices.

* :book: [CryptoPanic API docs](https://cryptopanic.com/developers/api/): This documentation contains all the endpoints and parameters that are available through the CryptoPanic API.

* :point_right: [Twitter Handler](https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/twitter_handler): This existing handler connects MindsDB with the Twitter API, allowing users to automate tasks related to posting and analyzing tweets. You can use the Twitter Handler as a reference for building the CryptoPanic API integration.

* :point_right: [Binance API Handler](https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/binance_handler): Another example of a successful MindsDB integration to the Binance API to make trade data available to use for model training and predictions.

## Next Steps :male_detective: :female_detective:
* You can familiarize yourself with the CryptoPanic API.
* Create a new handler that connects MindsDB to CryptoPanic.
* Implement the core features mentioned above.
* Thoroughly test the integration to ensure proper functionality.
* Submit a pull request with the new CryptoPanic Integration handler.

## Hackathon Issue :loudspeaker:

MindsDB has organized a hackathon on Hashnode to bring ML to more applications.

Each hackathon issue can bring you rewards and prizes :trophy: .

Check out the [MindsDB Hackathon rules on Hashnode](https://hashnode.com/hackathons/mindsdb)!

## The https://github.com/mindsdb/mindsdb/labels/hashnode-hackhathon Label

We are happy to welcome you on board! Please take a look at the rules below if you are participating in the [HashnodeHackhathon](https://hashnode.com/hackathons/mindsdb).

 *   We are not assigning this type of issue to anyone. Multiple contributors can work on this, or even better, you can create a team and work together. Join our [Slack](https://mindsdb.com/joincommunity) to discuss more details. We will merge the best-quality PR.

 *   After you create your first PR in the MindsDB repository, please sign our CLA to become a MindsDB contributor. You can do that by leaving a comment in the Pull Request that contains the following: I have read the CLA Document and I hereby sign the CLA

Thank you for contributing to MindsDB :bear: !

### Video or screenshots

_No response_

### Expected behavior

_No response_

### How to reproduce the error

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by parthiv11**
## Description

- Added Cryptopanic handler provides new related to crypto markets, for now added news table only

Fixes #5548 

## Type of change

- [x] ⚡ New feature (non-breaking change which adds functionality)
- [x] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [ ] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have appropriately commented on my code, especially in complex areas.
- [ ] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

[cryptopanic.webm](https://github.com/mindsdb/mindsdb/assets/75653580/abef2cd7-3612-403f-9742-8803fdcc427d)

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
Is this ready for review @parthiv11 ?

**Comment by parthiv11** [comment]
@ZoranPandovski  yes it is ready to review

Sorry for late reply

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
Please fix the flake8 warnings https://github.com/mindsdb/mindsdb/actions/runs/9139811415/job/25168381804?pr=9070#step:6:76

**Comment by parthiv11** [comment]
Fixed flake8 warning @ZoranPandovski

**Comment by parthiv11** [comment]
@ZoranPandovski anything left in this PR

**Pull request closed without merging**
