### PR TITLE
added edge case for gpt-3.5-turbo-instruct

### LINKED ISSUE #9795: [Bug]: Fix GPT-3.5-turbo-instruct bug
### Short description of current behavior

The `gpt-3.5-turbo-instruct` model is listed in [chat models here](https://github.com/mindsdb/mindsdb/blob/staging/mindsdb/integrations/handlers/openai_handler/constants.py#L3). But when querying it, it comes back with an error, as below.

```
CREATE MODEL text_classify
PREDICT response
USING
  engine = 'openai_engine',
  max_tokens = 128,
  temperature = 0.5,
  model_name = 'gpt-3.5-turbo-instruct',
  prompt_template = '{{payload}}';

DESCRIBE text_classify;

SELECT response FROM text_classify WHERE payload = 'my prompt';
```

The error message says `[openai_engine/text_classify]: Exception: Error status 404 raised by OpenAI API: This is not a chat model and thus not supported in the v1/chat/completions endpoint. Did you mean to use v1/completions?`.

Meanwhile, other models from this list work fine:

image

## :loudspeaker: Additional rewards :trophy:

This issue brings :five:  :zero:  points for SWAG and entry into the draw for a  :point_down: :
-  :three:  :x:   :computer:  [Razer Blade 16 Gaming Laptop](https://www.razer.com/gaming-laptops/Razer-Blade-16/RZ09-0510TEN3-R3U1)
- :shirt: :bear:  [MindsDB Swag](https://store.covver.io/mindsdb/collections/swag-collection)
:information_source: For more info check out https://mindsdb.com/hacktoberfest :point_left:

### PR DESCRIPTION
**Pull request by dfordp**
## Description

Short description of current behavior
The gpt-3.5-turbo-instruct model is listed in [chat models here](https://github.com/mindsdb/mindsdb/blob/staging/mindsdb/integrations/handlers/openai_handler/constants.py#L3). But when querying it, it comes back with an error, as below.

```
CREATE MODEL text_classify
PREDICT response
USING
  engine = 'openai_engine',
  max_tokens = 128,
  temperature = 0.5,
  model_name = 'gpt-3.5-turbo-instruct',
  prompt_template = '{{payload}}';

DESCRIBE text_classify;
SELECT response FROM text_classify WHERE payload = 'my prompt';
```

The error message says [openai_engine/text_classify]: Exception: Error status 404 raised by OpenAI API: This is not a chat model and thus not supported in the v1/chat/completions endpoint. Did you mean to use v1/completions?.

Meanwhile, other models from this list work fine:

image

Fixes #9795 

## Type of change

(Please delete options that are not relevant)

- [X] 🐛 Bug fix (non-breaking change which fixes an issue)

## Verification Process

To ensure the changes are working as expected:

 - [X ]   Test Location: Specify the URL or path for testing.
 - [ X]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [ ] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [X ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ X] I have appropriately commented on my code, especially in complex areas.
- [X ] Necessary documentation updates are either made or tracked in issues.
- [X ] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb/blob/main/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by dfordp** [comment]
recheck

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
@dfordp Please remove the changes to the `contributions-aggrements` files. To sign the CLA you just need to comment on this PR with `I have read the CLA Document and I hereby sign the CLA`. Also make sure you solve the `flake8` warnings in the changes https://github.com/mindsdb/mindsdb/actions/runs/11203617141/job/31143754754?pr=9799#step:6:115

**Comment by dfordp** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by dfordp** [comment]
@ZoranPandovski done

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
Hey @dfordp now you have deleted the files instead of removing them from this PR :) The PR should include only the `openai_handler.py`

**Comment by dfordp** [comment]
🥲 I will copy paste them from the original one ,

**Comment by dfordp** [comment]
@ZoranPandovski the issue has been resolved and the changes will only be reflected in only 1 file.

It's been a while since I contributed to open source , so sorry for causing such an issue

**Review by ZoranPandovski — APPROVED** [review]

**Comment by ZoranPandovski** [comment]
That is ok, thanks :raised_hands:

**Pull request merged**
