### PR TITLE
Added insert method for email campaigns table

### LINKED ISSUE #8115: [Sendinblue] Implement INSERT for the Email Campaigns table
MindsDB integrates with Sendinblue, which provides interfaces to connect to Sendinblue via APIs and pull repository data into MindsDB

## Resources

Familiarize yourself with the existing PayPal integration: https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/sendinblue_handler

## Steps to Follow

Currently, the Sendinblue integration with MindsDB accesses the Email Campaigns Table.

The task is to extend [this implementation](https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/sendinblue_handler) to include the INSERT command for the Email Campaigns table.

Please provide screenshots or a short video in the PR to show successful test results.

## :loudspeaker: Additional rewards :trophy:

Each integration extension issue brings 15+ points for SWAG and entry into the draw for a :point_down: :
-  :computer:  [Razer Blade 16 Laptop](https://www.razer.com/gaming-laptops/Razer-Blade-16/RZ09-0483SEJ3-R3U1)
- :shirt: :bear:  [MindsDB Swag](https://store.covver.io/mindsdb/collections/swag-collection)

:information_source: For more info check out https://mindsdb.com/hacktoberfest/ :point_left:

### PR DESCRIPTION
**Pull request by Sekhar-Kumar-Dash**
## Description

Added insert method for email campaigns table

Fixes #8115 

## Type of change
- [x] ⚡ New feature (non-breaking change which adds functionality)
- [x] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [x] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have appropriately commented on my code, especially in complex areas.
- [ ] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

content and subject:
Screenshot (420)
Name:
Screenshot (421)

### CODE REVIEW

**Comment by Sekhar-Kumar-Dash** [comment]
@chandrevdw31  please review this PR

**Review by MinuraPunchihewa — COMMENTED** [review]
Hey @Sekhar-Kumar-Dash,
Sorry for the late response, but this looks great! So, this should send out an email to all of the recipients, right? Could you please add a screenshot of an email actually going through?

**Comment by Sekhar-Kumar-Dash** [comment]
> Hey @Sekhar-Kumar-Dash, Sorry for the late response, but this looks great! So, this should send out an email to all of the recipients, right? Could you please add a screenshot of an email actually going through?

hey @MinuraPunchihewa  here are the screenshots                                                                                                                             
image
image

**Review by MinuraPunchihewa — APPROVED** [review]

**Comment by MinuraPunchihewa** [comment]
Thank you @Sekhar-Kumar-Dash.

**Pull request merged**
