### PR TITLE
Create hf_esg6_tutorial_test.mdx

### PR DESCRIPTION
**Pull request by MahenderPoshaboina**
## Description

**Fixes** #(6081)

## Added Test the Hugging Face - ESG (6) tutorial

- [ ] ⚡ New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@MahenderPoshaboina 
Please follow the rules as in the issue description.

1. comment on an issue you want to solve and wait until you are assigned.
2. create a PR and link the issue number like this: https://github.com/mindsdb/mindsdb/issues/6081

Please sign our CLA so we can merge your PR.

**Comment by MahenderPoshaboina** [comment]
@martyna-mindsdb I have commented at the issue. can you please assign me ?

**Pull request closed without merging**
