### PR TITLE
Fixes for Issue #8565

### LINKED ISSUE #8565: [Bug]: Anthropic models support
### Short description of current behavior

Currently our Anthropic integration supports [claude-1 and claude-2](https://github.com/mindsdb/mindsdb/blob/7e4c17dc97db651b77ac2d3ddc12f0e4d6d50f1c/mindsdb/integrations/handlers/anthropic_handler/anthropic_handler.py#L24) models which are outdated with the latest version of Anthropic and should be changed to:

Family |	Latest version |
------------|-----------
Claude Instant	|claude-instant-1.2|
Claude	|claude-2.1|

For more info check https://docs.anthropic.com/claude/reference/selecting-a-model. Related issue https://github.com/mindsdb/mindsdb/issues/8535

### PR DESCRIPTION
**Pull request by meet0806**
## Update model version

Changed the old model version with Updated version.

Fixes #8565

## Type of change

- [x] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [x]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have appropriately commented on my code, especially in complex areas.
- [x] Necessary documentation updates are either made or tracked in issues.
- [x] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb/blob/staging/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by meet0806** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ZoranPandovski** [comment]
@paxcema Do we need any more updates?

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
@meet0806 Please update the PR description with info following the template

**Comment by meet0806** [comment]
> @meet0806 Please update the PR description with info following the template

Done

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
