### PR TITLE
Added check if python version < 3.6 on server start

### LINKED ISSUE #742: Check if the python version is at least 3.6 on server start.
On Server start check if Python version is < 3.8

if lower version, print message:

```
MindsDB server requires Python >= 3.8 to run

Once you have Python 3.8 installed you can tun mindsdb as follows:

1. create and activate venv:
    python3.8 -m venv venv
    source venv/bin/activate
2. install MindsDB:
    pip3 install mindsdb
3. Run MindsDB
    python3.8 -m mindsdb

More instructions in https://docs.mindsdb.com

```

and exit

### PR DESCRIPTION
**Pull request by himadriganguly**
Fixes #742 

## Please describe what changes you made, in as much detail as possible
  - Added version check using **sys.version_info** for both **major** and **minor** version of **python**.
  - Added **venv** folder in **.gitignore** for **virtualenv**

### CODE REVIEW

**Comment by George3d6** [comment]
@himadriganguly  Can you change the check from being > 3.8 to > 3.6 ?

There was a misunderstanding leading to the original issue.

**Comment by himadriganguly** [comment]
> @himadriganguly Can you change the check from being > 3.8 to > 3.6 ?
> 
> There was a misunderstanding leading to the original issue having the wrong version.

So we have to check if the version is greater than >3.6? or The version is between 3.6 and 3.8?

**Comment by himadriganguly** [comment]
@George3d6 Updated the code please check.

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/> 
   - - -
   ***I have read the CLA Document and I hereby sign the CLA***
   - - - 
   <sub>You can retrigger this bot by commenting **recheckcla** in this Pull Request</sub>

**Comment by himadriganguly** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by himadriganguly** [comment]
@George3d6 Thank you for merge. 

There is another issue of a not graceful shutdown on entering **CTRL+C**, if you wish I can work on that as well.

**Pull request merged**
