### PR TITLE
Jupysql docs integration guide

### LINKED ISSUE #4302: [FR] Jupysql integration
### Short description and motivation for the proposed feature

It'd be great to see a tutorial or documentation of the 2 frameworks.
Probably a user working locally via a jupyter notebook and [jupysql](https://github.com/ploomber/jupysql) to query mindsdb and perform EDA/modeling work.

### Video or screenshots

_No response_

### Describe some possible solutions

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by idomic**
## Description
This PR adds a connection guide from Jupyter notebooks to MindsDB via Jupysql.

**Fixes** #(issue)
Closes #4302

## Type of change

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue) (Documentation)

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation, or created issues to update them.
- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] I have checked that my code additions will fail neither code linting checks nor unit test.
- [ ] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Review by ZoranPandovski — APPROVED** [review]
Thanks

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by idomic** [comment]
Done.
I have read the CLA Document and I hereby sign the CLA

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
Sorry, the bot will be triggered by only copying/pasting the agreement without Done :smile:

**Comment by idomic** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
