### PR TITLE
Invoices table implemented

### LINKED ISSUE #7673: [PayPal] Implement the Invoices table
MindsDB integrates with PayPal, so you can access PayPal data and make relevant predictions with MindsDB.

## Resources

Familiarize yourself with the existing PayPal integration: https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/paypal_handler

## Steps to Follow

Currently, the PayPal integration with MindsDB accesses the Payments table.

The task is to extend [this implementation](https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/paypal_handler) to include the Invoices table.

Please provide screenshots or a short video in the PR to show successful test results.

## :loudspeaker: Additional rewards :trophy:

Each integration extension issue brings 15+ points for SWAG and entry into the draw for a :point_down: :
-  :computer:  [Razer Blade 16 Laptop](https://www.razer.com/gaming-laptops/Razer-Blade-16/RZ09-0483SEJ3-R3U1)
- :shirt: :bear:  [MindsDB Swag](https://store.covver.io/mindsdb/collections/swag-collection)

:information_source: For more info check out https://mindsdb.com/hacktoberfest/ :point_left:

### PR DESCRIPTION
**Pull request by Tushar98644**
## Description
Implemented a Invoices table as an extension to the paypal integration

Fixes #7673

## Type of change

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [x] 📄 This change requires a documentation update

## Additional Media:

- [x] I have attached a brief loom video or screenshots showcasing the new functionality or change.
    
https://github.com/mindsdb/mindsdb/assets/107763774/e819ff0f-ee7d-43d6-9aec-66d990683a31

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have appropriately commented on my code, especially in complex areas.
- [x] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@Tushar98644 
Please sign our CLA following the instructions above.

Also, please provide screenshots or a short vide presenting the feature you implemented in this PR.

**Comment by Tushar98644** [comment]
I have read the CLA Document and I hereby sign the CLA


recheck

**Comment by Tushar98644** [comment]
recheck

**Comment by Tushar98644** [comment]
> ## Description
> Implemented a Invoices table as an extension to the paypal integration
> 
> Fixes #7673
> 
> ## Type of change
> (Please delete options that are not relevant)
> 
> * [ ]  🐛 Bug fix (non-breaking change which fixes an issue)
> * [x]  ⚡ New feature (non-breaking change which adds functionality)
> * [ ]  📢 Breaking change (fix or feature that would cause existing functionality not to work as expected)
> * [x]  📄 This change requires a documentation update
> 
> ## Additional Media:
> * [ ]  I have attached a brief loom video or screenshots showcasing the new functionality or change.
> 
> ## Checklist:
> * [x]  My code follows the style guidelines(PEP 8) of MindsDB.
> * [x]  I have appropriately commented on my code, especially in complex areas.
> * [x]  Necessary documentation updates are either made or tracked in issues.
> * [ ]  Relevant unit and integration tests are updated or added.



> @Tushar98644 Please sign our CLA following the instructions above.
> 
> Also, please provide screenshots or a short vide presenting the feature you implemented in this PR.

done

**Comment by martyna-mindsdb** [comment]
Thanks @Tushar98644 
Please add a usage example to the `mindsdb/integrations/handlers/paypal_handler/README.md` file.

**Comment by Tushar98644** [comment]
> Thanks @Tushar98644 Please add a usage example to the `mindsdb/integrations/handlers/paypal_handler/README.md` file.

done

**Review by martyna-mindsdb — APPROVED** [review]

**Comment by Tushar98644** [comment]
it would be highly appreciated if you could apply the 'hacktoberfest-accepted' label, as this would count towards accepted pull requests in the Hacktoberfest event.

**Comment by martyna-mindsdb** [comment]
No worries. Your PR will be counted.

**Comment by someshfengde** [comment]
#7841

**Pull request merged**
