### PR TITLE
Changed `cloud-mysql.mindsdb.com` to `cloud.mindsdb.com`

### PR DESCRIPTION
**Pull request by Temidayo32**
Fixes #

- Changed `cloud-mysql.mindsdb.com` to `cloud.mindsdb.com` following error from a GUI client: Dbeaver ( `unable to read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.`)
-  I noticed the `Mindsdb Cloud Username` is the same as the `email address` so I pointed that out with a comment. 
- Then, adding a note on the behaviour of Sqlalchemy `create_engine` to the documentation

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
Recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   **Temidayo** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Review by Ricram2 — APPROVED** [review]

**Comment by Ricram2** [comment]
recheck

**Comment by Ricram2** [comment]
@ZoranPandovski, I am unsure what do we need from @Temidayo32 to merge this. help !

**Comment by Temidayo32** [comment]
I have read the CLA Document and I hereby sign the CLA

Temidayo Azeez

**Comment by ZoranPandovski** [comment]
@Temidayo32 You will need to  [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by Temidayo32** [comment]
> 

I have added it

**Comment by ZoranPandovski** [comment]
Awesome, now please just copy paste `I have read the CLA Document and I hereby sign the CLA` without adding additional words :)

**Comment by Temidayo32** [comment]
>

**Comment by Temidayo32** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ZoranPandovski** [comment]
recheckcla

**Pull request merged**
