### PR TITLE
add short cut for installing handler requirements

### PR DESCRIPTION
**Pull request by dusvyat**
## Description

update Makefile to shortcut handler requirements install

**Shortcuts:**

Install mindsdb locally, dev requirements and install pre-commit hooks:

`make install_mindsdb` 

Run precommit on local staged changes:

`make precommit`

Install requirements for a specific handler:

`make install_handler  HANDLER_NAME=writer`

run mindsdb locally with python:

`make run_mindsdb`

## Type of change

(Please delete options that are not relevant)

- [x] ⚡ New feature (non-breaking change which adds functionality)

## Verification Process

To ensure the changes are working as expected:

 - [x]   Test Location: locally

## Additional Media:

- [ ] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have appropriately commented on my code, especially in complex areas.
- [x] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Comment by dusvyat** [comment]
Update Makefile to shortcut handler requirements install

**Comment by dusvyat** [comment]
@ZoranPandovski I think we should update docs for local install based on these additions.

any objections?

**Review by paxcema — APPROVED** [review]
LGTM, worth asking Hamish, Farley or Lucas for their input though.

**Comment by dusvyat** [comment]
@lucas-koontz / @AndrewFarley  / @hamishfagg any issue with this?

**Pull request merged**
