### PR TITLE
[Instatus] Implemented Components table

### PR DESCRIPTION
**Pull request by ritwickrajmakhal**
## Description

Implemented Components table for instatus handler

## Type of change

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] 📄 This change requires a documentation update

## Verification Process
Verification Process would be same as #8030 

### SELECT:
image

### WHERE:
image

### INSERT:
image

### UPDATE:
image

- [x] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have appropriately commented on my code, especially in complex areas.
- [x] Necessary documentation updates are either made or tracked in issues.
- [x] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Review by MinuraPunchihewa — CHANGES_REQUESTED** [review]
Hey @ritwickrajmakhal,
Similar to your other PR, it would be great if you can structure the output of the table, so that, for instance, such complex of string values need not be used when entering data.

**Comment by ritwickrajmakhal** [comment]
Hey @MinuraPunchihewa, thanks for the review, But actually I am having my University exam from 1st of December. I should make all the changes after 21th of December, till then please bear with me 🙌.

**Comment by MinuraPunchihewa** [comment]
@ritwickrajmakhal Sure, I think this should be fine.

**Comment by ritwickrajmakhal** [comment]
Here, I have flattened the `translations` column, and created two extra columns, `translations_desc` and `translations_name`. So that writing complex json syntax can be avoided.

**Comment by MinuraPunchihewa** [comment]
Hey @ritwickrajmakhal,
Thank you for this!
Could you please add some new screenshots of how this works after your changes?

**Comment by ritwickrajmakhal** [comment]
Before changes:
### INSERT:
```sql
INSERT INTO mindsdb_instatus.components (page_id, name, description, status, order, showUptime, grouped, translations)
VALUES (
  'clow3ez3g586478hxn40j2cju3o',
  'Test component',
  'Testing',
  'OPERATIONAL',
  6,
  true,
  false,
'{
    "name": {
      "fr": "Composant de test"
    },
    "description": {
      "fr": "En test"
    }
  }' 
);
```
### UPDATE:
```sql
UPDATE mindsdb_instatus.components
SET
  name = 'Test component 4',
  description = 'Test test test',
  status = 'OPERATIONAL',
  order = 6,
  showUptime = true,
  grouped = false,
  translations = '{
    "name": {
      "fr": "Composant de test"
    },
    "description": {
      "fr": "En test"
    }
  }' 
WHERE page_id = '<status-page-id>'
AND component_id = '<component-id>';
```
## After changes:
### INSERT:
```sql
INSERT INTO mindsdb_instatus.components (page_id, name, description, status, order, showUptime, grouped, translations_name, translations_desc)
VALUES (
  'clow3ez3g586478hxn40j2cju3o',
  'Test component',
  'Testing',
  'OPERATIONAL',
  6,
  true,
  false,
  '{"fr": "Composant de test"}',
  '{"fr": "En test"}'
);
```
### UPDATE:
```sql
UPDATE mindsdb_instatus.components
SET
  name = 'Test component 4',
  description = 'Test test test',
  status = 'OPERATIONAL',
  order = 6,
  showUptime = true,
  grouped = false,
  translations_name = '{"fr": "Composant de test 4"}',
  translations_desc = '{"fr": "Test test test"}'
WHERE page_id = '<status-page-id>'
AND component_id = '<component-id>';
```

**Comment by MinuraPunchihewa** [comment]
Is it not possible to provide flattened structure for values like this as well: `{"fr": "Composant de test 4"}`?
Also, does `SELECT` return a flattened table?

**Comment by ritwickrajmakhal** [comment]
Screenshot from 2023-12-21 18-10-28
As you can see from the screenshot that there is number of options available for different languages, So I think it can't be further flattened.

**Comment by ritwickrajmakhal** [comment]
Hey @MinuraPunchihewa, I working to to provide flattened structure for values like this: {"fr": "Composant de test 4"}

**Comment by ritwickrajmakhal** [comment]
**INSERT QUERY:**
```sql
INSERT INTO mindsdb_instatus.components (page_id, name, description, status, order, showUptime, grouped, translations_name_in_fr, translations_desc_in_fr)
VALUES (
  '<page-id>',
  'Test component',
  'Testing',
  'OPERATIONAL',
  6,
  true,
  false,
  "Composant de test",
  "En test"
);
```
**UPDATE QUERY:**
```sql
UPDATE mindsdb_instatus.components
SET
  name = 'Test component 4',
  description = 'Test test test',
  status = 'OPERATIONAL',
  order = 6,
  showUptime = true,
  grouped = false,
  translations_name_in_fr = "Composant de test 4",
  translations_desc_in_fr = "Test test test"
WHERE page_id = '<page-id>'
AND component_id = '<component-id>';
```
**SELECT QUERY:**
image

**Review by MinuraPunchihewa — COMMENTED** [review]
Hey @ritwickrajmakhal,
This looks great now! The last thing we need to do is to solve the CI check that is failing above. Then we should be good to go ahead and merge!

**Comment by ritwickrajmakhal** [comment]
@MinuraPunchihewa I have solved the CI issues, can you please re run actions now?

**Review by MinuraPunchihewa — APPROVED** [review]

**Pull request merged**
