### PR TITLE
Update plaid_handler.py

### LINKED ISSUE #7611: [Docs]: Typo in `mindsdb/integrations/handlers/plaid_handler/plaid_handler.py`
### Short description of what should be added or improved

typo can be fixed by changing Twitter to Plaid

### Video or screenshots

Screenshot 2023-10-06 224917

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by UdAyAn123**
Spelling Corrections

## Description

Please include a summary of the change and the issue it solves. 

Fixes #7611 
 
## Type of change

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [✓] 📄 This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have appropriately commented on my code, especially in complex areas.
- [ ✓] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

I have read the CLA Document and I hereby sign the CLA

recheck

### CODE REVIEW

**Review by work-mohit — COMMENTED** [review]
LGTM!

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by ZoranPandovski** [comment]
This was solved, please check help-wanted issues

**Pull request closed without merging**
