### PR TITLE
Fix and Updated tutorial URL in docs  customer-churn.md

### PR DESCRIPTION
**Pull request by idivyanshbansal**
Fixes #
#   #1518 

## Please describe what changes you made, in as much detail as possible
  -

mindsdb

### CODE REVIEW

**Comment by idivyanshbansal** [comment]
Not a single image is working  @ZoranPandovski 

screencapture-github-mindsdb-mindsdb-blob-stable-docs-mindsdb-docs-docs-sql-tutorials-customer-churn-md-2021-10-10-18_22_17

**Comment by idivyanshbansal** [comment]
And now see my change preview 
screencapture-github-mindsdb-mindsdb-pull-1530-files-2021-10-10-18_23_39

**Comment by ZoranPandovski** [comment]
They will work, once the md files are built to HTML pages using Mkdocs

**Comment by ZoranPandovski** [comment]
They point to the location of built assets, they don't need to point to GitHub location.

**Comment by idivyanshbansal** [comment]
> They point to the location of built assets, they don't need to point to GitHub location.

OHk @ZoranPandovski sir. Possibly my misunderstanding. Sorry for that .😔😔😔

**Pull request closed without merging**
