### PR TITLE
Add docs on how to DROP a file.

### PR DESCRIPTION
**Pull request by neonbhai**
## Description

Documentation update for instructions on how to DROP a file.

**Fixes** #5766

## Type of change

(Please delete options that are not relevant)

- [x] 📄 This change requires a documentation update

### What is the solution?

Adds documentation on how to DROP a file to `docs/sql/drop/table.mdx` file

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have updated the documentation, or created issues to update them.

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@neonbhai 
Please sign our CLA by leaving a comment here that contains this line: I have read the CLA Document and I hereby sign the CLA

**Comment by neonbhai** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
