### PR TITLE
Updated MongoDB link in README

### PR DESCRIPTION
**Pull request by gabcomby**
## Description

Updated the MongoDB link in the README file.

**Fixes** #5846

## Type of change

README Update.

### What is the solution?

Changed the HREF link.

## Checklist:

- [X ] My code follows the style guidelines(PEP 8) of MindsDB.
- [X ] I have commented my code, particularly in hard-to-understand areas.
- [X ] I have updated the documentation, or created issues to update them.
- [X ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [X ] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by gabcomby** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by gabcomby** [comment]
recheck

**Comment by gabcomby** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by martyna-mindsdb** [comment]
@gabcomby 
You have made a lot of changes to this file. But you didn't implement the change that was described in the issue.

Please undo all change you've made and update the link as instructed in the issue description.

**Comment by gabcomby** [comment]
@martyna-mindsdb sorry for the confusion, not really sure what happened :( I rebased the README on the current one in the repo and did the changes described in the issue #5846

**Pull request merged**
