### PR TITLE
Fix/docs create predictor

### PR DESCRIPTION
**Pull request by Ricram2**
For internal review

image

mindsdb

### CODE REVIEW

**Comment by mindsdbadmin** [comment]
****CLA Assistant Lite bot**** All contributors have signed the CLA  ✍️

**Comment by Dav1dF** [comment]
Minor typo

Screenshot 2022-05-11 at 11 27 21

**Comment by Dav1dF** [comment]
@Ricram2 For consistency it would be beneficial to show the returned predictions when running `USING Example` and also `CREATE PREDICTOR for Time Series Models Example`, in the same fashion that you've shown the values returned for the `CREATE PREDICTOR mindsdb.home_rentals_model`. This would enable users to build a higher degree of confidence if their results are close to the ones shown in the tutorial.

**Comment by Ricram2** [comment]
@Dav1dF Fixed on latest commit. :)

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
