### PR TITLE
Added Tip to duckdb.mdx

### PR DESCRIPTION
**Pull request by Aishwarya1396**
Added Tip to duckdb.mdx

Added Tip at the end of Implementation in the duckdb.mdx file.

Thanks.

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by martyna-mindsdb** [comment]
@Aishwarya1396 
Please sign the CLA here.

**Comment by Aishwarya1396** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by martyna-mindsdb** [comment]
recheckcla

**Pull request merged**
