### PR TITLE
Change the license from MIT to GPL-3.0 in the about file

### PR DESCRIPTION
**Pull request by divait**
Fixes #
Fix the license for the setup.
## Please describe what changes you made, in as much detail as possible
  - In ```__about__.py``` change the license to GPL-3.0 from MIT

mindsdb

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
  - - -
  ***I have read the CLA Document and I hereby sign the CLA***
  - - - 
  <sub>You can retrigger the CLA Action by commenting **recheckcla** in this Pull Request</sub>

**Comment by George3d6** [comment]
Good point, we should have the correct license everywhere.

@divait could you please agree to the CLA (see instructions above) and then we can go ahead and merge this.

**Comment by divait** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ZoranPandovski** [comment]
Thanks @divait .This was successfully signed, but the fix for auto-updating the status is in the same branch(staging) :) . We can merge this.

**Comment by divait** [comment]
> **CLA Assistant Lite** All Contributors have signed the CLA.

Where can I find the CLA?

**Pull request closed without merging**
