### PR TITLE
updated the link

### PR DESCRIPTION
**Pull request by FahadRahman912**
## Description

Please include a summary of the change and the issue it solves. 

**Fixes** #(issue)

## Type of change

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📄 This change requires a documentation update

### What is the solution?

(Describe at a high level how the feature was implemented)

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation, or created issues to update them.
- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by FahadRahman912** [comment]
I have updated the designated link 
fixed issue #5881

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you all sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   **1** out of **2** committers have signed the CLA.<br/>:white_check_mark: @rafiya2003<br/>:x: @FahadRahman912<br/><sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@FahadRahman912 
Please link the issue number like this: https://github.com/mindsdb/mindsdb/issues/5877
Please sign the CLA as mentioned above.

Also, you've done many changes to the file. Could you please undo all changes and keep only the update to the link?

**Comment by FahadRahman912** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by FahadRahman912** [comment]
I have undid all the changes except the link

**Comment by martyna-mindsdb** [comment]
@FahadRahman912 
All the changes to the file (such as changing `*` to `-`) are still there. Please see the `FIle changed` tab of this PR and correct it.

**Comment by martyna-mindsdb** [comment]
@FahadRahman912 
Are you still working on the changes here?

**Comment by martyna-mindsdb** [comment]
@FahadRahman912 
You can have a look at other open help-wanted issues.

**Pull request closed without merging**
