### PR TITLE
Star rocks integration

### LINKED ISSUE #4356: Add StarRocks Integration to the README
I would like to source my data from StarRocks (real-time OLAP). Thanks

### PR DESCRIPTION
**Pull request by ratika-12**
Fixes #4356 

Add StarRocks Integration.

### CODE REVIEW

**Comment by ratika-12** [comment]
@ZoranPandovski  Please review it :-)

**Review by ZoranPandovski — APPROVED** [review]

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by ratika-12** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ratika-12** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ratika-12** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ZoranPandovski** [comment]
recheckcla

**Pull request merged**
