### PR TITLE
Updated link in docs/sql/tutorials/twitter-chatbot.mdx

### PR DESCRIPTION
**Pull request by ankit-dahal**
## Description

Please include a summary of the change and the issue it solves. 

Updated the link as mentioned in the issue #6412 

## Type of change 
- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [ ] I have updated the documentation, or created issues to update them.

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@ankit-dahal 
Please sign our CLA by leaving a comment here: I have read the CLA Document and I hereby sign the CLA

**Comment by ankit-dahal** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by martyna-mindsdb** [comment]
recheckcla

**Pull request merged**
