### PR TITLE
Created the Readme file for Rayserve handler  

### PR DESCRIPTION
**Pull request by Atharva1723**
## Description
This pull request introduces an updated README file for the `RayServeHandler` package. The README now includes detailed information about the package

## Type of change
The changes aim to enhance the package's documentation, making it easier for users to understand and use the `RayServeHandler` effectively.

- [ ✔] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [✔ ]   Test Location: Specify the URL or path for testing.
 - [✔ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [✔ ] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [ ✔] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ✔] I have appropriately commented on my code, especially in complex areas.
- [✔ ] Necessary documentation updates are either made or tracked in issues.
- [ ✔] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Comment by Atharva1723** [comment]
@chandrevdw31 Can you please review this PR ? Thank You :)

**Comment by Atharva1723** [comment]
@chandrevdw31 Can you please review this PR ? Thank You :)

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
We need to include more informations. you can check some of other handlers as reference

**Comment by Atharva1723** [comment]
@ZoranPandovski I have added more information about RayServe

**Comment by ZoranPandovski** [comment]
This is not up to the standards as other ML Engines docs. Please look for a help-wanted issues if you want to contribute

**Pull request closed without merging**
