### PR TITLE
Update the MatrixOne link in the README.md file

### PR DESCRIPTION
**Pull request by roberanegussie**
## Description
Updated  the MatrixOne link in the README.md file from
`<a href="https://docs.mindsdb.com/data-integrations/all-data-integrations#matrix-one"></a>` 
to `https://docs.mindsdb.com/data-integrations/matrixone`
**Fixes** #5923 

## Type of change 

- [x] 📄 This change requires a documentation update

### What is the solution?

Updated the README.md file to have the latest matrix-one link.

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have updated the documentation, or created issues to update them.

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@roberanegussie 
Please sign our CLA so we can merge your PR.

**Comment by roberanegussie** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
