### PR TITLE
Added update to orders_table

### PR DESCRIPTION
**Pull request by alanyoung7**
## Description

Added update function to Shopify_tables - orders_table

[Shopify] Implement UPDATE for the Orders table #7846

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by martyna-mindsdb** [comment]
@alanyoung7 
Please provide a short video that presents that this UPDATE works on Orders table.

Also, please sign our CLA by leaving a comment here: I have read the CLA Document and I hereby sign the CLA

**Comment by alanyoung7** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by alanyoung7** [comment]
I will work on the video.

**Comment by ZoranPandovski** [comment]
Hey @alanyoung7 how did you implement this without installing mindsdb? Can you please share the issue you have?

**Comment by martyna-mindsdb** [comment]
@alanyoung7 
If you have issues while installing MindsDB, please feel free to ask in the community Slack, so we can help you troubleshoot it.

**Comment by ZoranPandovski** [comment]
Closing as outdated, please comment so we sync if you continue working on this

**Pull request closed without merging**
