### PR TITLE
Tested & Added docs for YouTube Integration

### PR DESCRIPTION
**Pull request by tcchawla**
## Description

Please include a summary of the change and the issue it solves. 

Tested the YouTube Integration in different env(s) like local, public cloud, docker. It is working nicely in every environment. Added docs tutorial for `YouTube` Integration.

## Type of change

- [x] 📄 This change requires a documentation update

### What is the solution?

Tutorial for `YouTube` integration.

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation, or created issues to update them.
- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
@tcchawla 
Please create the `Manual_QA.md` file inside the `.../mindsdb/integrations/handlers/youtube_handler` folder, and add screenshots of your test results.

**Comment by tcchawla** [comment]
Hey @martyna-mindsdb, I have added the `Manual_QA.md`.

**Comment by martyna-mindsdb** [comment]
Thanks @tcchawla 

FYI: The issue #6958 is for community contributors - the more people test the handlers, the better.

**Comment by tcchawla** [comment]
Sorry, I didn't knew if many can test the same handler.

**Comment by martyna-mindsdb** [comment]
@tcchawla 
No worries. We post these Manual QA issues for community, so multiple people can work on it and append their test results.

**Comment by tcchawla** [comment]
Got it 🙏

**Pull request merged**
