### PR TITLE
Updated a link to the Amazon Redshift integration

### PR DESCRIPTION
**Pull request by Raghav-Programmer**
Updated a link to the Amazon Redshift integration to this link -->  https://docs.mindsdb.com/data-integrations/all-data-integrations#amazon-redshift

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
@Raghav-Programmer 
Please mention the issue number (https://github.com/mindsdb/mindsdb/issues/4751) when creating PRs in future.

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@Raghav-Programmer 
Before we can merge your PR, please sign our CLA following the instructions above. Thanks.

**Comment by Raghav-Programmer** [comment]
> @Raghav-Programmer Please mention the issue number (#4751) when creating PRs in future.

I'll surely take care of this in the future. Thanks for the feedback

**Comment by Raghav-Programmer** [comment]
***
I have read the CLA Document and I hereby sign the CLA
***

**Comment by Raghav-Programmer** [comment]
recheckcla

**Comment by Raghav-Programmer** [comment]
I have signed the CLA in the same format as mentioned above.....now what I have to do to make this pull request accepted?

**Comment by martyna-mindsdb** [comment]
@Raghav-Programmer 
Could you please leave a comment here that includes only this: `I have read the CLA Document and I hereby sign the CLA`

**Comment by Raghav-Programmer** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by martyna-mindsdb** [comment]
Thanks, @Raghav-Programmer 
Now, you can have a look at other https://github.com/mindsdb/mindsdb/labels/help%20wanted issues.

**Pull request merged**
