### PR TITLE
TripAdvisor Integration #5369: Implemented two other API references + Tested locally (v.0.0.1)

### PR DESCRIPTION
**Pull request by HahaBill**
## Description

- added PhotosTable
- added NearbyLocationTable

Issue: #5369

## Type of change

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x ] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [x ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [ ] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [x ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ x] I have appropriately commented on my code, especially in complex areas.
- [x ] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
Please check https://github.com/mindsdb/mindsdb/actions/runs/6496718337/job/17644278195?pr=7734#step:5:12

**Comment by HahaBill** [comment]
Got it, I will look into it soon

**Comment by HahaBill** [comment]
@ZoranPandovski Hey, I fixed the code according to the code_checking.

**Comment by tomhuds** [comment]
@ZoranPandovski please ensure checklist is completed

**Comment by HahaBill** [comment]
@tomhuds I wrote unit tests for other 3 tables but not for these ones. I will create another PR with the tests, then the checklist will be completed

**Comment by HahaBill** [comment]
@tomhuds I wrote unit tests for other 3 tables but not for these ones. I will create another PR with the tests, then the checklist will be completed

**Comment by tomhuds** [comment]
Amazing - thank you @HahaBill

**Pull request merged**
