### PR TITLE
Deleted select-diagram.png

### PR DESCRIPTION
**Pull request by Mirza-Hassan**
Remove asset file

Fixes https://github.com/mindsdb/mindsdb/issues/3847

  -removed select-diagram image file

mindsdb

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by Mirza-Hassan** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
recheck

**Comment by ZoranPandovski** [comment]
Sorry, you will need to copy/paste the exact message, without tagging

**Comment by Mirza-Hassan** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by ZoranPandovski** [comment]
recheck

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
It looks like you've pushed from one account and then made the PR with another. Are both emails added to your Git account?

**Comment by Mirza-Hassan** [comment]
@ZoranPandovski It's the last day of `hacktoberfest`. can you please merge this PR?

**Comment by ZoranPandovski** [comment]
https://github.com/mihassan-nisum-com

**Comment by Mirza-Hassan** [comment]
@ZoranPandovski Should I close this PR? create a new PR again.

**Pull request closed without merging**
