### PR TITLE
Add litellm integration - Add support for Azure OpenAI , OpenAI, Palm, VertexAI, SageMaker, Bedrock, Replicate  (100+ LLMs)

### PR DESCRIPTION
**Pull request by ishaan-jaff**
## Description
This PR addresses https://github.com/mindsdb/mindsdb/issues/6549 

This PR adds support for the above mentioned LLMs using LiteLLM https://github.com/BerriAI/litellm/ 
LiteLLM is a lightweight package to simplify LLM API calls - use any llm as a drop in replacement for gpt-3.5-turbo. 

Example
```python
from litellm import completion

## set ENV variables
os.environ["OPENAI_API_KEY"] = "openai key"
os.environ["COHERE_API_KEY"] = "cohere key"

messages = [{ "content": "Hello, how are you?","role": "user"}]

# openai call
response = completion(model="gpt-3.5-turbo", messages=messages)

# cohere call
response = completion(model="command-nightly", messages)

# anthropic call
response = completion(model="claude-instant-1", messages=messages)
```
Please include a summary of the change and the issue it solves. 

**Fixes** #(issue)
This PR addresses https://github.com/mindsdb/mindsdb/issues/6549

## Type of change

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📄 This change requires a documentation update

### What is the solution?

(Describe at a high level how the feature was implemented)

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation, or created issues to update them.
- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by ishaan-jaff** [comment]
cc @StpMax @tmichaeldb

**Comment by ishaan-jaff** [comment]
@ZoranPandovski @tmichaeldb @StpMax can you please take a look at this PR when possible ? Happy to add docs/tests if this initial version looks good. 

LiteLLM now powers 90+ LLM Applications and we'd love to support mindsdb - if adding new LLMs is a priorty 

If you'd like to meet over call to discuss this integration I'm sharing my calendly for your convenience:  https://shorturl.at/lBC05

**Comment by ZoranPandovski** [comment]
Thanks @ishaan-jaff , sorry we've missed this somehow

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by dusvyat** [comment]
@ishaan-jaff thanks for your contribution, nice project.

We have discussed internally and think it would be easier to create a separate litellm handler.

This will be quick to do, simply create a new folder called 'litellm_handler' from a copy openai handler folder with your changes and rename the relevant parts from openai to litellm.

**Comment by ishaan-jaff** [comment]
@dusvyat sounds good - will take care of this today

**Comment by ZoranPandovski** [comment]
@ishaan-jaff Thank you for this. Let's do it in a separate handler, as mentioned in  @dusvyat comment. I will close this for now

**Comment by ZoranPandovski** [comment]
Hey @ishaan-jaff will you work on this on another PR ? We want to support litellm as ML Engine

**Comment by dusvyat** [comment]
@ZoranPandovski opened this issue - https://github.com/mindsdb/mindsdb/issues/8499

Def would be helpful to add suport for litellm

**Pull request closed without merging**
