### PR TITLE
added readme and updated docs for Microsoft SQL Server

### PR DESCRIPTION
**Pull request by tcchawla**
## Description

This PR includes updates in the existing docs in order to make the process of setting up the Microsoft SQL Server simple. Also, added `README` file to the integration.

## Type of change

- [x] 📄 This change requires a documentation update

### What is the solution?

Updated the docs on how to use to this integration in the cloud env, and docker env.

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation, or created issues to update them.
- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
@tcchawla 
In the case of docs, please follow the format template (e.g. do not use `I am going to ...`, etc.)

Also, in the docs, we want to present general information on how to connect MS SQL Server, so do not go for Docker, but rather focus on describing MS SQL Server handler like it is here: https://docs.mindsdb.com/data-integrations/microsoft-sql-server

**Comment by martyna-mindsdb** [comment]
@tcchawla 
I believe there is no need to update docs for MS SQL Server.

The installation of MS SQL Server should be done on the user's side and not MindsDB - so we don't need that in our docs.

As for using Docker and creating ngrok tunnel - these are presented elsewhere in docs.

**Comment by martyna-mindsdb** [comment]
@tcchawla 
Please undo all changes to `docs/data-integrations/microsoft-sql-server.mdx`.

Let's keep all the content you added in the `README.md` file.

**Comment by tcchawla** [comment]
Hey @martyna-mindsdb , I reverted the changes made in the `docs/data-integrations/microsoft-sql-server.mdx` file. Let me know if you need any other changes.

**Pull request merged**
