### PR TITLE
Fix some bug risks and code quality issues

### PR DESCRIPTION
**Pull request by jaipradeesh**
Changes:
   - Fix dangerous mutable default arguments in `mindsdb/libs/controllers/predictor.py`, `mindsdb/libs/backends/ludwig.py` and `mindsdb/libs/backends/lightwood.py`
   - Merge redundant calls to `isinstance()` in `mindsdb/libs/helpers/text_helpers.py`
   - Removed duplicate imports in `mindsdb/libs/controllers/predictor.py`, `mindsdb/libs/data_sources/file_ds.py`, `mindsdb/libs/phases/data_splitter/data_splitter.py` and `tests/integration_tests/run_example.py`.

---

Find the other issues found here - [https://deepsource.io/gh/jaipradeesh/mindsdb/issues/?category=all](https://deepsource.io/gh/jaipradeesh/mindsdb/issues/?category=all)

This PR also adds `.deepsource.toml` configuration file to run Continuous Quality analysis on the repo with [DeepSource](https://deepsource.io). Upon enabling DeepSource, quality analysis will be run on every PR to detect 550+ types of issues in the changes — including bug risks, anti-patterns, security vulnerabilities, etc.

DeepSource is free to use for open-source projects, and is used by teams at Uber, ThoughtWorks, Slack among many others.

To enable DeepSource analysis after merging this PR, please follow these steps:
1. [Signup](https://deepsource.io/signup/) on DeepSource with your GitHub account and grant access to this repo.
2. Activate analysis on this repo [here](http://deepsource.io/gh/mindsdb/mindsdb).

You can also look at the [docs](https://deepsource.io/docs/guides/quickstart.html) for more details. Do let me know if I can be of any help!
  Also added a `.deepsource.toml` configuration file to run continuous static analysis on the repository with DeepSource.

Signed-off-by: Jai <jai@deepsource.io>

### CODE REVIEW

**Comment by George3d6** [comment]
@jaipradeesh 
Thank you for your PR, however there's a few issues I'd need addressed before merging though:

a) The read-only parameter in the interfaces of those functions, the one which you changed to be `None`, are read only. So you can safely assign object values (e.g. `[]`) to them. Thus the extra clutter and the less expressive interface by assigning their default values later is not something I want to do.

b) Possibly remove the ` .deepsource.toml`, I am not certain we want to use a tool like deepsource at the moment, It's not that I don't think it could be useful, but I don't think it provides any benefits significant enough for me to deal with the overhead (e.g. configuring it to not give warnings about stuff like (a)), If you are willing to help us with the configuration so that it gives us meaningful alerts, I'd be glad to introduce it, but even then I'd need some time to look over the current alerts and tell you which of them are the type of issues I'd rather *not* have reported (e.g. https://deepsource.io/gh/jaipradeesh/mindsdb/issue/PYL-W0614/occurrences)

**Comment by jaipradeesh** [comment]
Hey @George3d6 — thanks for your review.

Regarding point 1, I agree that it’s not required to do this when you’re certain the arguments won’t be changed later; although it’s still an anti-pattern and generally not recommended for the sake of ensuring that nothing goes wrong in the future (see [python docs](https://docs.python.org/3/tutorial/controlflow.html#default-argument-values)). That being said, happy to remove it from the PR if you want.
Regarding point 2, it’s super easy to ignore issues on a case-by-case basis from the DeepSource UI and created sophisticated rules to tune your results — you don’t have to write any config files for this, and you can do this as and when you use thr product (you won’t be able to see the controls on my copy of the repo since you don’t have access to it, but your own dashboard will have these controls).

 There are a bunch of issues which would be valuable to fix: like these [performance issues](https://deepsource.io/gh/jaipradeesh/mindsdb/issues/?category=performance), or [parameter mismatch in over-ridden methods](https://deepsource.io/gh/jaipradeesh/mindsdb/issue/PYL-W0221/occurrences).

Let me know what you think.

**Comment by George3d6** [comment]
@jaipradeesh In that case I'll merge and try playing with it over the weekend, a few of the issues you listed are actually relevant things I hadn't though about.

**Comment by jaipradeesh** [comment]
Hey @George3d6, did you manage to look at the issues/fixes?

**Comment by George3d6** [comment]
Hi @jaipradeesh sorry for the lack of answers, I was quite busy these last few weeks and forgot to look at this. Overall I want to merge this and I'll try using the tools but I need to fix the merge conflicts first... as some stuff changed around on master.

If you have time to look at them feel free to do that and ping in here once it's done, if not I'll do it myself sometime before end of last week and merge.

Again, sorry for the delay, I completely forgot about this PR :/

**Comment by jaipradeesh** [comment]
No worries. Let me fix the conflicts and update the PR in a couple of hours.

**Comment by jaipradeesh** [comment]
@George3d6 Rebased.

**Pull request merged**
