### PR TITLE
Added MindsDB Java SDK as community SDK

### LINKED ISSUE #9790: [Feature] Mindsdb Java SDK
### Short description and motivation for the proposed feature

Proposal to build java sdk, similar to python and javascript sdks - https://docs.mindsdb.com/sdks/overview, 
APIs - https://docs.mindsdb.com/rest/overview

### Video or screenshots

_No response_

### Describe some possible solutions

1. The SDK will need a new github repository
2. Since, there are multiple features to be built, this will have to be broken down into multiple smaller tasks.
3. Relevant unit tests are needed
4. Documentation
5. Publishing the sdk to Maven central repository

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by md-abid-hussain**
image

closes #9790

### CODE REVIEW

**Comment by mindsdbadmin** [comment]
<br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb/blob/main/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request. </sub><sub>Posted by the **CLA Assistant Lite bot**.</sub>

**Comment by md-abid-hussain** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by md-abid-hussain** [comment]
@quest-bot loot

**Comment by md-abid-hussain** [comment]
@quest-bot loot #9790

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
Please remove the `mint` file

**Comment by md-abid-hussain** [comment]
I have made the required changes.

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
