### PR TITLE
removed r

### PR DESCRIPTION
**Pull request by ayesha-firdaus**
## Description
removed r  from 31

Please include a summary of the change and the issue it solves. 

**Fixes** #5799

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you all sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   **1** out of **2** committers have signed the CLA.<br/>:white_check_mark: @rafiya2003<br/>:x: @ayesha-firdaus<br/><sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@ayesha-firdaus 
Before we can merge, please see the instructions above on how to sign a CLA. Thanks.

**Comment by ayesha-firdaus** [comment]
I have read the CLA document and I hereby sign CLA.

**Comment by ayesha-firdaus** [comment]
@martyna-mindsdb  is the above way or i have to email at the mail link to sign CLA

**Comment by martyna-mindsdb** [comment]
@ayesha-firdaus 
That's exactly the way. Just copy this line from above:

I have read the CLA Document and I hereby sign the CLA

**Comment by FahadRahman912** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ayesha-firdaus** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
