### PR TITLE
Delete home_rentals_model.csv

### PR DESCRIPTION
**Pull request by Ln11211**
Deleted home_rentals_model.csv table

Fixes 
This PR when merged will close the issue #3054 .
## Please describe what changes you made, in as much detail as possible
  - Just deleted the `home_rentals_model.csv` [table](https://github.com/mindsdb/mindsdb/blob/4bfd210382314a4147d902243b0ff26d2dc2f1b9/docs/mindsdb-docs/docs/sql/api/home_rentals_model.csv) as instructed in the issue #3054 

mindsdb

### CODE REVIEW

**Comment by Ln11211** [comment]
@ZoranPandovski The issue #3054  mentions that there are more files that need to be removed.. I want to know the rest of the files that I need to remove to close this issue.

I also want to know why is the PR failing a test and how to resolve it. Thank you :)

P.S-If there are none, I would be happy if you merge the pr but, do know that someone else has raised a same PR before me so if you want me to close this, I will close this.

**Comment by luiserdef** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by Ln11211** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Ln11211** [comment]
recheck

**Pull request closed without merging**
