### PR TITLE
added snowflake demo video

### PR DESCRIPTION
**Pull request by martyna-mindsdb**
## Description

added snowflake demo video

Fixes #issue_number

## Type of change

- [ ] 📄 This change is a documentation update

### CODE REVIEW

**Comment by MinuraPunchihewa** [comment]
Hey @martyna-mindsdb,
I can't really see the video that has been added here, but do you still need that read-only user for Snowflake?

**Comment by martyna-mindsdb** [comment]
Hey @MinuraPunchihewa 
It was suggested by @torrmal to include a [demo video similar to this one](https://www.loom.com/share/c9eebb857ed246f58a697cfbc3e36f5a) in the Snowflake docs.
So it'd be good to have a user with read-only permissions.

**Comment by MinuraPunchihewa** [comment]
@martyna-mindsdb I create a user with read-only permissions for your email. Can you please have a look? I think you should have received an email?
@ZoranPandovski Can you also please confirm it is alright to expose an account from this Snowflake account to the public?

**Comment by martyna-mindsdb** [comment]
@MinuraPunchihewa 
I haven't received any email from Snowflake.

Alternatively, I can try and blur connection parameters and just show how to connect and query tables. That would be fine I guess.

**Comment by ZoranPandovski** [comment]
Can we link the video from s3 or google drive, so we can avoid adding it to the repo?

**Comment by martyna-mindsdb** [comment]
@ZoranPandovski 
I tried using Google Drive link and Loom link, but videos do not load.
I'm going to upload it to YT as unlisted and link it here.

**Pull request merged**
