### PR TITLE
Updated the href links for IBM DB2 integration

### PR DESCRIPTION
**Pull request by Siddh744542**
## Description

I have updated the href links as mentioned in #4973 

**Fixes** #4973 

## Type of change
Documentation Upgrade 

(Please delete options that are not relevant)

- [ ] 📄 This change requires a documentation update

### What is the solution?

(Describe at a high level how the feature was implemented)

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation, or created issues to update them.
- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by Siddh744542** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@Siddh744542
Please note that this issue is already assigned to another contributor.

Please have a look at other unassigned issues here: [first-timers-only](https://github.com/mindsdb/mindsdb/labels/first-timers-only).
Thanks.

**Comment by martyna-mindsdb** [comment]
recheckcla

**Pull request closed without merging**
