### PR TITLE
Update README.md supabase link

### PR DESCRIPTION
**Pull request by 1ce-one**
## Description
Updated the href tag in :

href="https://docs.mindsdb.com/data-integrations/all-data-integrations#supabase"

to:
https://docs.mindsdb.com/data-integrations/supabase

**Fixes** #(5958)

## Type of change

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have updated the documentation, or created issues to update them.

### CODE REVIEW

**Comment by 1ce-one** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by 1ce-one** [comment]
recheck

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by martyna-mindsdb** [comment]
@1ce-one 
Please link the issue in the PR description like this: https://github.com/mindsdb/mindsdb/issues/5958

**Pull request merged**
