### PR TITLE
[Manual QA] Test Cassandra and Scylla Handlers Manually

### PR DESCRIPTION
**Pull request by dahjah**
Contributes to #3246

## Please describe what changes you made, in as much detail as possible
  - Completed the desired steps to manually check the Cassandra Handler as outlined in the issue.
  - I also added to the Manual Check for Scylla while I was at it.

mindsdb

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
recheckcla

**Review by ZoranPandovski — APPROVED** [review]
Thanks

**Comment by dahjah** [comment]
Just noticed an issue was created for manual QA for ScyllaDB (PR #3916 ). Commenting that here, just for linking purposes (in case that is helpful :))

**Pull request merged**
