### PR TITLE
updated tests/readme formatting as 1.2,1.3,1.4 were on single line

### PR DESCRIPTION
**Pull request by siddarth-patil**
## Description

Reformatting tests/README.md file. The reason for this was the current version has points 1.2, 1.3, and 1.4 on the single line. 

**Fixes** #4305 

## Type of change

(Please delete options that are not relevant)

- [X ] 📄 This change requires a documentation update

### What is the solution?

Reformatting the md file

## Checklist:

- [ X] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ X] I have updated the documentation, or created issues to update them.
- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] I have checked that my code additions will fail neither code linting checks nor unit test.
- [ ] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Review by ZoranPandovski — APPROVED** [review]

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   **Siddarth Shantinath Patil** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
Hey @siddarth-patil Siddarth Shantinath Patil seems not to be a GitHub user. You need to [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by siddarth-patil** [comment]
recheck

**Comment by siddarth-patil** [comment]
Hi @ZoranPandovski I have added the email ID used to commit. And tried to retrigger the bot. I didn't receive any notification after that. Did I miss something?

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
recheckcla

**Pull request merged**
