### PR TITLE
making changes to the docker.mdx mindsdb docs

### PR DESCRIPTION
**Pull request by Sujeendra**
## Description
 [Docs] Update the config.json file on Docker doc page #4889 

## Type of change
Modified docker.mdx file and changed json section as per the requirement provided in the issue and validated the json syntax.

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation, or created issues to update them.
- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by Sujeendra** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Sujeendra** [comment]
recheck

**Comment by Sujeendra** [comment]
recheck

**Comment by martyna-mindsdb** [comment]
recheckcla

**Pull request merged**
