### PR TITLE
[Docs] Updated SingleStore Link in `README.md`.

### PR DESCRIPTION
**Pull request by iamv1n**
## Description

Documentation Update:  Updated the SingleStore Link in Data Integration Section in `/mindsdb/README.md`.

**Fixes** #5874 

- [x] 🐛 Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by iamv1n** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
recheckcla

**Pull request merged**
