### PR TITLE
Add AthenaDS

### PR DESCRIPTION
**Pull request by ytannai**
## Please describe what changes you made, in as much detail as possible
- Add [Athena datasource](https://github.com/mindsdb/mindsdb_native/blob/stable/mindsdb_native/libs/data_sources/aws_athena_ds.py)

~~TODO: bump mindsdb_native version to fix AthenaDS issue~~
see also: https://github.com/mindsdb/mindsdb_native/pull/365

### CODE REVIEW

**Comment by torrmal** [comment]
Thank you @ytannai 

@George3d6 should we merge this PR for this weeks release

**Comment by George3d6** [comment]
@torrmal not sure why this didn't get merged thus far, my bad (or maybe, hopefully not, there was an issue I forgot to write down and it will crash everything horribly, but code looks fine atm, so 80% I just forgot). Solved all merge conflict, should be in today's release :)

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/> 
   - - -
   ***I have read the CLA Document and I hereby sign the CLA***
   - - - 
   <sub>You can retrigger this bot by commenting **recheckcla** in this Pull Request</sub>

**Comment by ytannai** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
