### PR TITLE
Fixed typo in the eef-forecasting-doc

### PR DESCRIPTION
**Pull request by shivam-dhaka**
## Description
**Fixes** #([issue](https://github.com/mindsdb/mindsdb/issues/4595))

## Type of change

- [x] 📄 This change requires a documentation update

## Checklist:

- [x] I have updated the documentation.

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
Recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@shivam-dhaka
Before we can merge your PR, please sign our CLA following the instructions above.

**Comment by shivam-dhaka** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by shivam-dhaka** [comment]
@martyna-mindsdb Done! ✅

**Comment by martyna-mindsdb** [comment]
recheckcla

**Pull request merged**
