### PR TITLE
Open browser when http-api started

### PR DESCRIPTION
**Pull request by sergey-mindsdb**
After initializing the application, the function of opening the browser with the main link is launched in a separate thread.
This function scans the availability of the api-http port of the service and the browser opens only after the service is started. 
If an error occurs while scanning the port or when opening the browser, then nothing happens, an error log is displayed.
  
-

mindsdb

### CODE REVIEW

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/> 
   - - -
   ***I have read the CLA Document and I hereby sign the CLA***
   - - - 
   <sub>You can retrigger this bot by commenting **recheckcla** in this Pull Request</sub>

**Comment by sergey-mindsdb** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by sergey-mindsdb** [comment]
recheck CLA

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by sergey-mindsdb** [comment]
recheckcla

**Comment by sergey-mindsdb** [comment]
request closed because commit with another author name

**Pull request closed without merging**
