### PR TITLE
[Docs][Manual QA] Test the Hugging Face - Toxicity tutorial

### PR DESCRIPTION
**Pull request by truskovskiyk**
## Description

[Docs][Manual QA] Test the Hugging Face - Toxicity tutorial

https://github.com/mindsdb/mindsdb/issues/6080

### What is the solution?

[Docs][Manual QA] Test the Hugging Face - Toxicity tutorial

## Checklist:

- [N/A] My code follows the style guidelines(PEP 8) of MindsDB.
- [N/A] I have commented my code, particularly in hard-to-understand areas.
- [Y] I have updated the documentation, or created issues to update them.
- [N/A] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [N/A] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by truskovskiyk** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by truskovskiyk** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ZoranPandovski** [comment]
recheckcla

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
