### PR TITLE
docs: Fix simple typo, semaphor -> semaphore

### PR DESCRIPTION
**Pull request by timgates42**
There is a small typo in mindsdb/api/http/namespaces/predictor.py.

Should read `semaphore` rather than `semaphor`.

### CODE REVIEW

**Comment by George3d6** [comment]
@ZoranPandovski any idea why the CLA assistant is failing on this one ?

**Comment by ZoranPandovski** [comment]
@George3d6 Cla assistance wasn't triggered due to `Error: Parameter token or opts.auth is required`. I will check if the token expired or somehow was updated.

**Comment by timgates42** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/> 
   - - -
   ***I have read the CLA Document and I hereby sign the CLA***
   - - - 
   <sub>You can retrigger this bot by commenting **recheckcla** in this Pull Request</sub>

**Comment by timgates42** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
Thanks for the contribution @timgates42. I will fix the token bot issue in next PR.

**Pull request merged**
