### PR TITLE
Update sql-alchemy.mdx

### PR DESCRIPTION
**Pull request by ya-sh-vardh-an**
## Description

Replaced line 114:  `port = <port>` with `port = 3306`

**Fixes** #6192 

## Type of change

(Please delete options that are not relevant)

- [x] 📄 Updated documentation

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have updated the documentation, or created issues to update them.

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@ya-sh-vardh-an 
Please sign our CLA so we can merge your PR.

**Comment by ya-sh-vardh-an** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
