### PR TITLE
docs: update link in docs\nlp\nlp-mindsdb-openai.mdx

### PR DESCRIPTION
**Pull request by jssonx**
## Description

Please include a summary of the change and the issue it solves. 

**Fixes** #6359 

## Type of change

(Please delete options that are not relevant)

- [x] 📄 Documentation change

### What is the solution?

update link in docs\nlp\nlp-mindsdb-openai.mdx #6359

## Checklist:

- [x] I have updated the documentation, or created issues to update them.

### CODE REVIEW

**Comment by jssonx** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by jssonx** [comment]
> 

I have read the CLA Document and I hereby sign the CLA

**Comment by martyna-mindsdb** [comment]
recheckcla

**Pull request merged**
