### PR TITLE
Fidelity

### PR DESCRIPTION
**Pull request by g-s-eire**
## Description

Please include a summary of the change and the issue it solves. 

#5152 
I have added databricks.mdx in docs/mint.json file to the "pages".

Add the file to the like this:
**Fixes** #(issue)

## Type of change

(Please delete options that are not relevant)

- [ ] ⚡ New feature (non-breaking change which adds functionality)

### What is the solution?

Added a line to the appropriate line with the relevant databricks.mdx file.

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation, or created issues to update them.
- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by martyna-mindsdb** [comment]
@g-s-eire 
Please link the issue you are solving, like this: https://github.com/mindsdb/mindsdb/issues/5152

Also, note that you duplicated this line `"data-integrations/DynamoDB"`. Please remove it.

\* Before we can merge your PR, please sign our CLA following the instructions above.

**Comment by martyna-mindsdb** [comment]
@g-s-eire 
Please link the issue you are solving, like this: https://github.com/mindsdb/mindsdb/issues/5152

Also, note that you duplicated this line `"data-integrations/DynamoDB"`. Please remove it.

\* Before we can merge your PR, please sign our CLA by leaving a comment here: I have read the CLA Document and I hereby sign the CLA

**Comment by g-s-eire** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
recheckcla

**Pull request merged**
