### PR TITLE
Added Crate-integration Documentation

### PR DESCRIPTION
**Pull request by srini047**
## Description

Please include a summary of the change and the issue it solves. 

**Fixes** #4560 

## Type of change

- [x] 📄 This change requires a documentation update

### What is the solution?

Added the Crate Integration docs as per the instructions provided in the issue and resources.

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation, or created issues to update them.
- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
@srini047 
Please see the review comments above and implement the updates in this PR.
Thanks.

**Comment by srini047** [comment]
Hey @martyna-mindsdb!! I couldn't view any comments made.

**Comment by martyna-mindsdb** [comment]
@srini047 
Can you view the comments from your email? You've got a notification about my review of your PR.

**Comment by martyna-mindsdb** [comment]
@srini047 
You should be able now to see the changes.

**Comment by srini047** [comment]
> @srini047 
> You should be able now to see the changes.

Yes @martyna-mindsdb !! I will make the changes and revert soon.

**Comment by srini047** [comment]
@martyna-mindsdb Please review the changes. I have addressed them.

**Pull request merged**
