### PR TITLE
Add documentation to connect through ngrok.

### PR DESCRIPTION
**Pull request by nablabits**
Addresses this issue: https://github.com/mindsdb/mindsdb/issues/2300

## Please describe what changes you made, in as much detail as possible
  - With the help of @chandrevdw31, I added the documentation to connect a local database with Ngrok tunneling

### CODE REVIEW

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   ***I have read the CLA Document and I hereby sign the CLA***
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by nablabits** [comment]
Some formalism 🙃 

***
***I have read the CLA Document and I hereby sign the CLA***
***

**Comment by nablabits** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
