### PR TITLE
Update README.md in derby_handler folder

### PR DESCRIPTION
**Pull request by ByronHan333**
I have read the CLA Document and I hereby sign the CLA. closes issue #5937

## Description

I edited README.md in `derby_handler` folder, 

**Fixes** #5937 

## Type of change

- [x] 📄 This change requires a documentation update

### What is the solution?

I edited README.md file according to issue requirement.

## Checklist:

- [x] I have updated the documentation, or created issues to update them.

### CODE REVIEW

**Comment by ByronHan333** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by martyna-mindsdb** [comment]
@ByronHan333 
Your PR removes some files. Please undo these changes and keep the change only in the indicated file. Thanks.

**Pull request merged**
