### PR TITLE
Added the Description in Chinese with multiple languages

### PR DESCRIPTION
**Pull request by qianmoQ**
Fixes #

Added the Description in Chinese with multiple languages

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
It would be awesome if you translate the main README to Chinese too, I can create an issue if you want to do it?

**Comment by qianmoQ** [comment]
> Thanks @qianmoQ, about the docs, before we add i18n we will need to have the files already translated so please remove docs files.

Which files need to be removed?

**Comment by ZoranPandovski** [comment]
docs/mindsdb-docs/mkdocs.yml and docs/requirements.txt

**Comment by qianmoQ** [comment]
> Thanks @qianmoQ, about the docs, before we add i18n we will need to have the files already translated so please remove docs files.

This PR allows users to select the language they want to view on the documentation site!

image

**Comment by qianmoQ** [comment]
> docs/mindsdb-docs/mkdocs.yml and docs/requirements.txt

> > Thanks @qianmoQ, about the docs, before we add i18n we will need to have the files already translated so please remove docs files.
> 
> This PR allows users to select the language they want to view on the documentation site!
> 
> image

I will add more Chinese documents here, I understand that this language option should be retained, default not translated will jump to English

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
