### PR TITLE
Google Cloud Storage Integration

### LINKED ISSUE #9724: [Integration]: Google Cloud Storage Integration
### Is there an existing integration?

- [X] I have searched the existing integrations.

### Use Case

Google Cloud Storage is one of the most used data sources.

### Motivation

This integration will help getting your data from gcp bucket to build your own ai system based on this data

### Implementation

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by TalaatHasanin**
## Description

Add google cloud storage handler.

Fixes #9724 #7695

## Type of change

- [x] ⚡ New feature (non-breaking change which adds functionality)
- [x] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [x]   Test Location: Specify the URL or path for testing.
 - [x]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [x] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have appropriately commented on my code, especially in complex areas.
- [x] Necessary documentation updates are either made or tracked in issues.
- [x] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Comment by mindsdbadmin** [comment]
<br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb/blob/main/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request. </sub><sub>Posted by the **CLA Assistant Lite bot**.</sub>

**Comment by TalaatHasanin** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by TalaatHasanin** [comment]
UI Tests:
image

**Comment by TalaatHasanin** [comment]
Hi @MinuraPunchihewa 
Can you review this?

**Comment by TalaatHasanin** [comment]
It's done by #9886

**Pull request closed without merging**
