### PR TITLE
feat:update delete insert

### PR DESCRIPTION
**Pull request by RickDeb2004**
## Description

Please include a summary of the change and the issue it solves. 

Fixes #issue_number
resolve: #7935 
## Type of change

(Please delete options that are not relevant)

- [x] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] ⚡ New feature (non-breaking change which adds functionality)
- [x] 📢 Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [x] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [x]   Test Location: Specify the URL or path for testing.
 - [x]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [x] I have attached a brief loom video or screenshots showcasing the new functionality or change.
image

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have appropriately commented on my code, especially in complex areas.
- [x] Necessary documentation updates are either made or tracked in issues.
- [x] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Comment by RickDeb2004** [comment]
why the first check is failing not understand

**Comment by martyna-mindsdb** [comment]
@RickDeb2004 
It's an issue on our end, no worries.

Please provide a short video that presents how to use the commands you implemented for the comments table.

**Comment by RickDeb2004** [comment]
> @RickDeb2004 It's an issue on our end, no worries.
> 
> Please provide a short video that presents how to use the commands you implemented for the comments table. To do that, run the INSERT/UPDATE/DELETE commands in your local MindsDB editor and provide outputs here.

ok

**Comment by ZoranPandovski** [comment]
This doesn't work closing. @RickDeb2004 Please make sure you implement all of the required functionalities and adress all of the PRs checklist

**Pull request closed without merging**
