### PR TITLE
Added planet-scale.mdx to docs navigation group

### LINKED ISSUE #5318: [Docs] Add the `planet-scale.mdx` file to docs navigation
## Instructions :page_facing_up:

Here are the step-by-step instructions:

1. Go to the `/docs/mint.json` file.

2. Go to the `"navigation"` item (at line 48). This `"navigation"` item stores the navigation structure of the [MindsDB docs](https://docs.mindsdb.com/).

3. Find the `"Data Integrations"` group (at line 291).

4. Add the `planet-scale.mdx` file to the `"pages"`, like this:

```
	{
          "group": "Data Integrations",
          "pages": [
            "data-integrations/all-data-integrations",
            "...",
            "data-integrations/planet-scale"
          ]
        }
```

3. Save the changes and create a PR.

## Hackathon Issue :loudspeaker:

MindsDB has organized a hackathon to let in more contributors to the in-database ML world.

Each hackathon issue is worth a certain amount of credits that will bring you prizes by the end of the MindsDB Hackathon.

Check out the [MindsDB Hackathon rules](https://mindsdb.com/mindsdb-hackathon)!

## The https://github.com/mindsdb/mindsdb/labels/first-timers-only Label

We are happy to welcome you on board! Please take a look at the rules below for first-time contributors.

1. You can solve only one issue labeled as https://github.com/mindsdb/mindsdb/labels/first-timers-only. After that, please look at other issues labeled as https://github.com/mindsdb/mindsdb/labels/good%20first%20issue, https://github.com/mindsdb/mindsdb/labels/help%20wanted, or https://github.com/mindsdb/mindsdb/labels/integration.

2. After you create your first PR in the MindsDB repository, please sign our CLA to become a MindsDB contributor. You can do that by leaving a comment that contains the following: `I have read the CLA Document and I hereby sign the CLA`

Thank you for contributing to MindsDB!

### PR DESCRIPTION
**Pull request by sjdex**
## Description

Added planet-scale.mdx to docs navigation group. It closes #5318 

## Type of change

(Please delete options that are not relevant)

- [ ] ⚡ New feature (non-breaking change which adds functionality)

### What is the solution?

Added planet-scale as an item in list

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation, or created issues to update them.
- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] I have shared a short loom video or screenshots demonstrating any new functionality.

I have read the CLA Document and I hereby sign the CLA

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   **Shubham Jadhav** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@sjdex 
Please sign our CLA following the instructions above.

**Comment by sjdex** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by martyna-mindsdb** [comment]
@sjdex 
Please add your email to your GitHub account as mentioned here:

   **Shubham Jadhav** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

Then you can sign the CLA.

**Comment by sjdex** [comment]
I have added my email. It seems I need to recommit so that it will get linked to my commit id. Not sure though.

**Comment by martyna-mindsdb** [comment]
@sjdex 
If you added your email, then please leave a comment again here that contains this line: I have read the CLA Document and I hereby sign the CLA

**Comment by martyna-mindsdb** [comment]
@sjdex 
Make sure that you add the same email as used for committing the changes.

**Comment by sjdex** [comment]
@martyna-mindsdb Can you close this pull request. I will recommit with updated email.

**Comment by martyna-mindsdb** [comment]
@sjdex 
Closing this PR.

**Pull request closed without merging**
