### PR TITLE
update packages metadata

### LINKED ISSUE #3062: Migrate from `requirements.txt`, `requirements_test.txt`, and `setup.py` to `pyproject.toml`.
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Hey folks. As you may already know, the use of `setup.py`, `setuptools`, and `requirements.txt` files is quite [outdated](https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html). Because of [PEP 517](https://peps.python.org/pep-0517/), [PEP 660](https://peps.python.org/pep-0660/), and [PEP 631](https://peps.python.org/pep-0631/), the packaging is now being standardized on the usage of the `pyproject.toml` file.

### Describe the solution you'd like.

Given the above info, the project packaging should add support for `pyproject.toml`. This will introduce changes at [the root dir](https://github.com/mindsdb/mindsdb) and [`mindsdb/mindsdb/integrations/handlers/lightwood_handler/`](https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/lightwood_handler).

### Describe an alternate solution.

Not available.

### Anything else? (Additional Context)

That's pretty much it. I would like to work on this issue.

### PR DESCRIPTION
**Pull request by wiseaidev**
Fixes #3062

## Please describe what changes you made, in as much detail as possible

Described in the issue.

mindsdb

### CODE REVIEW

**Comment by wiseaidev** [comment]
It seems like a timeout issue. I am going to trigger the workflow to run the tests again.

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by ZoranPandovski** [comment]
@wiseaidev Please fix the conflicts and sign the CLA so we can merge this. Feel free to re-open once you are ready

**Pull request closed without merging**
