### PR TITLE
Integrated Cloud Firestore with MindsDB

### PR DESCRIPTION
**Pull request by GeeteshMehto**
## Description

Please include a summary of the change and the issue it solves. 

Fixes #issue_number

## Type of change

(Please delete options that are not relevant)

- [x] ⚡ New feature (non-breaking change which adds functionality)

- [x] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [ ] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have appropriately commented on my code, especially in complex areas.
- [x] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Comment by GeeteshMehto** [comment]
@ZoranPandovski I have Integrated Cloud Firestore with MindsDB approve my PR with Hacktoberfest tag.

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb/blob/main/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by GeeteshMehto** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by MinuraPunchihewa — CHANGES_REQUESTED** [review]
Hi @GeeteshMehto,
A few comments,
1. I see that this handler has been implemented as a `VectorStoreHandler`? Is there any particular reason for this? As far as I a aware, Cloud Firestore is not a vector database, bu rather a NoSQL document store. I think it would be best if this was either a `DatabaseHandler` or `APIHandler`.
2. With the given implementation it is required to pass in a credentials file when using this integration, however, this will not work in a Cloud environment. Let's also include another option, such as passing in the contents of the file when running the `CREATE DATABASE` command. Our [BigQuery integration](https://docs.mindsdb.com/integrations/data-integrations/google-bigquery) includes such an option.
3. You should also include an icon for your handler (preferably SVG) and a `connection_args.py` file, which lists the required connection arguments. You can refer any of our other handlers to see what I mean.

**Pull request closed without merging**
