### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by RANJITHROSAN17**
I have read the CLA Document and I hereby sign the CLA
UPDATED href link to readme.md file in mindsdb/Readme.md

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@RANJITHROSAN17 
Please follow the rules as below:

Before creating a PR, leave a comment on an issue you want to resolve and wait until you are assigned.
Remember to link the issue number in the PR description: https://github.com/mindsdb/mindsdb/issues/5919

*** Please sign our CLA following the instructions above.

**Comment by RANJITHROSAN17** [comment]
> @RANJITHROSAN17 Please follow the rules as below:
> 
> Before creating a PR, leave a comment on an issue you want to resolve and wait until you are assigned. Remember to link the issue number in the PR description: #5919
> 
> *** Please sign our CLA following the instructions above.

sorry i am new to github i dont know can you give some important instructions like this

**Comment by martyna-mindsdb** [comment]
@RANJITHROSAN17 
Please see my previous comment for the important steps of how to start solving an issue.

Before we can merge your PR, please sign our CLA by leaving a comment here that contains this line: I have read the CLA Document and I hereby sign the CLA

**Comment by martyna-mindsdb** [comment]
@RANJITHROSAN17 
This issue has been resolved. Please have a look at other open issues labeled as help-wanted.

**Pull request closed without merging**
