### PR TITLE
Upgrading CKAN handler

### PR DESCRIPTION
**Pull request by tino097**
This update comes from slack discussion about availability to execute SQL queries with the Datastore data.
Now we can do more complex querying because we will use the `datastore_search_sql` 

image

### CODE REVIEW

**Comment by mallipatil** [comment]
Thanks for working thru request. 

Observation (Issue #1) - Looks like when company name value is passed in small letters (without capital) - getting error message 
" Giving error "[ckan/data_gov_au]: Can only use .str accessor with string values!"  

**Working as expected**
SELECT * FROM data_gov_au.datastore WHERE  resource_id = '5c3914e6-413e-4a2c-b890-bf8efe3eabf2' AND `Company Name` = "PREDICTIVE RESEARCH PTY LTD";

** Not Working **
SELECT * FROM data_gov_au.datastore WHERE  resource_id = '5c3914e6-413e-4a2c-b890-bf8efe3eabf2' AND `Company Name` = "predictive research pty ltd";

Error Snapshot 
image

**Comment by mallipatil** [comment]
**Observation No. 2-**

Scenario.  Count number of records in CKAN resource (SQL Command) is incorrect/truncated 
Query: SELECT COUNT(*) FROM data_gov_au.datastore WHERE resource_id = '5c3914e6-413e-4a2c-b890-bf8efe3eabf2';
Mindsdb:  response was 32000 (refer snapshot) however actual records in the resource is 4023859

image

**Direct API response** (copy & paste below command in browser)
 https://data.gov.au/data/api/3/action/datastore_search_sql?sql=SELECT COUNT(*) FROM "5c3914e6-413e-4a2c-b890-bf8efe3eabf2"
 Response is
{
   "help": "https://data.gov.au/data/api/3/action/help_show?name=datastore_search_sql",
   "success": true,
   "result": {
       "sql": "SELECT COUNT(*) FROM \"5c3914e6-413e-4a2c-b890-bf8efe3eabf2\"",
       "records": [
           {
               "count": 4023859
           }
       ],
       "fields": [
           {
               "id": "count",
               "type": "int8"
           }
       ]
   }
}
Excel-sheet manually loading & verifying the record count as **4023859**

**Comment by mallipatil** [comment]
**observation #3:

Scenario:  Try to fetch all records in CKAN resource

SELECT * FROM data_gov_au.datastore WHERE resource_id = '5c3914e6-413e-4a2c-b890-bf8efe3eabf2'   did not through any error (improvement), however it fetched the records up to 32000 (refer snapshot).
image

I do understand, there has to be limit and it's better to document it.

**Comment by tino097** [comment]
Thanks @mallipatil for your testing on this PR, i will check on the records issue later this week

**Comment by MinuraPunchihewa** [comment]
> Thanks @mallipatil for your testing on this PR, i will check on the records issue later this week
> 
> @ZoranPandovski before i dive in debugging, is there any limit for the number of rows that can be displayed on the UI ?

@tino097 No, there isn't such a limitation outside of performance concerns. The UI implements pagination, so the data will be displayed in pages.

**Comment by tino097** [comment]
@mallipatil 
I've added link to the docs about the limitation of 32000 records. - https://docs.ckan.org/en/2.11/maintaining/datastore.html#ckanext.datastore.logic.action.datastore_search_sql

**Comment by tino097** [comment]
@MinuraPunchihewa I think this is ready for review/merge. However it could be matter of change if/when more users will start working with it. Using `datastore_search_sql` will give to users more options but not all instances have enabled this action. 

Please feel free to ping me if there are questions/issues over this handler

**Comment by mallipatil** [comment]
Thank you @tino097 for updating limits.   Hope you have reviewed/addressed observation #2 which counts number of records in CKAN resource, so that we can handle 32000 record limitation programmatically. 

Scenario#2. Count number of records in CKAN resource (SQL Command) response is incorrect/truncated
Query: SELECT COUNT(*) FROM data_gov_au.datastore WHERE resource_id = '5c3914e6-413e-4a2c-b890-bf8efe3eabf2';
Mindsdb: response is 32000 (refer snapshot) however actual records in the resource is 4023859

**Comment by tino097** [comment]
Hey @mallipatil actually limit comes from CKAN insance https://docs.ckan.org/en/2.11/maintaining/datastore.html#ckanext.datastore.logic.action.datastore_search_sql

**Comment by mallipatil** [comment]
Look forward for this pull request to get merged..

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
