### PR TITLE
Setup pre-commit hooks. Fixes #3300

### LINKED ISSUE #3300: Add pre-commit hooks for development workflow
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

We should add Pre-commit hooks to clean up and standardize the code using black and flake8.

### Describe the solution you'd like.

_No response_

### Describe an alternate solution.

_No response_

### Anything else? (Additional Context)

_No response_

### PR DESCRIPTION
**Pull request by nehiljain**
Fixes #3300

## Please describe what changes you made, in as much detail as possible
  - Added flake8 config, pre-commit config
  - Added black, isort, flake8, and other checkers which will automatically scan and fix issued in code being committed/pushed to the repository. 
  - This will only run on files being changed on someone's local environment
  - Devs can by pass it with flag `--no-verify` in their commit. To enforce compliance we will have to run these same checks in a PR code integration pipeline.
  

## Open Questions
 - What are mindsdb repo norms? We will have to codify those in these configs
 - How do we want to deal with old files and code and configs breaking these norms? 

mindsdb

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by nehiljain** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ZoranPandovski** [comment]
recheckcla

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
