### PR TITLE
Setup GitHub actions

### PR DESCRIPTION
**Pull request by ZoranPandovski**
This PR adds GitHub actions for:

- [X]  Install MindsDB on Linux, Windows, macOS. Running tests on Linux only.

- [X]  Deploy to PyPi

- [ ]  Push installer to s3. Commented for now. 

- [x] Push to Docker

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
**CLA Assistant Lite** All Contributors have signed the CLA.

**Comment by ZoranPandovski** [comment]
**CLA Assistant Lite** All Contributors have signed the CLA.

**Comment by ZoranPandovski** [comment]
**CLA Assistant Lite** All Contributors have signed the CLA.

**Comment by ZoranPandovski** [comment]
**CLA Assistant Lite** All Contributors have signed the CLA.

**Comment by ZoranPandovski** [comment]
**CLA Assistant Lite** All Contributors have signed the CLA.

**Comment by ZoranPandovski** [comment]
**CLA Assistant Lite** All Contributors have signed the CLA.

**Comment by ZoranPandovski** [comment]
**CLA Assistant Lite** All Contributors have signed the CLA.

**Comment by ZoranPandovski** [comment]
**CLA Assistant Lite** All Contributors have signed the CLA.

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite** All Contributors have signed the CLA.

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite** All Contributors have signed the CLA.

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite** All Contributors have signed the CLA.

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite** All Contributors have signed the CLA.

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite** All Contributors have signed the CLA.

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite** All Contributors have signed the CLA.

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite** All Contributors have signed the CLA.

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite** All Contributors have signed the CLA.

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite** All Contributors have signed the CLA.

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite** All Contributors have signed the CLA.

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite** All Contributors have signed the CLA.

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite** All Contributors have signed the CLA.

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite** All Contributors have signed the CLA.

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite** All Contributors have signed the CLA.

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you all sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/> 
   - - -
   ***I have read the CLA Document and I hereby sign the CLA***
   - - - 
   **1** out of **2** committers have signed the CLA.<br/>:white_check_mark: @StpMax<br/>:x: @mindsdbadmin<br/><sub>You can retrigger this bot by commenting **recheckcla** in this Pull Request</sub>

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you all sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/> 
   - - -
   ***I have read the CLA Document and I hereby sign the CLA***
   - - - 
   **1** out of **2** committers have signed the CLA.<br/>:white_check_mark: @StpMax<br/>:x: @mindsdbadmin<br/><sub>You can retrigger this bot by commenting **recheckcla** in this Pull Request</sub>

**Review by StpMax — APPROVED** [review]

**Pull request merged**
