### PR TITLE
🧵🧵 Added Threads Table in Slack HAndler

### LINKED ISSUE #8641: 🧵🧵Add Threads table in Slack Handler
### Short description and motivation for the proposed feature

Add Support for Threads table in Slack Handler taking **`ts`** and **`channel`** as input and give threads corresponding to it

### Video or screenshots

_No response_

### Describe some possible solutions

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by parthiv11**
## Description

Please include a summary of the change and the issue it solves. 
- Added Threads Table
- Added _threads_ column in channel table

Fixes #8641 

## Type of change

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [x] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [x] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have appropriately commented on my code, especially in complex areas.
- [x] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

slack thread

### CODE REVIEW

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
Thanks @parthiv11. Please make sure you follow the PR template and you add all required informations

**Comment by parthiv11** [comment]
@ZoranPandovski is that correct?

**Comment by parthiv11** [comment]
@ZoranPandovski please check this out

**Comment by parthiv11** [comment]
@ZoranPandovski is there anything left in this PR

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
@parthiv11 The slack integration is not well covered with tests so we shouldn't do this refactor. Let's keep the initial implementation, add threads, then we can work on adding more tests and re-factor following the standard structure. This is important, since this is one of the most wildly used integration

**Comment by parthiv11** [comment]
> @parthiv11 The slack integration is not well covered with tests so we shouldn't do this refactor. Let's keep the initial implementation, add threads, then we can work on adding more tests and re-factor following the standard structure. This is important, since this is one of the most wildly used integration

you are asking for only adding **Threads Table**, and removing **threads** columns from **channels table**, right?

**Comment by parthiv11** [comment]
@ZoranPandovski can you please guide me here

**Comment by parthiv11** [comment]
@ZoranPandovski this PR is needed or not?

**Comment by ZoranPandovski** [comment]
@parthiv11 I think we should wait on this or even close since there are few ongoing changes in the Slack handler

**Comment by parthiv11** [comment]
Ok

**Pull request closed without merging**
