### PR TITLE
added the INSERT, UPDATE, and DELETE commands for the Payment Intents…

### LINKED ISSUE #7874: [Stripe] Implement INSERT, UPDATE, and DELETE for the Payment Intents table
MindsDB integrates with Stripe, so you can fetch data from Stripe and use it to make relevant predictions and forecasts with MindsDB.

## Resources

Familiarize yourself with the existing Stripe integration: https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/stripe_handler

## Steps to Follow

The task is to extend [this implementation](https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/stripe_handler) to include the INSERT, UPDATE, and DELETE commands for the Payment Intents table.

## :loudspeaker: Additional rewards :trophy:

Each integration extension brings 15+ points for SWAG and entry into the draw for a :point_down: :
-  :computer:  [Razer Blade 16 Laptop](https://www.razer.com/gaming-laptops/Razer-Blade-16/RZ09-0483SEJ3-R3U1)
- :shirt: :bear:  [MindsDB Swag](https://store.covver.io/mindsdb/collections/swag-collection)

:information_source: For more info check out https://mindsdb.com/hacktoberfest/ :point_left: 

**Please note that this issue is for first-time contributors to MindsDB**

### PR DESCRIPTION
**Pull request by Sekhar-Kumar-Dash**
## Description
This pull request adds the INSERT, UPDATE, and DELETE commands for the Payment Intents table in Stripe integration.

Fixes #7874 

## Type of change

(Please delete options that are not relevant)

- [ ] ⚡ New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by Sekhar-Kumar-Dash** [comment]
@martyna-mindsdb  can  you review this pull request

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@Sekhar-Kumar-Dash 
Please provide screenshots or a short video presenting the following commands run from the MindsDB editor:

- INSERT INTO payment_intent_table ...
- UPDATE payment_intent_table ...
- DELETE FROM payment_intent_table ...

**Comment by martyna-mindsdb** [comment]
@Sekhar-Kumar-Dash 
The implementation looks off - have you tested it?

**Comment by Sekhar-Kumar-Dash** [comment]
> @Sekhar-Kumar-Dash The implementation looks off - have you tested it?

doing i will update you

**Pull request closed without merging**
