### PR TITLE
Changed link in Exception

### PR DESCRIPTION
**Pull request by psmail147**
## Description

Replaced link in huggingface_handler.py on line 26 within the Exception. 

**Fixes** #6414 

## Type of change

- [ ] 📄 This change requires a documentation update

### What is the solution?

Deleted original link and replaced with specified link. 

Please let me know that I have made the correct change and thank you for creating this beginners opportunity. 

I have read the CLA Document and I hereby sign the CLA

Phil.

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@psmail147 
Please sign the CLA so we can merge your PR.

**Comment by psmail147** [comment]
> 

Apologies, I have replied to the issue with the signature and I have now updated the comment within the pull request with "I have read the CLA Document and I hereby sign the CLA" phrase. 

I hope that is correct. Again, my appolgies. 

Phil.

> ## Description
> Replaced link in huggingface_handler.py on line 26 within the Exception.
> 
> **Fixes** #6414
> 
> ## Type of change
> * [ ]  📄 This change requires a documentation update
> 
> ### What is the solution?
> Deleted original link and replaced with specified link.
> 
> Please let me know that I have made the correct change and thank you for creating this beginners opportunity.
> 
> I have read the CLA Document and I hereby sign the CLA
> 
> Phil.

I have read the CLA Document and I hereby sign the CLA

**Comment by psmail147** [comment]
> @psmail147 Please sign the CLA so we can merge your PR.

My apologies, I have signed the CLA by replying to the issue (which I think was wrong), I have edited my initial pull request with the signature line within the description of the pull request, and I have also replied to the pull request description with the signature. I hope one of those was correct. 

Apologies for the confusion. 

Phil.

**Comment by martyna-mindsdb** [comment]
@psmail147 
No worries. Please sign the CLA by leaving a comment here that contains only this line: I have read the CLA Document and I hereby sign the CLA

**Comment by psmail147** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
