### PR TITLE
update mysql href url

### PR DESCRIPTION
**Pull request by sudip-unb**
## Description
This is the pull request for issue #4821 which is the update of the MySQL integration URL link update in the readme file.
Please include a summary of the change and the issue it solves. 

**Fixes** #(issue)
4821
## Type of change

- [ ] 📄 This change requires a documentation update

### What is the solution?

update the URL in the README.md file.
<a href="https://docs.mindsdb.com/">Connect MySQL</a>

Update the href value to this link: https://docs.mindsdb.com/data-integrations/all-data-integrations#mysql

## Checklist:

- [ Y] My code follows the style guidelines(PEP 8) of MindsDB.
- [ NA] I have commented my code, particularly in hard-to-understand areas.
- [ Y] I have updated the documentation, or created issues to update them.
- [ NA] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ NA] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@sudip-unb 
Please sign the CLA here. Thanks.

**Comment by sudip-unb** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by martyna-mindsdb** [comment]
recheckcla

**Pull request merged**
