### PR TITLE
docs(helm readme): fix typo seperate -> separate

### PR DESCRIPTION
**Pull request by ryanrussell**
Fixes #

## Please describe what changes you made, in as much detail as possible
  - Helm Readme typo: seperate -> separate

mindsdb

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement]() before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   ***I have read the CLA Document and I hereby sign the CLA***
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by ZoranPandovski** [comment]
Thanks @ryanrussell can you please just sign the cla?

**Comment by ryanrussell** [comment]
I have read the CLA Document and I hereby sign the CLA

If this is not sufficient, please just reject and fix in your workflow :+1:

**Comment by ZoranPandovski** [comment]
Sorry, you will need to add just the `I have read the CLA Document and I hereby sign the CLA` without additional words on the same comment (not ideal but that is how the bot is working).

**Comment by ryanrussell** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
