### PR TITLE
added missing reqs to youtube handler

### PR DESCRIPTION
**Pull request by martyna-mindsdb**
## Description

added missing reqs to youtube handler

discussed here: https://mindsdbcommunity.slack.com/archives/C04EWFQEFEV/p1702899569784249

Fixes #issue_number

## Type of change

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Review by ZoranPandovski — APPROVED** [review]

**Comment by ZoranPandovski** [comment]
Is this required @martyna-mindsdb there is a check that fails for:

```
    None:None: DEP002 'google-auth-oauthlib' defined as a dependency but not used in the codebase
```

**Comment by martyna-mindsdb** [comment]
@ZoranPandovski 
I had to install this package to have the YouTube handler available in MindsDB. Also, another user had to do the same.

The error message in the handlers table says explicitly that this package is missing, so I guess it is required for YouTube:

image

**Review by MinuraPunchihewa — COMMENTED** [review]
Hey @ZoranPandovski,
Yes, I believe this is required. I think the reason that the CI check is failing is because the code that actually uses this package is [here](https://github.com/mindsdb/mindsdb/blob/staging/mindsdb/integrations/handlers/utilities/auth_utilities/google_oauth_utilities.py).
This is not ideal, but I think the way this can be solved is probably to do,
`import google_auth_oauthlib # noqa, required by GoogleOAuth2Manager`

**Comment by hamishfagg** [comment]
This has highlighted a blind spot with the requirements checks that it didn't check `mindsdb/integrations/handlers/utilities` with the core codebase.
So I've fixed the check, and fixed the errors caused by checking ALL of the code now :)

I've moved `google-auth-oauthlib` to the main requirements file, as it is imported in the core codebase. So checks should pass now

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
