### PR TITLE
Bug-fix-issue-#4784

### PR DESCRIPTION
**Pull request by daredevilteja**
## Description

Added the correct href link for mariadb integration

**Fixes** #4784

## Type of change

- [x] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] 📄 This change requires a documentation update

### What is the solution?
1. Go to the file /mindsdb/README.md.
2. Find the section titled ## Database Integrations. This section contains a table with integrations and their logos.
3. Find the below HTML tag:
```<a href="https://docs.mindsdb.com/">Connect MariaDB</a>```
4. Update the href value to this link: https://docs.mindsdb.com/data-integrations/all-data-integrations#mariadb

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation, or created issues to update them.
- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by daredevilteja** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by daredevilteja** [comment]
`I have read the CLA Document and I hereby sign the CLA`

**Comment by daredevilteja** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by martyna-mindsdb** [comment]
recheckcla

**Pull request merged**
