### PR TITLE
fix: semantic_search.mdx from file example

### PR DESCRIPTION
**Pull request by whygee-dev**
## Description
Engine is "rag_engine" not "rag"

### CODE REVIEW

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
@whygee-dev  `rag` is the correct name, check the [code](https://github.com/mindsdb/mindsdb/blob/main/mindsdb/integrations/handlers/rag_handler/rag_handler.py#L29). Did you got any errors for this?

**Comment by whygee-dev** [comment]
@ZoranPandovski I did get an error until I've changed to rag_engine. It also does not make sense that in some sections of this same documentation page engine = "rag_engine" is used and in others engine = "rag" is used

**Comment by ZoranPandovski** [comment]
I think most of the docs examples are mentioning `rag_engine` because that is the name assigned to the `rag` engine with:

```
CREATE ML_ENGINE rag_engine
FROM rag
USING
    openai_api_key = 'sk-xxx';
```

Does this make sense?

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb/blob/main/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by ZoranPandovski** [comment]
Oh, good point. You are right, please just sing the CLA so I can merge this

**Comment by whygee-dev** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
