### PR TITLE
updated langchain requirements

### PR DESCRIPTION
**Pull request by hui-jie-lim**
## Description

Please include a summary of the change and the issue it solves. 

**Fixes** #6726 

## Type of change

(Please delete options that are not relevant)

- [x] 🐛 Bug fix (non-breaking change which fixes an issue)

### What is the solution?

updated requirements.txt for langchain handler to include OpenAIHandler dependencies. 

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation, or created issues to update them.
- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Review by hui-jie-lim — COMMENTED** [review]
hi @paxcema , this is for [issue 6726](https://github.com/mindsdb/mindsdb/issues/6726)
I have scanned through all the handlers and seems like only langchain requirements update. Coudl you have a look at the edits and see if you can help approve this please? Thank you.

**Comment by hui-jie-lim** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by hui-jie-lim** [comment]
recheck

**Review by paxcema — APPROVED** [review]

**Comment by paxcema** [comment]
> I am not sure if I am doing this right btw. Cant seem to find any way to request for review

Yep, that's exactly how you'd do it @hui-jie-lim. Thanks for your contribution! Looks good.

**Pull request merged**
