### PR TITLE
[Docs] Update the Amazon DynamoDB link

### PR DESCRIPTION
**Pull request by kshitiz305**
Fixes : #5962

## Description

[Docs] Update the Amazon DynamoDB link in the README.md file

**Fixes** #5962 

## Type of change

(Please delete options that are not relevant)

- [x] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] 📄 This change requires a documentation update

### What is the solution?

(Describe at a high level how the feature was implemented)

## Checklist:
- [x] I have updated the documentation, or created issues to update them.

### CODE REVIEW

**Comment by kshitiz305** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by kshitiz305** [comment]
@mindsdbadmin @martyna-mindsdb I have not been added to the contributors list. May I know the reason fore that.

**Comment by martyna-mindsdb** [comment]
@kshitiz305 
The contributors' list is generated automatically by GitHub. So the GitHub account/login from which you made contributions to MindsDB should be present there.

**Pull request merged**
