### PR TITLE
Add the questdb.mdx file to docs navigation

### PR DESCRIPTION
**Pull request by Navinkhandeparkar**
## Description

Please include a summary of the change and the issue it solves. 

**Fixes** #(issue)
Add the questdb.mdx file to docs navigation #5314

## Type of change

(Please delete options that are not relevant)

- [✓] ⚡ New feature (non-breaking change which adds functionality)

### What is the solution?

(Describe at a high level how the feature was implemented)
I have added the questdb to docs/mint.json

## Checklist:

- [ ✓] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ✓] I have commented my code, particularly in hard-to-understand areas.
- [ ✓] I have updated the documentation, or created issues to update them.
- [ ✓] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ✓] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by Navinkhandeparkar** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   **navin** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by Navinkhandeparkar** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Navinkhandeparkar** [comment]
recheck

**Pull request merged**
