### PR TITLE
#7509: [MediaWiki] Implement Insert Query Utilities

### LINKED ISSUE #7509: [MediaWiki] Implement INSERT for the Pages table
MindsDB integrates with MediaWiki, so you can fetch data from MediaWiki and use it to train models or make predictions with MindsDB.

## Resources

Familiarize yourself with the existing MediaWiki integration: https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/mediawiki_handler

## Steps to Follow

Currently, the MediaWiki integration with MindsDB implements SELECT from the Pages table.

The task is to extend [this implementation](https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/mediawiki_handler) to include the INSERT command to insert data to the Pages table.

## :loudspeaker: Additional rewards :trophy:

Each integration test brings 15+ points for SWAG and entry into the draw for a :point_down: :
-  :computer:  [Razer Blade 16 Laptop](https://www.razer.com/gaming-laptops/Razer-Blade-16/RZ09-0483SEJ3-R3U1)
- :shirt: :bear:  [MindsDB Swag](https://store.covver.io/mindsdb/collections/swag-collection)

:information_source: For more info check out https://mindsdb.com/hacktoberfest/ :point_left:

### PR DESCRIPTION
**Pull request by dzmdre**
## Description

Please include a summary of the change and the issue it solves. 

Fixes #7509

## Type of change

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [x] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [ ] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have appropriately commented on my code, especially in complex areas.
- [ ] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Comment by Sohlar** [comment]
Hey, I see exact comments and code copy pasted from my earlier commits to the UPDATE issue. I know the end code will be similar but I would appreciate it if my unmerged code wasn't in your PR when you decide to submit.

**Comment by dzmdre** [comment]
@Sohlar as you can see the pr is in the draft mode. It will be similar, I cannot use your code yet, because your pr is not merged.

**Comment by martyna-mindsdb** [comment]
@dzmdre 
Please provide screenshots or a short video presenting that INSERT works for MediaWiki.

**Comment by martyna-mindsdb** [comment]
@dzmdre
To complete this PR, please provide screenshots or a short video presenting that INSERT works for MediaWiki.

**Comment by ZoranPandovski** [comment]
@dzmdre Please check the comments so we can merge this

**Comment by ZoranPandovski** [comment]
@dzmdre Any update on this?

**Pull request closed without merging**
