### PR TITLE
Updated the Redshift Implementation to Extend Postgres

### PR DESCRIPTION
**Pull request by MinuraPunchihewa**
## Description

This PR updates the implementation of the Redshift handler to extend the Postgres handler.

[Redshift is based on PostgresSQL](https://docs.aws.amazon.com/redshift/latest/dg/c_redshift-and-postgres-sql.html), therefore, it becomes possible to implement it this way. We are able to avoid the SQLAlchemy dependency issue with this approach as well.

Fixes https://github.com/mindsdb/mindsdb/issues/9321

## Type of change

- [X] 🐛 Bug fix (non-breaking change which fixes an issue)

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [X] I have attached a brief loom video or screenshots showcasing the new functionality or change.

image

## Checklist:

- [X] My code follows the style guidelines(PEP 8) of MindsDB.
- [X] I have appropriately commented on my code, especially in complex areas.
- [ ] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
Let's chat on slack for this

**Comment by MinuraPunchihewa** [comment]
@ZoranPandovski This also implements the other steps need to make the integration enterprise-ready.

**Review by ZoranPandovski — APPROVED** [review]

**Comment by ZoranPandovski** [comment]
@MinuraPunchihewa Please check https://github.com/mindsdb/mindsdb/actions/runs/9497616108/job/26174729552?pr=9335#step:6:194

**Comment by MinuraPunchihewa** [comment]
@ZoranPandovski The failing test is now fixed.

**Pull request merged**
