### PR TITLE
Stripe product table operations implementation INSERT, UPDATE, DELETE

### PR DESCRIPTION
**Pull request by shivam-dhaka**
## Description

Please include a summary of the change and the issue it solves. 

Fixes [#7778](https://github.com/mindsdb/mindsdb/issues/7778)

## Type of change

- [x] ⚡ New feature (non-breaking change which adds functionality)
- [x] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - []   Test Location: Specify the URL or path for testing.
 - [x]   Verification Steps: Create database with stripe api_key and insert values to columns(id, name, active, description, metadata). Column name is mandatory
## Additional Media:

- [x] I have attached a brief loom video or screenshots showcasing the new functionality or change.
insert
update
updated_select
delete
delete_exception

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have appropriately commented on my code, especially in complex areas.
- [x] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
@shivam-dhaka 
Please add sample commands to the README file.

**Comment by shivam-dhaka** [comment]
@martyna-mindsdb Done!

**Comment by martyna-mindsdb** [comment]
@shivam-dhaka 
Let's add sample INSERT, UPDATE, and DELETE commands (from your screenshots), as these are the ones you implemented.

**Comment by shivam-dhaka** [comment]
@martyna-mindsdb Done!

**Review by martyna-mindsdb — APPROVED** [review]

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
