### PR TITLE
close learn process gracefully

### LINKED ISSUE #1058: Close learn process gracefuly
`close_api_gracefully` only closes the API, but not any ongoing learn processes, which are left orphaned and consuming loads of memory.

### PR DESCRIPTION
**Pull request by ilia-tsyplenkov**
Fixes #1058 

  ## What:
 - ```close_api_gracefully only closes the API, but not any ongoing learn processes, which are left orphaned and consuming loads of memory.```
  ## How:
 - Each learning process when start working stories its own pid as empty file in `storage_dir/in_learning` directory and will delete it at the end if no interruption happens
 - `close_api_gracefully` read list of files in `storage_dir/in_learning` and sends SIGTERM to each of this process.

mindsdb

### CODE REVIEW

**Comment by StpMax** [comment]
What a reason was to choose this solution?
May be just go recursively through processes children at the end of main process?
```
import psutil
p = psutil.Process()
c = p.children(recursive=True)
for p in c:
    p.kill()
```

**Comment by ilia-tsyplenkov** [comment]
> @ilia-tsyplenkov What a reason was to choose this solution?
> May be just go recursively through processes children at the end of main process?
> 
> ```
> import psutil
> p = psutil.Process()
> c = p.children(recursive=True)
> for p in c:
>     p.kill()
> ```
Yes, this is first that I decided to implement. But since psutil is not fully cross-platform package, I decided to implement approach which is definitely will work on linux/mac/windows

**Comment by StpMax** [comment]
I checked that on macos - looks like it work. Can you try on windows?
I think getting process's children should be safe, so OS should not block that.

**Comment by ilia-tsyplenkov** [comment]
> I checked that on macos - looks like it work. Can you try on windows?
> I think getting process's children should be safe, so OS should not block that.

Sorry but I don't have Windows

**Review by StpMax — APPROVED** [review]

**Pull request merged**
