### PR TITLE
Test the Question Answering tutorial #6194

### PR DESCRIPTION
**Pull request by simonkowalski1**
I included all the outputs from the tutorial but wasn't sure if I should've added the output for this query: 
```sql
SELECT * FROM models
WHERE name = 'question_answering_model';
```

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by martyna-mindsdb** [comment]
@simonkowalski1 
Please sign the CLA by leaving a comment here that contains the below line:

I have read the CLA Document and I hereby sign the CLA

**Comment by simonkowalski1** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by martyna-mindsdb** [comment]
recheckcla

**Pull request merged**
