### PR TITLE
 [Docs] Update instructions for QuestDB #6705 

### PR DESCRIPTION
**Pull request by rajenderthota**
## Description

 [Docs] Update instructions for QuestDB #6705. Updating documentation

**Fixes** #(issue) 
#6705 
## Type of change

(Please delete options that are not relevant)

- [X ] ⚡ New feature (non-breaking change which adds functionality)
- [ X] 📄 This change requires a documentation update

### What is the solution?

Updating documentation
(Describe at a high level how the feature was implemented)

## Checklist:

- [X ] My code follows the style guidelines(PEP 8) of MindsDB.
- [X ] I have commented my code, particularly in hard-to-understand areas.
- [ X] I have updated the documentation, or created issues to update them.
- [X ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ X] I have shared a short loom video or screenshots demonstrating any new functionality.

I have read the CLA Document and I hereby sign the CLA

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
@rajenderthota 
Please undo changes to the cla.json file.
Keep only changes as in the issue description.

**Comment by rajenderthota** [comment]
@martyna-mindsdb - sure.. I will revert that file to previous version

**Comment by rajenderthota** [comment]
@martyna-mindsdb - are we good with this pull request ? please let me know if anything needs to be done for the same.

**Comment by rajenderthota** [comment]
@ryw / @tony / @martyna-mindsdb - can you please merge it or let me know if anything needs to be addressed for the same ?

**Comment by rajenderthota** [comment]
@martyna-mindsdb  do I need to do anything for CLA Document for the same ?

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@rajenderthota 
Please sign the CLA by leaving a comment here: I have read the CLA Document and I hereby sign the CLA

**Comment by rajenderthota** [comment]
@martyna-mindsdb  I have read the CLA Document and I hereby sign the CLA

**Comment by rajenderthota** [comment]
recheck

**Comment by rajenderthota** [comment]
@ryw / @tony /@martyna-mindsdb please let me know if anything needs to be done for the same (i.e. CLA Document) ?

**Comment by martyna-mindsdb** [comment]
recheckcla

**Pull request merged**
