### PR TITLE
issue  [Docs] Update instructions for QuestDB #6705 fix

### PR DESCRIPTION
**Pull request by rajenderthota**
## Description

 [Docs] Update instructions for QuestDB #6705

**Fixes** #(issue)
#6705
## Type of change

(Please delete options that are not relevant)

- [X ] 📄 This change requires a documentation update

### What is the solution?

Updating documentation for the issue #6705 

(Describe at a high level how the feature was implemented)

## Checklist:

- [X] My code follows the style guidelines(PEP 8) of MindsDB.
- [X ] I have commented my code, particularly in hard-to-understand areas.
- [X ] I have updated the documentation, or created issues to update them.
- [X ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ X] I have shared a short loom video or screenshots demonstrating any new functionality.

CLA Assistant Lite bot:
Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.

I have read the CLA Document and I hereby sign the CLA

 recheck

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@rajenderthota 
Please sign our CLA as mentioned above.

Also, read carefully the issue instructions. The tip box should be placed at line 22 (and not at the end of the file).
Please correct it and push changes to this PR.

**Comment by rajenderthota** [comment]
recheck

**Comment by rajenderthota** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by rajenderthota** [comment]
@martyna-mindsdb  I got it. I will update it. thank you

**Comment by rajenderthota** [comment]
I have read the CLA Document and I hereby sign the CLA

Updated actual documentation as per review comment. please recheck

**Comment by rajenderthota** [comment]
@martyna-mindsdb  Please let me know if anything else needs to be done for the same ?

**Comment by rajenderthota** [comment]
recheck

**Pull request closed without merging**
