### PR TITLE
Added Google-BigQuery.mdx to docs navigation

### PR DESCRIPTION
**Pull request by IAmP33l**
## Description

Please include a summary of the change and the issue it solves. 

Added "data-integrations/Google-BigQuery" to line #329

## Type of change

- [x] ⚡ New feature (non-breaking change which adds functionality)

### What is the solution?

Simply added the line to the docs file as instructed.

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation, or created issues to update them.
- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by IAmP33l** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by IAmP33l** [comment]
recheck

**Comment by martyna-mindsdb** [comment]
@IAmP33l 
Before creating a PR, please leave a comment on the issue (https://github.com/mindsdb/mindsdb/issues/5179) and wait until we assign you this issue.

**Pull request merged**
