### PR TITLE
Corrected a Typo

### PR DESCRIPTION
**Pull request by Sumanth077**
Fixes #

## Please describe what changes you made, in as much detail as possible
  - Fixed the Typo 'traning' to 'training'

mindsdb

### CODE REVIEW

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
Thanks can you please just remove the .DS files since they are vs code files

**Comment by Sumanth077** [comment]
Sure and I will make a PR again.
Thankyou

**Comment by Sumanth077** [comment]
Hi @ZoranPandovski I am getting conflict issue can you help to resolve this.
Thankyou

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement]() before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   ***I have read the CLA Document and I hereby sign the CLA***
   - - -
   **sumanth papareddy** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by paxcema** [comment]
Hi, the merge conflict probably happened because you force-pushed. I recommend correcting the typo in a new PR (with no .DS_Store files), it's probably faster 👍

**Comment by Sumanth077** [comment]
Sure will do it

**Comment by paxcema** [comment]
Okay cool, I will close this one then.

**Pull request closed without merging**
