### PR TITLE
Update predictor link

### PR DESCRIPTION
**Pull request by puhung**
## Description

Please include a summary of the change and the issue it solves. 

Update link in docs\sql\api\manage-models-versions.mdx 
**Fixes** #6360 

## Type of change
Documentation

### What is the solution?
(Describe at a high level how the feature was implemented)
Replace /sql/create/predictor with /sql/create/model .

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@puhung 
Please sign our CLA so we can merge your PR. You can do that by leaving a comment here: I have read the CLA Document and I hereby sign the CLA

**Comment by puhung** [comment]
@martyna-mindsdb 
 I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
