### PR TITLE
Delete depreciated SageMaker diagram from old docs

### LINKED ISSUE #3060: [Docs] Remove Sage diagram from old docs
**Describe the bug**
The SageMaker diagram is from old docs so it should be removed from current documentation.

**Fix**
1. Remove https://github.com/mindsdb/mindsdb/blob/staging/docs/mindsdb-docs/docs/assets/mdb-sage-flow.png

### PR DESCRIPTION
**Pull request by bilal-aamer**
Fixes #3060 

## Please describe what changes you made, in as much detail as possible
  -Successfully dealt with Issue [#3060](https://github.com/mindsdb/mindsdb/issues/3060).
  - Ready to close the relevent issue

mindsdb

### CODE REVIEW

**Comment by bilal-aamer** [comment]
Guys I am confused to why some checks are failing.

It is most probably because of the signing of the CLA pls tell me how to sign the CLA 
Thanks

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by bilal-aamer** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
Please don't push directly to the cla.json file. That should be automatically done

**Comment by bilal-aamer** [comment]
Noted :)

**Pull request closed without merging**
