### PR TITLE
Huggingface - finetune

### PR DESCRIPTION
**Pull request by paxcema**
## Description

~Note: needs #6836 to be merged first.~

Enables finetuning for HuggingFace models. Not all models are supported yet, but the most common are.

Updated use cases doc [[here](https://docs.google.com/document/d/1Xtatd49rmJm6GYuc8c7I0AA4fSf2FxVhcKENFDxytgE/edit?usp=sharing)].

Task support list:
- [x] Text classification
- [x] Zero shot text classification
- [x] Translation
- [x] Summarization

Example usage:

```sql
CREATE MODEL mindsdb.finetune_model
PREDICT PRED
USING
  engine = 'huggingface',
  task = 'text-classification',
  model_name = 'mrm8488/bert-tiny-finetuned-sms-spam-detection',
  input_column = 'text_spammy',
  labels = ['0', '1', '2', '3', '4'];


SELECT * FROM mindsdb.models_versions WHERE name = 'finetune_model';

SELECT text_spammy AS text FROM example_db.demo_data.hf_test;

SELECT h.*, t.text_spammy AS text
FROM example_db.demo_data.hf_test AS t
JOIN mindsdb.finetune_model AS h;

FINETUNE mindsdb.finetune_model 
FROM files (
    SELECT label as PRED, text as text_spammy FROM hf_finetune_sample WHERE PRED <= 1
)
USING
tokenizer_from = 'bert-base-cased';

SELECT h.*, t.text_spammy AS text
FROM example_db.demo_data.hf_test AS t
JOIN mindsdb.finetune_model.2 AS h; -- outputs finetuned predictions
```

## Type of change

(Please delete options that are not relevant)

- [x] ⚡ New feature (non-breaking change which adds functionality)
- [x] 📄 This change requires a documentation update

### What is the solution?
Added an `update()` method to the HF handler. Internal dispatch takes care of preprocessing data and setting everything up to produce the right trainer for any given task type.

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation, or created issues to update them.
- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by dusvyat** [comment]
@paxcema - Should we perhaps merge where we are up to so far with some caveats?

**Comment by paxcema** [comment]
Yep, so ideally tests would run, but that is perhaps a different issue. I do see that we're using `df` in tests but selecting some columns that are not there, so I'll fix that as well as an import error that is breaking the handler locally for me. Once that is done though, I am for merging as-is, doesn't make sense to block the entire thing due to e.g. not supporting `fill-mask` finetuning.

**Comment by paxcema** [comment]
Status update: translation is failing due to some internal error (which must've arisen during refactor process), and I'm blocked on trying zero-shot due to an unrelated issue with the file handler, so we can't/shouldn't merge just yet. @dusvyat for any LLM-related progress please fork off of this branch and set any PRs from that fork to merge into this one for the time being 🙏 .

**Comment by paxcema** [comment]
Ok, done. Merging now!

**Pull request merged**
