### PR TITLE
update airtable integration link

### PR DESCRIPTION
**Pull request by jeramiahgcoffey**
## Description

Updated README link to airtable integration

**Fixes** #4907 
## Type of change

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)

### What is the solution?

Replaced the `href` attribute on the appropriate `<a>` tag with https://docs.mindsdb.com/data-integrations/all-data-integrations#airtable

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation, or created issues to update them.
- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by jeramiahgcoffey** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by jeramiahgcoffey** [comment]
recheck

**Review by ZoranPandovski — APPROVED** [review]

**Comment by ZoranPandovski** [comment]
recheckcla

**Pull request merged**
