### PR TITLE
[Docs] Add community tutorial link to Mongo API regression page (#4564)

### PR DESCRIPTION
**Pull request by aamirxshaikh**
## Description

This PR adds a community tutorial link to the Mongo API regression page.

**Fixes** #(issue) #4564

## Type of change

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📄 This change requires a documentation update

### What is the solution?

To implement this feature, I added the community tutorial link to the appropriate location in the Mongo API regression page (regression.mdx).

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation, or created issues to update them.
- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] I have shared a short loom video or screenshots demonstrating any new functionality.

I have read the CLA Document and I hereby sign the CLA.

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@aamirxshaikh
Before we can merge your PR, could you please sign the CLA?
Thanks.

**Comment by ZoranPandovski** [comment]
Please check the comment from the bot above. Just copy the `I have read the CLA Document and I hereby sign the CLA`

**Comment by martyna-mindsdb** [comment]
@aamirxshaikh
Exactly as Zoran mentioned. Just comment with `I have read the CLA Document and I hereby sign the CLA`

**Comment by aamirxshaikh** [comment]
done @martyna-mindsdb

**Comment by martyna-mindsdb** [comment]
@aamirxshaikh
I don't see where you left a comment. Could you please leave a comment here?

Just write `I have read the CLA Document and I hereby sign the CLA` and comment.

**Comment by aamirxshaikh** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by martyna-mindsdb** [comment]
@aamirxshaikh
Thanks for contributing to MindsDB!
Now that you completed your first issue, please have a look at the issues labeled as https://github.com/mindsdb/mindsdb/labels/good%20first%20issue or https://github.com/mindsdb/mindsdb/labels/help%20wanted.

**Pull request merged**
