### PR TITLE
doc page to contain the community tutorial links is created 

### PR DESCRIPTION
**Pull request by shakeel-3**
## Description

doc page to contain the community tutorial links is created and mint,json file is updated

**Fixes** #(issue)

## Type of change

(Please delete options that are not relevant)

- [ ] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📄 This change requires a documentation update

### What is the solution?
step 1- New Markdown file inside the /docs/sql/tutorials directory is created with name  classification-community.mdx .
step 2- In newly Created Markdown file /docs/sql/tutorials/classification-community.mdx the given content is added .
step-3-  In the file mint.json under classification group and under Tutorials group "sql/tutorials/classification-community" is added

## Checklist:

- [*] My code follows the style guidelines(PEP 8) of MindsDB.
- [*] I have commented my code, particularly in hard-to-understand areas.
- [*] I have updated the documentation, or created issues to update them.
- [*] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [*] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by shakeel-3** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by shakeel-3** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by shakeel-3** [comment]
recheck

**Comment by martyna-mindsdb** [comment]
@shakeel-3 
Please make sure you are assigned to the issue before solving it. Also, please link the issue by its number in the PR description.

As this issue has been already solved, please have a look at other `first-timers-only` issues. Thanks.

**Pull request closed without merging**
