### PR TITLE
[Docs] Update a link to the Apache Druid integration #5000

### PR DESCRIPTION
**Pull request by rzz0**
## Description

Modified the `/mindsdb/README.md` file in the HTML tag to add the href: `https://docs.mindsdb.com/data-integrations/all-data-integrations#druid`

**Fixes** #(issue)

## Type of change

(Please delete options that are not relevant)

- [*] 📄 This change requires a documentation update

### What is the solution?

Go to the file /mindsdb/README.md.

Find the section titled ## Database Integrations. This section contains a table with integrations and their logos.

Find the below HTML tag:
`<a href="https://docs.mindsdb.com/">Apache Druid Badge</a>`

Update the href value to this link: `https://docs.mindsdb.com/data-integrations/all-data-integrations#druid`

## Checklist:

- [ * ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ * ] I have commented my code, particularly in hard-to-understand areas.
- [ * ] I have updated the documentation, or created issues to update them.
- [ * ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ * ] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@rzz0 
Please sign our CLA before we can merge your PR.

**Comment by rzz0** [comment]
I have read the CLA Document and I hereby sign the CLA

issue number #5000

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
Please just copy the `I have read the CLA Document and I hereby sign the CLA` only in the comment :)

**Comment by rzz0** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
