### PR TITLE
update the ckan link

### PR DESCRIPTION
**Pull request by Omokiti**
## Description

Please include a summary of the change and the issue it solves. 

**Fixes** #(issue)
wrong link for the Ckan with[ issue Number 4945](https://github.com/mindsdb/mindsdb/issues/4945)
## Type of change
Updated the link for Ckan to the right one
(Please delete options that are not relevant)

- [ ] 📢 Breaking change (fix or feature that would cause existing functionality to not work as expected)

### What is the solution?
Put in the right link
(Describe at a high level how the feature was implemented)

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation, or created issues to update them.
- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by Omokiti** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@Omokiti 
Please link the issue number in the PR description.

**Comment by Omokiti** [comment]
@martyna-mindsdb I have linked the issue number

**Comment by ZoranPandovski** [comment]
recheckcla

**Pull request merged**
