### PR TITLE
Added endpoint for mindsdb version

### LINKED ISSUE #811: Add endpoint for mindsdb version
Add HTTP route to get a version of mindsdb: /util/version/
That should return as mindsb version in JSON view:
```
{
  "mindsdb": "2.11.2"
}
```
The new endpoint needs to be added in [Utils](https://github.com/mindsdb/mindsdb/blob/staging/mindsdb/api/http/namespaces/util.py).

### PR DESCRIPTION
**Pull request by yash2189**
Fixes #811

## Please describe what changes you made, in as much detail as possible
  - Added endpoint for mindsdb version in [Utils](https://github.com/yash2189/mindsdb/blob/add-endpoint/mindsdb/api/http/namespaces/util.py)

mindsdb

### CODE REVIEW

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
Please change the name of the class to Version, and remove the hardcoded version of mindsdb. You can read the version from __about__ or if there is a better option to get the version do that.

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/> 
   - - -
   ***I have read the CLA Document and I hereby sign the CLA***
   - - - 
   <sub>You can retrigger this bot by commenting **recheckcla** in this Pull Request</sub>

**Comment by yash2189** [comment]
@ZoranPandovski can you please review my changes?

**Comment by ZoranPandovski** [comment]
@yash2189 Please just sign the CLA, as the above comment from admin

**Comment by yash2189** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by yash2189** [comment]
> @yash2189 Please just sign the CLA, as the above comment from admin

Done

**Comment by yash2189** [comment]
@ZoranPandovski Are the changes done by me correct?

**Comment by StpMax** [comment]
@yash2189 Thank you!
Everything is as it should be

**Review by StpMax — APPROVED** [review]

**Pull request merged**
