### PR TITLE
corrected display msg for installing packages

### LINKED ISSUE #7570: [Bug]: No package named mindsdb[langchain]
### Short description of current behavior

I tried to create langchain ml engine

```
CREATE ML_ENGINE langchain FROM langchain;
```

but got an error as follows.

Screenshot 2023-10-05 at 7 27 49 PM

When I tried to run the command, the package was not found.

```pip install mindsdb[langchain]```

### Expected behavior

Right command with correct package name to run has to be displayed.

### PR DESCRIPTION
**Pull request by Better-Boy**
## Description

Corrected msg for installing python packages via pip.

Fixes #7570 

## Type of change

(Please delete options that are not relevant)

- [x] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [ ] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have appropriately commented on my code, especially in complex areas.
- [ ] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Comment by StpMax** [comment]
`pip install telemetry` does not mean that need to install `telemetry` module. It mean that need to install [requirements for telemetry](https://github.com/mindsdb/mindsdb/blob/staging/requirements/requirements-telemetry.txt). Same for integrations: `pip install mindsdb[langchain]` mean that need to install requirements for [langchain handler](https://github.com/mindsdb/mindsdb/blob/staging/mindsdb/integrations/handlers/langchain_handler/requirements.txt), not only `langchain` module. Therefore i gonna close the PR.

**Comment by martyna-mindsdb** [comment]
@StpMax 
The message conveyed by `pip install mindsdb[package_name]` should be as follows:
```
Go to the package_name handler folder at /mindsdb/integrations/handlers/package_name_handler/ and execute this command "pip install -r requirements.txt"
```

**Comment by Better-Boy** [comment]
I agree with @martyna-mindsdb . Some handlers require more than one dependency to be installed. Hence, it's better to point to the right requirements.txt file.

**Comment by martyna-mindsdb** [comment]
Thanks @StpMax 

@Better-Boy 
This command should work for you `pip install mindsdb[package_name]` - e.g. `pip install mindsdb[cohere]` worked fine for me.

**Pull request closed without merging**
