### PR TITLE
Added the Tip in the Implementation chapter

### PR DESCRIPTION
**Pull request by Rythm18**
## Description

Added the Installation Tip in the Implementation chapter of the doc.

**Fixes** #6692 

## Type of change

(Please delete options that are not relevant)

- [x] 📄 This change requires a documentation update

### What is the solution?

Just needed to add the Tip in the installation past of doc.

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation, or created issues to update them.
- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by Rythm18** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Rythm18** [comment]
recheck

**Comment by Rythm18** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Rythm18** [comment]
recheck

**Comment by martyna-mindsdb** [comment]
@Rythm18 
You may need to [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user) - as mentioned in the instructions from the bot.

After that, you can sign our CLA.

**Comment by Rythm18** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Rythm18** [comment]
recheck

**Comment by Rythm18** [comment]
> @Rythm18 You may need to [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user) - as mentioned in the instructions from the bot.
> 
> After that, you can sign our CLA.

I actually did what the bot instructed that is to add my email after that I commented recheck but nothing happend. Shall i create a new PR? @martyna-mindsdb

**Comment by Rythm18** [comment]
recheck

**Comment by Rythm18** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Rythm18** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Rythm18** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request closed without merging**
