### PR TITLE
added examples to adjust and openai docs

### PR DESCRIPTION
**Pull request by martyna-mindsdb**
## Description

Please include a summary of the change and the issue it solves. 

**Fixes** [#89 from mindsdb_private](https://github.com/mindsdb/mindsdb_private/issues/89)

## Type of change

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] 📄 Documentation update

### What is the solution?

- added examples to adjust and openai docs
- adjusting an openai model gives an error - in progress

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation.
- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
@martyna-mindsdb Should we close this PR?

**Comment by martyna-mindsdb** [comment]
@ZoranPandovski 
I've been waiting for [this bug](https://github.com/mindsdb/mindsdb/issues/4734) to be fixed, so I can complete this PR.

I see there was some progress made, so I'll look into it this week.

**Comment by ZoranPandovski** [comment]
Yes, that should be solved

**Comment by martyna-mindsdb** [comment]
As this branch was created about 4 months ago, it has a lot of conflicts.
I'm going to close this PR and open a new one to implement fine-tuning of OpenAI models.

**Pull request closed without merging**
