### PR TITLE
Skip the CI when docs are changed

### PR DESCRIPTION
**Pull request by ritwik12**
This should solve #343

### CODE REVIEW

**Comment by George3d6** [comment]
Nice :)

Though I think what we really need is:

```
before_deploy:
  - if [[ "$DEPLOYMENT_ENV" = "true" && "$TRAVIS_BRANCH" = "master" ]]; then cd docs/website/website; fi
  - if [[ "$DEPLOYMENT_ENV" = "true" && "$TRAVIS_BRANCH" = "master" ]]; then npm install; fi
  - if [[ "$DEPLOYMENT_ENV" = "true" && "$TRAVIS_BRANCH" = "master" ]]; then npm run build; fi
  - if [[ "$DEPLOYMENT_ENV" = "true" && "$TRAVIS_BRANCH" = "master" ]]; then cd ../../..; fi
  - |
    if ! git diff --name-only $TRAVIS_COMMIT_RANGE | grep -qvE '(.md)|^(LICENSE)|^(travis.yml)'
    then
      echo "Deploy skipped since only Docs were changed."
      exit
    fi
```

Since we only want to skip the deploy, not running tests entirely.

(Note, the `before_deploy` section already exist, I just added a slightly modified version of your code to it, modified to inclue changes in the `travis.yml` file itself).

Does this approach seem correct to you @ritwik12  ?

**Comment by ritwik12** [comment]
Yes I did that only previously, but this means Travis will run but just don't deploy. if this is the intention. Let me do it

**Comment by ritwik12** [comment]
@George3d6 It should be good now :)

**Comment by George3d6** [comment]
@ritwik12  can you also add `travis.yml` to that list ? Since we also want skip tests if only that is update.d (I'd to it myself but I don't think I can commit on your branch)

**Comment by ritwik12** [comment]
@George3d6 Fine now? :)

**Comment by George3d6** [comment]
Shouldn't that be `travis.yml` instead of `.travis.yml` ?

**Comment by George3d6** [comment]
ah no, nevermind, my bad.

**Comment by George3d6** [comment]
Thanks for all the help, will see if it works and make the appropriate changes if it doesn't :)

This will probably save us a lot of pain down the line since we can now insta-merge doc related PRs without scaring users by having a "failing" button for our travis tests.

**Comment by ritwik12** [comment]
@George3d6 That's great :) Please tag me also if you make any changes later in this if it didn't work. Would like to see if it worked well

**Comment by George3d6** [comment]
@ritwik12 seems to work just fine on master

**Comment by ritwik12** [comment]
@ritwik12 That's great :) Thanks

**Pull request merged**
