### PR TITLE
Remove duplicate code

### PR DESCRIPTION
**Pull request by ajratnam**
## Description

This commit aims to **optimize** the code by removing **redundant code** in the `Hacker News Handler`

## Type of change

- [x] ⚙️ Code Optimization

## Verification Process

To ensure the changes are working as expected:

 - [x]   Verification Steps: Verified output of all hacker rank endpoints in MindsDB

## Additional Media:

image

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have appropriately commented on my code, especially in complex areas.
- [x] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by ajratnam** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by MinuraPunchihewa — APPROVED** [review]
This looks good to me. There has indeed been quite a bit of duplicate code in the handler.

**Pull request merged**
