### PR TITLE
Updated the MYSQL link in the README.md file

### PR DESCRIPTION
**Pull request by jpw3667**
## Description

The README.md file had an incorrect link, so I fixed it.

**Fixes** #(5848)

## Type of change

- [x] 🐛 Bug fix (non-breaking change which fixes an issue)

### What is the solution?

I replaced the old link in the <href> section of the readme file.

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have updated the documentation, or created issues to update them.

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
Issue: https://github.com/mindsdb/mindsdb/issues/5848

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@jpw3667 
Please sign our CLA by leaving a comment here: I have read the CLA Document and I hereby sign the CLA

**Comment by martyna-mindsdb** [comment]
@jpw3667 
Please let us know if you want to have your PR merged. If so, please sign the CLA as requested above.

**Comment by jpw3667** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by martyna-mindsdb** [comment]
recheck

**Comment by martyna-mindsdb** [comment]
@jpw3667 
Are you using the same GitHub email address for both your local and the commit here?
I'm asking so because the CLA bot has not detected the `jpw3667` username, but it has detected the `JWeinberg2` username.

@ZoranPandovski ^

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
Yes, it was pushed from a different user https://github.com/mindsdb/mindsdb/compare/staging...jpw3667:mindsdb:staging. You can include that user too, to your GitHub account

**Comment by martyna-mindsdb** [comment]
@jpw3667 
Could you please include this user (jpw3667) in your GitHub account? The bot detected only the user JWeinberg2.

**Comment by JWeinberg2** [comment]
Ok so it looks like my computer used a different email to commit from my computer, sorry I'm late but how should I fix this?

**Comment by martyna-mindsdb** [comment]
@JWeinberg2 
You used the username `jpw3667` while creating a PR, so please add this username to your GitHub account.
Here is a helpful link: https://docs.github.com/en/get-started/getting-started-with-git/setting-your-username-in-git

**Comment by jpw3667** [comment]
Alright I did that, should I sign the CLA with the other account or is there a better option?

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by martyna-mindsdb** [comment]
@jpw3667 @JWeinberg2 
Yes, please. Try to sign the CLA with the JWeinberg2 account.

**Comment by JWeinberg2** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by JWeinberg2** [comment]
Is there anything else I need to do?

**Comment by martyna-mindsdb** [comment]
All is fine now. Thanks!

**Pull request merged**
