### PR TITLE
Update Manual_QA.md after testing Google BigQuery Handler manually

### PR DESCRIPTION
**Pull request by fkamau1**
## Description

Please include a summary of the change and the issue it solves. 

Test Google BigQuery Handler Manually.

**Fixes** #(issue)
#6920 

## Type of change

(Please delete options that are not relevant)

- [x] Test functionality

### What is the solution?

(Describe at a high level how the feature was implemented)
Tested Google BigQuery Handler Manually

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation, or created issues to update them.
- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
@fkamau1 
If you provided your real tokens/keys in the Manual_QA file, please make sure to replace them with some placeholder values.

**Comment by fkamau1** [comment]
@martyna-mindsdb I have made the changes to include placeholder values instead of actual tokens in the commit [783e374](https://github.com/mindsdb/mindsdb/pull/6997/commits/783e374a6fa2d24323ad47e84e9abc3adf729a74)  thanks!

**Comment by martyna-mindsdb** [comment]
@fkamau1 
Please change the query in point `3. Testing SELECT FROM MODEL`. Here we expect you to [JOIN](https://docs.mindsdb.com/sql/api/join) the model table with the data table from the BigQuery connection and make batch predictions.

**Comment by fkamau1** [comment]
@martyna-mindsdb I have edited the SELECT statement to include results from joining those two tables.

**Pull request merged**
