### PR TITLE
Updated Link for CREATE DATABASE

### PR DESCRIPTION
**Pull request by Max-Miller03**
Fixes #

## Please describe what changes you made, in as much detail as possible
  -
I replaced the old link with a new one that works.

mindsdb

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement]() before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   ***I have read the CLA Document and I hereby sign the CLA***
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by Max-Miller03** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Max-Miller03** [comment]
recheck

**Pull request merged**
