### PR TITLE
updating mongodb DOCS

### PR DESCRIPTION
**Pull request by ndurumo254**
## Description

This issue updates the installation guides of MongoDB. The issue being solved is the dependency error that occurs when MongoDB is installed via pip. To solve the problem, you have to navigate to the handlers folder and manually install all the dependencies by running the pip install -r requirements.txt command.

**Fixes** #6694

## Type of change

- [ ] 📄 This change requires a documentation update

### What is the solution?

in case the dependencies are broken due to errors in MongoDB installation,  you have to navigate to the handlers folder and manually install all the dependencies by running the pip install -r requirements.txt command.
## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation, or created issues to update them.
- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] I have shared a short loom video or screenshots demonstrating any new functionality.

#I have read the CLA Document and I hereby sign the CLA

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@ndurumo254 
Please sign our CLA by leaving a comment here.

**Comment by martyna-mindsdb** [comment]
@ndurumo254 
You updated `monetdb.mdx`. Please undo these changes,
Then make the changes to `mongodb.mdx` file and push them to this PR.

**Comment by ndurumo254** [comment]
hope I can contribute to several other issues

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by martyna-mindsdb** [comment]
@ndurumo254 
As you have already solved one first-timers-only issue, now you can have a look at other issues labeled as help-wanted.

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by martyna-mindsdb** [comment]
recheckcla

**Pull request merged**
