### PR TITLE
(feat): Extending Confluence integration

### LINKED ISSUE #8076: [Confluence] Extend integration by adding the Content endpoint
MindsDB integrates with Confluence.

## Resources

Familiarize yourself with the existing Confluence integration: https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/confluence_handler

## Steps to Follow

The task is to extend [this implementation](https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/confluence_handler) to enable finding, creating, modifying and deleting Content (https://docs.atlassian.com/atlassian-confluence/REST/6.6.0/).

Please provide screenshots or a short video presenting this feature.

## :loudspeaker: Additional rewards :trophy:

Each integration extension brings 15+ points for SWAG and entry into the draw for a :point_down: :
-  :computer:  [Razer Blade 16 Laptop](https://www.razer.com/gaming-laptops/Razer-Blade-16/RZ09-0483SEJ3-R3U1)
- :shirt: :bear:  [MindsDB Swag](https://store.covver.io/mindsdb/collections/swag-collection)

:information_source: For more info check out https://mindsdb.com/hacktoberfest/ :point_left:

### PR DESCRIPTION
**Pull request by mobley-trent**
## Description

Adds these methods to the Confluence handler:
- `create_page`
- `modify_page`
- `delete_page`
- `get_content`

Fixes #8076

## Type of change

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [x] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have appropriately commented on my code, especially in complex areas.
- [ ] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Review by MinuraPunchihewa — CHANGES_REQUESTED** [review]
Hey @mobley-trent,
The functions that you have added here are useful, but they do not fall into the structure required for them to be applicable to the context of MindsDB.
All of your functions seem to be related interacting with Confluence pages, therefore, I think that maybe you can add a `ConfluencePagesTable` (as a subclass of `APITable`) and move your logic there.
Please refer this if you need further clarity on how Application handlers are developed for MindsDB,
https://docs.mindsdb.com/contribute/app-handlers

**Review by MinuraPunchihewa — CHANGES_REQUESTED** [review]
Hey @mobley-trent,
This looks a lot better! Thank you.

To complete this, we will need to do the following,
1. Update the README with the changes that you have made; the new table that has been added.
2. Provide screenshots or a short video of your changes working as expected.
3. It would be great if you can add some unit tests for this handler. We can maybe start with the table that you have created, but if you can cover the other one as well, it would be awesome.

**Comment by mobley-trent** [comment]
> Hey @mobley-trent, This looks a lot better! Thank you.
> 
> To complete this, we will need to do the following,
> 
> 1. Update the README with the changes that you have made; the new table that has been added.
> 2. Provide screenshots or a short video of your changes working as expected.
> 3. It would be great if you can add some unit tests for this handler. We can maybe start with the table that you have created, but if you can cover the other one as well, it would be awesome.

Working on it 👍

**Comment by mobley-trent** [comment]
Screenshot 2023-11-13 112859
Screenshot 2023-11-13 113010

**Comment by mobley-trent** [comment]
Screenshot 2023-11-13 131748
Screenshot 2023-11-13 132106
Screenshot 2023-11-13 132243

**Comment by chandrevdw31** [comment]
Hey there Eddy @mobley-trent, once you have updated this PR with the screenshots and Readme file, please DM me on slack https://mindsdb.com/joincommunity

**Review by MinuraPunchihewa — COMMENTED** [review]
Hey @mobley-trent,
This looks good now. However, there is one thing that I just noticed where going through the README. The initial table that was implemented for this handler, called `ConfluenceSpacesTable` was also registered as `pages` for some reason. I am not sure if this was a mistake or if there is some reasoning behind it.
@bala-ceg Could you please comment on this?

**Comment by bala-ceg** [comment]
Hi @MinuraPunchihewa,
Confluence api has both pages and spaces endpoint and Each space has multiple pages. In a way, confluence Spaces are subset of pages. Earlier Implementation would list the pages based on the type. @mobley-trent has implemented CRUD model on the spaces 
Long story short and to answer your question, I **mistakenly named pages as ConfluenceSpacesTable**

**Comment by MinuraPunchihewa** [comment]
@bala-ceg Does that mean what @mobley-trent has done here by registering the table that you had created (`ConfluenceSpacesTable`) is correct?
Your implementation is for `spaces` and his is for `pages`, is that correct?

**Comment by bala-ceg** [comment]
@MinuraPunchihewa when looked at it closely, I think both our implementation is somewhat common to pages only and not related to spaces. Eddy has enhanced the existing integration by implementing CRUD for the confluence api

@mobley-trent can you please confirm

**Comment by mobley-trent** [comment]
I meant to add the CRUD operations for pages. The current setup only allowed to view the info about the spaces and not the pages. I also refactored the handler such that the previous `pages` table is now the `spaces` and the new `pages` table is the one that supports the queries on the pages data
@MinuraPunchihewa
@bala-ceg

**Comment by MinuraPunchihewa** [comment]
@bala-ceg Do you think we should remove the `ConfluenceSpacesTable` in the case? I mean, if it is similar to pages? Or do you think we can refactor it to extract data for spaces?

**Comment by MinuraPunchihewa** [comment]
Hey @bala-ceg,
Please do let us know what you think is the best way to proceed with this.

**Comment by bala-ceg** [comment]
Hi @MinuraPunchihewa,
Sorry, I missed this communication. I think we can remove the`ConfluenceSpacesTable` in this case

**Comment by MinuraPunchihewa** [comment]
@bala-ceg No problem at all, thank you for your response.
@mobley-trent Can we please do this?

**Review by MinuraPunchihewa — CHANGES_REQUESTED** [review]
@mobley-trent Similar to how you have implemented the functionality to `UPDATE` and `DELETE` pages by passing in the page ID, can we make it possible to SELECT a single page as well. This does not seem to be possible at the moment.

**Comment by MinuraPunchihewa** [comment]
@mobley-trent One of the CI checks seem to be failing as well. Can you please merge the latest code from staging?

**Comment by mobley-trent** [comment]
Screenshot 2023-11-15 171212

@MinuraPunchihewa I just added the functionality to select pages by id. However, you will still have to provide the space name as this is the main variable used to extract pages from the atlassian API. As for the failing CI check, its coming up because I used `dotenv` to load the env variables which I used in the test. I stored the page ids and API keys in an env file, which I then listed into a gitignore file.

**Comment by MinuraPunchihewa** [comment]
@mobley-trent Shall we remove `dotenv` from your file and make a commit? I think when running these tests, we can use environment variables.
Once you do this, I believe we are ready to merge.

**Review by MinuraPunchihewa — APPROVED** [review]

**Comment by MinuraPunchihewa** [comment]
Thanks, @mobley-trent. Great work!

**Comment by MinuraPunchihewa** [comment]
@mobley-trent Sorry, I forgot one thing, if you can please add an example how to select a single page (as you have shown above) to the README. You can open another PR for this.

**Pull request merged**
