### PR TITLE
Added docs page for Couchbase data integration 

### PR DESCRIPTION
**Pull request by ShatilKhan**
## Description

Added docs page for couchbase

**Fixes** #4588

## Type of change

- [✔ ] 📄 This change requires a documentation update

### What is the solution?

I added a parameters required section & an example usage case to implement couchbase using Mindsdb

## Checklist:

- [ ✔] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ✔] I have commented my code, particularly in hard-to-understand areas.
- [ ✔] I have updated the documentation, or created issues to update them.

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
@ShatilKhan 
Please leave a comment containing `I have read the CLA Document and I hereby sign the CLA` so we can merge your PR.

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@ShatilKhan 
The task here was to create the `docs/data-integrations/couchbase.mdx` file.
Could you please undo the changes you made to other files?

**Comment by ShatilKhan** [comment]
Oh yes sure, my bad, I'll undo the changes on other files & create a pull request.

**Comment by ShatilKhan** [comment]
Hey @martyna-mindsdb , do check it out now & let me know if there's any problems anymore. I have deleted my other changes & commented on the pull request to sign the CLA. Thanks!

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
Please remove the mint.json file and the lock json from the PR

**Comment by ShatilKhan** [comment]
ok on it.

**Comment by ShatilKhan** [comment]
Hey @ZoranPandovski , it's done! check it & let me know.

**Comment by ZoranPandovski** [comment]
You will need to remove mint file from the PR not to delete it

**Comment by ShatilKhan** [comment]
Sorry, my bad, I'll remove it.

**Comment by martyna-mindsdb** [comment]
@ShatilKhan 
Also, please leave a comment here with `I have read the CLA Document and I hereby sign the CLA` so that we can merge your PR once ready.

**Comment by martyna-mindsdb** [comment]
@ShatilKhan 
You can remove files from this PR using this command: `git rm <file path>` followed by `git commit`.
Please let us know if you could resolve it.

**Pull request closed without merging**
