### PR TITLE
[Integration] Eventbrite integration (v.0.0.1)

### LINKED ISSUE #8021: Eventbrite integration
### Short description and motivation for the proposed feature

Writing an API integration to eventbrite that has an event table

SELECT date, event_name, event_description, attendies FROM my_eb.events where date = NOW();

### Video or screenshots

_No response_

### Describe some possible solutions

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by HahaBill**
## Description

Created Eventbrite integration with Mindsdb :)

Implementation + README.md + Tests done

Fixes #8021 

## Type of change

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x ] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [x ]   Test Location: Specify the URL or path for testing: **tests/handler_tests/test_eventbrite_handler.py**
 - [x ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [ x] I have attached a brief loom video or screenshots showcasing the new functionality or change.

Screenshot 2023-10-30 at 17 30 16

Screenshot 2023-10-30 at 17 31 01

Screenshot 2023-10-30 at 18 37 44

### Running Tests:

Screenshot 2023-10-30 at 23 12 25

## Checklist:

- [x ] My code follows the style guidelines(PEP 8) of MindsDB.
- [x ] I have appropriately commented on my code, especially in complex areas.
- [x ] Necessary documentation updates are either made or tracked in issues.
- [x ] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Comment by HahaBill** [comment]
@ZoranPandovski @martyna-mindsdb Created Eventbrite Integration with Mindsdb for Hacktoberfest

**Comment by HahaBill** [comment]
> ## Description
> Created Eventbrite integration with Mindsdb :)
> 
> Implementation + README.md + Tests done
> 
> Fixes #8021
> 
> ## Type of change
> (Please delete options that are not relevant)
> 
> * [ ]  🐛 Bug fix (non-breaking change which fixes an issue)
> * [x ] ⚡ New feature (non-breaking change which adds functionality)
> * [ ]  📢 Breaking change (fix or feature that would cause existing functionality not to work as expected)
> * [ ]  📄 This change requires a documentation update
> 
> ## Verification Process
> To ensure the changes are working as expected:
> 
> * [x ]   Test Location: Specify the URL or path for testing: **tests/handler_tests/test_eventbrite_handler.py**
> * [x ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.
> 
> ## Additional Media:
> * [ x] I have attached a brief loom video or screenshots showcasing the new functionality or change.
> 
> Screenshot 2023-10-30 at 17 30 16 Screenshot 2023-10-30 at 17 31 01 Screenshot 2023-10-30 at 18 37 44
Screenshot 2023-10-30 at 23 12 25


> ## Checklist:
> * [x ] My code follows the style guidelines(PEP 8) of MindsDB.
> * [x ] I have appropriately commented on my code, especially in complex areas.
> * [x ] Necessary documentation updates are either made or tracked in issues.
> * [x ] Relevant unit and integration tests are updated or added.

**Review by MinuraPunchihewa — COMMENTED** [review]
@HahaBill This looks good. If I am to be very critical, I think it would be great if we can use more standard table names like users, organization etc. This would make it more consistent with the other handlers as well.
If you agree, this change would need to made in registering the tables and also in the examples provided in the README.

**Comment by HahaBill** [comment]
@MinuraPunchihewa Got it, will do it! :)

**Comment by HahaBill** [comment]
@MinuraPunchihewa Alright all done! Changed table names. Additionally, run the app and everything works.

**Review by MinuraPunchihewa — APPROVED** [review]

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
