### PR TITLE
Google Sheets Integration

### PR DESCRIPTION
**Pull request by MinuraPunchihewa**
I have implemented the new integration for Google Sheets. After some initial testing, it looks to be working as expected. 

At the moment, however, I am facing a slight issue. When I launch the MindsDB SQL Editor and try to run a query using this handler, I get the following error, 
```
2022-10-10 07:38:37,235 - INFO - Traceback (most recent call last):
  File ".\mindsdb\api\http\namespaces\analysis.py", line 44, in post
    result = mysql_proxy.process_query(query)
  File ".\mindsdb\api\mysql\mysql_proxy\mysql_proxy.py", line 490, in process_query
    executor.query_execute(sql)
  File ".\mindsdb\api\mysql\mysql_proxy\executor\executor.py", line 110, in query_execute
    self.do_execute()
  File ".\mindsdb\api\mysql\mysql_proxy\executor\executor.py", line 221, in do_execute
    ret = self.command_executor.execute_command(self.query)
  File ".\mindsdb\api\mysql\mysql_proxy\executor\executor_commands.py", line 517, in execute_command
    session=self.session
  File ".\mindsdb\api\mysql\mysql_proxy\classes\sql_query.py", line 441, in __init__
    self.execute_query()
  File ".\mindsdb\api\mysql\mysql_proxy\classes\sql_query.py", line 843, in execute_query
    data = self.execute_step(step, steps_data)
  File ".\mindsdb\api\mysql\mysql_proxy\classes\sql_query.py", line 978, in execute_step
    data = self._fetch_dataframe_step(step)
  File ".\mindsdb\api\mysql\mysql_proxy\classes\sql_query.py", line 536, in _fetch_dataframe_step
    dn = self.datahub.get(step.integration)
  File ".\mindsdb\api\mysql\mysql_proxy\datahub\datanodes\information_schema_datanode.py", line 87, in get
    integration_controller=self.session.integration_controller
  File ".\mindsdb\api\mysql\mysql_proxy\datahub\datanodes\integration_datanode.py", line 20, in __init__
    self.integration_handler = self.integration_controller.get_handler(self.integration_name)
  File ".\mindsdb\utilities\with_kwargs_wrapper.py", line 43, in wrapper
    return method(*args, **kwargs)
  File ".\mindsdb\interfaces\database\integrations.py", line 279, in get_handler
    arg_name for arg_name in connection_data
  File ".\mindsdb\interfaces\database\integrations.py", line 280, in <listcomp>
    if connection_args.get(arg_name)['type'] == ARG_TYPE.PATH
TypeError: 'NoneType' object is not subscriptable
```
I would really appreciate it if someone could provide some insight as to what this could be.

One possibility that I could think of is the fact that the Query Language used for Google Sheets does not use the `FROM` keyword,
https://developers.google.com/chart/interactive/docs/querylanguage

Could this be why?

As a result of this, I am not quite sure how a query would be run against a data source created using this handler. For instance, is the following syntax correct?
`SELECT * FROM sheets_datasource.iris`

### CODE REVIEW

**Comment by MinuraPunchihewa** [comment]
@ZoranPandovski I think I actually have a better idea for getting this done. I will start pursuing it.
In the meantime, any comments you might have on the current implementation are welcome.

**Comment by ZoranPandovski** [comment]
This is really strange why it fails here. 
```
if connection_args.get(arg_name)['type'] == ARG_TYPE.PATH
```
This is only used for handlers that have a file for authentication as a path to ssl cert or service account keys file. Maybe there is some error before that and we catch the exception here. If you got still the same error I can try to debug it

**Comment by MinuraPunchihewa** [comment]
@ZoranPandovski, I have used a different approach to implement this and I am quite sure that it should work. However, I still get the same error. Do you think it will be possible for you to have a look?

**Comment by MinuraPunchihewa** [comment]
Hey @ZoranPandovski, this solved the issue! Thank you!
The integration seems to work fine now. Given below is a screenshot of creating a predictor on some data using this integration,
image

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
