### PR TITLE
Add mindsdb docker-compose #780

### PR DESCRIPTION
**Pull request by elvis2**
Add mindsdb docker-compose #780

For early adopters, we need a fast and simple use case to have mindsdb running as well as a flavor of databases.

Create a docker-compose that allows each docker resource to be avilable on the host.

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/> 
   - - -
   ***I have read the CLA Document and I hereby sign the CLA***
   - - - 
   **Elvis McNeely** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You can retrigger this bot by commenting **recheckcla** in this Pull Request</sub>

**Comment by elvis2** [comment]
Hello, I agree to the CLA. 

What branch should I be cloning from, Stable or Stage?

**Comment by George3d6** [comment]
A few things:
1. This seems to contain various changes not part of this PR, namely those in the cla file and in `__main__.py`.
2. The idea here, as far as I understand is:

Have a docker container that people can quickly boot up to try a mindsdb database integration. But shouldn't this come along with additional docs for this purpose ?

**Comment by elvis2** [comment]
@George3d6 The contribution section of this project says to make sure you pull the latest before creating the PR. I asked in a couple of locations "which" branch should we be cloning from, to contribute, and what PR destination branch to use. The documentation doesn't specify that.

Do I need to move my changes to a specific branch?

**Comment by George3d6** [comment]
Ideally, for now, you'd clone the `staging` branch and base the changes on that.

**Comment by elvis2** [comment]
I reset my branch, pulled from upstrea staging then readded my code. Hopefully all is well now.

**Pull request closed without merging**
