### PR TITLE
#5959 issue: update: change href link

### PR DESCRIPTION
**Pull request by Sourav56**
## Description

Solved a first-timers-only tag issue. Changed the href link to https://docs.mindsdb.com/data-integrations/sqlite from the following HTML tag: <a href="https://docs.mindsdb.com/data-integrations/all-data-integrations#sqlite">SQLite Badge</a>

**Fixes** #(issue)

## Type of change

- [x] 📄 This change requires a documentation update

### What is the solution?

Changed the old link to the updated one.

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation, or created issues to update them.
- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@Sourav56 
Please undo all the changes that you've made to this file (see the _Files changed_ tab above).
Please keep only the change to the link as requested in the issue description.

**Comment by Sourav56** [comment]
> @Sourav56 Please undo all the changes that you've made to this file (see the _Files changed_ tab above). Please keep only the change to the link as requested in the issue description.

Sorry for the delayed response. All the changes have been reverted, I apologize for the extra changes, I believe it was due to my extensions in VScode. I have made the appropriate changes in the readme file. Do you want me to create a pull request for that?

**Comment by martyna-mindsdb** [comment]
@Sourav56 
Please push your changes to this PR.

**Comment by Sourav56** [comment]
> @Sourav56 Please push your changes to this PR.

Hey martyna, I have made the changes to this PR. Kindly let me know if this is done correctly.

**Pull request merged**
