### PR TITLE
Predicting Microsoft Stock Prices on Dev.To

### LINKED ISSUE #3874: [Tutorial] Predict Microsoft Stock Prices
### Task Description

Write tutorial on predicting Microsoft Stock prices using data between 2015 and 2022.

You can use the dataset `microsoft_stocks.csv` available at https://www.kaggle.com/datasets/berkayalan/microsoft-stock-data-between-2015-and-2022.

## :loudspeaker: Additional rewards :trophy:

Each tutorial brings :five: points and entry into the draw for a  :point_down: :

-  :computer:  [Razer Blade 15 Laptop](https://www.razer.com/hard-bundles/Razer-Blade-15-Bundle-V5-Essential/RZHB-220912-11)
- :headphones:  10 cool audio gadgets 
- :shirt: :bear: MindsDB Swag
:information_source: For more info check out https://mindsdb.com/hacktoberfest/ :point_left: 

To participate in the prize draw, you need to complete this form with your contact details and links to all your merged PRs or no-code deliverables. Please submit the form once with all your contributions listed.

### PR DESCRIPTION
**Pull request by viveknshah**
Fixes #3874

## Please describe what changes you made, in as much detail as possible
  -

An account of how I set up my MindsDB predictor to try and predict Microsoft Stock Prices using a Kaggle Dataset [here](https://dev.to/viveknshah/using-mindsdb-to-predict-microsoft-stock-prices-3l79)

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by viveknshah** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by viveknshah** [comment]
recheck

**Comment by ZoranPandovski** [comment]
recheckcla

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
