### PR TITLE
added a tutorial

### PR DESCRIPTION
**Pull request by dhruv-porwal**
teaches ML implementationwith minds DB teaching step by step.

## Please describe what changes you made, in as much detail as possible
  -added a tutorial which teaches in detail about implementation of ML through MindDB

mindsdb

### CODE REVIEW

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
Can you follow the format please, and add the name after the tutorial title

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by dhruv-porwal** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by dhruv-porwal** [comment]
recheck

**Comment by dhruv-porwal** [comment]
now sir kindly add it

**Comment by dhruv-porwal** [comment]
Sir kindly add it now🙏

**Comment by dhruv-porwal** [comment]
sir kindly mark it hacktoberfest  accepted

**Pull request merged**
