### PR TITLE
Add the cratedb.mdx files to docs navigation

### PR DESCRIPTION
**Pull request by ancatoza**
## Description
Hi
On this issue I added the cratedb.mdx files to docs navigation. 

**Fixes** #4617

## Type of change

- [x] ⚡ New feature (non-breaking change which adds functionality)

### What is the solution?

Since this issue was for "first time only" I  followed the instructions that were contained on the description. 

## Checklist:
- [x] N/A
- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation, or created issues to update them.
- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
Recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@ancatoza
Before we can merge your PR, could you please sign our CLA by following the instructions above?

**Comment by ancatoza** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
