### PR TITLE
luma integration

### LINKED ISSUE #8022: LUMA Events integration
### Short description and motivation for the proposed feature

Write an integration that helps us query events form LUMA

SELECT date, event, description, url FROM my_luma.events WHERE date > NOW();

https://docs.lu.ma/reference/getting-started-with-your-api

### Video or screenshots

_No response_

### Describe some possible solutions

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Better-Boy**
## Description

Luma integration - https://docs.lu.ma/reference

Fixes #8022 

## Type of change

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [x] I have attached a brief loom video or screenshots showcasing the new functionality or change.

Screenshot 2023-11-14 at 7 44 17 PM

Screenshot 2023-11-14 at 8 03 28 PM

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have appropriately commented on my code, especially in complex areas.
- [x] Necessary documentation updates are either made or tracked in issues.
- [x] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Review by MinuraPunchihewa — CHANGES_REQUESTED** [review]
Hey @Better-Boy,
Since we are going for the concept of 'tables' here, let's not call the `APITable` implementations `list_events` or `get_events`. I think `events` should suffice.
Also, can you explain the difference between the implementations you have given for `list_events` and `get_events`? Do both of them return events data in the end?

**Comment by Better-Boy** [comment]
> Hey @Better-Boy, Since we are going for the concept of 'tables' here, let's not call the `APITable` implementations `list_events` or `get_events`. I think `events` should suffice. Also, can you explain the difference between the implementations you have given for `list_events` and `get_events`? Do both of them return events data in the end?

- `list_events` - returns/lists data about all events.
- `get_event` - This is `get_event` not `get_events` (no plural form). Returns all info about a single event.

You can see from the screenshots I have attached.

**Comment by MinuraPunchihewa** [comment]
> > Hey @Better-Boy, Since we are going for the concept of 'tables' here, let's not call the `APITable` implementations `list_events` or `get_events`. I think `events` should suffice. Also, can you explain the difference between the implementations you have given for `list_events` and `get_events`? Do both of them return events data in the end?
> 
> * `list_events` - returns/lists data about all events.
> * `get_event` - This is `get_event` not `get_events` (no plural form). Returns all info about a single event.
> 
> You can see from the screenshots I have attached.
> 
> @MinuraPunchihewa

@Better-Boy This should be one table (`events`); if a SELECT * is executed, all of the events should be returned, but if a SELECT is executed including a WHERE clause with the relevant ID (or other parameters), then only one should be returned.

**Comment by Better-Boy** [comment]
@MinuraPunchihewa You mean to say have one table called `events` where if `event_id` is given, then return all events. If `event_id` is given then return only that event. Is my understanding correct?

**Comment by MinuraPunchihewa** [comment]
> @MinuraPunchihewa You mean to say have one table called `events` where if `event_id` is not given, then return all events. If `event_id` is given then return only that event. Is my understanding correct?

@Better-Boy Yes, exactly.

**Comment by Better-Boy** [comment]
@MinuraPunchihewa I have implemented the required changes.

**Review by MinuraPunchihewa — COMMENTED** [review]
Hey @Better-Boy,
Can you please add a few screenshots with the changes that you have implemented?

**Comment by Better-Boy** [comment]
@MinuraPunchihewa The API key that I was using (provided by @torrmal ) is no longer valid. Getting `User not found` when trying to validate the key. If a new valid API key is given, I can test my changes and send screenshots.

**Comment by Better-Boy** [comment]
@MinuraPunchihewa Thanks for providing the API key. Tested the changes. Screenshots as follows:

Screenshot 2023-11-20 at 4 18 36 PM
Screenshot 2023-11-20 at 4 18 59 PM

**Review by MinuraPunchihewa — COMMENTED** [review]
LGTM!
Can you please just solve the Flake issues? Then, we are ready to merge.
Also, just mark the 'LUMA Get an event item' under 'Implemented Features' as done (tick the checkbox).

**Comment by Better-Boy** [comment]
@MinuraPunchihewa Fixed flake8 issues and ticked the checkbox.

**Review by MinuraPunchihewa — APPROVED** [review]

**Comment by MinuraPunchihewa** [comment]
Great work, @Better-Boy!

**Pull request merged**
