### PR TITLE
replaced slack join link

### PR DESCRIPTION
**Pull request by Sekinat-oyero**
## Description

**Fixes** #([#6383](https://github.com/mindsdb/mindsdb/issues/6383))

## Type of change
Documentation

### What is the solution?
Replaced the slack join link in crop-prediction.mdx

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@Sekinat-oyero 
Please sign our CLA so we can merge your PR.

**Comment by Sekinat-oyero** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
