### PR TITLE
Use parametrized Dockerfile for building images

### PR DESCRIPTION
**Pull request by abitrolly**
This removes generation step and makes the setup more readable.

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
Thanks, we have this done but the PR is not merged, you can check https://github.com/mindsdb/mindsdb/pull/169. Should be merged today/tomorrow. We can close this for now

**Comment by abitrolly** [comment]
@ZoranPandovski are you sure? #169 is two years old.

**Comment by ZoranPandovski** [comment]
I've missed the 8 at the end :) https://github.com/mindsdb/mindsdb/pull/1698

**Comment by abitrolly** [comment]
They do different things. It will be easier to redo the PR on top of this one.

**Comment by abitrolly** [comment]
@ZoranPandovski make sure to check #1753 before merging anything Docker related.

**Comment by abitrolly** [comment]
@ZoranPandovski rebased and reworked over #1698.

**Pull request closed without merging**
