### PR TITLE
Updated documentation on  sql-alchemy.md

### LINKED ISSUE #2913: [Bug]: No error response using incorrect parameters with SQLAlchemy
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Incorrect input parameters gives a successful response:

_Connection to the cloud-mysql.mindsdb.com for user MindsDB Cloud username created successfully._ 

Ref community post below:
https://mindsdbcommunity.slack.com/archives/C037482KJ22/p1663143779244629

image

### Expected Behavior

An error message like: 

_This username or password is incorrect_

### Steps To Reproduce

```markdown
https://docs.mindsdb.com/connect/sql-alchemy/
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ArmanChand**
Fixes #2913

## Updated documentation on sql-alchemy.md
  -  updated the documentation on SQLAlchemy with engine.connect()

mindsdb

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by ArmanChand** [comment]
@ZoranPandovski Please review

**Comment by ZoranPandovski** [comment]
@ArmanChand you will need to sign the CLA, please add `I have read the CLA Document and I hereby sign the CLA`

**Comment by ArmanChand** [comment]
recheck

**Review by martyna-mindsdb — APPROVED** [review]

**Comment by martyna-mindsdb** [comment]
@ArmanChand
You modified the code in the `Connecting MindsDB Cloud to SQL Alchemy` tab, but there is a similar code in the `Connecting Local MindsDB to SQL Alchemy` tab that should be updated the same way.

**Pull request merged**
