### PR TITLE
Fixed Broken in links in Getting Started Page

### LINKED ISSUE #3517: [Bug]: Most of the links in https://docs.mindsdb.com/getting-started/ are broken
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In the following page: https://docs.mindsdb.com/getting-started/

Links broken are: 
image
image
image

I want to submit a PR for this

### Expected Behavior

They should redirect to the expected pages

### Steps To Reproduce

```markdown
1. Open https://docs.mindsdb.com/getting-started/
2. In step 1, go to either docker/pip and click on the link, find a 404 page!
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by hridaya423**
Fixes #

Closes #3517 

## Please describe what changes you made, in as much detail as possible
  - Fixed all the broken links in the Getting Started

mindsdb

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by hridaya423** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by hridaya423** [comment]
Does this count as a contribution for hacktoberfest?

**Comment by hridaya423** [comment]
@ZoranPandovski could you please mark this as a hacktoberfest contribution?

**Pull request merged**
