### PR TITLE
Replaced <Note> with <Info>

### PR DESCRIPTION
**Pull request by Ambareen09**
## Description

Please include a summary of the change and the issue it solves. 

**Fixes** #5794 

## Checklist:

- [X] My code follows the style guidelines(PEP 8) of MindsDB.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have updated the documentation, or created issues to update them.
- [X] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [X] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@Ambareen09 
Please sign our CLA by leaving a comment here that contains this line: I have read the CLA Document and I hereby sign the CLA

**Comment by Ambareen09** [comment]
I have read the CLA Document and I hereby sign the CLA
Ambareen Azam

**Comment by Ambareen09** [comment]
recheckcla

**Pull request merged**
