### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by agarwal-aryan**
## Description

Updated the link to the IBM DB2 integration

**Fixes** #4973

## Checklist:

- [x] I have updated the documentation, or created issues to update them.

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@agarwal-aryan 
Please note that this issue is assigned to another contributor.

Please have a look at other issues for first-timers and make sure to be assigned to the issue before creating a PR. Thanks.

**Comment by agarwal-aryan** [comment]
@martyna-mindsdb   can you tell me what I should do now?

**Comment by martyna-mindsdb** [comment]
@agarwal-aryan 
Please see other issues here: https://github.com/mindsdb/mindsdb/labels/first-timers-only

After choosing an issue, please leave a comment there. You can create a PR after we assign you this issue.

**Pull request closed without merging**
