### PR TITLE
Added Virtual Environment install instructions

### LINKED ISSUE #743: Update Install instructions on README.md
We want to suggest people to run mindsdb on a venv, 
and we require python 3.8

Can you update the README.md so it reflects 

1. create and activate venv:
```
  python3 -m venv venv
  source venv/bin/activate
```
2. install MindsDB:
```
  pip3 install mindsdb
```
3. Run MindsDB
```
    python3 -m mindsdb
```

### PR DESCRIPTION
**Pull request by the-bose**
Fixes #743

  - Added install instructions to install MindsDB in a Python virtual environment

mindsdb

### CODE REVIEW

**Comment by torrmal** [comment]
Thank you @the-bose, I updated the issue with instructions to run the server

3. Run MindsDB
    python3.8 -m mindsdb

Perhaps same for host environment.

**Comment by torrmal** [comment]
@ZoranPandovski do you know why https://github.com/mindsdb/mindsdb/pull/745 may be happening?

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/> 
   - - -
   ***I have read the CLA Document and I hereby sign the CLA***
   - - - 
   <sub>You can retrigger this bot by commenting **recheckcla** in this Pull Request</sub>

**Comment by George3d6** [comment]
@the-bose can you change `3.8` to `3.6` and reply to the CLA bot in order to sign the CLA ?

**Comment by the-bose** [comment]
> @the-bose can you change `3.8` to `3.6` and reply to the CLA bot in order to sign the CLA ?

Hello, are you referring to this part to change `3.8` to `3.6`?
```
3. Run MindsDB
  python3.8 -m mindsdb
```

**Comment by the-bose** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
