### PR TITLE
Updating dbt docs to reflect dbt-mindsdb instead of mysql adapter

### PR DESCRIPTION
**Pull request by fromdavelewis**
Fixes #

## Please describe what changes you made, in as much detail as possible
  -

mindsdb

### CODE REVIEW

**Comment by fromdavelewis** [comment]
recheckcla

**Comment by fromdavelewis** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by dave** [comment]
> ❌ @dave Lewis**Dave Lewis** seems not to be a GitHub user. 

FYI this is inviting me to the chat 😉

Looks like @ibakshay develops this CLA Assistant action?

**Comment by fromdavelewis** [comment]
@dave sorry for the confusion!  yes it looks like CLA Assistant made a best attempt at parsing my name as my username.  Thank you for your gracious response

**Comment by dave** [comment]
> @dave sorry for the confusion! yes it looks like CLA Assistant made a best attempt at parsing my name as my username. Thank you for your gracious response

No problem, looks like it was corrected.

**Comment by fromdavelewis** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by fromdavelewis** [comment]
recheckcla

**Pull request merged**
