### PR TITLE
Feature/add couchbase vector store

### PR DESCRIPTION
**Pull request by prajwal-pai77**
## Description

Please include a summary of the change and the issue it solves. 

Adds #9751 

## Type of change

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [X] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [X]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [ ] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have appropriately commented on my code, especially in complex areas.
- [X] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb/blob/main/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Review by MinuraPunchihewa — CHANGES_REQUESTED** [review]
@prajwal-pai77 There are a bunch of failed lint issues that you can find here: https://github.com/mindsdb/mindsdb/actions/runs/10992819680/job/30576401340?pr=9752

Please fix them.

**Comment by prajwal-pai77** [comment]
@MinuraPunchihewa Yes, fixed the lint issues

**Review by MinuraPunchihewa — APPROVED** [review]

**Comment by prajwal-pai77** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
Thanks @prajwal-pai77 :rocket:

**Comment by prajwal-pai77** [comment]
Hi @ZoranPandovski / @MinuraPunchihewa 
I am not able to see Couchbase as a vector store here or any mention anywhere else here: https://docs.mindsdb.com/integrations/integrations
Can you please confirm this?

**Comment by MinuraPunchihewa** [comment]
Hey @prajwal-pai77, 
The documentation for our integrations need to be added separately. That is why you are not seeing it here.
Would you like to open a PR for this?

**Comment by prajwal-pai77** [comment]
@MinuraPunchihewa sure, let me know how/where i need to open a PR for this, so that we can see it there

**Comment by MinuraPunchihewa** [comment]
These docs are maintained in this same repository. I recently added the documentation for another one of our integrations [here](https://github.com/mindsdb/mindsdb/pull/9912). I think you can follow the same structure.

**Comment by prajwal-pai77** [comment]
I have created a PR: https://github.com/mindsdb/mindsdb/pull/10039 
Pls take a look when you can.
Thanks!

**Pull request merged**
