### PR TITLE
Fixed issue #810 by adding a link to the AI Tables in MySQL within th…

### LINKED ISSUE #810: Add AI Tables (MySQL) link to the Readme
In our [README](https://github.com/mindsdb/mindsdb/blob/staging/README.md#try-it-out) we need to add a link to AI Tables in MySQL in the unordered list. The link should point to the https://docs.mindsdb.com/databases/MySQL/

### PR DESCRIPTION
**Pull request by lucy-ctrl**
Fixes #810

## Please describe what changes you made, in as much detail as possible
  - Added a link to the AI tables in MySQL within the unordered list.

mindsdb

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/> 
   - - -
   ***I have read the CLA Document and I hereby sign the CLA***
   - - - 
   <sub>You can retrigger this bot by commenting **recheckcla** in this Pull Request</sub>

**Comment by lucy-ctrl** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by ZoranPandovski — APPROVED** [review]
Thanks

**Pull request merged**
