### PR TITLE
Delete mysql-ds.gif

### PR DESCRIPTION
**Pull request by Batmanrvb**
Fixes #

## Please describe what changes you made, in as much detail as possible
  -

mindsdb

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by Batmanrvb** [comment]
I Raj Vikrant Brahma have read the CLA Document and I hereby sign the CLA.

**Comment by ZoranPandovski** [comment]
Sorry you will need to copy the exact message without adding your name :)

**Comment by Batmanrvb** [comment]
recheckcla

**Comment by Batmanrvb** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
Sorry, you can't sign it through email

**Comment by Batmanrvb** [comment]
CLA Assistant Lite bot:
Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.

I have read the CLA Document and I hereby sign the CLA

**Comment by Batmanrvb** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
