### PR TITLE
Adding new mindsdb tutorial

### PR DESCRIPTION
**Pull request by aayushibansal2001**
### File Changed
`docs/mindsdb-docs/docs/tutorials.md`

### Details
Added new article to tutorials.md list
Article: [Deploying MindsDB on Scaleway Cloud](https://dev.to/rutamhere/deploying-mindsdb-on-scaleway-cloud-4kc6)
Author: [Rutam Prita Mishra](https://dev.to/rutamhere)

- [x] Links to article included
- [x] Links to author included

mindsdb

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by aayushibansal2001** [comment]
This PR is in reference to the issue #3095

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
Sorry this was already added by Rutam

**Pull request closed without merging**
