### PR TITLE
Created a unittest for Jira integration

### LINKED ISSUE #8930: Create a unittest for jira integration with MindsDB
### Short description and motivation for the proposed feature

The aim of this issue is to create a unit test for jira handler.

### Video or screenshots

_No response_

### Describe some possible solutions

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Sekhar-Kumar-Dash**
## Description

This PR creates a unittest for Jira Handler

## Type of change
- [X] ⚡ New feature (non-breaking change which adds functionality)

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [x] I have attached a brief loom video or screenshots showcasing the new functionality or change.
image

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have appropriately commented on my code, especially in complex areas.
- [ ] Necessary documentation updates are either made or tracked in issues.
- [x] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Comment by Sekhar-Kumar-Dash** [comment]
hey @MinuraPunchihewa  please review this PR.

**Comment by hamishfagg** [comment]
Can we please move the tests from `/tests` to the handler folder for this and the other similar PRs?
See the mysql handler for an example of where to put them. We're trying to make the handlers more self contained :)

**Comment by Sekhar-Kumar-Dash** [comment]
> Can we please move the tests from `/tests` to the handler folder for this and the other similar PRs? See the mysql handler for an example of where to put them. We're trying to make the handlers more self contained :)



> Can we please move the tests from `/tests` to the handler folder for this and the other similar PRs? See the mysql handler for an example of where to put them. We're trying to make the handlers more self contained :)

hey @hamishfagg actually i was told to put this test files in  /test folder

**Comment by MinuraPunchihewa** [comment]
Hey @hamishfagg,
When @Sekhar-Kumar-Dash reached out to me, I asked him to place the tests in the `/tests` directory. I apologize if this was an incorrect instruction. Have we decided to place the tests for handlers in their own folders?
CC: @ZoranPandovski

**Comment by hamishfagg** [comment]
Yeah that is the plan moving forward - it makes it much easier to find tests relevant to a handler, and makes it easier to execute tests based on changed files.
Thanks

**Comment by MinuraPunchihewa** [comment]
Thank you for this info, @hamishfagg.

**Comment by ZoranPandovski** [comment]
Closing as outdated, please comment so we sync if you continue working on this

**Pull request closed without merging**
