### PR TITLE
Create hf_sum_google_pegasus_tutorial_test.mdx

### PR DESCRIPTION
**Pull request by makingsurgeon**
## Description

Provides a tutorial for text summarization for Google Pegasus.

**Fixes** #(issue)

## Type of change

(Please delete options that are not relevant)

- [x] 📄 This change requires a documentation update

### What is the solution?

Incorporated the documentation on the official documentation website into this.

## Checklist:

- [x] I have updated the documentation, or created issues to update them.

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@makingsurgeon 
Please remember to link the issue number in the PR description: https://github.com/mindsdb/mindsdb/issues/6091

Please sign the CLA by leaving a comment here.

**Comment by makingsurgeon** [comment]
```
I have read the CLA Document and I hereby sign the CLA.
```
Sorry for not linking the issue. I will do better next time.

**Comment by martyna-mindsdb** [comment]
@makingsurgeon 
Could you please leave a comment that contains only the below line? (it is to activate the bot)

I have read the CLA Document and I hereby sign the CLA

**Comment by ZoranPandovski** [comment]
recheckcla

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
