### PR TITLE
Update docs/README.md

### PR DESCRIPTION
**Pull request by Ayush-Prabhu**
## Description

Updated docs/README.md to include the missing commands to run locally if CI/CD deployment fails.

## Type of change

- [X] 📄 This change is  a documentation update

## Checklist:

- [] My code follows the style guidelines(PEP 8) of MindsDB.
- [] I have appropriately commented on my code, especially in complex areas.
- [x] Necessary documentation updates are either made or tracked in issues.
- [] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by Ayush-Prabhu** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Ayush-Prabhu** [comment]
recheck

**Review by ZoranPandovski — APPROVED** [review]

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
We are not actually using mkdocs but mintlify so better to remove the deploy the docs section

**Comment by Ayush-Prabhu** [comment]
I have removed the deploy the docs section in the second commit. 
Thank you

**Pull request merged**
