### PR TITLE
☑☑  Added YugabyteDB Integration

### LINKED ISSUE #2672: [New Integration]: Integration with YugabyteDB
### Is there an existing integration?

- [X] I have searched the existing integrations.

### Use Case

YugabyteDB is a high-performance, cloud-native distributed SQL database.
It is also open source and similiar to postgres SQL.
It is best to fit for cloud-native OLTP (i.e. real-time, business-critical) applications that need absolute data correctness and require at least one of the following: scalability, high tolerance to failures, or globally-distributed deployments.

### Motivation

A it is compatible with postgresSQL it can be easily integrated and as YugabyteDB is very effective in app and therefore it is use to store business data.

### Implementation

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by parthiv11**
Fixes #2672 

## Please describe what changes you made, in as much detail as possible
  - I Have added yugabyteDB Handler ro mindsdb's Repo for DEV contest and it has passed all basic Testing
  - You can go to [yugabyte cloud](https://cloud.yugabyte.com/) and test my handler 
  - [YugabyteDB](https://docs.yugabyte.com/preview/quick-start/) can also be used for testing/

mindsdb

### CODE REVIEW

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
For all PostgreSQL, QuestDB, Supabase, etc we are using psycopg3. Let's migrate to it and use in this handler too, so we can have one psycopg dependency `psycopg>=3.0.16`

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
For all PostgreSQL, QuestDB, Supabase, etc we are using psycopg3. Let's migrate to it and use in this handler too, so we can have one psycopg dependency `psycopg>=3.0.16`

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
For all PostgreSQL, QuestDB, Supabase, etc we are using psycopg3. Let's migrate to it and use in this handler too, so we can have one psycopg dependency `psycopg>=3.0.16`

**Review by StpMax — CHANGES_REQUESTED** [review]
Looks like yugabyte allows only ssl connection with providing ca cert. I cant do it with current handler

**Comment by parthiv11** [comment]
@StpMax  have you readme file

**Review by StpMax — APPROVED** [review]

**Pull request merged**
