### PR TITLE
link updated

### LINKED ISSUE #2592: broken link anchors: Profile Setup and profiles.yml
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

broken link anchors: Profile Setup and profiles.yml
https://docs.mindsdb.com/connect/dbt/

### Expected Behavior

_No response_

### Steps To Reproduce

```markdown
https://docs.mindsdb.com/connect/dbt/
```

### Anything else?

For community members to contribute to

### PR DESCRIPTION
**Pull request by vivekthedev**
Fixes #2592 

## Please describe what changes you made, in as much detail as possible
  - updated the links according to https://github.com/mindsdb/mindsdb/issues/2592#issuecomment-1207917072
mindsdb

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   ***I have read the CLA Document and I hereby sign the CLA***
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by vivekthedev** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
You can change the link to point to `/connect/dbt/#initialization`

**Comment by vivekthedev** [comment]
> You can change the link to point to `/connect/dbt/#initialization`

Done

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
