### PR TITLE
[Doc Updated] - Title changed

### PR DESCRIPTION
**Pull request by imvisp**
## Description
Updated a title of the MongoDB Question Answering tutorial
- Changed `Title` and `SideTitle` in the documentation.

**Fixed** #5009

## Type of change
- Documentation changes.

(Please delete options that are not relevant)

- [✔️] 📄 This change requires a documentation update

## Checklist:

- [✔️] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [✔️] I have updated the documentation, or created issues to update them.
- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@imvisp 
Please sign our CLA as mentioned above so we can merge your PR.

**Comment by imvisp** [comment]
Yeah, sure!

Can you please tell me where can leave that comment to become contributor

**Comment by martyna-mindsdb** [comment]
@imvisp 
Please leave a comment here as follows:

I have read the CLA Document and I hereby sign the CLA

**Comment by imvisp** [comment]
Okay 👍

I have read the CLA Document and I hereby sign the CLA.

**Comment by martyna-mindsdb** [comment]
@imvisp 
Could you please leave a comment containing only the line below?

I have read the CLA Document and I hereby sign the CLA

**Comment by imvisp** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by imvisp** [comment]
Hello @martyna-mindsdb 👋

Any type of suggestions or feedback that you want to give from this pr ?

Would be really helpful for me!

**Comment by martyna-mindsdb** [comment]
Hi @imvisp 
This PR is already merged and all is fine.

As you have completed this issue (labeled as first-timers-only), please have a look at other https://github.com/mindsdb/mindsdb/labels/help%20wanted issues.

Please note that one user can solve only one issue labeled as first-timers-only, so avoid the ones with the first-timers label.

**Comment by imvisp** [comment]
Have one question

Should I create new branch before creating a pr ?

What's the best prectice ?

**Comment by martyna-mindsdb** [comment]
There must be one PR for one issue.

Once you choose an issue to work on, please create a PR for this issue and link this issue in the PR description, as you did here.

**Pull request merged**
