### PR TITLE
Add gitpod.io

### PR DESCRIPTION
**Pull request by ktyborowski**
## Description

Added gitpod.io configs to allow for mindsdb development in the cloud using Gitpod.

**Fixes** #4524 

## Type of change

- [x] ⚡ New feature (non-breaking change which adds functionality)

### What is the solution?

- Aded .gitpod.yml and .gitpod.Dockerfile to the repository root
- Aded _Open in Gitpod_ button at the top of the README

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by ktyborowski** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by ZoranPandovski** [comment]
recheckcla

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
