### PR TITLE
Added action step after 'deploy to pypi' to try to install latest min…

### LINKED ISSUE #804: Pip install after deploy
As part of our github action testing suite we need to add a step/script that runs *after* the deploy to pypi and tries to install the latest `mindsdb` version deployed there.

This is because, in certain scenarios, the pypi version install can be different from the way we install it in when testing and can thus still fail.

This should only happen when merging to stable, i.e. when a release to pypi is made.

### PR DESCRIPTION
**Pull request by jumc**
…dsdb

Fixes #804

## Added a step to run in command line "pip install mindsdb" after deploying to pypi
  -

mindsdb

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/> 
   - - -
   ***I have read the CLA Document and I hereby sign the CLA***
   - - - 
   <sub>You can retrigger this bot by commenting **recheckcla** in this Pull Request</sub>

**Review by George3d6 — CHANGES_REQUESTED** [review]
This probably requires a `sleep 10s` before trying to `pip install mindsdb` because otherwise it might not be deployed yet, it takes a bit for pip to actualize it's repos.

**Comment by George3d6** [comment]
@jumc are you still working on this ?

**Comment by jumc** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by jumc** [comment]
@George3d6 I've added the sleep command and reran the checks on my fork (they passed). Is there a way to run them again here?

**Comment by George3d6** [comment]
@jumc there's some other bugs causing tests to fail, once that's fixed I will merge

**Comment by ilia-tsyplenkov** [comment]
Closed since it is outdated https://github.com/mindsdb/mindsdb/pull/939

**Pull request closed without merging**
