### PR TITLE
Fixed mysqul typo

### LINKED ISSUE #5659: [Docs] Fix typo on the `pip on MacOS` page
## Instructions :page_facing_up:

Here are the step-by-step instructions:

1. Go to the `docs/setup/self-hosted/pip/macos.mdx` file.
2. Correct a typo: `mysqul` into `mysql`.
3. Save the changes and create a PR.

## The https://github.com/mindsdb/mindsdb/labels/first-timers-only Label

We are happy to welcome you on board! Please take a look at the rules below for first-time contributors.

1. You can solve only one issue labeled as https://github.com/mindsdb/mindsdb/labels/first-timers-only. After that, please look at other issues labeled as https://github.com/mindsdb/mindsdb/labels/good%20first%20issue, https://github.com/mindsdb/mindsdb/labels/help%20wanted, or https://github.com/mindsdb/mindsdb/labels/integration.

3. After you create your first PR in the MindsDB repository, please sign our CLA to become a MindsDB contributor. You can do that by leaving a comment that contains the following: `I have read the CLA Document and I hereby sign the CLA`

Thank you for contributing to MindsDB!

### PR DESCRIPTION
**Pull request by Zeesky-code**
## Description

Fixed the mysqul typo to close #5659

**Fixes** #5659

## Type of change

- 🐛 Bug fix (non-breaking change which fixes an issue)
- 📄 This change requires a documentation update

### CODE REVIEW

**Comment by Zeesky-code** [comment]
> ## Description
> Fixed the mysqul typo to close #5659
> 
> **Fixes** #5659
> 
> ## Type of change
> * 🐛 Bug fix (non-breaking change which fixes an issue)
> * 📄 This change requires a documentation update

I have read the CLA Document and I hereby sign the CLA

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@Zeesky-code 
Please sign the CLA by leaving a comment that contains only this line: I have read the CLA Document and I hereby sign the CLA

**Comment by Zeesky-code** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
