### PR TITLE
OpenAI Integration Improvements

### PR DESCRIPTION
**Pull request by MinuraPunchihewa**
## Description

This PR improves the OpenAI handler in order to make it Enterprise-ready.

## Type of change

- [X] 🐛 Bug fix (non-breaking change which fixes an issue)

## Verification Process

To ensure the changes are working as expected:

 - [X]   Test Location: `tests/unit/ml_handlers/test_openai.py` for unit tests and `mindsdb/integrations/handlers/openai_handler/tests/test_openai_handler.py` for integration tests.
 - [X]   Verification Steps: Run the above test modules (for integration tests, an OpenAI API key will be required).

- [X] My code follows the style guidelines(PEP 8) of MindsDB.
- [X] I have appropriately commented on my code, especially in complex areas.
- [X] Necessary documentation updates are either made or tracked in issues.
- [X] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Comment by MinuraPunchihewa** [comment]
@StpMax I cannot seem to run the fine-tuning test reliably; running into a bunch of errors. So, i've just commented it out for now.

**Comment by MinuraPunchihewa** [comment]
@ZoranPandovski I believe this is ready for review now.

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
Thanks. Before we merge let's remove the openai handler from flake ignore file https://github.com/mindsdb/mindsdb/blob/main/.flake8#L144C1-L144C49, also we can remove the commented test for now

**Comment by MinuraPunchihewa** [comment]
> Thanks. Before we merge let's remove the openai handler from flake ignore file https://github.com/mindsdb/mindsdb/blob/main/.flake8#L144C1-L144C49, also we can remove the commented test for now

Done.

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
