### PR TITLE
[DOC]: TPOT - Fixed the image url.

### PR DESCRIPTION
**Pull request by work-mohit**
## Description

**Fixes** #7429

Screenshot 2023-09-27 164151

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by work-mohit** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ZoranPandovski** [comment]
We are going to remove all of the Manual QA files. Please check the help-wanted issues if you want to contribute :raised_hands:

**Pull request closed without merging**
