### PR TITLE
add Github Commits Table github_tables.py

### LINKED ISSUE #7541: [GitHub] Implement the Commits table for a GitHub repository
MindsDB integrates with GitHub, so you can fetch data from GitHub and use it to train models or make predictions with MindsDB.

## Resources

Familiarize yourself with the existing GitHub integration: https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/github_handler

## Steps to Follow

Currently, the GitHub integration with MindsDB comes with the `issues` and `pull_requests` tables.

The task is to extend [this implementation](https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/github_handler) to include the `commits` table.

**Please note that we are not assigning this type of issue.
Create a PR and link it to this issue.
The first PR that solves this will be accepted** :fireworks:

## :loudspeaker: Additional rewards :trophy:

Each integration test brings 15+ points for SWAG and entry into the draw for a :point_down: :
-  :computer:  [Razer Blade 16 Laptop](https://www.razer.com/gaming-laptops/Razer-Blade-16/RZ09-0483SEJ3-R3U1)
- :shirt: :bear:  [MindsDB Swag](https://store.covver.io/mindsdb/collections/swag-collection)

:information_source: For more info check out https://mindsdb.com/hacktoberfest/ :point_left: 

**Please note that we are not assigning this type of issue.
Create a PR and link it to this issue.
The first PR that solves this will be accepted** :fireworks:

### PR DESCRIPTION
**Pull request by Daddypastor**
## Description

 Implement the Commits table for a GitHub repository

Fixes #7541 

## Type of change

(Please delete options that are not relevant)

- [x] ⚡ New feature (non-breaking change which adds functionality)
- [x] 📄 This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have appropriately commented on my code, especially in complex areas.
- [x] Necessary documentation updates are either made or tracked in issues.
- [x] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Comment by Daddypastor** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Daddypastor** [comment]
@martyna-mindsdb Yes I've tested it

**Comment by Daddypastor** [comment]
Signed.

**Comment by martyna-mindsdb** [comment]
@Daddypastor 
Please provide screenshots or a short video that presents querying this commits table in the MindsDB editor.

**Comment by Daddypastor** [comment]
Ok, I will do that.

**Comment by Daddypastor** [comment]
@martyna-mindsdb  Please can you guide me querying the commits table in MindsDB editor

**Comment by Daddypastor** [comment]
> @Daddypastor Please provide screenshots or a short video that presents querying this commits table in the MindsDB editor.

Please can you guide me using he mindsDB editor

**Comment by Daddypastor** [comment]
mindsdbcommit
@martyna-mindsdb this is the screenshot of successful querying of the commit table in mindsDB editor

**Comment by Daddypastor** [comment]
https://github.com/mindsdb/mindsdb/assets/68669639/1d3148ea-6df2-4dd7@martyna-mindsdb 9a7c-0c331938825b

@martyna-mindsdb

**Comment by Daddypastor** [comment]
https://github.com/mindsdb/mindsdb/assets/68669639/f48a638e-5d5e-441f-bb15-d867c8179cfe

@martyna-mindsdb this is the short video of the successful querying github commits table in the mindsDB editor

**Review by martyna-mindsdb — APPROVED** [review]

**Comment by Daddypastor** [comment]
wow i did it
Thanks for giving me this chance to work on this
i really appreciate

**Comment by martyna-mindsdb** [comment]
@Daddypastor 
Good work!

**Comment by Daddypastor** [comment]
Yes thank you

Please how can can i recieve my additional rewards ...

**Comment by martyna-mindsdb** [comment]
Each issue gives you a certain number of points which you can use in our SWAG store.

@chandrevdw31 ^

**Comment by Daddypastor** [comment]
How do i access my points given to me on this issue

**Comment by chandrevdw31** [comment]
@Daddypastor we assign your points once you have submitted your merged PR's. At the end of hacktoberfest we gift the accumulative points to you. If you want to know how much points you have,please contact me on Slack

**Comment by Daddypastor** [comment]
Here's my email on slack emmaexcellent030@gmail.com     or you can send me yours to send you a DM

**Comment by martyna-mindsdb** [comment]
@Daddypastor 
You can join our community slack here: https://mindsdb.com/joincommunity

**Comment by Daddypastor** [comment]
ohhh ok

**Pull request merged**
