### PR TITLE
UPDATE and DELETE Query Utilities

### PR DESCRIPTION
**Pull request by MinuraPunchihewa**
## Description

This PR adds the following to make the process of developing App handlers easier:

- UPDATE Query Parser and Executor
- DELETE Query Parser and Executor

To be more precise, it makes parsing and executing SQL queries for App handlers easier.

## Type of change

(Please delete options that are not relevant)

- [X] ⚡ New feature (non-breaking change which adds functionality)
- [X] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [X]   Verification Steps: The new query utilities were used to extend a couple of the existing Shopify tables and it seemed to work without an issue.

## Checklist:

- [X] My code follows the style guidelines(PEP 8) of MindsDB.
- [X] I have appropriately commented on my code, especially in complex areas.
- [ ] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Review by ZoranPandovski — APPROVED** [review]
Looks good, please add this to the handlers contributions guide on docs

**Comment by MinuraPunchihewa** [comment]
Will do, @ZoranPandovski.

**Comment by MinuraPunchihewa** [comment]
@ZoranPandovski Shall we merge this? I will make a new PR for the documentation.

**Comment by Sohlar** [comment]
I implemented my own update_query_utilities for https://github.com/mindsdb/mindsdb/issues/7510. Should I rewrite under the assumption this PR will get merged?

**Comment by ZoranPandovski** [comment]
@Sohlar please make PR and we can decide

**Pull request merged**
