### PR TITLE
Add docker-compose with code auto-reloading

### PR DESCRIPTION
**Pull request by hamishfagg**
## Description

Adds a docker-compose file for easy local development.
Mounts the code dir into the app container, and reloads the app when code changes are made.

**Fixes** #6151

## Type of change

- [x] ⚡ New feature (non-breaking change which adds functionality)

### What is the solution?

(Describe at a high level how the feature was implemented)

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have commented my code, particularly in hard-to-understand areas.

### CODE REVIEW

**Review by ZoranPandovski — APPROVED** [review]

**Comment by ZoranPandovski** [comment]
@hamishfagg Should we move this to docker dir, or change the name so we know it is for dev purposes?

**Comment by tcchawla** [comment]
@hamishfagg  Amazing!

**Comment by hamishfagg** [comment]
@ZoranPandovski my personal preference is to have to have a local dev `docker-compose.yml` in the repo root so that `docker-compose up` is all you need after cloning. The current docker folder seems pretty polluted to me too, but IDK maybe all the other docker-compose files are still being used for other things. Thoughts?

**Comment by ZoranPandovski** [comment]
Ok, let's keep it that way and we can move all of the unused docker-compose file in the docker dir as discussed on slack

**Pull request merged**
