### PR TITLE
Added a Tutorial on PayGrades

### PR DESCRIPTION
**Pull request by dhaneshragu**
Fixes #3230

## Please describe what changes you made, in as much detail as possible
  -
Created a tutorial on How to predict paygrade using MindsDb
mindsdb

### CODE REVIEW

**Comment by dhaneshragu** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   **dhanesh** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by dhaneshragu** [comment]
recheck

**Comment by dhaneshragu** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by dhaneshragu** [comment]
> 
recheck

**Comment by dhaneshragu** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by dhaneshragu** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by dhaneshragu** [comment]
> **CLA Assistant Lite bot:** Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> I have read the CLA Document and I hereby sign the CLA
> 
> **dhanesh** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).You can retrigger this bot by commenting **recheck** in this Pull Request

recheck

**Comment by dhaneshragu** [comment]
Hey @martyna-mindsdb , Why is this not accepting even though I have signed the CLA?

**Review by dhaneshragu — COMMENTED** [review]
I have read the CLA Document and I hereby sign the CLA

**Comment by dhaneshragu** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request closed without merging**
