### PR TITLE
show err msg if ds containt less than 10 rows

### LINKED ISSUE #918: Display warning message if training data contains less then 10 rows
Currently, if the user uses a dataset that has less then 10 rows the bellow error will be shown:

```
  File "/usr/local/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/zoran/MyProjects/mindsdb-examples/mdb/lib/python3.7/site-packages/mindsdb/interfaces/native/predictor_process.py", line 33, in run
    **kwargs
  File "/home/zoran/MyProjects/mindsdb-examples/mdb/lib/python3.7/site-packages/mindsdb_native/libs/controllers/predictor.py", line 302, in learn
    logger=self.log
  File "/home/zoran/MyProjects/mindsdb-examples/mdb/lib/python3.7/site-packages/mindsdb_native/libs/controllers/transaction.py", line 53, in __init__
    self.run()
  File "/home/zoran/MyProjects/mindsdb-examples/mdb/lib/python3.7/site-packages/mindsdb_native/libs/controllers/transaction.py", line 230, in run
    self._run()
  File "/home/zoran/MyProjects/mindsdb-examples/mdb/lib/python3.7/site-packages/mindsdb_native/libs/controllers/transaction.py", line 226, in _run
    raise e
  File "/home/zoran/MyProjects/mindsdb-examples/mdb/lib/python3.7/site-packages/mindsdb_native/libs/controllers/transaction.py", line 210, in _run
    self._call_phase_module(module_name='ModelInterface', mode='train')
  File "/home/zoran/MyProjects/mindsdb-examples/mdb/lib/python3.7/site-packages/mindsdb_native/libs/controllers/transaction.py", line 162, in _call_phase_module
    return module(self.session, self)(**kwargs)
  File "/home/zoran/MyProjects/mindsdb-examples/mdb/lib/python3.7/site-packages/mindsdb_native/libs/phases/base_module.py", line 53, in __call__
    ret = self.run(**kwargs)
  File "/home/zoran/MyProjects/mindsdb-examples/mdb/lib/python3.7/site-packages/mindsdb_native/libs/phases/model_interface/model_interface.py", line 31, in run
    self.transaction.model_backend.train()
  File "/home/zoran/MyProjects/mindsdb-examples/mdb/lib/python3.7/site-packages/mindsdb_native/libs/backends/lightwood.py", line 397, in train
    validation_predictions = self.predict('validate')
  File "/home/zoran/MyProjects/mindsdb-examples/mdb/lib/python3.7/site-packages/mindsdb_native/libs/backends/lightwood.py", line 473, in predict
    predictions = self.predictor.predict(when_data=run_df)
  File "/home/zoran/MyProjects/mindsdb-examples/mdb/lib/python3.7/site-packages/lightwood/api/predictor.py", line 162, in predict
    return self._mixer.predict(when_data_ds)
  File "/home/zoran/MyProjects/mindsdb-examples/mdb/lib/python3.7/site-packages/lightwood/mixers/base_mixer.py", line 70, in predict
    _, _ = when_data_source[0]
  File "/home/zoran/MyProjects/mindsdb-examples/mdb/lib/python3.7/site-packages/lightwood/api/data_source.py", line 195, in __getitem__
    cached_sample = self.transformed_cache[idx]
IndexError: list index out of range
```
Instead, we should return a message before the training start to say something like: `You must have at least 10 rows to train a model`.

### PR DESCRIPTION
**Pull request by StpMax**
Fix #918.
That 'dirty fix' for issue. I cant return messages from PredictorProcess, because it is separate process. To do it, im need some way to notify client about event from server: websockets, serverSideEvents or something else. Since we dont have it yet, i add check of ds rows count above process run.

### CODE REVIEW

**Review by George3d6 — CHANGES_REQUESTED** [review]
This requires creating a datasource each time we make this check, this is a lengthy process and we should avoid doing it as much as possible (hence why we are moving towards lazy intialization of datasources)

Unless there's a good reason we want this (business wise) this type of error doesn't take priority over any other type of error.

So I will say that for now I'd want to reject this change

**Comment by George3d6** [comment]
https://github.com/mindsdb/mindsdb/issues/918 is fixed in mindsdb_native which now send the appropriate error message and that should be enough, @ZoranPandovski any arguments against this?

**Comment by StpMax** [comment]
> #918 is fixed in mindsdb_native which now send the appropriate error message and that should be enough, @ZoranPandovski any arguments against this?

@George3d6  @ZoranPandovski Please, read first comment in PR. mindsdb_native really return exception:
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb/mindsdb/interfaces/native/predictor_process.py", line 34, in run
    **kwargs
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/controllers/predictor.py", line 303, in learn
    self.transaction.run()
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/controllers/transaction.py", line 244, in run
    self._run()
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/controllers/transaction.py", line 240, in _run
    raise e
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/controllers/transaction.py", line 203, in _run
    self._call_phase_module(module_name='DataCleaner')
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/controllers/transaction.py", line 170, in _call_phase_module
    ret = module(self.session, self)(**kwargs)
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/phases/base_module.py", line 53, in __call__
    ret = self.run(**kwargs)
  File "/home/maxs/dev/mdb/venv_new/sources/mindsdb_native/mindsdb_native/libs/phases/data_cleaner/data_cleaner.py", line 86, in run
    MINIMUM_ROWS
Exception: Your data contains very few rows (3). The minimum is 10 rows.
```
But there is no way to show error message in Scout or any db-console. That because 'learning' executing in separate process. For example, for Scout workflow is so:
1. scout send http query 'learn predictor'
2. mindsdb make some checks (ds exists, prediction columns exists and other), return 200 code, and then start new process with learning. 
3. error raised in separate process.
HTTP connection closed on 2 step, error raised on 3. We can not return error to user without websockets, serverSideEvents, longpooling or other thing.

So here two ways:
1. wait websockets.
2. use this dirty fix. Im agree, with big datasets is huge overhead to init DS each time.

**Comment by George3d6** [comment]
But this applies to *any* mindsdb_native learn exception and there's thousands of them, there's no reason (I think) to prioritize this error message specifically.

**Pull request closed without merging**
