### PR TITLE
Added IS NULL & IS NOT NULL to slack_handler.py

### LINKED ISSUE #8773: [Bug]: IS NULL not working for Slack integration
### Short description of current behavior

I am not sure whether this is a feature to add or a bug to report.
When using SQL keywords `IS NULL` and `IS NOT NULL` with a database (e.g., SQLite) MindsDB SQL works fine.
However, trying to do the same with slack_mindsdb integration, it is like the query does not consider these keywords at all. Whether I use `IS NULL` or `IS NOT NULL`, I obtain the same results.
No error is thrown; the query is executed successfully. 

### Video or screenshots

https://github.com/mindsdb/mindsdb/assets/115539886/7de3fad9-316c-4690-b5b6-9271191996de

### Expected behavior

`IS NULL` and `IS NOT NULL` should behave normally, returning different rows based on the presence of null values, also with Slack Database.

### How to reproduce the error

I have two datasources:
- slack
- sqlite
For slack I have the defaut table of channels, with some messages from the same channel in it.
For sqlite, I have a table called `fa-51`, with three columns `id varchar(30), message text, created at varchar`. 
I execute the following queries:

```
-- Context: In both sqlite and slack databases, there are NO Null values.

SELECT sl.client_msg_id FROM mindsdb_slack.channels as sl
WHERE sl.channel = 'fa-51'
AND sl.client_msg_id IS NOT NULL;

SELECT id FROM sqlite_solomon.fa_51
WHERE id IS NOT NULL;
```
 Try to remove the `NOT`, to test my bug.

The second query works well, the first (slack one) yelds the same rows independently from the presence of `NOT`.

### Anything else?

I am not sure whether this is an error on my side or an actual bug. In the second case, it is quite relevant given that it is impossible to perform some fundamental operations. For instance, performing many set operations with `Joins` becomes impossible.

### PR DESCRIPTION
**Pull request by jacopo-minniti**
## Description

slack_handler.py now handles the SQL keywords _IS NULL_ and _IS NOT NULL_. 

Fixes #8773 

## Type of change

- [x] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] ⚡ New feature (non-breaking change which adds functionality)

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have appropriately commented on my code, especially in complex areas.
- [x] Necessary documentation updates are either made or tracked in issues.
- [x] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb/blob/staging/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   **Jacopo Minniti** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by jacopo-minniti** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by jacopo-minniti** [comment]
recheck

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
It looks like you were logged in locally on git with another user that the one you have on GitHub. Can you double check?

**Pull request closed without merging**
