### PR TITLE
[DOC] Improved wording and clarity in documentation.

### PR DESCRIPTION
**Pull request by Smoothengineer**
## Description

- Updated phrasing to improve flow and consistency across sections
- Adjusted singular/plural forms for consistency

Fixes #9844

## Type of change

(Please delete options that are not relevant)

- [X] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [X]   Test Location: You can test the updated documentation by navigating to the README.md file in the root directory of the project.
 - [X]   Verification Steps: 
 - Navigate to the project repository and open the updated README.md file.
 - Review the grammar, and clarity of the sections where changes were made.
 - Ensure no sections are missing or incorrectly formatted.
 - Optionally, check the rendered view (if applicable, like on GitHub) to verify proper formatting.

## Additional Media:

- [ ] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have appropriately commented on my code, especially in complex areas.
- [ ] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb/blob/main/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by Smoothengineer** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by martyna-mindsdb** [comment]
@Smoothengineer 
If you want to contribute to MindsDB, please check the issues labeled as `help-wanted` or `hacktoberfest`.

**Pull request closed without merging**
