### PR TITLE
add support openGauss

### PR DESCRIPTION
**Pull request by Nelson-He**
Fixes #

Add support openGauss.
openGauss is a very famous enterprise database in china. There are lots of people use it in production environments.

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   **Nelson-He** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by Nelson-He** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Nelson-He** [comment]
recheck

**Comment by ZoranPandovski** [comment]
recheck

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by Nelson-He** [comment]
I will reconfigure my git email address and create a new PR so that the CLA can be signed. This PR is closed.

**Comment by ZoranPandovski** [comment]
No worries, I think you can just check the local `git user` you are logged in with and just add it as additional email in GItHub.

**Comment by Nelson-He** [comment]
> No worries, I think you can just check the local `git user` you are logged in with, and just add it as additional email in GItHub.

Thanks for you reminding，I fixed it just as you said. And I reopen this pr for your check.
Thanks again

**Comment by Nelson-He** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Nelson-He** [comment]
recheck

**Comment by ZoranPandovski** [comment]
recheckcla

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
