### PR TITLE
added mysql.mdx file to the pages of Data-integration

### PR DESCRIPTION
**Pull request by piyushyadav1617**
## Added mysql.mdx in DOCS/mint.json under the Data Integrations pages  #(5254)

**#(5254)** 

## Documentation change

- [x] 📄 This change requires a documentation update

## Checklist:
- [x] I have updated the documentation, or created issues to update them.

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@piyushyadav1617 
Please leave a comment on an issue you want to solve and make sure we assign you this issue before you create a PR.

Also, please link the issue in the PR description https://github.com/mindsdb/mindsdb/issues/5254

Before we merge your PR, please sign our CLA following the instructions above.

**Comment by piyushyadav1617** [comment]
@martyna-mindsdb 
understood! just one question : do I need to create another pull request to sign the CLA?

**Comment by piyushyadav1617** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
