### PR TITLE
updated docs to match gui until letter 'c'

### PR DESCRIPTION
**Pull request by srini047**
## Description
Made sure that there is consistency between the GUI and the documentation. I have made the changes until data integration until `C`. If this is fine then I would like to proceed with the entire documentation update.

**Fixes** #4072 and other

## Type of change

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] 📄 This change requires a documentation update

### What is the solution?

- Made use of the current template of each data source from the editor and updated the docs for the respective data source
- Also removed the white spaces between the empty string as it is more hectic as a user to delete the space every time and then write afterward.

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation, or created issues to update them.
- [ ] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [ ] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by srini047** [comment]
I have read the CLA Document and I hereby sign the CLA
=

**Comment by srini047** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request closed without merging**
