### PR TITLE
Added tutorial to predict TYE

### LINKED ISSUE #3285: [Tutorial] Predict Turbine Yield Energy(Gas industry)
### Task description

Write tutorial on predicting Turbine Energy Yield in the Gas industry.

Use the dataset `pp_gas_emission.zip` https://archive.ics.uci.edu/ml/datasets/Gas+Turbine+CO+and+NOx+Emission+Data+Set

**Tutorial should include:**

- Very short description on how MindsDB can assist with predicting Turbine yield energy
- Either connecting database to MindsDB or uploading dataset as a file.
- CREATE PREDICTOR Syntax.
- SELECT syntax(make prediction). 
- Must be specified that this is a regression machine learning model.

## :loudspeaker: Additional rewards :trophy:

Each tutorial brings :five: points and entry into the draw for a  :point_down: :

-  :computer:  [Razer Blade 15 Laptop](https://www.razer.com/hard-bundles/Razer-Blade-15-Bundle-V5-Essential/RZHB-220912-11)
- :headphones:  10 cool audio gadgets 
- :shirt: :bear: MindsDB Swag
:information_source: For more info check out https://mindsdb.com/hacktoberfest/ :point_left: 

To participate in the prize draw, you need to complete this form with your contact details and links to all your merged PRs or no-code deliverables. Please submit the form once with all your contributions listed.

### PR DESCRIPTION
**Pull request by dhaneshragu**
Fixes #3285

### CODE REVIEW

**Comment by dhaneshragu** [comment]
Hey, Can you please check this and accept this PR? @ZoranPandovski

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   **dhanesh** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by dhaneshragu** [comment]
recheckcla

**Comment by dhaneshragu** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by dhaneshragu** [comment]
recheck

**Comment by ZoranPandovski** [comment]
recheckcla

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
