### PR TITLE
4557 added doc changes for connecting mongo compass

### PR DESCRIPTION
**Pull request by sijilo**
## Description
Added changes to include tutorials to connect mongo compass with minds db

modified:
 - docs/connect/mongo-compass.mdx

FIXES:
   #4557

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   **sijilo** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@sijilo 
Please use your GitHub account and sign our CLA here. Then we can merge your PR.
Thanks.

**Comment by martyna-mindsdb** [comment]
Thanks, @sijilo. We'll merge your [previous PR](https://github.com/mindsdb/mindsdb/pull/4569).
 Please note that you can solve only one `first-timers-only` issue. Please have a look at other issues labeled as `help wanted` or `good first issue`.

**Pull request closed without merging**
