### PR TITLE
Add clickhouse to mint.json

### PR DESCRIPTION
**Pull request by minnayu**
## Description

Add `clickhouse.mdx` to mint.json

**Fixes** #5123 

## Type of change

- [ ] 📄 This change requires a documentation update

### What is the solution?

Added the file to the navigation section

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have updated the documentation, or created issues to update them.

### CODE REVIEW

**Comment by minnayu** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by minnayu** [comment]
recheck

**Comment by martyna-mindsdb** [comment]
recheckcla

**Pull request merged**
