### PR TITLE
[Shopify] Implement DELETE for the Customers table #7656

### LINKED ISSUE #7656: [Shopify] Implement DELETE for the Customers table
MindsDB integrates with Shopify, so you can fetch data from your online store and use it to make relevant predictions and forecasts with MindsDB.

## Resources

Familiarize yourself with the existing Shopify integration: https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/shopify_handler

## Steps to Follow

Currently, the Shopify integration with MindsDB implements SELECT from the Customers table.

The task is to extend [this implementation](https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/shopify_handler) to include the DELETE command to delete data from the Customers table.

## :loudspeaker: Additional rewards :trophy:

Each integration extension brings 15+ points for SWAG and entry into the draw for a :point_down: :
-  :computer:  [Razer Blade 16 Laptop](https://www.razer.com/gaming-laptops/Razer-Blade-16/RZ09-0483SEJ3-R3U1)
- :shirt: :bear:  [MindsDB Swag](https://store.covver.io/mindsdb/collections/swag-collection)

:information_source: For more info check out https://mindsdb.com/hacktoberfest/ :point_left:

### PR DESCRIPTION
**Pull request by rabroldan**
## Description

Implemeted a ```DELETE``` for the customers table in the shopify_table module

Fixes #7656 

## Type of change

(Please delete options that are not relevant)

- [x] ⚡ New feature (non-breaking change which adds functionality)

## Verification Process

To ensure the changes are working as expected:

 - [x]   Test Location: Specify the URL or path for testing.
 - [x]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have appropriately commented on my code, especially in complex areas.

### CODE REVIEW

**Comment by rabroldan** [comment]
hi @martyna-mindsdb I implemented a Delete function for the customers table , kindly please review. thank you

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@rabroldan 
Please sign our CLA as mentioned above.

Also, please provide screenshots or a short video that shows the feature you implemented works as expected.

**Comment by rabroldan** [comment]
---
I have read the CLA Document and I hereby sign the CLA
---
i apologize I am unable to provide a scrreenshot at the moment as I am having trouble with my computer. if ever please let me know if it not working then I might need to drop the issue as I am unable to provide proper documentation.

Thank you for your understanding

**Comment by martyna-mindsdb** [comment]
@rabroldan 
To sign our CLA, please leave a comment containing only this line: I have read the CLA Document and I hereby sign the CLA

**Comment by rabroldan** [comment]
---
I have read the CLA Document and I hereby sign the CLA
---

**Comment by martyna-mindsdb** [comment]
recheckcla

**Review by MinuraPunchihewa — CHANGES_REQUESTED** [review]
Hey @rabroldan,
Please provide a screenshot or a video of this running, i.e. deleting a customer. I remember attempting to do this and running across some issues.

**Pull request closed without merging**
