### PR TITLE
fix_link

### PR DESCRIPTION
**Pull request by Mishrasubha**
## Description

Changes the link in README.md. 

**Fixes** #4947 

## Type of change

(Please delete options that are not relevant)

- [ ] 📄 This change requires a documentation update

### What is the solution?

(Describe at a high level how the feature was implemented)

## Checklist:

- [X] My code follows the style guidelines(PEP 8) of MindsDB.
- [X] I have commented my code, particularly in hard-to-understand areas.
- [X] I have updated the documentation, or created issues to update them.
- [X] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [X] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   **Subhashree Mishra** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@Mishrasubha 
Before we can merge your PR, please sign our CLA following the instructions above. Thanks.

**Comment by Mishrasubha** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Mishrasubha** [comment]
recheck

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by martyna-mindsdb** [comment]
@Mishrasubha 
Please add the email address that you use to your GitHub account. After that, you can sign CLA. Thanks.

**Comment by Mishrasubha** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Mishrasubha** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Mishrasubha** [comment]
recheckcla

**Comment by Mishrasubha** [comment]
@martyna-mindsdb I did add the email to my commit, it's still not working?

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
@Mishrasubha You need to add the same email you are locally logged in to your GitHub  account

**Comment by Mishrasubha** [comment]
@ZoranPandovski it's the same, I checked with  `git config --global user.email` and in my settings, both emails are same

**Comment by ZoranPandovski** [comment]
recheckcla

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
