### PR TITLE
Added Improved Logos for Integrations

### PR DESCRIPTION
**Pull request by MinuraPunchihewa**
## Description

This PR updates the existing logs for integrations that already have one and adds new logs for integrations that don't (including ML Engines).

## Type of change

- [X] ⚡ New feature (non-breaking change which adds functionality)

## Verification Process

To ensure the changes are working as expected:

 - [X]   Test Location: Specify the URL or path for testing - N/A
 - [X]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality - N/A

## Checklist:

- [X] My code follows the style guidelines(PEP 8) of MindsDB - N/A
- [X] I have appropriately commented on my code, especially in complex areas - N/A
- [X] Necessary documentation updates are either made or tracked in issues - N/A
- [X] Relevant unit and integration tests are updated or added - N/A

### CODE REVIEW

**Review by Hazemmahdyx — APPROVED** [review]
You've added icons for some integrations without the 40px frame, but I think it's okay, and we can handle it on the frontend side

like 
altibase_handler/icon.svg
autokeras_handler/icon.svg
/bigquery_handler/icon.svg
mindsdb/integrations/handlers/chromadb_handler/icon.png
mindsdb/integrations/handlers/d0lt_handler/icon.svg
mindsdb/integrations/handlers/gmail_handler/icon.svg

**Comment by MinuraPunchihewa** [comment]
@Hazemmahdyx How can I fix this? By adding the `height` and `width` parameters?

**Comment by MinuraPunchihewa** [comment]
@ZoranPandovski The only handlers that don't have logos now are Anomaly Detection, RAG and BYOM. We were thinking of adding the MindsDB logo for these  (like we did with Lightwood) because they were essentially developed by us. What do you think?
CC: @Hazemmahdyx

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
Looks good. The only concern I have is that this PR affects all integrations and since we don't have everything fully covered with tests will be hard to spot any bugs. Let's quickly chat on slack how to move forward with this

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
