### PR TITLE
Test Result for MSSql Server Handler Manually!

### PR DESCRIPTION
**Pull request by Bhardwaj-Himanshu**
## Description
This includes test result from the issue as mentioned in #6919  

## Type of change

(Please delete options that are not relevant)

- [x]  Test case

### What is the solution?

Was asked to create and check a connection to MS Sql database, which was done following the test instructions in documentation

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have updated the documentation, or created issues to update them.
- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
Hi @Bhardwaj-Himanshu 
I see that you are connecting your local database. Please make a tunnel so that your local database is discoverable by MindsDB. Here is how to do that: https://docs.mindsdb.com/sql/create/database#making-your-local-database-available-to-mindsdb

**Comment by tcchawla** [comment]
Hey @Bhardwaj-Himanshu , were you able to setup the Microsoft SQL Server on your local machine?
if yes, then do `ngrok tunneling`, if not then first setup the SQL server on your local machine first.

**Comment by Bhardwaj-Himanshu** [comment]
Thanks for the suggestions @martyna-mindsdb @tcchawla, they are much appreciated!

So after following the documentation and successfully creating a tunnel through **ngrok** the error code still persists and is still the same!
Below are a few images attached for it-
Selection_014
Selection_013


Also, @tcchawla you were also recommending me to install a MS SQl server? I had a doubt regarding it!
Like installation is smooth, but do I need to tinker some settings around.
(**Considering my device does not have a MS SQL server installed on it, at the time of launching instances and taking images**)

**Comment by martyna-mindsdb** [comment]
@Bhardwaj-Himanshu 
Please follow the steps below to see where the error is initiated:

1. Install MS SQL Server locally (if you haven't done that before).
2. Try connecting your local MS SQL Server database to other SQL clients, such as DBeaver.
3. If step 2 was executed successfully, create an ngrok tunnel for your local database (as you did before).
4. Use this tunnel to connect your database to MindsDB.

Please let us know at which step you encounter errors.

**Comment by tcchawla** [comment]
Hey @Bhardwaj-Himanshu, please follow the step mentioned by @martyna-mindsdb. Let us know if you faced any problems.

**Pull request closed without merging**
