### PR TITLE
Gemini Handler 

### PR DESCRIPTION
**Pull request by parthiv11**
## Description

Please include a summary of the change and the issue it solves. 

Fixes #issue_number

## Type of change

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [x] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [x] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have appropriately commented on my code, especially in complex areas.
- [ ] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Comment by dusvyat** [comment]
@parthiv11 a handler was recently created for this fyi. See https://github.com/mindsdb/mindsdb/pull/8512

**Comment by parthiv11** [comment]
I searched for it but didn't find it that is why I thought to make it.

**Comment by parthiv11** [comment]
I seen #8512 , it has only one mode, I have added few more modes.

should I add it to exiting, or this will work. 

what you say? @dusvyat

**Comment by dusvyat** [comment]
@parthiv11 If not an issue, would prefer if you made changes on existing handler for gemini

**Pull request closed without merging**
