### PR TITLE
GROUP BY must go before ORDER BY Update neuralforecast.mdx 

### PR DESCRIPTION
**Pull request by chuangyeshuo**
GROUP BY must go before ORDER BY

## Description

Please include a summary of the change and the issue it solves. 

Fixes #issue_number

## Type of change

(Please delete options that are not relevant)

- [x] 🐛 Bug fix (non-breaking change which fixes an issue)
- [x] ⚡ New feature (non-breaking change which adds functionality)
- [x] 📢 Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [x] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [x]   Test Location: Specify the URL or path for testing.
 - [x]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [x] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have appropriately commented on my code, especially in complex areas.
- [x] Necessary documentation updates are either made or tracked in issues.
- [x] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Comment by mindsdbadmin** [comment]
<br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb/blob/main/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request. </sub><sub>Posted by the **CLA Assistant Lite bot**.</sub>

**Comment by chuangyeshuo** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by chuangyeshuo** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by martyna-mindsdb** [comment]
@chuangyeshuo 
Considering the order of execution of standard SQL queries, the ORDER BY goes after the GROUP BY.
However, in this case, either of the ways allows you to create a model.

Can you provide more context about this change that you suggest?

**Comment by mohamedmeqlad99** [comment]
the correct SQL writing order is 
Getting Data (FROM/JOIN)
Row Filter (WHERE)
Grouping (GROUP BY)
Group Filter (HAVING)
Return Expression (SELECT)
Order & Paging (ORDER BY & LIMIT/OFFSET)
16‏/09‏/2024

**Comment by chuangyeshuo** [comment]
> @chuangyeshuo Considering the order of execution of standard SQL queries, the ORDER BY goes after the GROUP BY. However, in this case, either of the ways allows you to create a model.
> 
> Can you provide more context about this change that you suggest?
I think this is more well, thanks: 
the correct SQL writing order is
(SELECT)
Getting Data (FROM/JOIN)
Row Filter (WHERE)
Grouping (GROUP BY)
Group Filter (HAVING)
Order & Paging (ORDER BY & LIMIT/OFFSET)

**Comment by martyna-mindsdb** [comment]
@chuangyeshuo 
Note that all three time-series models use this construct - [Neuralforecast](https://docs.mindsdb.com/integrations/ai-engines/neuralforecast), [Statsforecast](https://docs.mindsdb.com/integrations/ai-engines/statsforecast), and [TimeGPT](https://docs.mindsdb.com/integrations/ai-engines/timegpt).

If you want to have this PR merged, please do the following:

1. Test all three models within MindsDB.
2. Update doc pages of all three models to be consistent.

**Comment by chuangyeshuo** [comment]
> @chuangyeshuo Note that all three time-series models use this construct - [Neuralforecast](https://docs.mindsdb.com/integrations/ai-engines/neuralforecast), [Statsforecast](https://docs.mindsdb.com/integrations/ai-engines/statsforecast), and [TimeGPT](https://docs.mindsdb.com/integrations/ai-engines/timegpt).
> 
> If you want to have this PR merged, please do the following:
> 
> 1. Test all three models within MindsDB, and provide screenshots of successful tests.
> 2. Update the doc pages of all three models to be consistent.

Neuralforecast: https://github.com/mindsdb/mindsdb/pull/10119
TEST: 
TEST_NeuralForecast

Statsforecast: https://github.com/mindsdb/mindsdb/pull/10118
TEST: 
TEST_StatsForecast

TimeGPT: https://github.com/mindsdb/mindsdb/pull/10117
TEST: 
TEST_TimeGPT

**Comment by martyna-mindsdb** [comment]
@chuangyeshuo 
Please make all the docs updates in this PR.

**Comment by chuangyeshuo** [comment]
> @chuangyeshuo Please make all the docs updates in this PR.

all is ok 🚀

**Review by martyna-mindsdb — APPROVED** [review]

**Pull request merged**
