### PR TITLE
readme file has been updated

### PR DESCRIPTION
**Pull request by seenusnehil**
## Description

Removal of additional apostrophes

**Fixes** #(issue)

## Type of change

(Please delete options that are not relevant)

- [x] 📄 This change requires a documentation update

### What is the solution?

It was just the line 27, that I needed to delete some apostrophes to make the documentation look clean a bit.

## Checklist:

- [x] I have updated the documentation, or created issues to update them.

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by seenusnehil** [comment]
Let me know, if I did everything right!?

**Review by ZoranPandovski — APPROVED** [review]

**Comment by ZoranPandovski** [comment]
Please sign the CLA

**Comment by seenusnehil** [comment]
I need to sign the CLA here, right?

**Comment by seenusnehil** [comment]
I have read the CLA Document and I hereby sign the CLA

**Pull request merged**
