### PR TITLE
Bumped `scikit-learn` to 1.5.0

### PR DESCRIPTION
**Pull request by MinuraPunchihewa**
## Description

This PR bumps the version of `scikit-learn` to 1.5.0 to resolve the issues listed below: 

Fixes https://github.com/mindsdb/mindsdb/issues/9877
Fixes https://linear.app/mindsdb/issue/BE-545/scikit-learn-sensitive-data-leakage-vulnerability

## Type of change

- [X] 🐛 Bug fix (non-breaking change which fixes an issue)

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [ ] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [X] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have appropriately commented on my code, especially in complex areas - N/A
- [ ] Necessary documentation updates are either made or tracked in issues - N/A
- [ ] Relevant unit and integration tests are updated or added - N/A

### CODE REVIEW

**Comment by MinuraPunchihewa** [comment]
@ZoranPandovski For this to be compatible with `lightwood`, we will need update the `sktime` dependency there to be above 0.3.0. 

Further, I noticed that lightwood has the same `scikit-learn` vulnerability mentioned above, so I think it is worth making that bump as well?

What do you think; shall I make these changes?

**Comment by MinuraPunchihewa** [comment]
> @ZoranPandovski For this to be compatible with `lightwood`, we will need update the `sktime` dependency there to be above 0.3.0.
> 
> Further, I noticed that lightwood has the same `scikit-learn` vulnerability mentioned above, so I think it is worth making that bump as well?
> 
> What do you think; shall I make these changes?

@ZoranPandovski I have raised 2 PR in `lightwood` that will have to be merged in order to move forward with this:
https://github.com/mindsdb/lightwood/pull/1239
https://github.com/mindsdb/lightwood/pull/1238

**Comment by ZoranPandovski** [comment]
Perfect, let's fix Lightwood first

**Comment by ZoranPandovski** [comment]
@MinuraPunchihewa I guess we will need a new Lightwood release

**Comment by MinuraPunchihewa** [comment]
> @MinuraPunchihewa I guess we will need a new Lightwood release

Oh, yes. Shall I make the release, Zoran?
Here is the first PR: https://github.com/mindsdb/lightwood/pull/1240

**Comment by MinuraPunchihewa** [comment]
@ZoranPandovski Looks like this is ready with the new release of `ligthtwood`. I needed to bump the version used for the Lightwood handler.

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
