### PR TITLE
updating the href value

### PR DESCRIPTION
**Pull request by Debajyati**
## Description

As a first time contributor on this project I updated the `href` value in the html tag `<a href="https://docs.mindsdb.com/data-integrations/all-data-integrations#cloud-spanner">Cloud Spanner Badge</a>` according to the instructions given, at the section titled `## Database Integrations` in the README file .

**Fixes** #(issue)

## Type of change

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)

### What is the solution?

I opened the README.md file and after finding the section titled`## Database Integrations` , just simply changed `href` value to [https://docs.mindsdb.com/data-integrations/cloud-spanner](url) . 

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by martyna-mindsdb** [comment]
@Debajyati 
Please remember to link the issue in the PR description like this: https://github.com/mindsdb/mindsdb/issues/5967

Before we can merge your PR, please sign our CLA by leaving a comment here: I have read the CLA Document and I hereby sign the CLA

**Comment by Debajyati** [comment]
@martyna-mindsdb  #5967 
I have read the CLA Document and I hereby sign the CLA

**Comment by martyna-mindsdb** [comment]
@Debajyati 
In order to trigger the CLA bot, could you please leave a comment that includes only the below line?

I have read the CLA Document and I hereby sign the CLA

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by martyna-mindsdb** [comment]
recheck

**Comment by Debajyati** [comment]
please merge my pr !

**Comment by Debajyati** [comment]
recheckcla

**Comment by martyna-mindsdb** [comment]
@Debajyati 
Please ensure that the GitHub username that you use locally is the same as the one you used to create this PR.
Here is a useful link: https://docs.github.com/en/get-started/getting-started-with-git/setting-your-username-in-git

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by ZoranPandovski** [comment]
recheckcla

**Pull request merged**
