### PR TITLE
fix broken links  in mindsdb-docs 

### PR DESCRIPTION
**Pull request by saiyerniakhil**
Fixes #

fix broken links for Docker, PyPI and mindsdb-cloud in the following pages -

README files
and
https://docs.mindsdb.com/sql/tutorials/bitcoin-forecasting/
https://docs.mindsdb.com/sql/tutorials/crop-prediction/
https://docs.mindsdb.com/sql/tutorials/heart-disease/
https://docs.mindsdb.com/sql/tutorials/mushrooms/
https://docs.mindsdb.com/sql/tutorials/mindsdb-superset-snowflake/

### CODE REVIEW

**Comment by saiyerniakhil** [comment]
fixes issue https://github.com/mindsdb/mindsdb/issues/2595

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   ***I have read the CLA Document and I hereby sign the CLA***
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by saiyerniakhil** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by ZoranPandovski — APPROVED** [review]
Thanks

**Pull request merged**
