### PR TITLE
added delete table query for MediaWiki

### LINKED ISSUE #7947: [MediaWiki] Implement DELETE for the Pages table
MindsDB integrates with MediaWiki, so you can fetch data from MediaWiki and use it to train models or make predictions with MindsDB.

## Resources

Familiarize yourself with the existing MediaWiki integration: https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/mediawiki_handler

## Steps to Follow

Currently, the MediaWiki integration with MindsDB implements SELECT from the Pages table.

The task is to extend [this implementation](https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/mediawiki_handler) to include the DELETE command to delete data from the Pages table.

## :loudspeaker: Additional rewards :trophy:

Each integration test brings 15+ points for SWAG and entry into the draw for a :point_down: :
-  :computer:  [Razer Blade 16 Laptop](https://www.razer.com/gaming-laptops/Razer-Blade-16/RZ09-0483SEJ3-R3U1)
- :shirt: :bear:  [MindsDB Swag](https://store.covver.io/mindsdb/collections/swag-collection)

:information_source: For more info check out https://mindsdb.com/hacktoberfest/ :point_left:

### PR DESCRIPTION
**Pull request by SrijanSahaySrivastava**
for issue #7947

## Description

The change adds a delete function to the PagesTable class in mediawiki_tables.py. This function takes in a DELETE query and deletes the corresponding pages from the MediaWiki API. The function first parses the query to extract the conditions specified in the WHERE clause, and then uses these conditions to search for the pages to delete. If the query specifies a title condition, the function uses the search method of the MediaWiki API to find all pages with the specified title. If the query specifies a pageid condition, the function uses the page method of the MediaWiki API to find the page with the specified ID. Once the pages to delete have been identified, the function calls the delete method of each page object to delete it from the MediaWiki API. If the query does not specify any conditions, the function raises a ValueError.

Fixes #7947

### CODE REVIEW

**Comment by SrijanSahaySrivastava** [comment]
@martyna-mindsdb please check this. I've added a few changes

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by SrijanSahaySrivastava** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by martyna-mindsdb** [comment]
@SrijanSahaySrivastava 
Please follow the standard guidelines.

In the future, comment on an issue to get assigned - only after that you can create a PR.

**Pull request closed without merging**
