### PR TITLE
Improvements in the documentation

### PR DESCRIPTION
**Pull request by mariorodeghiero**
## Add

- CONTRIBUTING.md
- CHANGELOG.md

## Edit

- Readme.md

  - Badges
  - Add contents
  - Item alignment
  - Contributing
  - license
  - Report issue

### CODE REVIEW

**Comment by torrmal** [comment]
@mariorodeghiero, I was waiting until the v1.0 release, but if you can make this pull request to the v.1.0 branch,  I can merge it there.

**Comment by mariorodeghiero** [comment]
@torrmal Right! 
I'll send it to V. 1.0

**Comment by mariorodeghiero** [comment]
@keitaroinc Removed the badges. After accepting the PR I continue the translation and improvements.

**Comment by George3d6** [comment]
Currently there's some conflicts and v.1.0 has been merged into masters anyway, so no further merges into that.

This should have been reviewed sooner.

Since the README and docs changed a lot due to v.1.0 changes, those alterations are now mostly outdate (the one in this branch that is).

Changelog won't be added, as it is too much work to keep updated and the issues/PRs/branches/releases, in combination, serve all those purposes and more (especially the releases, which we can on using).

Adding the CONTRIBUTING.md might still be a good idea, so if @torrmal wants to, either create a new PR to master with that file, or we can manually merge just that file from your branch.

**Pull request closed without merging**
