### PR TITLE
add Refunds Table to Stripe 

### LINKED ISSUE #7764: [Stripe] Implement the Refunds table
### Short description of current behavior

MindsDB integrates with Stripe, so you can access Stripe data and make relevant predictions with MindsDB.

## Resources

Familiarize yourself with the existing Stripe integration: https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/stripe_handler

## Steps to Follow

Currently, the Stripe integration with MindsDB accesses the comments table.

The task is to extend [this implementation](https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/stripe_handler) to include the Refunds table.

## :loudspeaker: Additional rewards :trophy:

Each integration extension issue brings 15+ points for SWAG and entry into the draw for a :point_down: :
-  :computer:  [Razer Blade 16 Laptop](https://www.razer.com/gaming-laptops/Razer-Blade-16/RZ09-0483SEJ3-R3U1)
- :shirt: :bear:  [MindsDB Swag](https://store.covver.io/mindsdb/collections/swag-collection)

:information_source: For more info check out https://mindsdb.com/hacktoberfest/ :point_left: 

**This issue is for first-time contributors only**

### Video or screenshots

_No response_

### Expected behavior

_No response_

### How to reproduce the error

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Tanmai2002**
## Description

I have created Refund Table and Registered the Table with stripe handler. I have also updated Documentation accordingly

Fixes #7764 

## Type of change

(Please delete options that are not relevant)

- [ X] 🐛 Bug fix (non-breaking change which fixes an issue)

I have created the tables by following the initial Steps, Stripe documentation for python SDK

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@Tanmai2002 
Please sign our CLA as above.

Also, please provide a screenshot or a short video showing how you can query this table.

**Comment by Tanmai2002** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Tanmai2002** [comment]
image
I created db using stripe as engine and then run the query for one of my test stripe accounts where I had one refund transaction

**Comment by Tanmai2002** [comment]
@martyna-mindsdb  Kindly Check

**Comment by martyna-mindsdb** [comment]
Thanks @Tanmai2002 

Please add a sample query to the README file.

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
