### PR TITLE
Create a regression tutorial using MongoDB and MindsDB

### PR DESCRIPTION
**Pull request by Ayaan49**
## Description

 Created a step by step regression tutorial using MongoDB and MindsDB.

**Fixes** #4859

## Type of change

- [x] 📄 This change requires a documentation update

### What is the solution?

Created a step by step regression tutorial using MongoDB and MindsDB with an interesting search case.

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation, or created issues to update them.

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
@Ayaan49 
Please add the output of the commands you run.

For example, when you make predictions, add the output of what the model predicts.

**Comment by Ayaan49** [comment]
@martyna-mindsdb Done with the changes.

**Comment by Ayaan49** [comment]
Hey @martyna-mindsdb , is everything ok with my PR ? Please review it soon.

**Comment by martyna-mindsdb** [comment]
Hi @Ayaan49 
This tutorial is intended to use MQL. Please use Mongo Compass/Shell and MQL to solve it. You can find examples in MindsDB docs.

**Comment by Ayaan49** [comment]
I made the changes again. Is it ok now? @martyna-mindsdb

**Comment by martyna-mindsdb** [comment]
@Ayaan49 
No. You are not using MQL. Example: https://docs.mindsdb.com/nlp/sentiment-analysis-inside-mongodb-with-openai

**Comment by martyna-mindsdb** [comment]
@Ayaan49 
Please let us know if you are still working on it.

**Comment by Ayaan49** [comment]
@martyna-mindsdb Hey, looks like I am unable to do it correctly. Please unassign this from me.

**Comment by martyna-mindsdb** [comment]
@Ayaan49 
Here are some resources that could help you out if you decide to finish it:

You follow the right steps in your tutorial, that is, 1) connecting data, 2) creating/training a predictor, and 3) making predictions.
The idea is to use MQL statements and execute them from Mongo Shell or Mongo Compass.

Here are examples of regression tutorials using MongoDB and MindsDB: https://docs.mindsdb.com/using-mongo-api/regression

And here you can find MQL syntax: https://docs.mindsdb.com/mongo/collection-structure

**Comment by Ayaan49** [comment]
Ok thank you. Please give me some time to work on it. I will do it as soon
as possible.

**Comment by Ayaan49** [comment]
I have wrote the tutorial following your given steps and by executing MQL statements in the Mongo Shell or Mongo Compass. Please review it.

**Comment by martyna-mindsdb** [comment]
@Ayaan49 
Could you let me know if you got the output for each command? Many of them do not exist in MindsDB's Mongo API.

Please see how to use Mongo API in our docs and include the output that you get in the console.
Below are the sections to be included in this example:

1. Connect a database. Here is how to connect a database: https://docs.mindsdb.com/mongo/database
2. Create and train a predictor. Here is how to create a predictor: https://docs.mindsdb.com/mongo/insert
3. Make predictions. Here is how to make predictions: https://docs.mindsdb.com/mongo/find#example

**Comment by ZoranPandovski** [comment]
Closing this for now. @Ayaan49 Please make sure you learn more about MindsDB and then update the branch. If you need any help, feel free to aks questions on our Slack :raised_hands:

**Pull request closed without merging**
