### PR TITLE
[Hacktoberfest][fix] Resolves 'dict' object has no attribute 'type' in ElasticSearch

### LINKED ISSUE #10056: [Bug]: [elasticsearch/elasticsearch_datasource]: 'dict' object has no attribute 'type'
### Short description of current behavior

While running the job to sync data from the Elasticsearch data source to the Knowledge Base, I encountered the following error:
`ERROR    mindsdb.interfaces.jobs.jobs_controller: [elasticsearch/elasticsearch_datasource]: 'dict' object has no attribute 'type'`

Follow up: #10046

### Video or screenshots

image

### Expected behavior

_No response_

### How to reproduce the error

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by HahaBill**
## Description

It solves the error when running the job to sync data from the Elasticsearch data source to the Knowledge Base: 
```bash
ERROR    mindsdb.interfaces.jobs.jobs_controller: [elasticsearch/elasticsearch_datasource]: 'dict' object has no attribute 'type'
```

The root cause was the usage of the LAST keyword, which returned the dictionary instead of the data frame, causing the error mentioned above.

The fix follows this behaviour in mindsdb documentation (LAST keyword): https://docs.mindsdb.com/mindsdb_sql/sql/create/jobs#last

Fixes #10056 

## Type of change

- [x] 🐛 Bug fix (non-breaking change which fixes an issue)

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [x]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality: Syncing data from ElasticSearch datasource to knowledge base - https://docs.mindsdb.com/mindsdb_sql/agents/knowledge-bases

## Additional Media:

- [x] I have attached a brief loom video or screenshots showcasing the new functionality or change.

https://github.com/user-attachments/assets/f253492d-b430-4ac4-8019-84c4f7f0d91b

Screenshot 2024-11-09 at 23 12 52

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have appropriately commented on my code, especially in complex areas.
- [x] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Comment by HahaBill** [comment]
I run `black`, that is why it refactored some of the code.

**Comment by ZoranPandovski** [comment]
@HahaBill I am not sure what is the fix, can you please provide more info? I just see the code formated with black?

**Comment by HahaBill** [comment]
> @HahaBill I am not sure what is the fix, can you please provide more info? I just see the code formated with black?

@ZoranPandovski Alright, will do! 

But before that, can you see the video that I attached in the description? I attached 2 media: 1 video and 1 screenshot (code formatted in black as you mentioned). The screenshot formatted in black is just a log from my terminal to show that you no longer see the error.

**Comment by HahaBill** [comment]
The PR basically fixes the error: `ERROR    mindsdb.interfaces.jobs.jobs_controller: [elasticsearch/elasticsearch_datasource]: 'dict' object has no attribute 'type'`. The root cause was the usage of `LAST` keyword. 

When there are no newly inserted records/data, then it caused the `'dict' object has no attribute type` error. It should have returned an empty dataframe filled with `null`, which should be an expected behaviour with using `LAST` keyword **[1]** when there are no new inserted data from data sources. 

I hope it is clearer now, let me know if I should elaborate more.

References
[1] https://docs.mindsdb.com/mindsdb_sql/sql/create/jobs#last

**Comment by HahaBill** [comment]
Also before the fix, I tried to add a new record to ElasticSearch and use `LAST` keyword to fetch the new data/records and display it in MindsDB to see whether there are some more underlying issues with `LAST` keyword rather than the type error. Fortunately, it worked.

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
