### PR TITLE
Connect error in elasticsearch

### LINKED ISSUE #7828: [Bug]:  Connection error while using elastic search
### Short description of current behavior

newelastic

### Video or screenshots

_No response_

### Expected behavior

_No response_

### How to reproduce the error

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by Kamalesh-Seervi**
## Description

Fixes #7828

- This change addresses a bug where the Elasticsearch connection was not properly closed when an exception occurred. - This bug was causing resource leaks and connection issues.
- Improved error handling during the connection setup by handling `ConnectionError` and `AuthenticationException`.

## Type of change

- [x] 🐛 Bug fix (non-breaking change which fixes an issue)

## Verification Process

To ensure the changes are working as expected:

- [x] Test Location: N/A
- [x] Verification Steps: Not applicable as this is a bug fix, and no new functionality is added.

## Additional Media:

- [x] N/A

## Checklist:

- [x] My code follows the style guidelines (PEP 8) of MindsDB.
- [x] I have appropriately commented on my code, especially in complex areas.
- [x] Necessary documentation updates are either made or tracked in issues.
- [x] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   **kd14** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by Kamalesh-Seervi** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Kamalesh-Seervi** [comment]
recheck

**Comment by ZoranPandovski** [comment]
recheckcla

**Review by ZoranPandovski — APPROVED** [review]

**Comment by tomhuds** [comment]
@ZoranPandovski @Kamalesh-Seervi looks like the box is checked for unit/integration tests but I can't see any in the PR?

**Comment by Kamalesh-Seervi** [comment]
It was only bug fix I added error handling to connection of elastic search

**Comment by ZoranPandovski** [comment]
@Kamalesh-Seervi Let's work on the initial unit tests for Elasticsearch. Can you help with that?

**Comment by Kamalesh-Seervi** [comment]
Yeh sure based on what i added ?

**Pull request merged**
