### PR TITLE
README.md file updated

### PR DESCRIPTION
**Pull request by gitatractivo**
## Description

Please include a summary of the change and the issue it solves. 

**Fixes** #4908 

## Type of change
Updated README.md file to required change.

(Please delete options that are not relevant)

- [x] 🐛 Bug fix (non-breaking change which fixes an issue)

### What is the solution?

(Describe at a high level how the feature was implemented)

## Checklist:
- [x] I have updated the documentation, or created issues to update them.

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by gitatractivo** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by gitatractivo** [comment]
> recheckcla

Hi sorry for trouble but how do I do that?

**Comment by martyna-mindsdb** [comment]
You signed the CLA already.

Now you can have a look at other help-wanted issues. Thanks.

**Pull request merged**
