### PR TITLE
create doc for the sql-anywhere issue 5079

### PR DESCRIPTION
**Pull request by haojunsong-08**
## Description
Followed the instruction on issue, created the title and copied from the readme provided. the created file stored in 
```
mindsdb/docs/data-integrations
```
deleted the broken link at the original readme.

Not sure if this is what needed to be done, any recommendations are welcome!

**Fixes** #5079

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   **Haojun Song** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@haojunsong-08 
Please sign our CLA following the instructions above.

**Comment by haojunsong-08** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by martyna-mindsdb** [comment]
@haojunsong-08 
Please add your email to GitHub as mentioned here:
 **Haojun Song** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
 
 Only after adding your email you can sign the CLA.

**Comment by haojunsong-08** [comment]
Thanks will do that!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by haojunsong-08** [comment]
recheckcla

**Pull request merged**
