### PR TITLE
Feat add new handler to update Shopify orders

### LINKED ISSUE #7846: [Shopify] Implement UPDATE for the Orders table
MindsDB integrates with Shopify, so you can fetch data from your online store and use it to make relevant predictions and forecasts with MindsDB.

## Resources

Familiarize yourself with the existing Shopify integration: https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/shopify_handler

## Steps to Follow

The task is to extend [this implementation](https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/shopify_handler) to include the UPDATE command to update data in the Orders table.

## :loudspeaker: Additional rewards :trophy:

Each integration extension brings 15+ points for SWAG and entry into the draw for a :point_down: :
-  :computer:  [Razer Blade 16 Laptop](https://www.razer.com/gaming-laptops/Razer-Blade-16/RZ09-0483SEJ3-R3U1)
- :shirt: :bear:  [MindsDB Swag](https://store.covver.io/mindsdb/collections/swag-collection)

:information_source: For more info check out https://mindsdb.com/hacktoberfest/ :point_left: 

**Please note this issue is for first-time contributors to MindsDB**

### PR DESCRIPTION
**Pull request by Harsh-pandya**
## Description

This a new feature for the Shopify Handler. Under this feature, users can update the data for Shopify's Order Table.

Fixes #7846

## Type of change

(Please delete options that are not relevant)

- [x] ⚡ New feature (non-breaking change which adds functionality)
- [x] 📄 This change requires a documentation update

## Verification Process
* Set up mindsdb  on your local as a [documented here](https://docs.mindsdb.com/setup/self-hosted/pip/macos)
* Get your shophify Access key and your shop name URL
* Write the command to create a shophify database as mentioned [here](https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/shopify_handler#example-usage)
* Now write a simple update SQL query to test the changes

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [x] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have appropriately commented on my code, especially in complex areas.
- [x] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

https://github.com/mindsdb/mindsdb/assets/52901608/6cb5e079-7ead-4c28-b26b-4022c8fdad9e

### CODE REVIEW

**Comment by Harsh-pandya** [comment]
Hello @martyna-mindsdb,  here is my PR for the task to add  a new method to Shopify Orders Handler

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb/blob/staging/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   **Harsh Pandya** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by martyna-mindsdb** [comment]
@Harsh-pandya 
Please see the message from @mindsdbadmin above and follow the instructions to set up your GitHub account and sign the CLA.

Also, please add an example of using UPDATE in the `mindsdb/integrations/handlers/shopify_handler/README.md` file.

**Comment by Harsh-pandya** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Harsh-pandya** [comment]
recheck

**Comment by Harsh-pandya** [comment]
> **CLA Assistant Lite bot:** Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb/blob/staging/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> I have read the CLA Document and I hereby sign the CLA
> 
> **Harsh Pandya** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).You can retrigger this bot by commenting **recheck** in this Pull Request

recheck

**Comment by Harsh-pandya** [comment]
Hello @martyna-mindsdb,  I made the requested changes of adding an example of an update query in the following readme. ```mindsdb/integrations/handlers/shopify_handler/README.md```.

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by martyna-mindsdb** [comment]
Thanks @Harsh-pandya 

It seems you haven't added the email address that you used to create this PR to your GitHub account.
Please follow this instruction:

> Harsh Pandya seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).

**Comment by Harsh-pandya** [comment]
I have read the CLA Document and I hereby sign the CLA

**Review by martyna-mindsdb — APPROVED** [review]

**Comment by martyna-mindsdb** [comment]
recheckcla

**Pull request merged**
