### PR TITLE
Updated Docs for SQLAlchemy

### LINKED ISSUE #2914: [Bug]: Docs for SQLAlchemy requires additional step (pip install pymysql)
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running this example in the docs in fresh python environment: https://docs.mindsdb.com/connect/sql-alchemy/

I get this error: 
_Connection could not be made due to the following error: 
 No module named 'pymysql'_

Requires the user to _pip install pymysql_, then it works.
Possibly include this step at the top.

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ArmanChand**
Fixes #2914

## Docs for SQLAlchemy requires additional step (pip install pymysql)
  - Added pymysql library and Port change 

mindsdb

### CODE REVIEW

**Comment by ArmanChand** [comment]
@ZoranPandovski Please review the changes

**Comment by ArmanChand** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ZoranPandovski** [comment]
recheckcla

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
Can you move the `    pip install pymysql` out of the code as a separate command that user need to run please

**Comment by ArmanChand** [comment]
@ZoranPandovski , Please review

**Comment by ArmanChand** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by ArmanChand** [comment]
@ZoranPandovski ,
please review

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
