### PR TITLE
Adding icon.svg file for writer handler

### PR DESCRIPTION
**Pull request by maulanaakbardj**
## Description

This PR adds a icon.png file for writer handler which was missing
fyi, @MinuraPunchihewa @chandrevdw31 

Fixes #issue_number

## Type of change

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [ ] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have appropriately commented on my code, especially in complex areas.
- [ ] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Review by MinuraPunchihewa — CHANGES_REQUESTED** [review]
Hey @maulanaakbardj,
In the __init__.py file for the handler, you also need to add the path to the icon,
`icon_path = 'icon.png'`

**Comment by MinuraPunchihewa** [comment]
@maulanaakbardj It would also be even better if you can find a SVG.

**Review by maulanaakbardj — COMMENTED** [review]
done

**Review by MinuraPunchihewa — COMMENTED** [review]
@maulanaakbardj Please add `icon_path` to `__all__` as well.

**Comment by maulanaakbardj** [comment]
done. @MinuraPunchihewa 
> @maulanaakbardj Please add `icon_path` to `__all__` as well.

**Review by MinuraPunchihewa — APPROVED** [review]

**Pull request merged**
