### PR TITLE
Fix #8003

### LINKED ISSUE #8003: [Shopify] Implement INSERT/UPDATE/DELETE for the InventoryLevel table
MindsDB integrates with Shopify, so you can fetch data from your online store and use it to make relevant predictions and forecasts with MindsDB.

## Resources

Familiarize yourself with the existing Shopify integration: https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/shopify_handler

## Steps to Follow

The task is to extend [this implementation](https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/shopify_handler) to include the INSERT, UPDATE, and DELETE commands for the [InventoryLevel table](https://github.com/mindsdb/mindsdb/blob/staging/mindsdb/integrations/handlers/shopify_handler/shopify_tables.py#L413).

Please provide screenshots or a short video presenting this feature.

## :loudspeaker: Additional rewards :trophy:

Each integration extension brings 15+ points for SWAG and entry into the draw for a :point_down: :
-  :computer:  [Razer Blade 16 Laptop](https://www.razer.com/gaming-laptops/Razer-Blade-16/RZ09-0483SEJ3-R3U1)
- :shirt: :bear:  [MindsDB Swag](https://store.covver.io/mindsdb/collections/swag-collection)

:information_source: For more info check out https://mindsdb.com/hacktoberfest/ :point_left:

### PR DESCRIPTION
**Pull request by SrijanSahaySrivastava**
## Description

Implementation of Delete, Update and Insert queries for Shopify Inventory Level Table

Fixes #8003 

I need some help regarding getting it up and running locally and testing. Please guide me through it.

this is my initial commit.

### CODE REVIEW

**Comment by SrijanSahaySrivastava** [comment]
@martyna-mindsdb Please help me with locally running and testing of mindsDB. I'm having a hard time with running it locally on windows machine.

**Comment by ZoranPandovski** [comment]
Hey @SrijanSahaySrivastava how did you implemented this without testing? Please check https://docs.mindsdb.com/contribute/install

**Comment by ZoranPandovski** [comment]
recheckcla

**Review by ZoranPandovski — CHANGES_REQUESTED** [review]
Hey @SrijanSahaySrivastava how did you implemented this without testing? Please check https://docs.mindsdb.com/contribute/install

**Comment by SrijanSahaySrivastava** [comment]
I tested some parts of UPDATE query and Insert query on my spare PC. Sorry to just make a half done PR. I'm currently working on final PR

**Comment by SrijanSahaySrivastava** [comment]
I'm getting HTTP response code 422 error. could someone help me?

**Comment by martyna-mindsdb** [comment]
@SrijanSahaySrivastava 
Please provide more details like at which step do you get this error, did you try to debug your code?

**Comment by SrijanSahaySrivastava** [comment]
image

following is the exact error message.
```
[shopify/shopify_datasource]: Response(code=422, body="b''", headers={'Date': 'Sun, 29 Oct 2023 06:09:56 GMT', 'Content-Type': 'application/json', 'Transfer-Encoding': 'chunked', 'Connection': 'close', 'X-Sorting-Hat-PodId': '304', 'X-Sorting-Hat-ShopId': '84294566193', 'Referrer-Policy': 'origin-when-cross-origin', 'X-Frame-Options': 'DENY', 'X-ShopId': '84294566193', 'X-ShardId': '304', 'X-Stats-UserId': '', 'X-Stats-ApiClientId': '67384377345', 'X-Stats-ApiPermissionId': '655546384689', 'X-Shopify-API-Terms': 'By accessing or using the Shopify API you agree to the Shopify API License and Terms of Use at https://www.shopify.com/legal/api-terms', 'X-Shopify-API-Version': '2023-01', 'X-Shopify-API-Version-Warning': 'https://shopify.dev/concepts/about-apis/versioning', 'HTTP_X_SHOPIFY_SHOP_API_CALL_LIMIT': '1/40', 'X-Shopify-Shop-Api-Call-Limit': '1/40', 'Strict-Transport-Security': 'max-age=7889238', 'Server-Timing': 'processing;dur=133', 'X-Shopify-Stage': 'production', 'Content-Security-Policy': "default-src 'self' data: blob: 'unsafe-inline' 'unsafe-eval' https://* shopify-pos://*; block-all-mixed-content; child-src 'self' https://* shopify-pos://*; connect-src 'self' wss://* https://*; frame-ancestors 'none'; img-src 'self' data: blob: https:; script-src https://cdn.shopify.com https://cdn.shopifycdn.net https://checkout.shopifycs.com https://api.stripe.com https://mpsnare.iesnare.com https://appcenter.intuit.com https://www.paypal.com https://js.braintreegateway.com https://c.paypal.com https://maps.googleapis.com https://www.google-analytics.com https://v.shopify.com 'self' 'unsafe-inline' 'unsafe-eval'; upgrade-insecure-requests; report-uri /csp-report?source%5Baction%5D=index&source%5Bapp%5D=Shopify&source%5Bcontroller%5D=admin%2Finventory_levels&source%5Bsection%5D=admin_api&source%5Buuid%5D=514c0787-f7f5-4d99-a8dc-ba5ec5a4b014", 'X-Content-Type-Options': 'nosniff', 'X-Download-Options': 'noopen', 'X-Permitted-Cross-Domain-Policies': 'none', 'X-XSS-Protection': '1; mode=block; report=/xss-report?source%5Baction%5D=index&source%5Bapp%5D=Shopify&source%5Bcontroller%5D=admin%2Finventory_levels&source%5Bsection%5D=admin_api&source%5Buuid%5D=514c0787-f7f5-4d99-a8dc-ba5ec5a4b014', 'X-Dc': 'gcp-asia-south1,gcp-us-east1,gcp-us-east1', 'X-Request-ID': '514c0787-f7f5-4d99-a8dc-ba5ec5a4b014', 'CF-Cache-Status': 'DYNAMIC', 'Report-To': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=LXEQuOjSCgPAYiokWg3VO8roDmpQmelYstq%2FFlfTXzACJdVnpjue2oNlgSdJTfn0JSygalya3lSfyhtuCoea50XErRFJkN6AB945dEh1AVXJuHEIWQ%2F4rWwHicDaGwSiITYAbhOcQsxngX99TEvUGurt5Q%3D%3D"}],"group":"cf-nel","max_age":604800}', 'NEL': '{"success_fraction":0.01,"report_to":"cf-nel","max_age":604800}', 'Server': 'cloudflare', 'CF-RAY': '81d940a77e368599-BOM', 'alt-svc': 'h3=":443"; ma=86400'}, msg="Unprocessable Entity")
```

 I've asked github-copilot for help as well but got nowhere.

**Comment by ZoranPandovski** [comment]
This doesn't work, closing for now. @SrijanSahaySrivastava Please check the Shopify handler in details or find some of other `help-wanted` issues

**Pull request closed without merging**
