### PR TITLE
feat: add new greptimedb handler

### LINKED ISSUE #9066: [Integration] GreptimeDB database integration
[GreptimeDB](https://github.com/greptimeteam/greptimedb) is an open-source time series database. It has built-in support for mysql wire-protocol. I have tested it as a mysql database in mindsdb and it works out of box. 

It would be nice to include greptimedb on mindsdb integration. I think there are tasks:

- Add a new engine called `greptimedb` although it doesn't require much development and new dependency
- Add docs on mindsdb's doc site

Please let me know if I can help.

### PR DESCRIPTION
**Pull request by sunng87**
## Description

Please include a summary of the change and the issue it solves. 

Fixes #9066 

## Type of change

(Please delete options that are not relevant)

- [x] ⚡ New feature (non-breaking change which adds functionality)
- [x] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

Verified via add greptimedb as a valid datasource

```sql
CREATE DATABASE greptimedb_datasource
WITH
  engine = 'greptimedb',
  parameters = {
    "host": "127.0.0.1",
    "port": 4002,
    "database": "public",
    "user": "username",
    "password": "password"
  };
```

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have appropriately commented on my code, especially in complex areas.
- [x] Necessary documentation updates are either made or tracked in issues.

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb/blob/staging/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Review by ZoranPandovski — APPROVED** [review]
Thanks, please just sign the cla

**Comment by sunng87** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by ZoranPandovski** [comment]
@sunng87 Sorry for the late response, somehow we have missed this. Can you please merge main at this branch so we can merge the PR. Thanks

**Comment by sunng87** [comment]
@ZoranPandovski merged. Please let me know if there is any other issue with this.

**Comment by ZoranPandovski** [comment]
recheckcla

**Pull request merged**
