### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by geistnine**
## Description

Updated clickhouse link in data integrations section of README, which was missing the rest of the url

**Fixes** #4759

## Type of change

- [x] 🐛 Bug fix (non-breaking change which fixes an issue)

### What is the solution?
Appended correct url path to href value of anchor element on line 139 of mindsdb/README.md

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have updated the documentation, or created issues to update them.
- [x] I fixed|updated|added unit tests and integration tests for each feature (if applicable).
- [x] I have shared a short loom video or screenshots demonstrating any new functionality.

### CODE REVIEW

**Comment by geistnine** [comment]
I have read the CLA document and I hereby sign the CLA.

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Review by ZoranPandovski — APPROVED** [review]

**Comment by ZoranPandovski** [comment]
recheckcla

**Pull request merged**
