### PR TITLE
Added community tutorial links to the Using MindsDB via Mongo API -> Connect to MindsDB -> MongoDB Compass page #4557

### PR DESCRIPTION
**Pull request by apurvagandhi**
## Description

Added community tutorial links to the Using MindsDB via Mongo API -> Connect to MindsDB -> MongoDB Compass page 
This is in response to issue #4557

### CODE REVIEW

**Comment by martyna-mindsdb** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by apurvagandhi** [comment]
I have read the CLA Document and I hereby sign the CLA.

**Comment by ZoranPandovski** [comment]
recheckcla

**Review by ZoranPandovski — APPROVED** [review]

**Pull request merged**
