### PR TITLE
Milvus

### PR DESCRIPTION
**Pull request by Jacksonxhx**
## Description

Update the milvus integration handler and support milvus lite version.
Utilied MilvusClient to conduct operations

Fixes #issue_number

## Type of change

(Please delete options that are not relevant)

- [x] ⚡ New feature (non-breaking change which adds functionality)
- [x] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Checklist:

- [x] My code follows the style guidelines(PEP 8) of MindsDB.
- [x] I have appropriately commented on my code, especially in complex areas.
- [x] Necessary documentation updates are either made or tracked in issues.
- [x] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb/blob/main/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by Jacksonxhx** [comment]
Hi, I updated the format and sent the latest pr, could you help me approve the CI/CD workflow? Thank you!

**Comment by dusvyat** [comment]
@Jacksonxhx Please may you check https://github.com/mindsdb/mindsdb/blob/main/tests/handler_tests/test_milvus_handler.py and fix any broken tests based on the updates you made

**Comment by Jacksonxhx** [comment]
> @Jacksonxhx Please may you check https://github.com/mindsdb/mindsdb/blob/main/tests/handler_tests/test_milvus_handler.py and fix any broken tests based on the updates you made

No problem, I will take a look and fix it

**Comment by Jacksonxhx** [comment]
For the test_milvus_handler, I simulated other's tests like qdrant and pinecone but it turns out that all of them are not working for the down below issus. Could you take a look? How can i deal with this situation. Should I write a new test base on only python but not sql?

**Comment by Jacksonxhx** [comment]
Hi, is there anyone who can help me with the workflow?

**Comment by Jacksonxhx** [comment]
Some jobs are cancelled

**Comment by dusvyat** [comment]
@Jacksonxhx are you able to include a loom video of it working? I can see why the tests are failing.

This is because `select` and other functions on Milvus handler return HandlerResponse object where as they should return a pandas datafame.

See ChromaDB handler as an example, this is currently the best supported vector store handler we have.

**Comment by Jacksonxhx** [comment]
> dlerResponse

Got it, I will check it again, thank you for responding

**Comment by dusvyat** [comment]
@Jacksonxhx fyi fixes are being worked on here - https://github.com/mindsdb/mindsdb/pull/9678

**Comment by zc277584121** [comment]
@dusvyat @ZoranPandovski , I have update this branch with some bugs fixed, could you please take a review

**Comment by ZoranPandovski** [comment]
@Jacksonxhx , @zc277584121 Can you please sign the CLA so we can merge this https://github.com/mindsdb/mindsdb/pull/9570#issuecomment-2260202296

**Comment by zc277584121** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Jacksonxhx** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by zc277584121** [comment]
@ZoranPandovski  we have signed it

**Comment by ZoranPandovski** [comment]
recheckcla

**Review by ZoranPandovski — APPROVED** [review]

**Comment by zc277584121** [comment]
Do we need to do anything else to continue?

**Comment by zc277584121** [comment]
@ZoranPandovski @dusvyat

**Pull request merged**
