### PR TITLE
tutorial for solving house price prediction challenge

### PR DESCRIPTION
**Pull request by eren23**
## Description

Please include a summary of the change and the issue it solves. 

**Fixes** #4948 

## Type of change

- [x] 📄 This change requires a documentation update

### What is the solution?

I updated the tutorials page with a tutorial I wrote.

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by eren23** [comment]
I'm sorry, I wasn't aware tutorials were supposed to be based on an issue as well. My assumption is coming from the guide here: https://docs.mindsdb.com/contribute/tutorials https://docs.mindsdb.com/contribute/tutorials

**Comment by eren23** [comment]
> @eren23 Please mention the issue number in the PR description.

I'm sorry, I wasn't aware tutorials were supposed to be based on an issue as well. My assumption is coming from the guide here: https://docs.mindsdb.com/contribute/tutorials

**Comment by martyna-mindsdb** [comment]
@eren23 
Please note that any PR requires to have an issue linked to it.

Please see the issue description template that you used above: `Fixes #(issue)`

**Review by ZoranPandovski — APPROVED** [review]

**Comment by ZoranPandovski** [comment]
recheckcla

**Pull request merged**
