### PR TITLE
feat: added payments table shopify implementation

### LINKED ISSUE #7487: [Shopify] Implement the Payments table
MindsDB integrates with Shopify, so you can access your Shopify data and make relevant forecasts with MindsDB.

## Resources

Familiarize yourself with the existing Shopify integration: https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/shopify_handler

## Steps to Follow

Currently, the Shopify integration with MindsDB accesses tables from Shopify API that store products and customers.

The task is to extend [this implementation](https://github.com/mindsdb/mindsdb/tree/staging/mindsdb/integrations/handlers/shopify_handler) to include the Payments table from Shopify API.

## :loudspeaker: Additional rewards :trophy:

Each integration test brings 15+ points for SWAG and entry into the draw for a :point_down: :
-  :computer:  [Razer Blade 16 Laptop](https://www.razer.com/gaming-laptops/Razer-Blade-16/RZ09-0483SEJ3-R3U1)
- :shirt: :bear:  [MindsDB Swag](https://store.covver.io/mindsdb/collections/swag-collection)

:information_source: For more info check out https://mindsdb.com/hacktoberfest/ :point_left:

### PR DESCRIPTION
**Pull request by sahil9001**
## Description

Please include a summary of the change and the issue it solves. 

This PR addresses and implements the issue of Payments Table feature from shopify
Fixes #7487 

## Type of change

(Please delete options that are not relevant)

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ⚡ New feature (non-breaking change which adds functionality)
- [ ] 📢 Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] 📄 This change requires a documentation update

## Verification Process

To ensure the changes are working as expected:

 - [ ]   Test Location: Specify the URL or path for testing.
 - [ ]   Verification Steps: Outline the steps or queries needed to validate the change. Include any data, configurations, or actions required to reproduce or see the new functionality.

## Additional Media:

- [ ] I have attached a brief loom video or screenshots showcasing the new functionality or change.

## Checklist:

- [ ] My code follows the style guidelines(PEP 8) of MindsDB.
- [ ] I have appropriately commented on my code, especially in complex areas.
- [ ] Necessary documentation updates are either made or tracked in issues.
- [ ] Relevant unit and integration tests are updated or added.

### CODE REVIEW

**Comment by ZoranPandovski** [comment]
recheckcla

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by sahil9001** [comment]
recheck

**Comment by sahil9001** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by sahil9001** [comment]
recheck

**Comment by Better-Boy** [comment]
@sahil9001 When I tried to run this code, getting the following error -

`AttributeError: module 'shopify' has no attribute 'Payment'`

Are there any steps to resolve this issue?

**Comment by sahil9001** [comment]
I didn't test it, seems like there's an issue on Mac M1, but according to the shopify docs, there must be a Payment model

**Review by MinuraPunchihewa — COMMENTED** [review]
Hey @sahil9001,
Please be kind enough to test this and include a screenshot or some evidence that payment data can be accessed via the integration.

If you need some help testing this locally, please refer to the documentation here,
https://docs.mindsdb.com/setup/self-hosted/pip/source

**Comment by ZoranPandovski** [comment]
Closing this, it has already been solved by another functional PR. @sahil9001 Please check the other issues for Shopify or other open `help-wanted` issues

**Comment by sahil9001** [comment]
Sure, sorry this might take a while to test. I am setting up shopify store now, was occupied with other tasks.

**Comment by ZoranPandovski** [comment]
@sahil9001 Did you manage to test this or we should close it?

**Pull request closed without merging**
