### PR TITLE
Check if column is Boolean before casting #294

### LINKED ISSUE #294: ValueError: could not convert string to float: 'True'
**Your Environment**
* Python version: 3.7.3
* Operating system: Ubuntu 18.04
* Python environment used (e.g. venv, conda): venv
* Mindsdb version: 1.4.6

**Describe the bug**
Predict input value e.g `Number of times pregnant: 1`  is somehow converted to True instead of 1.
Inside [base_module](https://github.com/mindsdb/mindsdb/blob/f7ca6b842e2d0b29c9a0a465454bf772097431ee/mindsdb/libs/phases/base_module.py#L54) if you check the *kwargs data_frame value contains True as an input value. So the actual mapping error should be somewhere in transaction.py

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Link to [full-example](https://github.com/ZoranPandovski/mindsdb-examples/tree/master/diabetes_example) 

**Additional context**
Screenshot from 2019-08-20 16-14-32

### PR DESCRIPTION
**Pull request by ZoranPandovski**
This PR checks if the data frame value is boolean before casting it to 'True' or 'False'. Fixes #294

### CODE REVIEW

**Comment by George3d6** [comment]
Why is this extra check required ?
Is there a situation where the original way of doing replace fails to replace all True/False values ? or a situation in which we want to keep True and False values in the dataframe as python bools instead of as strings ?

**Comment by George3d6** [comment]
Also, you only want to do the casting on the column it should be something like `df[col] = df[col].replace(... etc`, right ? Or am I miss-understanding what you are trying to do here :?

**Comment by George3d6** [comment]
Ah, nevermind, I see the issue described in #294 , but my second comment still stands. Also, this doesn't fix cases of this bugs where pandas read a float column that's all 0 and or 1 in the when/when_data dataset and turns that into a bool. I think the easier fix will be:

If the column type is string/object in pandas, do the replace as is.
If the column type is numerical/bolean, do the replace using the dict: ` {True: 1, False: 0}`

Does that seem like a good solution to you @ZoranPandovski  ?

**Comment by ZoranPandovski** [comment]
I've made the required changes as we've talked.

**Pull request merged**
