### PR TITLE
Added manual qa for Hugging face Crypto Buy Signals

### PR DESCRIPTION
**Pull request by Anandprabhu530**
## Description

Added Manual QA for Hugging face - Crypto Buy Signals

### CODE REVIEW

**Comment by Anandprabhu530** [comment]
merging this pull request closes the issue https://github.com/mindsdb/mindsdb/issues/6084

**Comment by Anandprabhu530** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by mindsdbadmin** [comment]
**CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/mindsdb/mindsdb_native/blob/stable/assets/contributions-agreement/individual-contributor.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.<br/>
   - - -
   I have read the CLA Document and I hereby sign the CLA
   - - -
   <sub>You can retrigger this bot by commenting **recheck** in this Pull Request</sub>

**Comment by Anandprabhu530** [comment]
recheck

**Comment by Anandprabhu530** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Anandprabhu530** [comment]
recheck

**Pull request merged**
